### ISSUE TITLE
ASSERT (arch.c:3131) translation failure on decode-stress test

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#1025]
_From [bruen...@google.com](https://code.google.com/u/109494838902877177630/) on December 14, 2012 17:25:22_

this test was disabled for a while ( issue #105 ) and when I re-enable I hit a translation failure:

5: Test command: /work/dr/git/build_x64_dbg_tests/bin64/runstats "-s" "60" "-killpg" "-silent" "/work/dr/git/build_x64_dbg_tests/bin64/drrun" "-debug" "-ops" "-stderr_mask 0xC -dumpcore_mask 0 -stress_recreate_state -code_api " "/work/dr/git/build_x64_dbg_tests/suite/tests/bin/common.decode"
5: Test timeout computed to be: 1500
5: Testing nops
5: Done with nops
5: Testing SSE3
5: Bad instruction, instance 1
5: Testing 3D-Now
5: Bad instruction, instance 2
5: Testing far call/jmp
5: <Application /work/dr/git/build_x64_dbg_tests/suite/tests/bin/common.decode (29489).  Internal Error Internal DynamoRIO Error: /work/dr/git/src/core/x86/arch.c:3131 false
5: (Error occurred @651 frags)
5: version 4.0.1782, custom build
5: -code_api -stderr_mask 12 -stack_size 56K -max_elide_jmp 0 -max_elide_call 0 -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct -stress_recreate_pc -stress_recreate_state 
5: 0x0000000073332160 0x000000007110e94d
5: 0x00000000733322c0 0x00000000712044e5
5: 0x00000000733323b0 0x0000000071205de7
5: 0x00000000733329f0 0x00000000712060da
5: 0x0000000073332cf0 0x0000000071105702
5: 0x0000000073332d50 0x0000000071255bf8
5: 0x0000000073332f10 0x00000000710f97cf
5: 0x0000000073332ff0 0x00000000732c6e85
5: 0x00007fff0bac4790 0x00000032ed621735>

_Original issue: http://code.google.com/p/dynamorio/issues/detail?id=1025_

**Comment by hgreving2304** [comment]
It's enabled only for Win32. It would be a nice-to-have for Unix.
