### ISSUE TITLE
Issues of the bbcov tool in the release package

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#1241]
_From [zhao...@google.com](https://code.google.com/u/106321947286816917100/) on August 05, 2013 12:19:06_

There are several issues on the bbcov tool in the release package:

1. bbcov2lcov.debug should be in tools/bin64
12:12|zhaoqin@zhaoqin:~/Workspace/DynamoRIO/RCs/DynamoRIO-Linux-4.1.0-8
\> ls tools/bin64/
bbcov2lcov  libdrsyms.so  libdynamorio.so  libdynamorio.so.4.1

12:12|zhaoqin@zhaoqin:~/Workspace/DynamoRIO/RCs/DynamoRIO-Linux-4.1.0-8
\> ls tools/lib64/debug/
bbcov2lcov.debug  libbbcov.so  libbbcov.so.debug

12:12|zhaoqin@zhaoqin:~/Workspace/DynamoRIO/RCs/DynamoRIO-Linux-4.1.0-8
\> ls tools/lib64/release/
bbcov2lcov.debug  libbbcov.so  libbbcov.so.debug

2. bbcov2lcov cannot run directly, has to set the path LD_LIBRARY_PATH:
12:12|zhaoqin@zhaoqin:~/Workspace/DynamoRIO/RCs/DynamoRIO-Linux-4.1.0-8
\> ./tools/bin64/bbcov2lcov
./tools/bin64/bbcov2lcov: error while loading shared libraries: libdynamorio.so.4.1: cannot open shared object file: No such file or directory

12:16|zhaoqin@zhaoqin:~/Workspace/DynamoRIO/RCs/DynamoRIO-Linux-4.1.0-8
\> export LD_LIBRARY_PATH=~/Workspace/DynamoRIO/RCs/DynamoRIO-Linux-4.1.0-8/tools/bin64/

12:17|zhaoqin@zhaoqin:~/Workspace/DynamoRIO/RCs/DynamoRIO-Linux-4.1.0-8
\> ./tools/bin64/bbcov2lcov
[BBCOV2LCOV] ERROR:      bbcov2lcov: covert bbcov file format to lcov file format
usage: bbcov2lcov [options]
      --help                          Print this message.
      --verbose \<int>                 Verbose level.
      --warning \<int>                 Warning level.
      --list \<input list file>        The file with a list of bbcov files to be processed.
      --dir \<input directory>         The directory with all bbcov.*.log files to be processed.
      --output \<output file>          The output file.
      --mod_filter \<module filter>    Only process the module whose path contains the filter string.
      --src_filter \<source filter>    Only process the source file whose path contains the filter string.
      --reduce_set \<reduce_set file>  Find a smaller set of log files from the inputs that have the same code coverage and write those file paths into \<reduce_set file>.

_Original issue: http://code.google.com/p/dynamorio/issues/detail?id=1241_

**Comment by zhaoqin** [comment]
```
$ ls ../../dynamorio.git/exports/tools/bin32/ -l       
total 12412
-rw-r--r-- 1 zhaoqin zhaoqin  342890 Aug 16 21:09 bbcov2lcov
-rwxr-xr-x 1 zhaoqin zhaoqin  657720 Aug 15 21:04 drcachesim
-r-xr-xr-x 1 zhaoqin zhaoqin 7234844 Aug 15 21:04 drcachesim.debug
```
bbcov2lcov is marked is not marked as executable. If it has been that way for a while and on one complains, it means no one really use it. I would say just remove bbcov2lcov.
