### ISSUE TITLE
samples/CMakeLists.txt makes it confusing to build debug samples using VS generators

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#1392]
_From [bruen...@google.com](https://code.google.com/u/109494838902877177630/) on March 13, 2014 23:06:47_

Us developers are always using Ninja so we sometimes miss issues with VS
generators.

Using samples/CMakeLists.txt, if you specify just "-DDEBUG=ON" or just
"-DCMAKE_BUILD_TYPE=Debug", you won't end up with full debug info: for the
former b/c DynamoRIOConfig.cmake will not pull in the _DEBUG flags, and for
the latter b/csamples/CMakeLists will ask for Release config.  You have to
specify both, and even then you might think the /Zi is not present as it is
on the source files and not the target.

The Ninja or Makefile generators are immune to these problems as they have
no configs or config suffixes.

We should make two changes:

1) DynamoRIOConfig.cmake should set CMAKE_BUILD_TYPE to match DEBUG if only
   the latter is set.  It should pick RelWithDebInfo if DEBUG is off.

2) samples/CMakeLists should collapse the configs based on both DEBUG and
   CMAKE_BUILD_TYPE, and should also set the latter if not set, again
   picking RelWithDebInfo over Release.

Someone who knowingly wants Release presumably knows enough to set it up
explicitly.

_Original issue: http://code.google.com/p/dynamorio/issues/detail?id=1392_

**Comment by illera88** [comment]
I see a reference to this issue in this code:

```
# To match Makefiles and have just one build type per configured build
# dir, we collapse VS generator configs to a single choice.
# This must be done prior to the project() command and the var
# must be set in the cache.
if ("${CMAKE_GENERATOR}" MATCHES "Visual Studio")
  if (DEBUG OR "${CMAKE_BUILD_TYPE}" MATCHES "Debug")
    set(CMAKE_CONFIGURATION_TYPES "Debug" CACHE STRING "" FORCE)
  else ()
    # Go w/ debug info (i#1392)
    set(CMAKE_CONFIGURATION_TYPES "RelWithDebInfo" CACHE STRING "" FORCE)
  endif ()
  # we want to use the _LOCATION_<config> property
  string(TOUPPER "${CMAKE_CONFIGURATION_TYPES}" upper)
  set(location_suffix "_${upper}")
else ("${CMAKE_GENERATOR}" MATCHES "Visual Studio")
  set(location_suffix "")
endif ("${CMAKE_GENERATOR}" MATCHES "Visual Studio")
```

That code prevents cmake to create all types of configurations (Debug;Release;MinSizeRel;RelWithDebInfo) I don't understand why you do so. can you elaborate?

I guess I need to use Debug if I want to debug my client right?
