### ISSUE TITLE
drcov compile error

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#1416]
_From [mingwayz...@gmail.com](https://code.google.com/u/110943286627176757601/) on April 08, 2014 15:40:08_

When I am using DynamoRIO v2642 under Ubuntu 12.04 32bit, I try to compile the client code of drcov with option "CBR_COVERAGE" turned on. The following is the compile time error:

In function ‘bb_table_check_cbr’:
$DYNAMORIO_ROOT/clients/drcov/drcov.c:331:9: error: implicit declaration of function ‘module_table_entry_print’ [-Werror=implicit-function-declaration]
cc1: all warnings being treated as errors
make[2]: **\* [clients/drcov/CMakeFiles/drcov.dir/drcov.c.o] Error 1
make[1]: **\* [clients/drcov/CMakeFiles/drcov.dir/all] Error 2
make: **\* [all] Error 2

I double checked and find that the API function "module_table_entry_print" defined in $DYNAMORIO_ROOT/clients/common/modules.c becomes an internal (static) function. That's probably why I have such an issue.

_Original issue: http://code.google.com/p/dynamorio/issues/detail?id=1416_

**Comment by anshuman-goel** [comment]
how to resolve this error on windows ?

**Comment by derekbruening** [comment]
> how to resolve this error on windows ?

This issue is closed.  Please ask new questions on the dynamorio-users mailing list.
