### ISSUE TITLE
cmake 2.8.12 if Qt is present warns about policy CMP0020

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#1418]
_From [bruen...@google.com](https://code.google.com/u/109494838902877177630/) on April 08, 2014 16:55:42_

-- Found Qt 5: DrGUI will be built
CMake Warning (dev) at CMakeLists.txt:1084 (export):
  Policy CMP0020 is not set: Automatically link Qt executables to qtmain
  target on Windows.  Run "cmake --help-policy CMP0020" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.
Call Stack (most recent call first):
  ext/drgui/CMakeLists.txt:85 (DR_export_target)
This warning is for project developers.  Use -Wno-dev to suppress it.

Xref a similar cmake policy warning involving interface imports: https://code.google.com/p/drmemory/issues/detail?id=1481 For now let's set the policy to OLD and resolve both issues with interface imports later once more people are on 2.8.12 and we can use the new features.

_Original issue: http://code.google.com/p/dynamorio/issues/detail?id=1418_

**Comment by hgreving2304** [comment]
From reading into the the policy this shouldn't affect us and we prob. can just remove the policy. Checking w/ Windows + Qt build.
