### ISSUE TITLE
allow RLIMIT_NOFILE to be set to the same or lower value

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#1466]
_From [bruen...@google.com](https://code.google.com/u/109494838902877177630/) on July 07, 2014 15:33:13_

Today -steal_fds has a very simple policy on SYS_setrlimit: it fails everything with EPERM.  We could easily relax that to allow reducing the limit (remembering the imposed upper limit of course) which may avoid some transparency issues.

_Original issue: http://code.google.com/p/dynamorio/issues/detail?id=1466_

**Comment by zhaoqin** [comment]
Fixed issue 2c74063
