### ISSUE TITLE
port to ARM master issue

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#1551]
_From [bruen...@google.com](https://code.google.com/u/109494838902877177630/) on October 08, 2014 00:19:33_

xref issue #1550 xref issue #269 This is a container case for references in the code for tasks we're delaying while we're porting.

_Original issue: http://code.google.com/p/dynamorio/issues/detail?id=1551_

**Comment by derekbruening** [comment]
After a massive amount of work and hundreds of commits, AArch32 support is pretty much complete.  We can run large applications now (including Chrome with simple workloads, though some bugs are seen there).  There are still some known missing features (IT splits, some cases of fault handling) but we'll treat those as corner cases and file separate issues on them from here on out.

**Comment by algr** [comment]
The ARM port is looking great.  It is already very functional, and it seems right that this issue is now closed.  The source still has several comments "FIXME i#1551: NYI on ARM".  Perhaps these could be made specific to open issues for individual features?

**Comment by zhaoqin** [comment]
```
> git grep "FIXME i#1551: NYI on ARM" | wc -l
74
```
We put FIXME comment back then and thought those are much less common cases. Some are small fixes and some need more efforts. ASSERT will be triggered if any is hit, so we can file issue or fix it then.

**Comment by derekbruening** [comment]
> The source still has several comments "FIXME i#1551: NYI on ARM". Perhaps these could be made
> specific to open issues for individual features?

Yes, these should be cleaned up.  Some should be removed as they are in code we do not plan to ever port.  Likely some should be updated to already-filed issues.  There may be some that need new issues: someone will need to go through them.  Any volunteers?
