### ISSUE TITLE
core/arch/x86_code.c:444: Use of Uninitialized Variable

### ISSUE THREAD

**Issue by groleo** [DynamoRIO/dynamorio#1577]
/home/adrian/workspace/dbi/dynamorio/core/arch/x86_code.c: In function ‘test_func’:
/home/adrian/workspace/dbi/dynamorio/core/arch/x86_code.c:444:5: error: ‘*(&var+-1)’ is used uninitialized in this function [-Werror=uninitialized]
     memcpy(&var, &var-1, 1); /* avoid uninit warning */

Using gcc (Debian 4.9.2-2) 4.9.2

**Comment by derekbruening** [comment]
The fix was reverted due to failing on Windows: re-opening.

**Comment by derekbruening** [comment]
This is blocking contributors so let's get it fixed
