### ISSUE TITLE
CMake Error at CMakeLists.txt:226 (append_property_string):

### ISSUE THREAD

**Issue by djn3m0** [DynamoRIO/dynamorio#1586]
Hi
i tried to make visual studio project for dynamorio samples with cmake 3.x and 5.0.0-9 that i got that message.
then i tried latest build with both cmake 2.x and 3.x cmake but i still have that problem and i cannot build visual studio project for those samples.

thanks

**Comment by derekbruening** [comment]
We should add better sample-building tests that more closely mimic use of a release package as our internal tests did not catch this.  The methodology will be the same as the solution to https://github.com/DynamoRIO/drmemory/issues/1652: adding tests that use 'ctest --build-and-test' to drive full projects.

**Comment by derekbruening** [comment]
To elaborate on the problem, we have a call to an undefined routine in samples/CMakeLists.txt:

	CMake Error at CMakeLists.txt:221 (append_property_string):
	  Unknown CMake command "append_property_string".

**Comment by derekbruening** [comment]
Fix is likely:   s/append_property_string/_DR_append_property_string/
