### ISSUE TITLE
Cbrtrace Sample Fails to Link

### ISSUE THREAD

**Issue by newgre** [DynamoRIO/dynamorio#1588]
The cbrtrace sample fails to link when using CMake to build all samples. The error message is:

2>LINK : fatal error LNK1104: cannot open file 'D:\derek\dr\build_package\build_release-32\core\ntdll_imports.lib'

Verified on win7 x64 using DynamoRIO 5.0.0-9 with CMake 3.1 and VS 2013.

**Comment by derekbruening** [comment]
Does this only happen with CMake 3.x?  CMake 3.x broke backward compatibility and changed how location properties work.

**Comment by newgre** [comment]
Can't say for sure - I only have CMake 3.x

**Comment by derekbruening** [comment]
I cannot reproduce this with CMake 2.8.12.2, 3.0.2, or 3.1.0, with VS 2010 or 2013.

I had to edit DynamoRIO-Windows-5.0.0-9/samples/CMakeLists.txt for s/append_property_string/_DR_append_property_string/ (to fix #1586) first, and then:

```
% ~/extsw/cmake/install/bin/cmake.exe --version
cmake version 3.1.0
% ~/extsw/cmake/install/bin/cmake.exe -G"Visual Studio 12" ../DynamoRIO-Windows-5.0.0-9/samples/ 
<has warnings about Policy CMP0026 (i#1557, since suppressed in r2933>
% ~/extsw/cmake/install/bin/cmake.exe --build . --config RelWithDebInfo
  ...
Build succeeded.
    0 Warning(s)
    0 Error(s)
% ls bin/cbrtrace.dll
bin/cbrtrace.dll
<or in IDE:>
% dclick DynamoRIO_samples.sln 
  ...
========== Build: 23 succeeded, 0 failed, 0 up-to-date, 1 skipped ==========
```

-DDEBUG=ON also builds fine.

**Comment by derekbruening** [comment]
My mistake, this machine has that precise path existing on it.  Once removed I can reproduce with any generator.

Somehow cmake is putting absolute paths into the exported files:

DynamoRIOTarget32-debug.cmake:  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "drdecode;drdecode;libcmtd;D:/derek/dr/build_package/build_debug-32/core/ntdll_imports.lib;kernel32;advapi32;imagehlp"
DynamoRIOTarget32-debug.cmake:  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "libcpmtd;libcmtd;dynamorio;dbghelp;D:/derek/dr/build_package/build_debug-32/ext/drsyms/dbghelp_imports.lib;drcontainers;dwarf;elftc"
DynamoRIOTarget32-debug.cmake:  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "dynamorio;drcontainers;drmgr;D:/derek/dr/build_package/build_debug-32/core/ntdll_imports.lib;D:/derek/dr/build_package/build_debug-32/core/ntdll_imports.lib"

(Also for the other configs and bitwidths.)

This seems to be the case for the 4.2.0 release as well.

Xref issue #1586's proposal for more thorough external-project automated tests.

**Comment by derekbruening** [comment]
While I was able to add automated tests that detect i#1586 it is not simple to detect the bug here.  For now we may have to rely on more thorough manual per-release testing.
