### ISSUE TITLE
make/git/hook-pre-commit.sh: 40: [: t2: unexpected operator

### ISSUE THREAD

**Issue by groleo** [DynamoRIO/dynamorio#1590]
Line 40 reads:
   if [ "${branch##*/}" == "master" ]; then

'==' is a bash-ism and the script's shabang is '/bin/sh'
so it fails when /bin/sh is not a symlink to /bin/bash

**Comment by derekbruening** [comment]
One possibility would be to just change it to /bin/bash which I believe is always present on default Linux and OSX (recent enough for DR support) installs, and DR itself does not support/run on BSD or other *nix flavors.  What OS are you on?  Did you take an explicit step to change /bin/sh to point at a different shell or was it like that by default?

**Comment by groleo** [comment]
I'm on Debian unstable. By default /bin/sh points to /bin/dash. Ubuntu also switched to dash as default shell, in 6.10.
Also, I guess changing from #!/bin/sh to #!/bin/bash
when bash is expected, makes sense for all scripts, just to avoid this type of bug in the future.

**Comment by derekbruening** [comment]
It seems that the Ubuntu-with-some-mods install used by some longstanding devs has /bin/sh swapped back to bash, so nobody else was hitting these issues.

The one question I'm not sure about is: what will happen to #!/bin/bash in a native git on Windows?  I believe #!/bin/sh ends up using a built-in shell layer in git.

**Comment by groleo** [comment]
Using msysgit (https://msysgit.github.io/) I tested both **#!/bin/sh** and **#!/bin/bash** in a pre-commit hook, with no errors; also **$(echo $SHELL)** was **/bin/sh** both cases

**Comment by derekbruening** [comment]
xref #1584
