### ISSUE TITLE
client.modules fails: module_unload_event() is never called

### ISSUE THREAD

**Issue by byron-hawkins** [DynamoRIO/dynamorio#1608]
This issue is apparently specific to my peculiar environment. On Windows 32-bit, the `module_unload_event()` never gets called for `ADVAPI32.DLL` at the end of client.modules. The `module_load_event()` gets called like normal for this lib. 

It's also strange that the log seems to be missing all the entries for `process_mmap()` in the 32-bit run--other log entries for level 2 are there, and in the 64-bit run all the `process_mmap()` entries are there. 

I'm not able to get a breakpoint to stop on module load or at a function or line number in windbg for this test. So I'm not quite sure how to go about debugging it.

**Comment by derekbruening** [comment]
Is advapi32.dll statically imported from?  If so it won't be unloaded.

Use the windbg events to stop or print on module load.

**Comment by byron-hawkins** [comment]
The module advapi32.dll is dynamically loaded by the test target, so there really should be an unload event (which is why it's in the `expect` file). 

The windbg module load events aren't working either for some reason, even thought it does show the module client.modules.dll.dll being loaded in the command output window.

**Comment by byron-hawkins** [comment]
The reason advapi32.dll was not getting unloaded is that the Windows application compatibility feature was in effect for the 32-bit build in an msys shell, and that feature loads advapi32.dll (along with several other modules) as static dependencies, making it impossible for Windows to unload advapi32.dll when the test app requests to. The resolution is to just change the test to use a module that is always available but doesn't get loaded for app compat (comdlg32.dll).
