### ISSUE TITLE
Finalize the annotation framework

### ISSUE THREAD

**Issue by byron-hawkins** [DynamoRIO/dynamorio#1613]
The annotation framework is currently available as a special build option. In the process of adding annotation tests to the suite (#1610) and considering special cases, minor corrections and adjustments may be necessary. After resolving these details and completing #1610, annotations will be enabled in the build by default.

**Comment by byron-hawkins** [comment]
An easy spot test for annotation overhead is to launch IE with the following page, which just exits IE:

```
<html>
<head>
<script language="JavaScript">
  document.write("closing in 1 second");
  // fool IE into thinking this is not a main window,
  // so closing needs no confirmation
  window.open('','_self','');
  window.close();
</script>
</head>
<body>
foo
</body>
</html>
```

It may be necessary to put the page on a webserver somewhere, or IE will not know what security domain it belongs in and will complain about running the script. The following DR options reduce noise in the test:

```
-disable_traces
-nop_initial_bblock
-fast_client_decode
````

**Comment by derekbruening** [comment]
Annotations are enabled by default now for x86.  For Mac we have the #1799 issue but that will be resolved once clang-9 is widespread.  The main issue is the lack of ARM and AArch64 support: #1672.
