### ISSUE TITLE
Ninja also requires explicit dependency on ntdll_imports

### ISSUE THREAD

**Issue by byron-hawkins** [DynamoRIO/dynamorio#1616]
The pre-commit suite occasionally fails to build using `ninja` in my environment because `ntdll_imports` can be scheduled after the `dynamorio` target. Adding an explicit dependency in cmake resolves the issue (this dependency is already explicit for the Visual Studio generator). My environment has MSVC 2012 in an msys shell on Windows 7 x64.

**Comment by derekbruening** [comment]
Unlike the other libs that use ntdll_imports, dynamorio links as a flag and not a target_link_libraries, which would explain this.  It is strange that we never saw this show up before, b/c it should have existed prior to #1588.
