### ISSUE TITLE
Destructors for Globals not Invoked on Client Termination

### ISSUE THREAD

**Issue by newgre** [DynamoRIO/dynamorio#1617]
What version of DynamoRIO are you using?

5.1.0-RC1

Does the latest build from
http://build.chromium.org/p/client.dynamorio/builds/ solve the problem?

No.

What operating system version are you running on?

Win7 x64

What application are you running?

notepad.exe

Is your application 32-bit or 64-bit?

32-bit

How are you running the application under DynamoRIO?

drrun -c test_client -- $PATH_TO_NOTEPAD

What happens when you run without any client?

N/A

What happens when you run with debug build ("-debug" flag to
drrun/drconfig/drinject)?

Everything works as expected - the file contains the text as it should!

What steps will reproduce the problem?
1. Compile attached test client and run it
2.
3.

What is the expected output? What do you see instead?  Is this an
application crash, a DynamoRIO crash, a DynamoRIO assert, or a hang (see
https://github.com/DynamoRIO/dynamorio/wiki/Bug-Reporting and set the title
appropriately)?

Output file should contain:
"Hello from client init\n"
"Good Bye!\n"

but it's empty.

Destructors are not executed properly; In the attached test client, the created file ("C:\temp\test_output.txt") stays empty, but should contain some text as the destructor of the global class instance writes to the file.

Please provide any additional information below.

Here is the test client to reproduce above behavior:

```
#include "dr_api.h"
#include <fstream>
#include <memory>

// Simple client to test tear down behaviour!
// Issue: without explicitly deleting the Test isntance, the file will be empty after the client quits.

class Test {
 public:
   Test() : stream_("C:\\temp\\test_output.txt") {}
  ~Test() {
    stream_ << data_.c_str();
  }
  void Add(std::string data) {
    data_ += data;
  }
 private:
  std::ofstream stream_;
  std::string data_;
};

std::unique_ptr<Test> g_test;  // NOT DESTROYED automatically! Thus, destructor of Test is never invoked!

static void event_exit(void);

DR_EXPORT void dr_init(client_id_t id) {
  dr_set_client_name("DynamoRIO Sample Client 'empty'", "http://dynamorio.org/issues");
  dr_register_exit_event(event_exit);
  g_test = std::make_unique<Test>();
  g_test->Add("Hello from client init!\n");
}

static void event_exit() {
  g_test->Add("Good Bye!\n");
  // Uncomment this line to make it output appear in the file.
  //g_test.reset();
}
```

**Comment by derekbruening** [comment]
The reason is pretty simple: we have a fast exit path for release build that avoids as much work as possible.  It was written before we focused on clients, or C++ clients in particular, and it does not call loader_exit() and thus does not call any fini or fini array or DllMain in any client or private library.  I suppose we'll have to live with the extra perf cost and put the call in.

**Comment by derekbruening** [comment]
The implemented fix is not quite correct as it crashes Dr. Memory release build 64-bit:

```
0:000> kn
  *** Stack trace for last set context - .thread/.cxr resets it
 # Child-SP          RetAddr           Call Site
00 00000000`bf57e8f0 00000000`cf51a030 dbghelp!dh+0x21b7
01 00000000`bf57e920 00000000`cf536726 dbghelp!dh+0x3660
02 00000000`bf57e9c0 00000000`cf528494 dbghelp!ImagehlpApiVersionEx+0x6766
03 00000000`bf57ea10 00000000`bf34827a dbghelp!SymUnloadModule64+0xe4
04 00000000`bf57ea70 00000000`bf33be35 drmemorylib!modtable_entry_free+0x3a [d:\derek\drmemory\git\src\dynamorio\ext\drsyms\drsyms_windows.c @ 187]
05 00000000`bf57eaa0 00000000`bf33bec0 drmemorylib!hashtable_clear_internal+0x95 [d:\derek\drmemory\git\src\dynamorio\ext\drcontainers\hashtable.c @ 472]
06 00000000`bf57eae0 00000000`bf345925 drmemorylib!hashtable_delete+0x20 [d:\derek\drmemory\git\src\dynamorio\ext\drcontainers\hashtable.c @ 497]
07 00000000`bf57eb10 00000000`bf330a39 drmemorylib!drsym_exit+0x45 [d:\derek\drmemory\git\src\dynamorio\ext\drsyms\drsyms_windows.c @ 248]
08 00000000`bf57eb40 00000000`bf2e3960 drmemorylib!utils_exit+0x9 [d:\derek\drmemory\git\src\common\utils.c @ 1364]
09 00000000`bf57eb70 00000000`71069cd4 drmemorylib!event_exit+0x90 [d:\derek\drmemory\git\src\drmemory\drmemory.c @ 429]
0a 00000000`bf57eba0 00000000`7102b389 dynamorio!instrument_exit+0x94 [d:\derek\drmemory\git\src\dynamorio\core\lib\instrument.c @ 692]
0b 00000000`bf57ec00 00000000`710b5329 dynamorio!dynamo_process_exit+0x359 [d:\derek\drmemory\git\src\dynamorio\core\dynamo.c @ 1414]
0c 00000000`bf57ec70 00000000`00000000 dynamorio!cleanup_and_terminate+0x7a [D:\derek\drmemory\build_suite\build_drmemory-rel-64\dynamorio\core\CMakeFiles\dynamorio.dir\arch\x86\x86.asm.obj.s @ 1808]
```

We need to delay the loader_thread_exit() for the current thread until after calling the client's exit event to avoid problems with private library state.
