### ISSUE TITLE
ctest erroneously reports passing test when .expect contains a semicolon

### ISSUE THREAD

**Issue by byron-hawkins** [DynamoRIO/dynamorio#1618]
When the `.expect` file for a test contains a semicolon (anywhere in the file), ctest will approve all runs of that test, even if the output is totally different from the contents of the `.expect` file. This is obviously a bug (or feature?) in ctest, but fairly treacherous for developing a new test. I'd suggest adding a `MATCHES` statement to cmake, which will exit the build with an error if any `.expect` file contains a semicolon.

**Comment by derekbruening** [comment]
Just add an escape for semicolon in the part of the code where we already escape regex chars like parentheses when we turn .expect into a cmake regex.
