### ISSUE TITLE
clean call optimizations on AArch64: out-of-line, analyze and reduce cxt sw, inline

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#1621]
We put in place basic unoptimized clean call support on ARM but all of the performance features are missing.  This issue covers adding out-of-line calls (maybe less nec b/c the register lists on ARM reduce code size) and analysis of callees to reduce context switch size and inline the callee where possible.

**Comment by fhahn** [comment]
Looks like #2094 addresses a similar issue. I'll update this ticket to only include AArch64 work and #2094 to cover the AArch32 work (the FIXMEs in ./core/arch/arm/clean_call_opt.c mention that issue)
