### ISSUE TITLE
asm build warnings w/ cross-compiler about IT block deprecation for ARMv8

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#1675]
We should either suppress these or decide we don't need to test these corner cases (probably former is better):

/work/dr/git/src/suite/tests/common/allasm_thumb.asm: Assembler messages:
/work/dr/git/src/suite/tests/common/allasm_thumb.asm:105: Warning: it blocks containing wide Thumb instructions are deprecated in ARMv8
/work/dr/git/src/suite/tests/common/allasm_thumb.asm:105: Warning: it blocks of more than one conditional instruction are deprecated in ARMv8
/work/dr/git/src/suite/tests/common/allasm_thumb.asm:110: Warning: it blocks of more than one conditional instruction are deprecated in ARMv8
/work/dr/git/src/suite/tests/common/allasm_thumb.asm:116: Warning: it blocks of more than one conditional instruction are deprecated in ARMv8
/work/dr/git/src/suite/tests/common/allasm_thumb.asm:122: Warning: it blocks of more than one conditional instruction are deprecated in ARMv8
/work/dr/git/src/suite/tests/common/allasm_thumb.asm:128: Warning: it blocks of more than one conditional instruction are deprecated in ARMv8
/work/dr/git/src/suite/tests/common/allasm_thumb.asm:148: Warning: it blocks containing wide Thumb instructions are deprecated in ARMv8
/work/dr/git/src/suite/tests/common/allasm_thumb.asm:150: Warning: it blocks containing wide Thumb instructions are deprecated in ARMv8
/work/dr/git/src/suite/tests/common/allasm_thumb.asm:166: Warning: it blocks containing wide Thumb instructions are deprecated in ARMv8
/work/dr/git/src/suite/tests/common/allasm_thumb.asm:166: Warning: it blocks of more than one conditional instruction are deprecated in ARMv8
/work/dr/git/src/suite/tests/common/allasm_thumb.asm:171: Warning: it blocks containing wide Thumb instructions are deprecated in ARMv8
/work/dr/git/src/suite/tests/common/allasm_thumb.asm:188: Warning: it blocks containing wide Thumb instructions are deprecated in ARMv8
/work/dr/git/src/suite/tests/common/allasm_thumb.asm:193: Warning: it blocks containing wide Thumb instructions are deprecated in ARMv8
/work/dr/git/src/suite/tests/common/allasm_thumb.asm:202: Warning: it blocks containing wide Thumb instructions are deprecated in ARMv8
/work/dr/git/src/suite/tests/common/allasm_thumb.asm:208: Warning: it blocks containing wide Thumb instructions are deprecated in ARMv8
/work/dr/git/src/suite/tests/common/allasm_thumb.asm:215: Warning: it blocks containing 16-bit Thumb intsructions of the following class are deprecated in ARMv8: Literal loads
/work/dr/git/src/suite/tests/common/allasm_thumb.asm:229: Warning: it blocks containing wide Thumb instructions are deprecated in ARMv8
/work/dr/git/src/suite/tests/common/allasm_thumb.asm:254: Warning: it blocks of more than one conditional instruction are deprecated in ARMv8

**Comment by fhahn** [comment]
This is currently blocking me from setting up precommit tests for AArch32, because with recent versions of GCC, the warnings are not prefixed with 'Warning' and ctest thinks they are errors. This causes the runsuite_wrapper.pl script to fail.

**Comment by fhahn** [comment]
I tried to add -mno-warn-deprecated for `allasm_thumb.asm`, but  it seems like no flags are passed through to the assembler in make/cpp2asm_support.cmake (except the global ASM_FLAGS). Do you have any ideas how to go about this @derekbruening ?

**Comment by derekbruening** [comment]
> I tried to add -mno-warn-deprecated for allasm_thumb.asm, but it seems like no flags are passed through to the assembler in make/cpp2asm_support.cmake (except the global ASM_FLAGS). Do you have any ideas how to go about this @derekbruening ?

See https://github.com/DynamoRIO/dynamorio/blob/master/make/cpp2asm_support.cmake#L315 where it may now work to pass rule_flags though which includes <FLAGS> which should include target flags set via cmake code.

**Comment by fhahn** [comment]
I think we would need to set the assembler flags separately. The GNU as does not support -OX options for example, and cpp does not support -mno-warn-deprecated :(

Would it be hard to add assembler flags using a source file property or something similar? Unfortunately I have no experience with Cmake Makefile generators.

**Comment by derekbruening** [comment]
I think such source file property flags will show up in <FLAGS.  I would look at what's in <FLAGS> today: is there anything there that cpp is using?  If not, for cmake 3.4+ we can pass it only to the assembler.

**Comment by fhahn** [comment]
Yes the problem is that FLAGS always seems to contain "-O2", which GNU as does not understand :( 

Adding -mno-warn-deprecated as a COMPILE_FLAGS source file property is easy.... I tried just using gcc to pre-preprocess and assemble, but then other things fell over. I am out of ideas.

**Comment by egrimley** [comment]
Would it be better if cmake did not invoke `/usr/bin/as` but instead used `/usr/bin/cc -x assembler`, or just `/usr/bin/cc`, as the assembler, on ARM and AArch64 at least? (I understand that people sometimes have to use a different assembler for Intel.)

Likewise for preprocessing: one doesn't have to invoke `cpp`; it is also possible to use `gcc -E`.

I generally do everything through the compiler driver. But perhaps cmake has a different preference.
