### ISSUE TITLE
gdb script commands crash gdb

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#1678]
The gdb script tools/libdynamorio.so-gdb.py has not been executing on my
Fedora machine for a long time due to failure to parse my gdb version
string.  Once I fixed that, though, the script has been crashing gdb.

At first I thought it was RunDR() doing the "set exec-wrapper" b/c it
worked when I removed it: but it's really non-det and it crashes about
half the time and the other half it works fine.

It looks like this:

```
# gdb --args bin32/drrun -debug -- /work/dr/test/hello
GNU gdb (GDB) Fedora 7.7.1-21.fc20
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from bin32/drrun...Reading symbols from /work/dr/git/build_x86_dbg/bin32/drrun.debug...done.
done.
(gdb) run
Starting program: /work/dr/git/build_x86_dbg/bin32/drrun -debug -- /work/dr/test/hello
WARNING: To successfully launch DynamoRIO from gdb, be sure to run 'set disable-randomization off' first.
process 28847 is executing new program: /work/dr/git/build_x86_dbg/lib32/debug/libdynamorio.so.5.0
Missing separate debuginfos, use: debuginfo-install glibc-2.18-19.fc20.i686
Loading gdb scripts for debugging DynamoRIO...
<Starting application /work/dr/test/hello (28847)>
Executing gdb command: add-symbol-file '/work/dr/git/build_x86_dbg/lib32/debug/libdynamorio.so' 0xf7013becL
<Paste into GDB to debug DynamoRIO clients:
set confirm off
add-symbol-file '/work/dr/git/build_x86_dbg/lib32/debug/libdynamorio.so' 0xf7013bec
>
Segmentation fault (core dumped)

# <Initial options = -no_dynamic_options -code_api -stack_size 56K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
Hello world!
Goodbye world!
<Stopping application /work/dr/test/hello (28847)>
```

**Comment by zhaoqin** [comment]
I just tried my machine:

> gdb --args bin64/drrun -debug -- ./suite/tests/bin/common.fib
GNU gdb (GDB) 7.9-gg5
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-grtev4-linux-gnu".
Type "show configuration" for configuration details.

<http://go/gdb-home  FAQ: http://go/gdb-faq  Email: gdb-team  IRC: gdb>
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Reading symbols from bin64/drrun...Reading symbols from /usr/local/google/home/zhaoqin/Workspace/DynamoRIO/builds/build_x64_dbg.git/bin64/drrun.debug...done.
Unable to determine compiler version.
Skipping loading of libstdc++ pretty-printers for now.
done.
(gdb) run
Starting program: /usr/local/google/home/zhaoqin/Workspace/DynamoRIO/builds/build_x64_dbg.git/bin64/drrun -debug -- ./suite/tests/bin/common.fib
process 19095 is executing new program: /usr/local/google/home/zhaoqin/Workspace/DynamoRIO/builds/build_x64_dbg.git/lib64/debug/libdynamorio.so.5.0
Unable to determine compiler version.
Skipping loading of libstdc++ pretty-printers for now.
Loading gdb scripts for debugging DynamoRIO...
Traceback (most recent call last):
  File "/usr/local/google/home/zhaoqin/Workspace/DynamoRIO/builds/build_x64_dbg.git/lib64/debug/libdynamorio.so.5.0-gdb.py", line 171, in <module>
    PrivloadBP()
  File "/usr/local/google/home/zhaoqin/Workspace/DynamoRIO/builds/build_x64_dbg.git/lib64/debug/libdynamorio.so.5.0-gdb.py", line 137, in __init__
    internal=not self.DEBUG)
RuntimeError: Cannot access memory at address 0x712f4c52

**Comment by derekbruening** [comment]
Closing in favor of duplicate #2100
