### ISSUE TITLE
Function tracing

### ISSUE THREAD

**Issue by farhanshariff2013** [DynamoRIO/dynamorio#1696]
I want to know if it possible to record fucntion names, input output parameters per thread 
using DynamoRio and its tools?

**Comment by derekbruening** [comment]
Normally something like this should be asked on the mailing list (https://groups.google.com/forum/#!forum/DynamoRIO-Users).  The issue tracker is for filing bug reports and feature requests.

The answer is yes, core DR has routines to get exported names and drsyms has support for function names from debug info.  drwrap has support for acquiring function parameter values.
