### ISSUE TITLE
Support inserting clean calls and other ctis prior to predicated instructions (in IT blocks) in Thumb mode

### ISSUE THREAD

**Issue by zhaoqin** [DynamoRIO/dynamorio#1702]
On ARM Thumb code, a cti instrution can only be the last instruction of an IT block, and this makes it tricky to insert a clean call or other cti instructions within an IT block.
Currently DynamoRIO automatically reinstates the IT block with instrumented code but did not check if the cti instruction (e.g., the instruction jumps to clean call callee) is the last instruction of the IT block, which makes inserting clean call for a predicated instruction in IT blocks fail.

**Comment by derekbruening** [comment]
It's not DR who reinstates, it's drmgr

**Comment by derekbruening** [comment]
This seems solvable: the branch part is easy, we just need enough consecutive IT blocks so that each branch/call ends one.  The hard part is with the flags: they won't hold the original value on first coming back from the callee.  We could solve with an explicit check and jump, or we could disallow the out-of-line call when inside an IT block.  The latter may be better to avoid internal control flow which complicates drreg, and it's easier to make it part of dr_insert_it_instrs().

**Comment by toshipiazza** [comment]
I'm a little confused by this. If we insert a clean call in the middle of an IT-block in Thumb mode, as in `{memtrace,instrace}_simple`, why would there be a problem? Since neither of these samples are predicating anything emitted by the clean call, `dr_insert_it_instrs()` would never produce a non-terminating cbr into an IT-block, right? Yet we still explicitly do not place clean calls in this case.

**Comment by derekbruening** [comment]
That sounds right: if the inserted clean call is not predicated there will be no problem (assuming the tool wants it un-predicated).  This issue should just be about a clean call or other instrumentation that is predicated to match its corresponding app instruction in the IT block.

**Comment by toshipiazza** [comment]
Noted. Should we remove the `i#1702:` comments and associated checks in these samples?

> The hard part is with the flags: they won't hold the original value on first coming back from the callee. We could solve with an explicit check and jump, or we could disallow the out-of-line call when inside an IT block.

Just to make sure, if we do disable out-of-line calls and inlining, then the client only needs to predicate the `blx` instruction emitted by `dr_insert_clean_call()`, right? This way they don't have to worry about `cspr` being clobbered and other associated problems.

**Comment by derekbruening** [comment]
Are you sure we don't want to predicate these clean calls?  I don't remember what they're used for: if they're for the buffer filling up and aren't really related to the instr they're inserted in front of, then I guess not.

> > The hard part is with the flags: they won't hold the original value on first coming back from the callee. We could solve with an explicit check and jump, or we could disallow the out-of-line call when inside an IT block.
> 
> Just to make sure, if we do disable out-of-line calls and inlining, then the client only needs to predicate the `blx` instruction emitted by `dr_insert_clean_call()`, right? This way they don't have to worry about `cspr` being clobbered and other associated problems.

You're suggesting, for situations where a client does want to predicate a clean call, it could unconditionally run all the code except the actual call itself?

**Comment by toshipiazza** [comment]
> if they're for the buffer filling up and aren't really related to the instr they're inserted in front of, then I guess not.

Actual usage [here](https://github.com/DynamoRIO/dynamorio/blob/master/api/samples/memtrace_simple.c#L316). They are only related to clearing the buffer, and don't depend on the predication of the instruction themselves. This is the case for both memtrace and instrace, I believe. I will file an issue.

> You're suggesting, for situations where a client does want to predicate a clean call, it could unconditionally run all the code except the actual call itself?

Yes, I have been using this workaround in testing (specifically for `drx_buf_insert_buf_memcpy()`), and it seems to work (given that no inlining occurs for my particular routine). Not sure if this should be the recommended way to do things though.

**Comment by toshipiazza** [comment]
Alternatively, we could suggest people do the more intuitive thing and create an explicit conditional jmp over the clean call. This does seem a lot cleaner, and also doesn't seem brittle like my previous idea. In that case this current issue does need to be addressed, to allow cbr's to be handled correctly in `dr_insert_it_instrs()`.

Your call @derekbruening, which do you prefer? I already had a patch planned for this issue (to address cbr's). Do you prefer an explicit conditional jump, or just predicating the `blx` instruction?

**Comment by derekbruening** [comment]
Sounds fine. Could this be automated in some way?  Some tools today have
one component blindly predicate all instru inserted by other components:
that predicator might not know whether there's a clean call in there.

**Comment by toshipiazza** [comment]
I can't think of a good way to automate this. My plan was to simply make `drx_buf_insert_buf_memcpy()` take an extra `pred` option, and suggest other tools which emit clean calls do the same.

**Comment by derekbruening** [comment]
Here is how drcachesim's tracer predicates afterward, avoiding complicating library routines by adding options to have them insert predication:https://github.com/DynamoRIO/dynamorio/blob/master/clients/drcachesim/tracer/instru_offline.cpp#L286

**Comment by toshipiazza** [comment]
Unfortunately I can't think of a clean way to automate predicating the clean call (short of modifying the callee to restore `cspr` before each ret, i.e. as part of `analyze_clean_call`, though this is probably infeasible in the general case).

However, would it be worth it to take the `drx_buf_insert_update_buf_ptr()` out of `drx_buf_insert_buf_memcpy()`? If we did this, then the user could *at least* predicate the buffer pointer update routine, and we could document that the memcpy routine should not be predicated.

**Comment by toshipiazza** [comment]
Nevermind, I don't think it would work to simply predicate the update routine and not the memcpy routine, since it's possible for the load in `insert_load` to fault, if we don't predicate it correctly. Will continue to think over a general solution for automating predicating a clean call as that is what would work best here.

**Comment by toshipiazza** [comment]
Sorry about the delay, I've been mulling over some possible implementations. 

I propose a routine (which can live in utils.c, for example -- it's just for clients), which functions the same as in [instru_offline.cpp#L286](https://github.com/DynamoRIO/dynamorio/blob/master/clients/drcachesim/tracer/instru_offline.cpp#L286), except in the case that it detects an instruction is part of a clean call, will emit an explicit jump instead (from the top of the clean call).

Unfortunately, it's not so easy to determine if an instruction is part of a clean call. Could we maybe use the note API to mark all instructions in a clean call?

**Comment by derekbruening** [comment]
You're talking about just something for drcacheim?  Could we generalize further?  Xref #1723 which is about auto-predication.  We implemented a form of auto-predication but then reverted it: https://github.com/DynamoRIO/dynamorio/commit/f28be26e4c98e5f58334d172205fe809f295cf39#diff-3dc105a6394e27276cd720d261cbc39dR673

Should we revisit that drmgr-based auto-predication?  If we can come up with a way to control it when it's not wanted, and to handle clean calls.

**Comment by derekbruening** [comment]
> Unfortunately, it's not so easy to determine if an instruction is part of a clean call. Could we maybe use the note API to mark all instructions in a clean call?

Yes that should work.

**Comment by toshipiazza** [comment]
> You're talking about just something for drcacheim

Nope, I'm just using drcachesim for inspiration, but we can encapsulate this behavior (plus correct handling of clean calls) in a routine for *all* samples pretty easily. If we choose to put this routine in drmgr itself it can be used as part of drmgr-based auto-predication. Will add some discussion in #1723 as to what we'd like the API to look like.

**Comment by toshipiazza** [comment]
Considering auto-predication (#1723 mentions an `instrlist_set_translation()`-type approach), we won't need to use the note API I mentioned earlier (which I considered pretty fragile)--from any internal DR component that inserts instrumentation that's not directly compatible with auto predication, e.g. `dr_insert_clean_call()`, it can detect and handle it internally via the instrlist flag.
