### ISSUE TITLE
out-of-line clean call

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#171]
_From [derek.br...@gmail.com](https://code.google.com/u/117968039472581148324/) on July 23, 2009 15:07:14_

xref issue #42 /PR 307874: optimize and shrink clean call sequences

another approach to deal with the large clean call footprint, for
frequently-inserted clean calls where cache expansion is a key concern, is
to use an out-of-line common clean call sequence that is transferred to
from each call site using a small-footprint transfer.  we should consider
adding direct support for this in DR.  the client could provide us with a
+x mem region where we'll put the shared clean call code and then call a
new routine insert_transfer_to_clean_call() or sthg.

_Original issue: http://code.google.com/p/dynamorio/issues/detail?id=171_

**Comment by zhaoqin** [comment]
We perform out-of-line clean call for both x86 and x86_64.
On x86, the register save/restore is simple: pusha/popa. However the xmm/ymm registers save/restore is space consuming, so the out-of-line would still likely be a win.
Code snippet about a clean call save.
```
  0x4d9d2a4e  c5 fd 7f 44 24 18    vmovdqa %ymm0 -> 0x18(%esp)[32byte]
  0x4d9d2a54  c5 fd 7f 4c 24 38    vmovdqa %ymm1 -> 0x38(%esp)[32byte]
  0x4d9d2a5a  c5 fd 7f 54 24 58    vmovdqa %ymm2 -> 0x58(%esp)[32byte]
  0x4d9d2a60  c5 fd 7f 5c 24 78    vmovdqa %ymm3 -> 0x78(%esp)[32byte]
  0x4d9d2a66  c5 fd 7f a4 24 98 00 vmovdqa %ymm4 -> 0x98(%esp)[32byte]
              00 00
  0x4d9d2a6f  c5 fd 7f ac 24 b8 00 vmovdqa %ymm5 -> 0xb8(%esp)[32byte]
              00 00
  0x4d9d2a78  c5 fd 7f b4 24 d8 00 vmovdqa %ymm6 -> 0xd8(%esp)[32byte]
              00 00
  0x4d9d2a81  c5 fd 7f bc 24 f8 00 vmovdqa %ymm7 -> 0xf8(%esp)[32byte]
              00 00
  0x4d9d2a8a  68 00 00 00 00       push   $0x00000000 %esp -> %esp 0xfffffffc(%esp)[4byte]
  0x4d9d2a8f  9c                   pushf  %esp -> %esp 0xfffffffc(%esp)[4byte]
  0x4d9d2a90  60                   pusha  %esp %eax %ebx %ecx %edx %ebp %esi %edi -> %esp 0xffffffe0(%esp)[32byte]
```
