### ISSUE TITLE
Build can fail to generate include/dr_api.h after 'make clean'

### ISSUE THREAD

**Issue by algr** [DynamoRIO/dynamorio#1711]
If you do
```
cmake
make
make clean
make
```
the 'make clean' will delete dr_api.h but the subsequent 'make' won't then rebuild it:
```
root@sdperf-ve2:~/dynamorio/build# make
[  1%] Built target generate_syslog
[  2%] Built target drhelper
[ 13%] Built target drdecode
[ 16%] Built target drinjectlib
[ 19%] Built target drpreload
[ 19%] Generating include/dr_app.h, include/dr_api.h
[ 19%] Built target api_headers
[ 67%] Built target dynamorio
[ 69%] Built target drconfiglib
[ 72%] Built target drfrontendlib
[ 72%] Built target drconfig
[ 73%] Built target drinject
[ 74%] Built target drloader
[ 75%] Built target drrun
[ 76%] Built target nudgeunix
[ 77%] Built target run_in_bg
[ 77%] Built target runstats
[ 78%] Building C object ext/drcontainers/CMakeFiles/drcontainers.dir/hashtable.c.o
/root/dynamorio/ext/drcontainers/hashtable.c:39:20: fatal error: dr_api.h: No such file or directory
compilation terminated.
make[2]: *** [ext/drcontainers/CMakeFiles/drcontainers.dir/hashtable.c.o] Error 1
make[1]: *** [ext/drcontainers/CMakeFiles/drcontainers.dir/all] Error 2
make: *** [all] Error 2
root@sdperf-ve2:~/dynamorio/build# find .. -name dr_app.h
../core/lib/dr_app.h
../build/include/dr_app.h
root@sdperf-ve2:~/dynamorio/build# find .. -name dr_api.h
../core/lib/dr_api.h
```
CMakeFiles/api_headers.dir/build.make is written as if genapi.pl creates include/dr_api.h as well as include/dr_app.h (and it prints "Generating... include/dr_api.h").  But genapi.pl has comments saying "dr_api.h is now created at configure time", "dr_api.h is copied by top-level CMakeLists.txt" .

Should include/dr_api.h be deleted by 'make clean'?  If not, then api_headers.dir/build.make shouldn't delete it.  But if it should, the same makefile needs a rule to rebuild it.

**Comment by derekbruening** [comment]
Cannot reproduce:

```
% mkdir build_foo
% cd build_foo
% cmake ../src && make && make clean && make && echo success
...
[100%] Built target drcov2lcov
success
```

This is with cmake version 2.8.12.2, gcc version 4.8.3 20140911, GNU Make 3.82.

**Comment by derekbruening** [comment]
Please investigate whether this is limited to a particular cmake version.

**Comment by algr** [comment]
It looks like there might be some sensitivity to cmake version, although I don't think this is the root cause (see below).  I tried Intel (cmake 2.8.12 and 2.8.9) and ARM (cmake 2.8.10.1) and only 2.8.12 worked.

- 'cmake ..' creates include/dr_api.h on both systems, using configure_file()

- 'make clean' deletes include/dr_api.h on both systems

- with all cmake versions the first action that the cmake-generated Makefile has 'make' do is cmake_check_build_system, which runs 'cmake -Hroot -Broot/build --check-build-system CMakeFiles/MakeFile.cmake', and that only creates include/dr_api.h when the makefile was built with 2.8.12

- when 'cmake ..' creates build/CMakeFiles/MakeFile.cmake, with cmake 2.8.12 there is an entry for "include/dr_api.h" in CMAKE_MAKEFILE_PRODUCTS.  With cmake 2.8.10 and 2.8.9 there isn't, and overall that section is much smaller, it's missing other configure_file() targets too.

But that's not the root cause. Why was 'make clean' deleting a file that was created by cmake's Makefile generation, and not by make? It's because CMakeLists.txt declares include/dr_api.h as an output of genapi.pl, when it is not. Once this is fixed to declare include/dr_app.h as the only output, 'make clean' no longer deletes include/dr_api.h, the makefile no longer thinks it's rebuilding it and the make log is now correct:
```
Scanning dependencies of target api_headers
[ 19%] Generating include/dr_app.h
[ 19%] Built target api_headers
```

**Comment by derekbruening** [comment]
An aside: note that I can't recall the last time I ran "make clean" with a cmake-based project as cmake has proper dependence checking for incremental builds, and "make clean" is not sufficient to start over with a new configuration: the recommendation is just to blow the build dir away if re-configuring with different-enough config params.

**Comment by derekbruening** [comment]
Thank you for investigating and finding the bug.  If you are interested in directly contributing the fix we would welcome a patch: see https://github.com/DynamoRIO/dynamorio/wiki/Contributing
