### ISSUE TITLE
Add drwrap_redirect_execution

### ISSUE THREAD

**Issue by byron-hawkins** [DynamoRIO/dynamorio#1713]
Add a new function to the drwrap API: redirect execution following the drwrap_wrap post-function callback(s). The primary goal is to support repeating the wrapped function, but it can be used to redirect the return of the wrapped function to any location. This new function is necessary because dr_redirect_execution() will interfere with the internal accounting of drwrap if it is invoked from a post-function callback.

xref drmem-issue [#1734](https://github.com/DynamoRIO/drmemory/issues/1734)

**Comment by derekbruening** [comment]
Could you comment as to why this is needed: why dr_redirect_execution() can't just be used as-is.

**Comment by derekbruening** [comment]
The drwrap-test now fails on ARM:

```
in repeatme with arg 3
  <post-repeat#1>
<Source operand #0 has wrong type/size>
<Application /home/derek/dr/git/build_local/suite/tests/bin/client.drwrap-test (21289) DynamoRIO usage error : instr_encode error: no encoding found (see log)>
```
