### ISSUE TITLE
Add cmake policy CMP0054

### ISSUE THREAD

**Issue by byron-hawkins** [DynamoRIO/dynamorio#1718]
CMake version 3.2.3 requires a new policy CMP0054 set to "OLD" to allow dereferencing of quoted variables. The default policy is still "OLD", but there is a warning (and with the "NEW" policy, quoted variables will be taken as literals).

**Comment by hgreving2304** [comment]
xref #1774

**Comment by derekbruening** [comment]
The warning from this in CMake 3.3+ is really annoying (#1774: closed as dup since fixing it is the same as fixing this) (along with CMP0042 (i#1375) and CMP0058 (#1955, now fixed)): it is printed for every policies.cmake include.
