### ISSUE TITLE
code_api|client.exception test failure

### ISSUE THREAD

**Issue by zhaoqin** [DynamoRIO/dynamorio#1722]
(precise)zhaoqin@localhost:~/Workspace/DynamoRIO/builds/build_a32_dbg.svn$ ctest -V -I 73,73
UpdateCTestConfiguration  from :/home/zhaoqin/Workspace/DynamoRIO/builds/build_a32_dbg.svn/DartConfiguration.tcl
Parse Config file:/home/zhaoqin/Workspace/DynamoRIO/builds/build_a32_dbg.svn/DartConfiguration.tcl
UpdateCTestConfiguration  from :/home/zhaoqin/Workspace/DynamoRIO/builds/build_a32_dbg.svn/DartConfiguration.tcl
Parse Config file:/home/zhaoqin/Workspace/DynamoRIO/builds/build_a32_dbg.svn/DartConfiguration.tcl
Test project /home/zhaoqin/Workspace/DynamoRIO/builds/build_a32_dbg.svn
Constructing a list of tests
Done constructing a list of tests
Checking test dependency graph...
Checking test dependency graph end
test 73
    Start 73: code_api|client.exception

73: Test command: /home/zhaoqin/Workspace/DynamoRIO/builds/build_a32_dbg.svn/bin32/drrun "-s" "60" "-quiet" "-debug" "-killpg" "-ops" "-stderr_mask 0xC -dumpcore_mask 0  -code_api -client_lib '/home/zhaoqin/Workspace/DynamoRIO/builds/build_a32_dbg.svn/suite/tests/bin/libclient.exception.dll.so;0;'  -code_api " "/home/zhaoqin/Workspace/DynamoRIO/builds/build_a32_dbg.svn/suite/tests/bin/simple_app"
73: Test timeout computed to be: 1500
73: dl_iterate_phdr returned 0
73: about to throw
73: <Application /home/zhaoqin/Workspace/DynamoRIO/builds/build_a32_dbg.svn/suite/tests/bin/simple_app (6494).  Internal Error: DynamoRIO debug check failure: /home/zhaoqin/Workspace/DynamoRIO/dynamorio.svn/core/unix/signal.c:4084 memcmp(&try_cxt->context.sigmask, &ucxt->uc_sigmask, sizeof(ucxt->uc_sigmask)) == 0
73: (Error occurred @0 frags)
73: version 5.0.2914, custom build
73: -no_dynamic_options -client_lib '/home/zhaoqin/Workspace/DynamoRIO/builds/build_a32_dbg.svn/suite/tests/bin/libclient.exception.dll.so;0;' -code_api -stderr_mask 12 -stack_size 56K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_manage
73: /home/zhaoqin/Workspace/DynamoRIO/builds/build_a32_dbg.svn/suite/tests/bin/libclient.exception.dll.so=0xb6fab000
73: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6=0xb6f03000
73: /lib/arm-linux-gnueabihf/libgcc_s.so.1=0xb6d81000
73: /lib/arm-linux-gnueabihf/libm.so.6=0xb6e98000
73: /lib/arm-linux-gnueabihf/libc.so.6=0xb6d93000
73: /lib/ld-linux-armhf.so.3=0xb6e77000>
1/1 Test #73: code_api|client.exception ........***Failed  Required regular expression not found.Regex=[^dl_iterate_phdr returned 0
about to throw
caught runtime_error test throw
all done
Hello, world!
$
]  0.05 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.61 sec

The following tests FAILED:
         73 - code_api|client.exception (Failed)
Errors while running CTest

**Comment by zhaoqin** [comment]
duplicated i#1717

**Comment by derekbruening** [comment]
Wait, are you sure this is a dup?  The test should pass on Linux.  The output looks weird, it's missing a line or two: that's an ASSERT I assume.

**Comment by derekbruening** [comment]
Or do you mean to place the task of fixing this ASSERT under #1717?

**Comment by zhaoqin** [comment]
Seems #1717 is a different assert, reopen it.
