### ISSUE TITLE
add controllable auto-predication of instrumentation to match application predication

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#1723]
Split from #1551

In f28be26e4c98e5f58334d172205fe809f295cf39 we added auto-predication of instrumentation in Thumb IT blocks, but it was asymmetric wrt ARM mode and we abandoned it.  We have cases of instrumentation where we do not want predication (e.g., drcachesim tracer's instr fetch instrumentation) and thus we need to give some control to the client.

To re-add the feature, we should have it apply to both Thumb and ARM, and have it controllable by the client.  The proposal is to have both blacklist and whitelist modes: a global flag of some kind indicating whether to always add or never add, and individual flags on instrs overriding the global.

**Comment by derekbruening** [comment]
We could also consider an instrlist flag akin to instrlist_set_translation_target, though the client would have to call it in every bb event; or this flag could be how some global thing is implemented internally.

**Comment by derekbruening** [comment]
Xref #1555 though we are not a fan of such a solution

**Comment by derekbruening** [comment]
We already have automated IT block handling via dr_remove_it_instrs() and dr_insert_it_instrs() which are called by drmgr.

**Comment by derekbruening** [comment]
Here is a direct pointer to the auto-predication we added and then removed: https://github.com/DynamoRIO/dynamorio/commit/f28be26e4c98e5f58334d172205fe809f295cf39#diff-3dc105a6394e27276cd720d261cbc39dR673

Here is how drcachesim's tracer predicates currently: https://github.com/DynamoRIO/dynamorio/blob/master/clients/drcachesim/tracer/instru_offline.cpp#L286

**Comment by derekbruening** [comment]
Xref #1702 and issues with predicating clean calls

**Comment by toshipiazza** [comment]
If we consider using something akin to `instrlist_set_translation_target()`, will that work well in the presence of tools utilizing multiple drmgr passes, like drreg?

If I remember correctly, drreg can lazily spill/restore things in a late drmgr pass, so this late pass might see no predication flag even though at the time of `drreg_reserve_register()` the predication flag was set. Is the solution just not to attempt to predicate `drreg_reserve_register()` and friends?

We could also make drreg changes to support this, but I don't know how feasible it is.

**Comment by derekbruening** [comment]
> ...will that work well in the presence of tools utilizing multiple drmgr passes, like drreg?
> ...If I remember correctly, drreg can lazily spill/restore things in a late drmgr pass, so this late pass might see no predication flag even though at the time of drreg_reserve_register() the predication flag was set. 

Could you elaborate on why drreg's code wouldn't see the flag?  The 4 drmgr phases, including the late drreg events, operate on a single instrlist, so the flag would still be there, right?

**Comment by toshipiazza** [comment]
Forgot to respond to this. I ran some tests and drreg does crash when we enabled auto predication globally, though it's probably not the same reason I had thought (you are correct in saying that the flag would still be there if we set the flag in a previous drmgr pass). More work needs to be done to analyze exactly why drreg breaks.
