### ISSUE TITLE
drcachesim: Assertion (VA=0 || PA !=0) failure 

### ISSUE THREAD

**Issue by peterpengwei** [DynamoRIO/dynamorio#1735]
When running Command "sudo ./bin64/drrun -debug -root ~/DynamoRIO/dynamorio_x86_test -t drcachesim -ipc_name mypipe -use_physical -- ls" in an X64 Ubuntu desktop computer, the assertion in Function memtrace(...) in $DYNAMORIO_HOME/clients/drcachesim/tracer/tracer.cpp failed. After commenting out the assertion, the command runs successfully after commenting out the assertion.

It seems to be possible that the physical address is 0 while the virtual address is not 0 in a program, or there might be something wrong with the VA->PA translation.

**Comment by zhaoqin** [comment]
you do not have to comment out the assert, you can use the option -ignore_assert_list "/path/to/the/assert/file:line" to ignore the assert.
Also could you print the possible mapping table between VA and PA there?
If it does allow mapping from non-zero VA to zero PA, I think the fix is just to remove the assertion.

**Comment by peterpengwei** [comment]
I added some debugging info and found that the assertion failure is due to a "return 0" in Line 131 of $DYNAMORIO_HOME/clients/drcachesim/tracer/physaddr.cpp. It seems that the if statement of Line 130 is true.

**Comment by derekbruening** [comment]
What is the return value of read() there?

**Comment by peterpengwei** [comment]
It returns 0.

**Comment by derekbruening** [comment]
Actually I can reproduce this, will take a look.

**Comment by derekbruening** [comment]
One problem we have is that va2pa will fail on recent kernels, or even on sort-of-recent distros that have backported the change (e.g., Fedora with 3.19 kernel).  Thus we cannot easily add a test on our suite as it will become a flaky test.

**Comment by derekbruening** [comment]
This is a bug in the tracer's redzone optimization: it fills the redzone with -1, yet optimizes 64-bit PC writes to not bother to fill in the top bits.  Thus we end up with 0xffffffff00411b0e instead of 0x411b0b and try to read beyond EOF in the pagemap.

**Comment by peterpengwei** [comment]
The "ls" command passed, but the same error occurred in another application. When I tried to run octane on the same x64 machine via "sudo ./bin64/drrun -debug -max_bb_instrs 256 -t drcachesim -ipc_name mypipe -use_physical -- /bin/bash /PATH/TO/OCTANE/run x86_64 octane", the same error occurs again.

**Comment by zhaoqin** [comment]
Did you try the latest checkout, there were a bug yesterday may cause the problem.

**Comment by peterpengwei** [comment]
Yeah. I checked it out and tried it this afternoon. You know, the "ls"
command works correctly now, which means the bug fixing takes effect for
this case. But just in case, I will double-check it tomorrow morning.

**Comment by peterpengwei** [comment]
The package in my copy is the newest one and I still encountered the problem in Octane. To reproduce the phenomenon, you make need to run octane on Linux in a x64 machine. Here is the command that I ran octane in my workstation: "sudo ./bin64/drrun -debug -max_bb_instrs 256 -t drcachesim -ipc_name mypipe -use_physical -- /bin/bash ~/workloads/Google-WLs/run x86_64 octane". To run octane, find the "run" bash script in the Google-WLs package, and set it to be run in x86_64 mode for a x64 machine.

**Comment by derekbruening** [comment]
If you have it in front of you, it would be great if you could investigate: the virtual to physical code is very simple.  Look at what virtual address is being translated: is the address not allocated or something and the resulting offset is off the end of the pagemap file?

**Comment by zhaoqin** [comment]
I can reproduce one:
The address is:
(gdb) p/x mem_ref->addr
$8 = 0xffffffffff5ff0a8

It is a strange place that Linux store some kernel information data (e.g., time) that can be read from user space without entering kernel mode for better performance, but it is not listed in the /proc/self/maps
      0x7ffca1346000     0x7ffca1348000     0x2000        0x0 [vdso]
  0xffffffffff600000 0xffffffffff601000     0x1000        0x0 [vsyscall]

It looks like we should disable the assert.

**Comment by derekbruening** [comment]
It's not maps that matter, it's pagemap.  If it's not in the pagemap file,
what phys addr are you going to use?

**Comment by zhaoqin** [comment]
The app code is
   0x7fff386fdf60 <time>:       push   %rbp
   0x7fff386fdf61 <time+1>:     test   %rdi,%rdi
   0x7fff386fdf64 <time+4>:     mov    0xffffffffff5ff0a8,%rax
   0x7fff386fdf6c <time+12>:    mov    %rsp,%rbp
A typical way to get time info without entering the kernel mode.

On translating VA to PA:
(gdb) p/x vpage
$15 = 0xffffffffff5ff000
(gdb) p/x vpage>>9
$16 = 0x7fffffffffaff8
at line 127: if (lseek64(fd, vpage >> 9, SEEK_SET) < 0)
lseek64 returns 0x7fffffffffaff8, which seems succeed.
at line 137: if (read(fd, (char *)&entry, sizeof(entry)) != sizeof(entry))
read() returns 0
(gdb) p/x $rax
$24 = 0x0
which indicate read failure.
And  physaddr.virtual2physical() returns 0.

      0x7ffeda7f0000     0x7ffeda7f2000     0x2000        0x0 [vdso]
  0xffffffffff600000 0xffffffffff601000     0x1000        0x0 [vsyscall]
I tried call physaddr.virtual2physical(0xffffffffff600000), which returns 0 too.
So my guess is the physical address for vsyscall and the kernel space is not translated via this pagemap.

**Comment by derekbruening** [comment]
We don't need to guess: is the offset beyond the end of the pagemap file, as implied by read() returning 0?  And if there's no translation what is a reasonable workaround?
