### ISSUE TITLE
file descriptor isolation fails to watch SYS_prlimit64

### ISSUE THREAD

**Issue by zhaoqin** [DynamoRIO/dynamorio#1739]
Running some chrome test, I saw:
<app trying to close DR file(s)>
[0717/130009:FATAL:launch_posix.cc(328)] Check failed: ret == 0. : Bad file descriptor

More log shows:
system call 6
SYSLOG_WARNING: app trying to close DR file(s)
WARNING: app trying to close DR file 4000!  Not allowing it.

This means we did not handle some getrlimit call correctly.

From the log, I also saw
system call 369
Exit from system call
post syscall: sysnum=0x00000171, result=0x00000000 (0)

From source code for ARM
 # define __NR_prlimit64                  (__NR_SYSCALL_BASE+369)

It seem we did not handle system call prlimit64.

**Comment by derekbruening** [comment]
xref https://github.com/DynamoRIO/drmemory/issues/1019
