### ISSUE TITLE
add DR_ASSERT_CURIOSITY

### ISSUE THREAD

**Issue by zhaoqin** [DynamoRIO/dynamorio#1744]
We have DR_ASSERT to assert on unexpected failures.
We should have DR_ASSERT_CURIOSITY to report unexpected but non-critical issues, e.g., #1735  virtual address to physical address translation failure.

**Comment by derekbruening** [comment]
I'm not sure this can easily be provided by the DR API: it completely depends on the tool and how the tool wants to log or print or notify a user.

**Comment by zhaoqin** [comment]
It should be similar to DR_ASSERT_MSG without calling dr_abort.
We just provide a default one, if the client has different way of log/notification, they will implement the one they need.

**Comment by derekbruening** [comment]
It still does not seem like a good idea to me.  We don't provide DR_WARN_USER or DR_INFO_MSG_TO_USER.

**Comment by zhaoqin** [comment]
Then I guess we just do not implement it.
