### ISSUE TITLE
DRCacheSim: error occurred after certain commit when run with Chrome OS on an ARM-based Chromebook

### ISSUE THREAD

**Issue by peterpengwei** [DynamoRIO/dynamorio#1754]
I tried to run DynamoRIO with DRCacheSim with Chrome OS on an ARM-based Chromebook, it failed with an "out of memory" error. I checked back all the previous commits, and found that after the following commit, it does not work any more. The command line is "./bin32/drrun -t drcachesim -ipc_name mypipe -- suite/tests/bin/common.fib". 

commit 11dc4620f8b01e29a116dd72333b6c43f7dd39ae
Author: Derek Bruening <bruening@google.com>
Date:   Thu Jul 23 13:57:51 2015 -0400

    i#1747 no-libc on Linux: -nostdlib and string routines redirection
    
    Adds !DynamoRIO_USE_LIBC support for Linux by passing -nostdlib to the
    compiler.
    
    Adds redirection of string and memory routines by our private loader to our
    private versions inside DR.
    
    Fixes #1747
    
    Review-URL: https://codereview.appspot.com/255410043

**Comment by derekbruening** [comment]
The drcachesim tests on ARM passed for that commit:

```
 7/95 Test #89: code_api|tool.drcachesim.phys ...................   Passed   11.04 sec
21/95 Test #88: code_api|tool.drcachesim.simple .................   Passed   14.65 sec
22/95 Test #92: code_api|tool.drcachesim.multiproc ..............   Passed   33.95 sec
83/95 Test #90: code_api|tool.drcachesim.thumb ..................   Passed    0.96 sec
86/95 Test #91: code_api|tool.drcachesim.arm ....................   Passed    0.87 sec
```

**Comment by derekbruening** [comment]
It's not clear why that CL would have any effect, because as a C++ client, the drcachesim tracer should always be forced to use libc.

**Comment by zhaoqin** [comment]
The failure happens on chromeos not Linux,   I was debugging it today,
suspect something related to private loader or symbol relocation. One
problem is the IPC_name default value is wrong. Trying to finde the cause.

**Comment by derekbruening** [comment]
OK, I added an OpSys-ChromeOS label.  Please remember to use the labels.

**Comment by zhaoqin** [comment]
Ok, at least find one bug, it is indirectly exposed by the commit 11dc4620f8b01e29a116dd72333b6c43f7dd39ae.
This commit adds !DynamoRIO_USE_LIBC support for Linux by redirecting a few symbols provided by DR including `memcpy`.
However, there is a bug in our `memcpy` implementation.
The `memcpy(void *dest, const void *src, size_t n)` should return a pointer to `dest`, but our implementation returns the pointer after the `dest` instead:
```
GLOBAL_LABEL(memcpy:)
        cmp      ARG3,   #0
1:      beq      2f
        ldrb     REG_R3, [ARG2]
        strb     REG_R3, [ARG1]
        subs     ARG3, ARG3, #1
        add      ARG2, ARG2, #1
        add      ARG1, ARG1, #1
        b        1b
2:      mov      REG_R0, ARG1
        bx       lr
        END_FUNC(memcpy)
```
