### ISSUE TITLE
add cross-arch support in drsym

### ISSUE THREAD

**Issue by zhaoqin** [DynamoRIO/dynamorio#1764]
I have a program build for ARM, and run it with drcov on ARM.
Then I tried to collect the line coverage info by running drcov2lcov on my x86 machine, which failed.

> ~/Workspace/DrMemory/builds/build_x86_drm_dbg.git/bin/symquery -v -f -e ~/Downloads/my_arm_prgram --lines
<debug info: type=ELF symtab, has symbols, has line numbers>
line enum error 6

**Comment by zhaoqin** [comment]
xref issue #1532

**Comment by derekbruening** [comment]
The Linux x86 drsyms and symquery work fine on a cross-compiled ARM ELF file.  I made sure of this when making drcov work on Android.  The only drcov issue was the file paths which I added support for in 8718404.

```
% /work/drmemory/git/build_x86_dbg/bin/symquery -v -f -e /extsw/android/test/hello-android  --lines
<debug info: type=ELF symtab, has symbols, has line numbers>
cu="hello.c", file="/extsw/android/test/hello.c" line=4, addr=0x388
cu="hello.c", file="/extsw/android/test/hello.c" line=5, addr=0x3a4
cu="hello.c", file="/extsw/android/test/hello.c" line=6, addr=0x3b4
cu="hello.c", file="/extsw/android/test/hello.c" line=7, addr=0x3d8
cu="hello.c", file="/extsw/android/test/hello.c" line=8, addr=0x3dc
```

Thus there is no need for a general feature issue on ARM symbols when running on Linux.
