### ISSUE TITLE
drinject should fail if the app is not registered using drconfig

### ISSUE THREAD

**Issue by zhaoqin** [DynamoRIO/dynamorio#1785]
On Win8-x86, if we did not register an app, e.g., `.\bin32\drconfig.exe -unreg calc.exe`, we should fail on command `.\bin32\drinject.exe -- calc.exe`. However, on Win8-x86, it starts calc without any warning message.

**Comment by derekbruening** [comment]
Is this really limited to win8-x86 as the title and initial msg say?

**Comment by derekbruening** [comment]
win7x64 has no warning and runs an unconfigured app:

```
% DynamoRIO-Windows-6.0.0-5/bin32/drconfig -list_registered | grep hello
% DynamoRIO-Windows-6.0.0-5/bin32/drinject d:/derek/dr/test/hello.exe
Hello world!
Goodbye world!
```
