### ISSUE TITLE
Passing DR_REG_XXX to opnd_size_in_bytes(), opnd_size_in_bits()

### ISSUE THREAD

**Issue by iwrinc** [DynamoRIO/dynamorio#1811]
The above functions are declared with a single opnd_size_t argument.
According to the documentation, they also accept DR_REG_ constants, i.e. reg_id_t.
But reg_id_t is now wider that opnd_size_t.

**Comment by derekbruening** [comment]
DR_REG_ inputs are disallowed (cannot distinguish for ARM anyway).  The docs and code need to be updated.  The caller should call reg_get_size() first.
