### ISSUE TITLE
upload.py failing with 404 on re-authentication

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#1818]
Password authentication support was dropped months ago, but my cached credentials kept working until today:

```
> git review
Creating a new code review request.
Uploading the review...
Password for <me>:
Traceback (most recent call last):
  File "/work/dr/git/src/make/upload.py", line 2394, in <module>
    main()
  File "/work/dr/git/src/make/upload.py", line 2386, in main
    RealMain(sys.argv)
  File "/work/dr/git/src/make/upload.py", line 2342, in RealMain
    response_body = rpc_server.Send("/upload", body, content_type=ctype)
  File "/work/dr/git/src/make/upload.py", line 383, in Send
    self._Authenticate()
  File "/work/dr/git/src/make/upload.py", line 428, in _Authenticate
    super(HttpRpcServer, self)._Authenticate()
  File "/work/dr/git/src/make/upload.py", line 318, in _Authenticate
    auth_token = self._GetAuthToken(credentials[0], credentials[1])
  File "/work/dr/git/src/make/upload.py", line 262, in _GetAuthToken
    response = self.opener.open(req)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found
Upload server: codereview.appspot.com (change with -s/--server)
ERROR: failed to record Rietveld issue number.
```

The solution is to get the latest upload.py and pass --oauth2.

However, I am having a lot of trouble with its auto-browser-launch, which has never worked well on Fedora + KDE with my multiple Chrome profiles.  I may add support for caching a separately-acquired token to upload.py.  Note that we can't just use the depot_tools auth scripts b/c we'd have to change the codereview server to honor them.

**Comment by derekbruening** [comment]
Documenting some of the things we discussed offline:

+ We discussed how best to make the defaults work for everyone and went with a solution where if the token file documented in the wiki is present that's used; else the browser should be interactively launched

+ To cache authentication longer than the short (~1 hour?) current token, we would have to change the server side, which is how Chromium does it

+ We considered switching to git pull requests but they are designed for a merge workflow, and there are other downsides like comments on a commit or diff disappearing when a new patchset is uploaded

**Comment by byron-hawkins** [comment]
A quick way to get an access token is to use the text-mode browser `elinks`, which is in the apt repo for Ubuntu (version 0.12pre6, which supports javascript). The first time requires a manual sign-in, but after that the token can be obtained with a one-liner:

    elinks -dump 1 https://codereview.appspot.com/get-access-token | tail -1 | awk '{print $1}'

**Comment by derekbruening** [comment]
Nice, w3m has trouble with such stuff, good to know that links works and this can be further automated.  Could you add this to the wiki page?
