### ISSUE TITLE
std=c++11 flag in client CMakeFiles.txt causes error

### ISSUE THREAD

**Issue by iwrinc** [DynamoRIO/dynamorio#1820]
The error is at https://github.com/DynamoRIO/dynamorio/blob/master/make/DynamoRIOConfig.cmake.in :354
Escaping ++ in cur_flags and flag vars solves this issue:

```
352: get_source_file_property(cur_flags ${src} COMPILE_FLAGS)
++    string(REPLACE "++" "\\+\\+" cur_flags_esc ${cur_flags})
         foreach (flag ${tgt_flags})
++       string(REPLACE "++" "\\+\\+" flag_esc ${flag})
           if (NOT cur_flags_esc MATCHES " ${flag_esc}")
              _DR_append_property_string(SOURCE ${src} COMPILE_FLAGS "${flag}")
           endif ()
```

**Comment by fhahn** [comment]
I think this issue has been resolved, it seems like clients can be built with -std=c++11. 

drcachesim builds ok for me after adding `+add_definitions("-std=c++11")`  to  clients/drcachesim/CMakeLists.txt

**Comment by egrimley** [comment]
Was this a bug in some version of CMake, perhaps? I don't see that anything relevant has changed in DynamoRIO since 2015.

**Comment by derekbruening** [comment]
Precisely where did you add the flag?  If it's after the configure, that won't test the original problem.  Also, add_definitions is intended only for preprocessor definitions, not general compiler flags.

**Comment by derekbruening** [comment]
Looks like the reported error has the flag showing up in get_source_file_property: make sure that happens in your test.

**Comment by derekbruening** [comment]
Adding this to the top of clients/drcachesim/CMakeLists.txt:

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")

Produces:

```
RegularExpression::compile(): Nested *?+.
RegularExpression::compile(): Error in compile.
CMake Error at /home/bruening/dr/git/build_x64_rel_tests/cmake/DynamoRIOConfig.cmake:545 (if):
  if given arguments:

    "NOT" "cur_flags" "MATCHES" " -std=c++11"

  Regular expression " -std=c++11" cannot compile
Call Stack (most recent call first):
  /home/bruening/dr/git/build_x64_rel_tests/cmake/DynamoRIOConfig.cmake:1131 (_DR_set_compile_flags)
  clients/drcachesim/CMakeLists.txt:86 (configure_DynamoRIO_standalone)


-- Configuring incomplete, errors occurred!
```
