### ISSUE TITLE
how to build a client on Windows

### ISSUE THREAD

**Issue by zhonghh13** [DynamoRIO/dynamorio#1828]
can somebody show me how to build a client on Windows? 
i have tried cl, like this: 
```
cl my-client.c /I$DYNAMORIO_HOME/include /GS- /DWINDOWS /DX86_64
   /link /libpath:$DYNAMORIO_HOME/lib64/debug dynamorio.lib /dll /out:my-client.dll
   /base:0x72000000 /fixed
```
but always got error LNK 2019  cannot resolved external symbol _drwrap_get_arg, for i include the drwrap.h; i think some dll may not include or some path is wrong, i have no idea about the problem, can anybody help me out?

**Comment by derekbruening** [comment]
The issue tracker is for bug reports and feature requests.  Please use the mailing list https://groups.google.com/forum/#!forum/dynamorio-users for questions.
