### ISSUE TITLE
prof_pcs not initializing its dcontext field

### ISSUE THREAD

**Issue by byron-hawkins** [DynamoRIO/dynamorio#1830]
When running octane in DynamoRIO on x64 Linux with `-prof_pcs`, the `dcontext->pcprofile_field` is not getting set in the case of a shared itimer. The app crashes immediately in `pcprofile_lookup()` because the field is `NULL`. It looks like there is a line missing in `pcprofile_thread_init()`, and adding this line does fix it (for octane, at least):

    if (shared_itimer) {
        ASSERT(parent_info != NULL);
        info = (thread_pc_info_t *) parent_info;
    +   dcontext->pcprofile_field = (void *) info;
        ASSERT(info->thread_shared);
        return;
    }

But after reading #359, I'm not sure if this is a reasonable way to resolve it--there seem to be a lot of related factors that I'm not familiar with.

**Comment by derekbruening** [comment]
At a first glance this does seem like a dup of #359 whose comment "on November 28, 2010 12:00:41" seems to explain several problems including this one, which was introduced in ba4456c24d1589a5a4ac2f28c8a9853cc37019ea.  If you agree, please resolve with Status-Duplicate.

**Comment by byron-hawkins** [comment]
My mistake, I thought the clone syscall could only spawn child processes (which does not occur in v8 or ion). So I confirmed that it's using clone to spawn threads, which makes this the same as #359.
