### ISSUE TITLE
Javadoc link does not work for me

### ISSUE THREAD

**Issue by rekire** [DynamoRIO/dynamorio#1841]
Hello out there. I'm wondering what I am doing wrong I cannot use normal `{@link #someMethod}` and similar links. Here take this example code:

```/**
 * ... you might be interested in overriding {@link #foo()} like in
 * {@link MyClass#bla() MyClass42}. Keep in mind to implement...
 * Created on 07.01.2016.
 *
 * @author me
 */
public abstract class MyClass {
	int foo() {
		return 42;
	}
	
	abstract void bla();
}
```

In the console I get this error:

>foo.java:3: warning: unable to resolve link to \`#foo()' for \link command
>foo.java:4: warning: unable to resolve link to \`MyClass#bla()' for \link command

What am I doing wrong?

**Comment by zhaoqin** [comment]
wrong repository
