### ISSUE TITLE
support ordinal forwarders

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#1870]
In #1866 we see this forwarder:

```
00000000`02054e70  "SHUNIMPL.#210"
```

It seems to be special notation for an ordinal forwarder:

```
shunimpl's ord #210:
        210      00001B34 [NONAME]
```

This issue covers adding support for these.

**Comment by woodruffw** [comment]
Ran into this while working on #3206, so I'll take a stab at it.
