### ISSUE TITLE
add Android test suite

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#1873]
Xref #1701

The plan for adding a test suite is to cross-compile, adb push the whole build dir over, and prepend "adb shell" to all of the test commands, thus running ctest itself from the host.  (It would not be easy to try and get a version of ctest built to run natively on Android as we would have to custom-build many system libraries that it uses.)

**Comment by derekbruening** [comment]
It is not worth trying to support -no_early_inject on Android so I will disable all such tests.

**Comment by derekbruening** [comment]
*** TODO how trigger the adb push?

To automate: have a POST_BUILD push after every binary we need?  drrun,
libDR, each test, etc.?  Kind of a pain to have to add sthg to every target
scattered around, or to use a layer like "DR_add_executable".

Plus, we'd have to individually copy data files like drmem default supp or
input files that some of the tests take.

Note that for DR there are no data files.  The only args are a couple tests
that pass paths to other binaries:
```
# grep -o '"--".*)' /work/dr/git/build_android_dbg/suite/tests/CTestTestfile.cmake
```
It's similar for DrM:
```
# egrep -o '@--@[^"]*"' /work/drmemory/git/build_x86_dbg/tests/CTestTestfile.cmake 
```

The alternative is some manually-run push of the entire build dir (there's
no "END_OF_BUILD" cmake trigger).
We'd not support local testing and do this push from runsuite?
Or we'd have a copy_to_device.cmake a dev could run manually.
Or we could make it part of the "install" target when tests are enabled:
but can we disable all the other install commands?

Pushing the whole build dir takes 2:44 and needs 264MB.

Pushing just the targets we need: 18MB and much faster (plus, distributed
within the parallel build).  This also supports a nice rebuild-and-rerun
dev model.  So I'm going with this.

**Comment by zhaoqin** [comment]
For fuzz test, the error comes from the wrong fuzz target function size argument.
We tries to get size info from `repeatme(buffer, size)`. However, in `get_priv_mcontext_from_dstack`
```
gdb) p/x *(priv_mcontext_t *)(dcontext->dstack - sizeof(priv_mcontext_t))
$10 = {r0 = 0xbe8fca50, r1 = 0x55059c98, r2 = 0xb0850858, r3 = 0x10, r4 = 0x4, r5 = 0x2, r6 = 0xb0f59828, r7 = 0xbe8fca44, r8 = 0x2, r9 = 0xbe8fca50, r10 = 0x0, r11 = 0x0, r12 = 0x54e29000, {
    r13 = 0xbe8fca0c, sp = 0xbe8fca0c, xsp = 0xbe8fca0c}, {r14 = 0x7399e501, lr = 0x7399e501}, {r15 = 0x54e3aec4, pc = 0x54e3aec4}, {xflags = 0xb0f59a54, apsr = 0xb0f59a54, cpsr = 0xb0f59a54},
...
```
It looks like the value is off by two reg size, where r2 is holding the actual r0 value, and r3 is holding the r1 value.

**Comment by derekbruening** [comment]
I think you meant to put that comment in https://github.com/DynamoRIO/drmemory/issues/1860 instead of here?
