### ISSUE TITLE
DynamoRIO fails to build when /usr/sbin/selinuxenabled says NO

### ISSUE THREAD

**Issue by egrimley** [DynamoRIO/dynamorio#1880]
$ cmake -DBUILD_TESTS=ON ..
    ...
    -- Detected selinux: will chcon binaries with text relocations.
    ...
    $ make
    ...
    /bin/chcon: can't apply partial context to unlabeled file '.../dynamorio/build/suite/tests/bin/libclient.drwrap-test.appdll.so'

Here's the code in suite/tests/CMakeLists.txt:

      find_program(SEUNIXENABLED selinuxenabled DOC "path to selinuxenabled")
      if (SEUNIXENABLED)
        find_program(CHCON chcon DOC "path to chcon")
        if (CHCON)
          message(STATUS "Detected selinux: will chcon binaries with text relocations.")
          set(SEUNIXFOUND "yes")
        endif (CHCON)
        mark_as_advanced(CHCON)
      endif (SEUNIXENABLED)

It seems that the program "selinuxenabled" is being found, in /usr/sbin/, even though that's not on my PATH, and that is enough to set SEUNIXENABLED.

Is this what's intended? (I don't know much about SELinux.) Should the code in CMakeLists.txt try running selinuxenabled?

$ /usr/sbin/selinuxenabled ; echo $?
1

Is there an easy way to disable this SELinux detection from the cmake command line so that I don't have to modify suite/tests/CMakeLists.txt?

**Comment by algr** [comment]
Apologies, I duplicated this as #1888 and I've submitted a patch.
