### ISSUE TITLE
Relocation bypassed when load_delta is zero

### ISSUE THREAD

**Issue by egrimley** [DynamoRIO/dynamorio#1882]
On my branch, DynamoRIO crashes unless I run it under GDB. This afternoon I decided to investigate this, and I tracked it down to these lines in privload_get_os_privmod_data in loader.c:

        if (opd->load_delta == 0)
            return false;

The reasoning seems to be that if the load_delta is zero, then no relocation is required, so privload_get_os_privmod_data returns false, so relocate_dynamorio does not call privload_early_relocate_os_privmod_data.

Perhaps this reasoning is correct for REL relocations, but for RELA?

Try building this into a shared object:

    // gcc -fpic -c r.c && gcc r.o -shared -o libr.so

    const char string[] = "string";
    const char *a[] = { (const char *)0x1111, string, (const char *)0x2222 };

Then look at what's in the file between the "1111" and the "2222". I see a zero which needs to be replaced by the linker whatever the load_delta.

In any case, deleting the two lines quoted above lets me run DynamoRIO without GDB.

But why hasn't this caused a problem for anyone else? Is the load_delta never zero on X86_64, and the other architectures use only REL relocations?

**Comment by derekbruening** [comment]
The load_delta is usually zero.  It seems a performance bug to me for the linker to ask the loader to relocate something and waste runtime effort when the linker could have easily put the right value in for the preferred base.

**Comment by egrimley** [comment]
Presumably the load_delta is usually non-zero if address space layout randomisation (ASLR) is in use. However, that doesn't seem like a sufficient explanation for the linker not filling in the "right" value.

**Comment by egrimley** [comment]
There is now a proposed patch for binutils that also fixes this problem, but of course there will be systems out there with the old binutils for years to come, even if this patch is accepted, so I'm not proposing anything different for DynamoRIO:
https://sourceware.org/ml/binutils/2016-04/msg00407.html
