### ISSUE TITLE
DynamoRIO does not work if built on Debian stretch i386

### ISSUE THREAD

**Issue by egrimley** [DynamoRIO/dynamorio#1895]
But you can make it work by replacing "jmp hashlookup_null_handler" with "RAW(e9) RAW(fc) RAW(ff) RAW(ff) RAW(ff)" in core/arch/x86/x86.asm.

That might not be the best fix, but it shows where the problem is, I think: stretch's assembler turns the jmp instruction into two bytes, rather than five, and the preceding comment says "we patch this up".

I found this by bisection: copying .o files from one build tree into another.

**Comment by derekbruening** [comment]
What version of gas is it?

**Comment by egrimley** [comment]
$ as --version
GNU assembler (GNU Binutils for Debian) 2.26

**Comment by derekbruening** [comment]
Hmm, my machines have 2.25-9 and 2.24 -- so this could be something hit in the future on other machines.

**Comment by egrimley** [comment]
Yes. By the way, I think there were five jmp instructions in that file that the new binutils turns into 2 bytes instead of 5, but presumably the others don't matter. Debian's 2.26 binutils is probably tracking the upstream 2.26 branch so other distributions might get this feature with 2.26.1. The changelog mentions "relax-relocations" as a configuration and command-line option. (I think the term "relax" is often used to refer to this adaptation of forward branches. It's a good thing to do in binary translation, too...)

This bug might nicely explain the varying failures I was seeing. If you patch a 2-byte branch with a dynamically determined 4-byte offset then you could end up branching to anywhere in the vicinity of the branch instruction.
