### ISSUE TITLE
core/unix/module_elf.c:999:10: error: ‘EM_AARCH64’ undeclared

### ISSUE THREAD

**Issue by egrimley** [DynamoRIO/dynamorio#1905]
A buildbot has discovered that c2ecca24 does not build on older systems that do not have `EM_AARCH64` defined in `<elf.h>`. One could perhaps use something like this in module_get_platform:

    #ifdef EM_AARCH64
        case EM_AARCH64:
    #endif

**Comment by zhaoqin** [comment]
If we do not have a quick fix, should we revert the change?

**Comment by derekbruening** [comment]
Yes, normally automated build breakage is considered high priority and is
either fixed or reverted ASAP, with a code freeze in place until then.

**Comment by derekbruening** [comment]
Revert via TBR (== To Be Reviewed, meaning commit prior to review).

**Comment by derekbruening** [comment]
I went ahead and reverted (reverted the suite commit too as it's dependent
on the build one) as we do not want TOT to have a broken x86 build.

**Comment by egrimley** [comment]
793392d seems not to have failed in the way that c2ecca2 did, so I'm closing this.
