### ISSUE TITLE
CRASH caused by generated LDR PC from unaligned address

### ISSUE THREAD

**Issue by lgeek** [DynamoRIO/dynamorio#1906]
The ARM architectural manual specifies that the address used by an LDR instruction into PC has to be word aligned:

```
[...]
if t == 15 then
  if address<1:0> == '00' then LoadWritePC(data); else UNPREDICTABLE;
[...]
```

However, DynamoRIO seems to sometimes generate loads from unaligned addresses into PC. For example:

```
   0x47e6c318:  ldr.w   r0, [r10]
   0x47e6c31c:  ldr     r3, [r7, #48]   ; 0x30
   0x47e6c31e:  ldr     r3, [r3, #12]
   0x47e6c320:  cmp     r3, #0
   0x47e6c322:  beq.w   0x47e6c32a
   0x47e6c326:  b.w     0x47e6c35c
=> 0x47e6c32a:  ldr.w   pc, [pc, #14]   ; 0x47e6c33a
   0x47e6c32e:  movw    r0, #51396      ; 0xc8c4
   0x47e6c332:  movt    r0, #18411      ; 0x47eb
   0x47e6c336:  ldr.w   pc, [r10, #24]
   0x47e6c33a:  pop     {r0, r3, r5, r7}
```

This is causing a bus error on certain cores, for example APM X-Gene.

How to reproduce the crash: run a few Thumb applications via DR on a system using X-Gene cores. Many will crash immediately.

**Comment by derekbruening** [comment]
All our load into PC instructions use aligned offsets (ibl, fcache return, ARM mode) except for Thumb mode far links where the direct target is not reachable from a regular branch: thus, this will only show up in a Thumb app with a relatively large code footprint.

I put a fix into 9a261f59e206fde1ffc8788a7f0a849219f6eab0 though as we do not have access to X-Gene hardware I cannot be 100% sure of the fix.  Help in testing this is appreciated.

**Comment by egrimley** [comment]
In an armhf chroot on an APM X-Gene Mustang board `bin32/drrun top` crashed with "Bus error" before 9a261f5. Now it works, so the bug seems to be fixed. Thanks.

**Comment by lgeek** [comment]
I've tested a few of the applications which were crashing before, and they work correctly now, so 9a261f5 seems to have fixed this issue. Many thanks
