### ISSUE TITLE
Whethre countcalls.c is suitable or not on Android Plat

### ISSUE THREAD

**Issue by ealibaba** [DynamoRIO/dynamorio#1914]
Hi,i have read the code of countcalls.c,and can run Windows 7 X64 well. but i do not known how to compile the codes which will be running on Android. and whether countcalls.c containing in Linux is suitable or not on Android Plat? Can you give me a response. thx!

**Comment by derekbruening** [comment]
The issue tracker is for filing bugs.  For asking questions, please use the dynamorio-users mailing list.
