### ISSUE TITLE
add proper signal support while threads are native

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#1921]
xref #38

DR_EMIT_GO_NATIVE is considered experimental on Linux and one feature missing is:

```
    /* For proper native execution with re-takeover we need to propagate
     * signals to app handlers while native.  For now we do not support re-takeover
     * and we give up our handles via signal_remove_handlers().
     */
```

**Comment by derekbruening** [comment]
I'm considering this issue to also cover signal support for start/stop where all threads are either native or under DR.  Because handling signals for just one thread being native is difficult (we aren't tracking syscalls so we'll have to query for the proper handler and mask) the plan for start/stop whole-process is to remove our handler while the app is native.

**Comment by derekbruening** [comment]
The api.detach_spawn test I'm trying to add for #2601 is revealing a bunch of races, some of which overlap with this issue.

Today there are race windows where we haven't removed our handler completely: e.g., during detach we remove the alarm handlers after the synchall before we let any thread go native, but we leave other signal handlers.

All of this has corner cases with no guarantees.  For alarms we can be reasonably confident that the app's handler will come right back but that may not be true for other signals.  This affects us whether we keep our handler and implement the feature covered here, sending native control to the app's handler, or whether we drop our handler and let the kernel send native control to the app's handler.  The only way to get guarantees is to delay all signals which gets complicated when trying to clean up and detach.

For doing native delivery, the kernel mask should be native, so we should be able to just undo the master_signal_handler_C frame and jump to the app's handler if it exists: if not we'll have to decide what to do.  If the native action is to terminate and we're during detach it'd be best to wait so that any client can run exit time code.

One option is to not let any thread go native until we've cleaned them all up.  Then we remove our handler and then we let them all go at once.  Performance will be worse though with 600 threads stacking up for much longer than before.

**Comment by hgreving2304** [comment]
xref #2941

**Comment by derekbruening** [comment]
I think it's time to close this.  Nearly everything is covered.  There are a few cases that are not, such as too-small sigaltstack for the extra space we take to copy the frame, or default actions: but those are going to exit anyway.  Let's file separate issues on anything that becomes important enough to spend time on; I think we can certainly live with the current shortcomings.
