### ISSUE TITLE
Cannot find required libs pthread

### ISSUE THREAD

**Issue by clarkb7** [DynamoRIO/dynamorio#1924]
Failed to configure debug-internal-32 on new ubuntu 14.04 x64 setup.
> "cannot find required libs m, dl, and/or pthread"

Looks like pthread was left out of the extra path search added for math and dl.

xref #720

**Comment by derekbruening** [comment]
The #720 fix did include pthread.  It was removed in 97cfb53d364a7cfd72a8c02de895b1633d10c286.  I believe that was a mistake: probably the original diff removed it just for Android, and when later pthread was handled differently it wasn't put back together.
