### ISSUE TITLE
Hi,how  dynamoRIO can be transparent  for  self codes check? 

### ISSUE THREAD

**Issue by jiqizaisikao** [DynamoRIO/dynamorio#1932]
HI,I kown that dynamoRIO  can be transparent for modified codes because it  own a copy of origin codes,and it make modification on origin codes.so normal check for codes using module handle wont find something wrong .
but ,when the app using EIP of itself for code check ,i think it will find the copy of codes,not the origin codes.so is there any solution for this?
for eg,call XX will copy the EIP on stack ,and some float instrs will copy the eip too,so it is not difficulty to konw what if the codes  were actually  modified.

**Comment by jiqizaisikao** [comment]
I have tried many ways to fix this,i found that even in ring0,the app can read the codes if it can execute it,so  what ever methods we use to disable read,it will disable execute too.

**Comment by zhaoqin** [comment]
Please post questions like this in DynamoRIO user list.
Please xref DynamoRIO's tutorial slides and the paper [Transparent Dynamic Instrumentation](http://www.burningcutlery.com/derek/docs/transparency-VEE12.pdf) how we keep DynamoRIO transparent.
It is a best-effort approach. It is extremely hard, if not impossible, to keep DynamoRIO completely transparent,

**Comment by derekbruening** [comment]
Call XX is easily handled.  Float PC is handled by default if write and read are in the same bb -- if further apart it is off by default (performance tradeoff) and you'll need to turn on -translate_fpu_pc for your app.  But yes, please use the user list for this type of discussion.  The issue tracker is for reporting a bug or a feature request.  Have you found a bug?  Do you have a specific instance where a code cache PC is leaked?  It sounds like you're just speculating and not have actually found an instance?
