### ISSUE TITLE
Skylake: assertion fail in unix/signal.c: sc->fpstate->sw_reserved.extended_size <= XSTATE_FRAME_EXTRA

### ISSUE THREAD

**Issue by algr** [DynamoRIO/dynamorio#1937]
On Intel Skylake model 78 with Ubuntu 16.04 LTS, many of the tests crash out with this assert.  It turns out that extended_size = 1092 and XSTATE_FRAME_EXTRA = 896, i.e. there is an extra 196 bytes in the state.

This core has AVX2 but not (as far as I can tell) AVX-512.  DR supports AVX2 and has already checked YMM_ENABLED() on this code path.  But I don't know if the extra state is AVX-related.  Even if it was AVX-512, that would only be an extra 32*16 = 128 bytes.

Some documentation explaining the rationale for what DR is doing here and how it arrives at XSTATE_FRAME_EXTRA would help enormously.  It looks as if this code would have to be aware of all types of extra state including kinds not normally documented in the system's sigcontext.h.

**Comment by algr** [comment]
Seems like the kernel calculates the extended state size by interrogating CPUID registers (kernel/fpu/xstate.c, function calculate_xstate_size), and the extended state could include things like MPX, "Protection Keys User registers", "unknown xstate feature".

So there's essentially no way for userspace to accurately predict the xstate size based on testing specific features at userspace.  It either has to adapt to whatever the kernel tells it via extended_size, or hard-wire some limit that's hopefully good for a few years.

**Comment by algr** [comment]
Confirmed that it really is just this problem - adding 200 bytes to XSTATE_FRAME_EXTRA raises the pass rate on Skylake from 78% to 100%. But this is not future-proof.  Server variants and future variants will likely add new forms of xstate.

**Comment by derekbruening** [comment]
Don't forget to use the labels

**Comment by rocallahan** [comment]
The extra XSAVE state is for MPX registers (128 bytes).

To properly fix this, DR needs to not make assumptions about the XSAVE area having a fixed layout.
