### ISSUE TITLE
`XSTATE_FRAME_EXTRA` assertion failure runnning precommit tests

### ISSUE THREAD

**Issue by rocallahan** [DynamoRIO/dynamorio#1944]
Output 
````
	code_api,no_early_inject|client.events =>  Application /home/roc/dynamorio/build_suite/build_debug-internal-64/suite/tests/bin/client.events (23756).  Internal Error: DynamoRIO debug check failure: /home/roc/dynamorio/dynamorio/core/unix/signal.c:2400 sc-fpstate-sw_reserved.extended_size = XSTATE_FRAME_EXTRA 
````
Configuration:
````
vendor_id       : GenuineIntel
cpu family      : 6
model           : 94
model name      : Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
Linux glory 4.4.9-300.fc23.x86_64 #1 SMP Wed May 4 23:56:27 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
````
Pretty sure I didn't break this :-)

**Comment by rocallahan** [comment]
The assertion looks invalid to me:
````
                    ASSERT(sc->fpstate->sw_reserved.extended_size <= XSTATE_FRAME_EXTRA);
````
`sc->fpstate->sw_reserved.extended_size` comes from the kernel's `fpu__init_prepare_fx_sw_frame`. computed by `calculate_xstate_size`, which calls `cpuid` to get the full size of the xsave area computed by the processor.  `XSTATE_FRAME_EXTRA` is computed by DR and is roughly `sizeof(struct _xstate)` which is includes everything up to the YMM registers but nothing else. On my machine the full XSAVE area also includes space for MPX registers so the assertion fails :-(

**Comment by rocallahan** [comment]
This causes a significant number of precommit tests to fail:
````
debug-internal-64: 178 tests passed, **** 49 tests failed, of which 1 were flaky: ****
````

**Comment by rocallahan** [comment]
Fixing this is going to be a bit of a chore since the xsave-related sigcontext logic will have to be updated to account for larger xsave areas. To do it properly, we should eliminate the assumption that `struct _xstate` describes the layout of the xsave area, since going forward there is no guarantee that all xsave layouts can be totally ordered into a prefix order. (E.g. if we add MPX fields to _xstate, then AVX-512 fields, then pkeys, but Intel decides to release a CPU with pkeys but not AVX-512, we're stuffed.) The kernel makes no such assumption.

**Comment by algr** [comment]
This looks like a duplicate of #1937.

**Comment by rocallahan** [comment]
Yes, sorry about that.
