### ISSUE TITLE
Windows build broken by aarch64 asm CL

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#1950]
Every Windows build was broken by d966e7d282180611749cfdcff9929d5e55ad4c11

http://dynamorio.org/CDash/viewConfigure.php?buildid=7709

CMake Error at core/CMakeLists.txt:418 (add_dependencies):
  add_dependencies called with incorrect number of arguments

**Comment by egrimley** [comment]
I wonder if this is caused by the version of CMake running on the Windows buildbot, rather than by Windows per se. If it is, then I might be able to test the following patch, which might be a fix:

    --- a/core/CMakeLists.txt
    +++ b/core/CMakeLists.txt
    @@ -414,8 +414,7 @@ if (WIN32)
     endif ()
     if ("${CMAKE_GENERATOR}" MATCHES "Visual Studio")
       # For VS generators, we also need one for our asm custom commands.
    -  add_dependencies(dynamorio ${arch_core_asm_tgt})
    -  add_dependencies(dynamorio ${archshared_core_asm_tgt})
    +  add_dependencies(dynamorio ${arch_core_asm_tgt} ${archshared_core_asm_tgt})
     endif ()
     
     target_link_libraries(dynamorio drhelper)

**Comment by derekbruening** [comment]
It would be best to get access to a Windows setup and always run the pre-commit suite there (as we request from all contributors), as Windows is a primary target with a very different compiler and a lot of dedicated build system code.  Breakage like #1949 from aarch64 CL's is likely to continue otherwise and that is not ideal.

**Comment by egrimley** [comment]
It seems that a later build, using an older compiler, did not fail in the same way:

http://dynamorio.org/CDash/viewConfigure.php?buildid=7793

So the failure may be specific to particular tool chain versions. If so, it's likely I won't be able to reproduce it. However, if after further examination the patch above still looks good I might push it anyway.
