### ISSUE TITLE
how to get the dynamic value of register and memory reference?

### ISSUE THREAD

**Issue by niguoyue** [DynamoRIO/dynamorio#1951]
First,i want to read the value of register.so i use the function dr_get_mcontext to get *mc,then read the value of mc->eax,but the value is nerver changed,which is diffierent form what i get when i use vs2013 debuger.
Next,i want to read the value of a memory reference.so i use the function opnd_compute_address() to get the address,but how to get the value?

**Comment by derekbruening** [comment]
The issue tracker is for filing bug reports and feature requests.  Please use the [mailing list](https://groups.google.com/forum/#!forum/DynamoRIO-Users)  for questions.

**Comment by niguoyue** [comment]
thinks，i make it now。thank you derekbruening。
