### ISSUE TITLE
Compile error: c++11 invalid suffix on literal

### ISSUE THREAD

**Issue by clarkb7** [DynamoRIO/dynamorio#1959]
Compile error
```C
Building CXX object clients/drcachesim/CMakeFiles/drcachesim.dir/simulator/launcher.cpp.o
/home/branden/git/dynamorio/clients/drcachesim/simulator/launcher.cpp:232:15: error: invalid suffix on literal; C++11 requires a space between literal and string macro [-Werror=literal-suffix]
               "Please choose "CPU_CACHE" or "TLB".\n");
               ^
/home/branden/git/dynamorio/clients/drcachesim/simulator/launcher.cpp:232:40: error: invalid suffix on literal; C++11 requires a space between literal and string macro [-Werror=literal-suffix]
               "Please choose "CPU_CACHE" or "TLB".\n");
```
This error pops a bunch of times in the clients

xref #1958

**Comment by clarkb7** [comment]
Unfortunately, simply setting the c++ version does not fix this problem, it throws -Wc++11-compat instead.
```C
home/branden/git/dynamorio/clients/drcachesim/simulator/launcher.cpp:232:15: error: C++11 requires a space between string literal and macro [-Werror=c++11-compat]
               "Please choose "CPU_CACHE" or "TLB".\n");
               ^
/home/branden/git/dynamorio/clients/drcachesim/simulator/launcher.cpp:232:40: error: C++11 requires a space between string literal and macro [-Werror=c++11-compat]
               "Please choose "CPU_CACHE" or "TLB".\n");
```

**Comment by derekbruening** [comment]
-Wno-literal-suffix should avoid these if we want to go that route and assume we'll never make user-defined literal suffixes

**Comment by egrimley** [comment]
That would be telling GCC to accept incorrect code (officially "ill-formed" perhaps; I'm not a C++ language lawyer), wouldn't it? Do you really want to do that? You would, in effect, be relying on a GCC extension. Are you sure you can persuade other compilers to accept incorrect code in the same way?

A better way of suppressing the warnings might be "--std=c++03" as the code is only incorrect in C++11.

**Comment by derekbruening** [comment]
Re:  changing the C++ version: see the comment right up above that says "Unfortunately, simply setting the c++ version does not fix this problem" (though what flag was used there is not specified).

Re: incorrect code: the same argument could be made for some of the other warnings that we (and other code bases) suppress.  E.g., we're setting many cmake policies to "old" to avoid spending time on them, and thus our current cmake is ill-formed according to the new cmake.
