### ISSUE TITLE
client.destructor fails on AArch64

### ISSUE THREAD

**Issue by egrimley** [DynamoRIO/dynamorio#1960]
On our branch of DynamoRIO, client.destructor fails on AArch64. It produces the output "hasdtr::hasdtr" and then crashes. It seems that any attempt to write a string to cerr in the client library causes a crash in the C++ library after the string has been written. The test passes if we replace cerr with cout, or if we use fprintf to stderr instead.

We are unsure whether it is, in general, safe to use cout and cerr in a static constructor as those things are also static data that might need to be initialised, while the order in which static constructors are invoked is undefined, at least in some versions of C++.

So, are you sure that it ought to be safe to use cerr in hasdtr::hasdtr? If not, shall we replace the use of cerr with fprintf to stderr?

**Comment by derekbruening** [comment]
What happens natively on A64?  If it works natively but not under DR then there is a problem.

**Comment by egrimley** [comment]
Do you mean to ask, what happens if I write my own program linked against client.destructor.dll.so? If it did work, what would that prove? If the order in which static initialisers is invoked is undefined, then I would expect it sometimes to work, sometimes not to work.

**Comment by derekbruening** [comment]
So this cerr code is in the client and not in the app.

**Comment by egrimley** [comment]
That's right: https://github.com/DynamoRIO/dynamorio/blob/master/suite/tests/client-interface/destructor.dll.cpp#L44

**Comment by derekbruening** [comment]
Looks like it is guaranteed safe in C++11 and while not guaranteed it is expected to work in "mainstream implementaions" for pre-C++11 and can be made guaranteed by constructing std::ios_base::Init: http://stackoverflow.com/questions/8784892/is-stdcout-guaranteed-to-be-initialized

**Comment by egrimley** [comment]
That doesn't help. Is it possible that DynamoRIO's loader is somehow affecting how initialisers are invoked?

**Comment by derekbruening** [comment]
It is quite possible -- maybe A64 ELF is using something different from what the DR loader is calling?

**Comment by egrimley** [comment]
I put breakpoints in privload_call_entry and I can see it calling libstdc++.so.6's initializers before it calls libclient.destructor.dll.s's, during which it crashes, with this stack:

    #0  0x0000000000000000 in ?? ()
    #1  0x0000007fb7ed4380 in __cxa_get_globals ()
    #2  0x0000007fb7ed429c in std::uncaught_exception() ()
    #3  0x0000007fb7f4f7ac in std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long) ()
    #4  0x0000007fb7f4fb40 in std::basic_ostream<char, std::char_traits<char> >& std::operator<< <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*) ()
    #5  0x0000000072000c48 in hasdtr::hasdtr (this=0x72011310 <global_hasdtr>)
        at /nas/egrimley/dynamorio/suite/tests/client-interface/destructor.dll.cpp:44
    #6  0x0000000072000be4 in __static_initialization_and_destruction_0 (__initialize_p=1, 
        __priority=65535) at /nas/egrimley/dynamorio/suite/tests/client-interface/destructor.dll.cpp:48
    #7  0x0000000072000c20 in _GLOBAL__sub_I_destructor.dll.cpp(void) ()
        at /nas/egrimley/dynamorio/suite/tests/client-interface/destructor.dll.cpp:54
    #8  0x0000005555825ffc in privload_call_lib_func (
        func=0x72000c0c <_GLOBAL__sub_I_destructor.dll.cpp(void)>)
        at /nas/egrimley/dynamorio/core/unix/loader.c:938
    #9  0x0000005555825004 in privload_call_entry (privmod=0x54b9ede8, reason=1)
        at /nas/egrimley/dynamorio/core/unix/loader.c:577

So I can't see anything wrong with the way initializers are invoked, unfortunately.

**Comment by egrimley** [comment]
Aha. I have a strong suspicion this is caused by us not having implemented ELF_R_TLS_DESC properly.

**Comment by egrimley** [comment]
Fixed by 1b6a007
