### ISSUE TITLE
add AArch64 automated testing and increase ARM automated testing

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#1966]
Xref #1962 

This issue covers two things:

First, adding A32 + A64 cross-compilation builds to Travis, to ensure that contributors without access to either platform do not break anything in any push to the repository.  Travis does not have non-x86 machines but we can at least test the build by installing cross-compilers in the install rule.  We should consider the total build time: maybe only do the cross-compilation in the clang build which is in parallel with the much longer gcc run?

Second, adding A32 and especially A64 machines that run the the test suite as a cron job and report the results to our CDash server.  See https://github.com/DynamoRIO/dynamorio/wiki/Test-Suite

**Comment by egrimley** [comment]
I was able to test cross-compiling for ARM and AArch64 in a Trusty chroot like this:

```
apt-get install cmake git
apt-get install g++-arm-linux-gnueabihf g++-aarch64-linux-gnu
...
CC=gcc ctest -VV -S /nas/egrimley/dynamorio/suite/runsuite.cmake,travis
```

(It was necessary to use user_pt_regs instead of user_regs_struct for the build to succeed. I hope to send a patch for that to codereview soon.)

**Comment by egrimley** [comment]
Cross-compiling with clang: I don't yet know how to do this. Also, the newest clang in Trusty is 3.5, which is perhaps a bit old for AArch64. On the other hand, we're not going to run the AArch64 code so code generator bugs that don't cause an internal error are not a problem.

**Comment by egrimley** [comment]
I've made some progress. There are now 4 build jobs instead of 3, and the extra job successfully cross-compiles for ARM and AArch64:

https://travis-ci.org/DynamoRIO/dynamorio/builds/151761229
https://travis-ci.org/DynamoRIO/dynamorio/jobs/151761231

It seems necessary to use an extra job because g++-multilib cannot be installed at the same time as the cross-compiler packages.

Unfortunately, the extra job also tries to do the native builds, which is a waste of CPU time, and the 32-bit native builds then fail because there is no multilib.

How can one tell ctest not to do the native builds?

**Comment by derekbruening** [comment]
> How can one tell ctest not to do the native builds?

Ctest is just running our own script, runsuite.cmake.  You'll have to tweak the script with a new param.

**Comment by egrimley** [comment]
I have a patch for runsuite.cmake that makes it finish like this on Trusty:

```
RESULTS

android-release-external-32: skipped (cross-compile configuration unavailable)
android-debug-internal-32: skipped (cross-compile configuration unavailable)
arm-debug-internal-32: build successful; no tests for this build
arm-debug-internal-64: build successful; no tests for this build
arm-release-external-32: build successful; no tests for this build
arm-release-external-64: build successful; no tests for this build

Error in read script: /nas/egrimley/dynamorio/suite/runsuite.cmake
```

Is that good enough for now, or will that spurious and incomprehensible error at the end be a problem?

**Comment by derekbruening** [comment]
It looks good.  For Travis you can see that I set it up to run ctest through a wrapper to avoid that annoying ctest message and exit code from affecting the results (I consider that a bug in ctest though there is some argument over whether my use of ctest is out of the bounds of what they want to support: https://github.com/DynamoRIO/dynamorio/issues/636).

**Comment by egrimley** [comment]
Thanks. The patch is in https://codereview.appspot.com/306170043/

**Comment by egrimley** [comment]
I think it worked: https://travis-ci.org/DynamoRIO

**Comment by egrimley** [comment]
Replacing CROSS with DYNAMORIO_CROSS_ONLY probably would be a good idea, though...

**Comment by fhahn** [comment]
It looks like the only work left for this issue is submitting nightly results from native AArch32 machines to CDash.

We have ARM cross-compilation jobs on Travis-CI and also AArch64 machines submitting nightly results to CDash (AArch64.ubuntu1604.gcc540.SoftDocker, AArch64.susetumbleweed.gcc621.SoftDocker, AArch64.centos73.gcc485.SoftDocker)

**Comment by fhahn** [comment]
It looks like there is an AArch32 machine submitting results as well (ARM.Ubuntu1404.gcc484.CAM). Should we close this issue?

**Comment by zhaoqin** [comment]
I am not sure how long ARM.Ubuntu1404.gcc484.CAM is going to last
Its batter has died, and there have been several wired failures and crashes. It would be nice to setup some other machine to replace it.

**Comment by fhahn** [comment]
We now have pre, postcommit and nightly testing on a Raspberry Pi for ARM.
