### ISSUE TITLE
API of instrlist_insert_mov_immed_ptrsz,... not good for AArch64

### ISSUE THREAD

**Issue by egrimley** [DynamoRIO/dynamorio#1977]
The DR_API functions `instrlist_insert_{mov,push}_{immed_ptrsz,instr_addr}` have final arguments `instr_t **first OUT, instr_t **second OUT`. The documentation says: "The created meta instructions are returned in first and second. Note that second may return NULL if only one instruction is created."

In AArch64 more than two instructions may be required, so this interface is insufficient.

A compatible extension would be to rename the last argument to "last" and specify: "Pointers to the first and last created meta instructions are returned in first and last, unless only one meta instruction is created, in which case NULL is returned in last."

An almost compatible extension would be: "Pointers to the first and last created meta instructions are returned in first and last (first and last are equal if there is just one)."

Code that just wants to mark the created instructions as "api" rather than "meta" would probably not get confused by the "almost compatible" change but it is possible that someone's code relies on "first" and "second/last" being different. On the other hand, the "compatible extension" leaves us stuck with a slightly more complex API as code that wants to iterate from "first" to "last" has to check that last is not NULL.

So which should we do? Or something else instead?

**Comment by derekbruening** [comment]
s/api/app/, s/meta/tool/ (we deprecated or at least are avoiding "meta" and have been calling it "tool" to avoid confusion)

I would vote for the compatible and avoid breaking anything

**Comment by egrimley** [comment]
I've created https://codereview.appspot.com/305890043/, which uses the compatible approach.
