### ISSUE TITLE
spurious rep/repne prefix on BND JMPQ

### ISSUE THREAD

**Issue by algr** [DynamoRIO/dynamorio#1978]
Running Ubuntu 16.04 LTS on Skylake. Any use of drrun warns with

`
<spurious rep/repne prefix @0x00007f57947207f8 (f2 41 ff e3): >
`

This is BND JMPQ which was added to ld.so as per https://gcc.gnu.org/ml/gcc/2014-01/msg00151.html

This is similar to #1899 but the fix for that tested for instructions of these categories:

`
info->type != OP_call && info->type != OP_call_ind && info->type != OP_ret &&
              info->type != OP_jmp && info->type != OP_jmp_short &&
`

while this one is OP_jmp_ind. This test ought to be factored out into a robust self-contained test. There are similar tests in instr.c but not directly on opcodes, they expect an instr, but only use its opcode.

**Comment by derekbruening** [comment]
This is confusing people so it's time to fix it.
