### ISSUE TITLE
sigaction seems to return new action as old action

### ISSUE THREAD

**Issue by egrimley** [DynamoRIO/dynamorio#1984]
This seems to happen on all architectures. Test program:

```
#include <signal.h>
#include <stdio.h>
#include <string.h>

int main()
{
    struct sigaction act, oldact;
    memset(&act, 0, sizeof(act));
    memset(&oldact, 0, sizeof(act));

    act.sa_handler = (void *)0x1001;
    sigaction(28, &act, &oldact);
    printf("%p\n", oldact.sa_handler);

    act.sa_handler = (void *)0x1002;
    sigaction(28, &act, &oldact);
    printf("%p\n", oldact.sa_handler);

    act.sa_handler = (void *)0x1003;
    sigaction(28, &act, &oldact);
    printf("%p\n", oldact.sa_handler);

    return 0;
}
```

Output running natively:

```
(nil)
0x1001
0x1002
```

Output running under DynamoRIO:

```
0x1001
0x1002
0x1003
```

**Comment by egrimley** [comment]
This test case may be relevant:

```
#include <signal.h>
#include <string.h>

void handler(int signum)
{
}

int main()
{
    struct sigaction act, oact;
    memset(&act, 0, sizeof(act));
    memset(&oact, 0, sizeof(oact));
    act.sa_handler = handler;
    sigaction(SIGINT, &act, 0);
    sigaction(SIGINT, &act, &oact);
    act.sa_handler = SIG_IGN;
    sigaction(SIGTSTP, &act, &oact);
    return 0;
}
```

With DEBUG, running this under DynamoRIO gives:

Internal Error: DynamoRIO debug check failure: .../dynamorio/core/unix/signal.c:1566 oact->handler == (handler_t) SIG_IGN || oact->handler == (handler_t) SIG_DFL

**Comment by derekbruening** [comment]
@egrimley, please assign this if you're working on it: it is not assigned to anyone right now -- else I would like to take it over now to see if it explains failures on some large Linux apps (unlikely, since few apps seem to notice this)

**Comment by egrimley** [comment]
Please do take it over, though https://codereview.appspot.com/311350043/ should perhaps refer to this issue with something like: "i#1984 sigaction: Add linux.sigaction0: test sigaction without signals."

The memory-protection-related tests are rather esoteric, doing things that probably no real program does. You might want to disable tests_prot and tests_edge (in sigaction0.c) for now, leaving just tests_rw.

**Comment by derekbruening** [comment]
I have all of the sigaction_nosignals tests passing under DR for 64-bit, but for 32-bit the test fails natively: strangely it sees -6 == -ENXIO on sigaction which makes no sense.  Investigating.  Does it pass as 32-bit for you?

**Comment by egrimley** [comment]
I think I saw -ENXIO, or something equally weird, on one 32-bit system that I tested on. I hoped it was just a peculiarity of that system; it was a 32-bit chroot running under a 64-bit kernel. If it happens on lots of systems it would be good to investigate, but the weirdness would probably only be worth emulating in DynamoRIO if it's almost universal, and perhaps not even then if it's too weird.

(I remember that a few years ago I had a system that implemented sigaction for an AArch32 process running under an AArch64 kernel a bit strangely: the restorer member was not copied into the oldact argument. I had to adapt some regression tests specially. None of my current systems has that weirdness so perhaps it was a bug that has since been fixed.)

**Comment by derekbruening** [comment]
Passing NULL for act and inaccessible memory for oact returns -6 when built as 32-bit and run on 2 different 64-bit kernels, Ubuntu 15.04 VM (3.19.0 kernel) and Fedora 22 (4.4.14 kernel):

    print("%d\n", sys_sigaction(SIGTERM, NULL, (unsigned char *)1, SIGSETSIZE));

Same for, in sigaction.c:

    print("%d\n", dynamorio_syscall(SYS_rt_sigaction, 4, SIGTERM, NULL, (struct sigaction *)1, 8));

Having invalid act, or both invalid, returns -14.

I will simply relax the assert in the test.

**Comment by derekbruening** [comment]
There's another 32-bit failure: syscall() returns 1 instead of 0 or -1 in some cases.

    linux.sigaction_nosignals: /work/dr/git/src/suite/tests/linux/sigaction_nosignals.c:88: sys_sigaction: Assertion `ret == 0 || ret == -1' failed.

errno is still -14.

**Comment by derekbruening** [comment]
It would be nice to add non-RT support, especially for Android where RT is not fully supported, but we'll live without it.  I'll just disable for Android where there are several other reasons this test won't work w/o some work (pre-installed handlers by Bionic, e.g.).
