### ISSUE TITLE
drconfig fails to resolve user path on localized Windows due to improper codepage use

### ISSUE THREAD

**Issue by ormoulu** [DynamoRIO/dynamorio#1985]
Hi,
I found this bug first on Windows Server 2008, then checked it on Windows 7 and XP.
If current user's name (and user directory) is in language other than English (mine is Russian), drconfig tool fails to resolve it's name and create registration.

This is the command line:
`C:\TRACE\DR4\bin32\drconfig.exe -reg calc.exe -syswide_on -no_follow_children -c MyClient32.dll`
This is the result:
`ERROR: process calc.exe registration failed: check config dir C:\Users\9335~1\AppData\Local\Temp/dynamorio permissions`

Quick debug showed that file name given  to GetFileAttributesW is spoiled by previous call to MultiByteToWideChar setting CodePage argument to CP_UTF8 (dr_frontend_win.c:221). When I changed this parameter to CP_ACP everything worked fine and calc.exe was registered. So maybe the solution would be to set CP_ACP for MultiByteToWideChar call.

**Comment by derekbruening** [comment]
We do want to use the portable UTF-8.  I'm pretty sure that what you are observing is due to the use of GetEnvironmentVariableA in dr_config.c's reading of the USERPROFILE environment variable, which is a known issue under #943.

**Comment by derekbruening** [comment]
Perhaps you could try replacing the GetEnvironmentVariableA in env_var_exists() in libutil/dr_config.c with a call to drfront_get_env_var() to confirm that it fixes the issue?

**Comment by ormoulu** [comment]
Unfortunately, it didn't help, though the spoiled directory name had slightly changed, now the error is
`ERROR: process calc.exe registration failed: check config dir C:\Users\╨а╤Т╨а╥С╨а╤Ш╨а╤С╨а╨Е╨а╤С╨б╨Г╨бтАЪ╨б╨В╨а┬░╨бтАЪ╨а╤Х╨б╨В/dynamorio permissions`

This is the code I changed:

> static bool
> env_var_exists(const char *name, char *buf, size_t buflen)
> {

> #ifdef WINDOWS
>     //size_t len = GetEnvironmentVariableA(name, buf, (DWORD) buflen);
>     //if (len == 0 || len > buflen)
>     //    return false;

>     drfront_status_t drfstat = drfront_get_env_var(name, buf, (DWORD) buflen);
>     if (drfstat != DRFRONT_SUCCESS)
>         return false;

> #else
> /////
> #endif
>     return true;
> }

**Comment by derekbruening** [comment]
The other fixes listed in #943 presumably are also needed: CreateDirectoryA, convert_to_tchar

**Comment by derekbruening** [comment]
This should be fixed by 46cbef71027af7e3a279321560a7b0f876e25833
