### ISSUE TITLE
NULL pointer dereference in ./core/fragment.c (crash)

### ISSUE THREAD

**Issue by bastoica** [DynamoRIO/dynamorio#1989]
Hi,

I've stumbled upon a `NULL` pointer dereference when monitoring clang with a slightly modified version of `memtrace_x86.c`.

Steps to reproduce:
1. install `clang` from http://llvm.org/ (I'm running 3.7, but I guess that's not so relevant...)
2. alter `memtrace()` (and `event_bb_insert()`) from ./api/samples/memtrace_x86.c by adding a call to `dr_app_pc_from_cache_pc()` (see atachement below).
3. run `$ ./bin64/drrun -c ./api/bin/libmemtrace_x86.so -- clang dummy.c -o dummy` 
    where `dummy.c` is simply `1.    int main() { return 0; }`

I've traced the error back to ./core/fragment.c in both `enter_nolinking()` and `enter_coudbelinking()`. DR crashes with a `SEGFAULT` when it tries to acquire `pt->linking_lock` because pt is `NULL`. 
Unfortunately, I couldn't figure out why `dcontext->fragment_field` is `NULL` at this point...

Thanks,
-Bogdan.

[memtrace_x86_bis.c.txt]
(https://github.com/DynamoRIO/dynamorio/files/434783/memtrace_x86_bis.c.txt)

**Comment by derekbruening** [comment]
A quick sanity test of the 6.2.0-2 binary release's memtrace client (does not have your change) shows that everything works there:

```
% bin64/drrun -c samples/bin64/libmemtrace_x86_binary.so -- clang /tmp/dummy.c -o /tmp/dummy
Client memtrace is running
Data file /work/dr/releases/rel-6.2.0/DynamoRIO-Linux-6.2.0-2/samples/bin64/memtrace.clang.12077.0000.log created
Data file /work/dr/releases/rel-6.2.0/DynamoRIO-Linux-6.2.0-2/samples/bin64/memtrace.clang.12079.0000.log created
Client memtrace is running
Data file /work/dr/releases/rel-6.2.0/DynamoRIO-Linux-6.2.0-2/samples/bin64/memtrace.clang.12079.0001.log created
Instrumentation results:
  saw 4059747 memory references

Data file /work/dr/releases/rel-6.2.0/DynamoRIO-Linux-6.2.0-2/samples/bin64/memtrace.clang.12080.0000.log created
Client memtrace is running
Data file /work/dr/releases/rel-6.2.0/DynamoRIO-Linux-6.2.0-2/samples/bin64/memtrace.ld.gold.12080.0000.log created
Instrumentation results:
  saw 10454762 memory references

Instrumentation results:
  saw 2276222 memory references
```

```
> clang -v
clang version 3.5.0 (tags/RELEASE_350/final)
```

Using -debug also works.

**Comment by derekbruening** [comment]
A more recent clang that happens to be available:

```
> /work/llvm/build_rel/bin/clang -v
clang version 4.0.0 (trunk 275945) (llvm/trunk 275942)

> bin64/drrun -c samples/bin64/libmemtrace_x86_binary.so -- /work/llvm/build_rel/bin/clang /tmp/dummy.c -o /tmp/dummy
Client memtrace is running
Data file /work/dr/releases/rel-6.2.0/DynamoRIO-Linux-6.2.0-2/samples/bin64/memtrace.clang-3.9.12199.0000.log created
<Application /work/llvm/build_rel/bin/clang-3.9 (12199). Basic block or trace instrumentation exceeded maximum size.  Try lowering -max_bb_instrs and/or -max_trace_bbs.>

> bin64/drrun -max_bb_instrs 50 -c samples/bin64/libmemtrace_x86_binary.so -- /work/llvm/build_rel/bin/clang /tmp/dummy.c -o /tmp/dummy
Client memtrace is running
Data file /work/dr/releases/rel-6.2.0/DynamoRIO-Linux-6.2.0-2/samples/bin64/memtrace.clang-3.9.12205.0000.log created
Data file /work/dr/releases/rel-6.2.0/DynamoRIO-Linux-6.2.0-2/samples/bin64/memtrace.clang-3.9.12208.0000.log created
Client memtrace is running
Data file /work/dr/releases/rel-6.2.0/DynamoRIO-Linux-6.2.0-2/samples/bin64/memtrace.clang-3.9.12208.0001.log created
Instrumentation results:
  saw 5488789 memory references

Data file /work/dr/releases/rel-6.2.0/DynamoRIO-Linux-6.2.0-2/samples/bin64/memtrace.clang-3.9.12209.0000.log created
Client memtrace is running
Data file /work/dr/releases/rel-6.2.0/DynamoRIO-Linux-6.2.0-2/samples/bin64/memtrace.ld.gold.12209.0000.log created
Instrumentation results:
  saw 8897942 memory references

Instrumentation results:
  saw 2656682 memory references
```

An aside: maybe we should lower the default max bbs.

**Comment by derekbruening** [comment]
First, why are you calling dr_app_pc_from_cache_pc?  The stored pc is already an app pc.

Second, the crash occurs not at any instrumentation call, but the call from the thread exit event.  The thread has exited and a good bit of its state is already cleaned up.  We have to clean up the fragment state before we invoke the client's thread exit event so that the client will see fragment deletion events before it throws its own state away.  You can see the comment about the potential risk of this ordering here https://github.com/DynamoRIO/dynamorio/blob/master/core/dynamo.c#L1217

We can't change the exit order without breaking parts of the interface, so we'll have to explicitly disallow dr_app_pc_from_cache_pc in the thread exit event.

**Comment by bastoica** [comment]
> First, why are you calling dr_app_pc_from_cache_pc? The stored pc is already an app pc 

I've minimized the failing code and kept only the relevant parts (although it might not make sense functionally :-) ).

> Second, the crash occurs not at any instrumentation call, but the call from the thread exit event. 

Yes, in fact I need to call `dr_app_pc_from_cache_pc()` from the thread exit event in order to translate a code cache pc. 

> We have to clean up the fragment state before we invoke the client's thread exit event so that the client will see fragment deletion events before it throws its own state away. You can see the comment about the potential risk of this ordering here https://github.com/DynamoRIO/dynamorio/blob/master/core/dynamo.c#L1217 We can't change the exit order without breaking parts of the interface

I see. I'll modify my library accordingly. Thanks much.

**Comment by derekbruening** [comment]
In general, the API tries to hide the details of the code cache, and tools should not normally want to know about cache pcs.  dr_app_pc_from_cache_pc() is expected to only be used in sophisticated callout schemes, so it's hard to give any priority to calling it from a thread exit event when we have never seen a need for something like that.  You could certainly file a feature request or send a patch with an explanation of why it's necessary.

**Comment by bastoica** [comment]
Well, I'm working on an application that intercepts memory accesses via a kernel module. So, basically, when I'm reading UNIX's `regs` data structure (`regs->ip` to be more precise) I intercept the translated PC rather than the original PC. What my library does is to load the kernel module and poll a shared buffer periodically to get the intercepted PCs. However, it needs to call `dr_app_pc_from_cache_pc()` when the application stops to translate the PCs.

As a workaround I'm trying to send a signal right before dynamo_process_exit() does anything and give control back to my own client to call dr_app_pc_from_cache_pc() but I cannot manage to link `libc` using the cmake files... I just need `kill()` from `signal.h` and keep getting `undefined global symbol` when compiling.... 

I've tried an easier workaround, i.e., capturing the _exit() signal, but that didn't work....
