### ISSUE TITLE
Warnings for deprecated IT blocks in allasm_thumb.asm

### ISSUE THREAD

**Issue by egrimley** [DynamoRIO/dynamorio#2002]
If you build DynamoRIO on an ARMv8 system you get lots of warnings like this from allasm_thumb.asm:

IT blocks containing 16-bit Thumb instructions of the following class are deprecated in ARMv8: Short branches, Undefined, SVC, LDM/STM
IT blocks containing 32-bit Thumb instructions are deprecated in ARMv8
IT blocks containing more than one conditional instruction are deprecated in ARMv8

It seems reasonable to test deprecated things, but the warnings are a nuisance and may be treated as errors.

You can get rid of them by adding "-mno-warn-deprecated" after "-mfpu=neon" in make/cpp2asm_support.cmake, but that would presumably suppress the warnings for arm.asm, too, which we perhaps do not want. I was unable to persuade CMake (I now know what the 'C' stands for) to add the option only for allasm_thumb.asm. Perhaps someone else knows how to do it.

**Comment by fhahn** [comment]
dup of #1675
