### ISSUE TITLE
AArch64 build failures with static DR

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#2007]
#975 made static DR first-class-supported and it builds on its own and in small startstop test apps, but linking with drmemtrace it fails to link:

https://travis-ci.org/DynamoRIO/dynamorio/jobs/161201683

```
Linking CXX executable ../bin64/tool.drcacheoff.burst_static
../../lib64/debug/libdynamorio_static.a(libdynamorio_static.o): In function `check_param_bounds':
/home/travis/build/DynamoRIO/dynamorio/core/options.c:561:(.text+0x108c4): .relocation truncated to fit: R_AARCH64_LD64_GOT_LO12_NC against `main_logfile'
/home/travis/build/DynamoRIO/dynamorio/core/options.c:561:(.text+0x10934): relocation truncated to fit: R_AARCH64_LD64_GOT_LO12_NC against `main_logfile'
../../lib64/debug/libdynamorio_static.a(libdynamorio_static.o): In function `update_dynamic_options':
/home/travis/build/DynamoRIO/dynamorio/core/optionsx.h:221:(.text+0x339f8): relocation truncated to fit: R_AARCH64_LD64_GOT_LO12_NC against `main_logfile'
/home/travis/build/DynamoRIO/dynamorio/core/optionsx.h:227:(.text+0x33b28): relocation truncated to fit: R_AARCH64_LD64_GOT_LO12_NC against `main_logfile'
/home/travis/build/DynamoRIO/dynamorio/core/optionsx.h:228:(.text+0x33c58): relocation truncated to fit: R_AARCH64_LD64_GOT_LO12_NC against `main_logfile'
/home/travis/build/DynamoRIO/dynamorio/core/optionsx.h:229:(.text+0x33d88): relocation truncated to fit: R_AARCH64_LD64_GOT_LO12_NC against `main_logfile'
/home/travis/build/DynamoRIO/dynamorio/core/optionsx.h:230:(.text+0x3!3eb8): relocation truncated to fit: R_AARCH64_LD64_GOT_LO12_NC against `main_logfile'
/home/travis/build/DynamoRIO/dynamorio/core/optionsx.h:231:(.text+0x33fe8): relocation truncated to fit: R_AARCH64_LD64_GOT_LO12_NC against `main_logfile'
/home/travis/build/DynamoRIO/dynamorio/core/optionsx.h:232:(.text+0x34118): relocation truncated to fit: R_AARCH64_LD64_GOT_LO12_NC against `main_logfile'
/home/travis/build/DynamoRIO/dynamorio/core/optionsx.h:233:(.text+0x34248): relocation truncated to fit: R_AARCH64_LD64_GOT_LO12_NC against `main_logfile'
/home/travis/build/DynamoRIO/dynamorio/core/optionsx.h:234:(.text+0x34378): additional relocation overflows omitted from the output
collect2: error: ld returned 1 exit status
make[2]: *** [clients/bin64/tool.drcacheoff.burst_static] Error 1
make[1]: *** [clients/drcachesim/CMakeFiles/tool.drcacheoff.burst_static.dir/all] Error 2
```

We'll have to disable larger static tests for A64 until we understand what is going on.

**Comment by egrimley** [comment]
I think that's probably caused by conflicting declarations of main_logfile in different files. Perhaps some files are seeing the "typedef int file_t" while others are getting the definition of file_t from the system headers. If the file importing the symbol expects it to be 8-byte-aligned, but the file exporting it only makes it 4-byte-aligned, then the linker may find it has an impossible relocation to perform, and, because it's a linker, it tends to give an error message that isn't very helpful for a typical C programmer... (Presumably the linker doesn't even know that the source was C, rather than Haskell, say.)

**Comment by egrimley** [comment]
In fact, the problem seems to be caused by a bug in binutils: https://sourceware.org/bugzilla/show_bug.cgi?id=18270

I reproduced the problem in an Ubuntu amd64 chroot, and the problem went away when I upgraded binutils-aarch64-linux-gnu from 2.24-<something> to 2.25.1-6ubuntu1.

However, burst_static doesn't pass on AArch64 even when it builds, so upgrading binutils isn't an urgent requirement.

**Comment by derekbruening** [comment]
This shows up in my new opcode_mix_launcher static exe as well:

https://travis-ci.org/DynamoRIO/dynamorio/jobs/418923810
```
lib64/debug/libdynamorio_static.a(libdynamorio_static.o): In function `check_param_bounds':
/work/dr/git/src/core/options.c:697:(.text+0x4350): relocation truncated to fit: R_AARCH64_LD64_GOT_LO12_NC against `main_logfile'
/work/dr/git/src/core/options.c:697:(.text+0x43c0): relocation truncated to fit: R_AARCH64_LD64_GOT_LO12_NC against `main_logfile'
lib64/debug/libdynamorio_static.a(libdynamorio_static.o): In function `update_dynamic_options':
/work/dr/git/src/core/options.c:1001:(.text+0x5284): relocation truncated to fit: R_AARCH64_LD64_GOT_LO12_NC against `main_logfile'
lib64/debug/libdynamorio_static.a(libdynamorio_static.o): In function `synchronize_dynamic_options':
/work/dr/git/src/core/options.c:2486:(.text+0x8edc): relocation truncated to fit: R_AARCH64_LD64_GOT_LO12_NC against `main_logfile'
lib64/debug/libdynamorio_static.a(libdynamorio_static.o): In function `add_shared_block':
/work/dr/git/src/core/fragment.c:391:(.text+0x1cdd8): relocation truncated to fit: R_AARCH64_LD64_GOT_LO12_NC against `main_logfile'
/work/dr/git/src/core/fragment.c:404:(.text+0x1ced0): relocation truncated to fit: R_AARCH64_LD64_GOT_LO12_NC against `main_logfile'
/work/dr/git/src/core/fragment.c:431:(.text+0x1d184): relocation truncated to fit: R_AARCH64_LD64_GOT_LO12_NC against `main_logfile'
lib64/debug/libdynamorio_static.a(libdynamorio_static.o): In function `print_shared_table_stats':
/work/dr/git/src/core/fragment.c:468:(.text+0x1d3bc): relocation truncated to fit: R_AARCH64_LD64_GOT_LO12_NC against `main_logfile'
/work/dr/git/src/core/fragment.c:469:(.text+0x1d428): relocation truncated to fit: R_AARCH64_LD64_GOT_LO12_NC against `main_logfile'
/work/dr/git/src/core/fragment.c:470:(.text+0x1d494): relocation truncated to fit: R_AARCH64_LD64_GOT_LO12_NC against `main_logfile'
/work/dr/git/src/core/fragment.c:471:(.text+0x1d500): additional relocation overflows omitted from the output
collect2: error: ld returned 1 exit status
```

**Comment by derekbruening** [comment]
Re: the main_logfile file_t alignment theory: I tried replacing both the decl and def of main_logfile with `int` instead of `file_t` and the link error persists.  I have not found a workaround short of upgrading binutils and I'm not sure I want to spend time now trying to do that on Travis: so I'm probably going to disable opcode_mix_launcher for AArch64.

**Comment by derekbruening** [comment]
A test for #2001 was most easily implemented as a static-DR test so I ran into this again.  The A64 TLS setup is clobbering the app's TLS base with NULL for static DR resulting in an early crash.  After fixing that, burst_static passes, along with several others:

```
The following tests passed:
	code_api|tool.drcacheoff.burst_traceopts
	code_api|tool.drcacheoff.burst_replace
	code_api|tool.drcacheoff.burst_replaceall
	code_api|tool.drcacheoff.burst_static
	code_api|tool.drcacheoff.burst_noreach
	code_api|tool.drcacheoff.burst_maps
	code_api|tool.drcacheoff.burst_client

64% tests passed, 4 tests failed out of 11

Total Test time (real) = 175.05 sec

The following tests FAILED:
	175 - code_api|tool.drcacheoff.burst_threads (Failed)
	176 - code_api|tool.drcacheoff.burst_malloc (Failed)
	177 - code_api|tool.drcacheoff.burst_threadfilter (Failed)
	178 - code_api|tool.drcacheoff.burst_threadL0filter (Failed)
Errors while running CTest
```

However we can't enable the tests on Travis yet b/c of the binutils bug.  I will put in the TLS fix in any case.

**Comment by derekbruening** [comment]
This is becoming higher priority as we have more use cases of static DR on AArch64 and there is a big gap in automated testing there.

**Comment by AssadHashmi** [comment]
> This is becoming higher priority as we have more use cases of static DR on AArch64 and there is a big gap in automated testing there.

Is the gap based on what is being tested with x86 but not AArch64?
Do we have use-cases which can be ported/added to AArch64 tests?

**Comment by derekbruening** [comment]
> > This is becoming higher priority as we have more use cases of static DR on AArch64 and there is a big gap in automated testing there.
> 
> Is the gap based on what is being tested with x86 but not AArch64?

Right, that is the gap that I mean.  For example, this toolchain build issue here is preventing 11 drcachesim tests from running on AArch64, resulting in bugs we end up hitting that should have been tested and identified in the tests in the suite, like #4461.

> Do we have use-cases which can be ported/added to AArch64 tests?

I think just reaching the same coverage as x86 would help substantially: i.e., ensuring that all the tests currently run on x86 (that are not inherently x86-specific) are also run on AArch64 should be the goal.  It looks like x86 has about 140 more tests running that AArch64.  A few of these will take some effort, such as the detach-state test, but others like these 11 tests should be relatively easy: install a newer binutils in a local dir or sthg if we can't get a system upgrade on the Travis VM.

We are also unfortunately having to spend time debugging and figuring out what turn out to be known gaps in AArch64 features omitted in the initial porting: such as #4271, which was caused by #2043.

**Comment by derekbruening** [comment]
I filed #4474 to help drive improving A64 testing.

**Comment by AssadHashmi** [comment]
> I think the fix is to upgrade the toolchain on the Jenkins machine?

@derekbruening could this issue be fixed when we upgrade to the new CI machine?
What exactly do we have to do with regard to the toolchain to enable this?

**Comment by derekbruening** [comment]
> @derekbruening could this issue be fixed when we upgrade to the new CI machine?
> What exactly do we have to do with regard to the toolchain to enable this?

It is @egrimley who identified the toolchain versions involved up above: see https://github.com/DynamoRIO/dynamorio/issues/2007#issuecomment-248564346

**Comment by derekbruening** [comment]
The tests seem to build on the new Jenkins machine, and the burst ones at least all pass:
```
$ ctest -V -R drcacheoff.burst
The following tests passed:
	code_api|tool.drcacheoff.burst_aarch64_sys
	code_api|tool.drcacheoff.burst_static
	code_api|tool.drcacheoff.burst_replace
	code_api|tool.drcacheoff.burst_replaceall
	code_api|tool.drcacheoff.burst_noreach
	code_api|tool.drcacheoff.burst_maps
	code_api|tool.drcacheoff.burst_traceopts
	code_api|tool.drcacheoff.burst_threads
	code_api|tool.drcacheoff.burst_malloc
	code_api|tool.drcacheoff.burst_reattach
	code_api|tool.drcacheoff.burst_threadfilter
	code_api|tool.drcacheoff.burst_threadL0filter
	code_api|tool.drcacheoff.burst_client

100% tests passed, 0 tests failed out of 13
```
