### ISSUE TITLE
Support C++11 in DR

### ISSUE THREAD

**Issue by zhaoqin** [DynamoRIO/dynamorio#2020]
There are some nice features  in C++11, e.g., unsorted_map, that might be useful for a C++ client. Adding support to build those clients with C++11 would be nice.

**Comment by derekbruening** [comment]
Please explain why anything needs to be done: why does this require a DR change?  Is something broken when you try this today?

**Comment by fhahn** [comment]
I think this issue has been resolved, it seems like clients can be built with -std=c++11. 

drcachesim builds ok for me after adding `+add_definitions("-std=c++11")`  to  clients/drcachesim/CMakeLists.txt

**Comment by egrimley** [comment]
There are two mentions of "i#2020" in the source code. But should all these references to "unsorted_map" really be "unordered_map"?

I was able to build with add_definitions("-std=c++11") and with various references to "map" replaced with "unordered_map", but presumably that change would not work with older compilers. When will it be safe to require C++11?

**Comment by derekbruening** [comment]
There's no description of the actual problem here.  Closing as a dup of #1820.

**Comment by egrimley** [comment]
You've closed this issue, but it's still referred to in the source code. Did you mean to close the other one instead?

**Comment by derekbruening** [comment]
Generally the earlier-filed of two dups is kept.  Plus #1820 is much more concrete (though even it does not describe the symptoms of an actual problem, only a fix).  A ref from the code will just have an extra hop to land at #1820 is all.

**Comment by egrimley** [comment]
I thought perhaps the purpose of this issue was to collect a list of changes that should be made when it has been decided that DynamoRIO can require C++11. So the reason that there's no description of an actual problem is that there is no actual problem apart from the problem of some people being very unwilling to upgrade their compilers.

**Comment by fhahn** [comment]
Gcc 4.8 (https://gcc.gnu.org/gcc-4.8/cxx0x_status.html) and clang 3.3 (https://clang.llvm.org/cxx_status.html) were the first versions with complete c++11 support and both were released in 2013. All machines submitting results to CDash (on Linux) are using compilers with C++11 support.

On a slightly related note, maybe we should update the tested compiler versions in https://github.com/DynamoRIO/dynamorio/wiki/How-To-Build#details-for-building-on-linux to match the versions used for CDash? Currently it says `We have tested the following versions of gcc: 4.4.3, 4.3.0, 4.1.2, and 3.4.3.`

**Comment by derekbruening** [comment]
VS2010 was still in use at the time of the thread above, and it does not support enough C++11 for us to switch.  We have now dropped VS2010 and are only supporting VS2013 and above, which does support most (not all) of C++11 and is probably enough to switch DR's C++ code to use C++11.

**Comment by derekbruening** [comment]
#1820 already covered c++11 in clients.  This issue is being changed to be about DR's own code (the parts that are C++).

**Comment by derekbruening** [comment]
The original filed comment does have merit:

Using the gzip trace from #2056:
```
$ /usr/bin/time clients/bin64/drraw2trace -indir drmemtrace.gzip.01022.4725.dir/raw -out /tmp/xx
$ for ((i=0; i<3; i++)); do /usr/bin/time bin64/drrun -t drcachesim -infile /tmp/xx -simulator_type reuse_distance; done 2>&1 | grep elapsed
12.19user 0.17system 0:12.37elapsed 99%CPU (0avgtext+0avgdata 5204maxresident)k
12.25user 0.15system 0:12.42elapsed 99%CPU (0avgtext+0avgdata 5128maxresident)k
12.23user 0.17system 0:12.41elapsed 99%CPU (0avgtext+0avgdata 5316maxresident)k
```

Now with c++11 std::unordered_map instead of std::map:
```
$ for ((i=0; i<3; i++)); do /usr/bin/time bin64/drrun -t drcachesim -infile /tmp/xx -simulator_type reuse_distance; done 2>&1 | grep elapsed
10.15user 0.25system 0:10.64elapsed 97%CPU (0avgtext+0avgdata 5080maxresident)k
9.82user 0.16system 0:09.99elapsed 99%CPU (0avgtext+0avgdata 4884maxresident)k
9.79user 0.14system 0:09.94elapsed 99%CPU (0avgtext+0avgdata 4952maxresident)k
```

**Comment by derekbruening** [comment]
If we do something like `set(BASE_CXXONLY_FLAGS "-std=c++11")` we should be sure to fix the later incorrect reference to `BASE_CXXONLY_CFLAGS`.

**Comment by derekbruening** [comment]
Another problem is that mixed C and C++ clients have their flags squished together by configure_DynamoRIO_common()'s use of tgt_cxx based on the target.  This causes drsyms to fail to build when -std=c++11 is in CMAKE_CXX_FLAGS.
