### ISSUE TITLE
drcachesim pipe-using tests can get into an all-fail state with stale pipe files

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#2023]
```
*Tests failing* (first 5)
code_api|linux.signest (http://dynamorio.org/CDash/testDetails.php?test=4183&build=13022)
code_api|tool.drcachesim.simple (http://dynamorio.org/CDash/testDetails.php?test=133170&build=13022)
code_api|tool.drcachesim.TLB-simple (http://dynamorio.org/CDash/testDetails.php?test=133171&build=13022)
code_api|tool.drcachesim.phys (http://dynamorio.org/CDash/testDetails.php?test=133172&build=13022)
code_api|tool.drcachesim.thumb (http://dynamorio.org/CDash/testDetails.php?test=133173&build=13022)
```

All the pipe ones failed:

```
failed to read from drtestpipe1
ERROR: failed to run analyzer
```

These passed in the prior build.  They also pass on my ARM chromebook.

**Comment by egrimley** [comment]
Have you tried "rm /tmp/drtest*"?

I don't know whether left-over pipes in /tmp can cause this particular problem, but they certainly can cause problems. It would be good if the scripts could be a bit more careful about creating files in /tmp.

**Comment by derekbruening** [comment]
These tests should remove stale files of their same name before running.

These aren't failing on Travis but they are on CDash: http://dynamorio.org/CDash/buildSummary.php?buildid=17836

**Comment by egrimley** [comment]
> These tests should remove stale files of their same name before running.

But how do you know that the file is stale rather than in use by
another instance of "make test" running on the same system? It might
be safer to generate new files and not to worry too much about stale
files left over from interrupted runs, which won't cause practical
problems unless there are thousands of them. A testbot or buildbot
should probably have some higher-level clean-up mechanism in any case
because there are so many things that can leave behind a temporary
file after an unexpected failure.

**Comment by derekbruening** [comment]
Another machine got into this state:

```
*Tests failing* (first 5)
code_api|common.decode (http://dynamorio.org/CDash/testDetails.php?test=4795&build=18705)
code_api|tool.drcachesim.multiproc (http://dynamorio.org/CDash/testDetails.php?test=134309&build=18705)
code_api|tool.drcachesim.TLB-simple (http://dynamorio.org/CDash/testDetails.php?test=169877&build=18705)
code_api|tool.drcachesim.phys (http://dynamorio.org/CDash/testDetails.php?test=169878&build=18705)
code_api|tool.drcachesim.simple (http://dynamorio.org/CDash/testDetails.php?test=169879&build=18705)
```

```
failed to read from drtestpipe1
ERROR: failed to run analyzer
```

**Comment by derekbruening** [comment]
I plan to change -ipc_name to accept an absolute path and to use the build dir as the path for the tests.  Then stale files will be blown away on the next suite run, solving this problem on the bots.
