### ISSUE TITLE
statically linked drmemtrace crashed

### ISSUE THREAD

**Issue by zhaoqin** [DynamoRIO/dynamorio#2028]
When the drmemtrace is statically linked with the app, it may use the applications memory allocator.
On event_exit, `delete instru;` may cause segfault.

**Comment by derekbruening** [comment]
See the final comment in #975 -- client library isolation from the app.

**Comment by zhaoqin** [comment]
hmm, we may have to use DR api like `dr_thread_alloc` instead, so C only?

**Comment by zhaoqin** [comment]
By using dr_thread_alloc and placement new, we are able to work around this problem.
We do not have to use C, but should be careful about what function we called.
Close this issue.
