### ISSUE TITLE
test_times in client.file_io (file_io.dll.c) is flaky

### ISSUE THREAD

**Issue by egrimley** [DynamoRIO/dynamorio#2041]
5380417 added a test of dr_get_time which expects the day and minute to match the return value from localtime, but not the hour "due to UTC vs time zone differences". Three problems:
1. Time zone offsets are not always a multiple of one hour: TZ='Asia/Kolkata' ctest -I 143,143 (or whatever the number of client.file_io is now)
2. If the hour can be wrong, so can the day: either TZ=UTC-13 or TZ=UTC+13 will fail.
3. A new minute could start between the calls to dr_get_time and localtime.

The last problem could only be properly solved by sandwiching the call to dr_get_time between two calls to localtime, but if you don't want to arrange for both functions to use the same time zone, and you don't want to add a second call to localtime, then a reasonable way to compare the two return values might be to check that they are within 36 hours of each other and check that they are within one or two seconds of each other modulo 15 minutes. (I think all time zones in practical use today are offset from UTC by a multiple of 15 minutes. The test still might fail on a very slow or very heavily loaded system...)

**Comment by egrimley** [comment]
The test seems to have failed here, though it's not clear to me why, as it was at 09:20 UTC:

http://dynamorio.org/CDash/testDetails.php?test=137495&build=13395

That machine's not in Hawaii, is it? :-)

**Comment by zhaoqin** [comment]
The test failed on my machine last night too.
It reports different mday (21 vs 20) and wday (5 vs 4).

**Comment by derekbruening** [comment]
Clearly I did not think this one through very well at all.  Maybe simplest to just bail and remove that part of the test.
