### ISSUE TITLE
drcachesim sometimes fails to open pipe file

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#2045]
This happened once for a test that passed many many times:

http://dynamorio.org/CDash/testDetails.php?test=141155&build=13692

ASSERT FAILURE: /work/dr/nightly/src/clients/drcachesim/tracer/tracer.cpp:766: fd != -1 ()

**Comment by derekbruening** [comment]
This hasn't happened since.  Assuming to be an instance of #2023.

**Comment by makmanalp** [comment]
Hit this on the 7.0.0-RC1 build (linux):

```
ubuntu@xxxxxxxxx:~/test$ time ../DynamoRIO-Linux-7.0.0-RC1/bin64/drrun -c ../DynamoRIO-Linux-7.0.0-RC1/tools/lib64/release/libdrmemtrace.so -- ./a.out
ASSERT FAILURE: /dynamorio_package/clients/drcachesim/tracer/tracer.cpp:890: fd != -1 ()
```

Though I'm unsure I'm supposed to be invoking it like that. In my case `/tmp` didn't seem to have any `dr*` files left over.

**Comment by derekbruening** [comment]
It turns out this is *not* a dup of #2023: there is a race between the pipe creator and writer in the drcachesim launcher.
