### ISSUE TITLE
Incomplete zeroing of the "raw_ldt_entry_t" array before calling "modify_ldt_syscall(...)"

### ISSUE THREAD

**Issue by maksqwe** [DynamoRIO/dynamorio#2074]
Line 224: /drmemory/dynamorio/core/unix/tls_linux_x86.c
```C++
    raw_ldt_entry_t ldt[LDT_ENTRIES_TO_CHECK];
...
    memset(ldt, 0, sizeof(*ldt));
    bytes = modify_ldt_syscall(0, (void *)ldt, sizeof(ldt));
```
sizeof(*ldt) == sizeof(raw_ldt_entry_t)
sizeof(ldt) == sizeof(raw_ldt_entry_t) * LDT_ENTRIES_TO_CHECK

**Comment by derekbruening** [comment]
The memset is presumably not necessary and is just defensive but it should be the whole array.
