### ISSUE TITLE
c4b2d20 broke the build on Debian stretch

### ISSUE THREAD

**Issue by egrimley** [DynamoRIO/dynamorio#2083]
Link: c4b2d20

The error message is:

/usr/bin/ld: -r and -pie may not be used together

It works if you specify both options: -r -Wl,-r

Derek, can you check whether using both options works with clang?

**Comment by derekbruening** [comment]
I can check for whatever clang is on my fedora, but it may be best to do a try build on Travis using a pull request to check that clang.

**Comment by derekbruening** [comment]
If we want to support this build env, a CDash bot would help -- otherwise we will never know if it's broken.

**Comment by derekbruening** [comment]
The build fails with "-r -Wl,-r":

```
clang: error: argument unused during compilation: '-r'
```

For:
```
clang version 3.5.0 (tags/RELEASE_350/final)
Target: x86_64-redhat-linux-gnu
```

**Comment by egrimley** [comment]
It looks like you can fix the problem on a reasonably recent GCC by adding "-no-pie": -nostartfiles -nodefaultlibs -Wl,-r -no-pie (core/CMakeLists.txt:793)

However, an ancient GCC has never heard of that option: gcc: error: unrecognized command line option '-no-pie'

I can't see a better solution than detecting the GCC version or somehow directly testing whether "-no-pie" is understood. But I don't know enough about cmake to implement that.

One may also need to suppress the "-no-pie" when using (some versions of) clang. Perhaps "if (CMAKE_COMPILER_IS_CLANG)" is the way to do that.

I'm leaving this for now as I have some other problems to work on...
