### ISSUE TITLE
Problems with "-Wl,-static"

### ISSUE THREAD

**Issue by egrimley** [DynamoRIO/dynamorio#2084]
With i#2083 fixed, there are still problems on Debian armhf/arm64 stretch. (The problem may also exist on Intel. It's hard to tell as the tests are architecture-specific and there is also another problem on Intel.)

On ARM, two tests fail:

	103 - code_api|tool.drcachesim.thumb (Failed)
	104 - code_api|tool.drcachesim.arm (Failed)

On AArch64, the build fails:

/usr/bin/ld: CMakeFiles/common.allasm_aarch64_isa.dir/common/allasm_aarch64_isa.asm.o: relocation R_AARCH64_MOVW_UABS_G3 against `a local symbol' can not be used when making a shared object; recompile with -fPIC

Both these problems can be fixed with:

perl -i -pe 's/-Wl,-static/-static/;' suite/tests/CMakeLists.txt

So the question is: was there ever a good reason for bypassing the compiler driver with "-Wl"?

**Comment by derekbruening** [comment]
I would assume that it didn't build otherwise (or maybe it was just translated from "as .asm && ld -static" in local tests where the compiler driver was never invoked, but why add -nostartfiles yet bother to prefix -Wl for -static?).

**Comment by egrimley** [comment]
Note that Stretch is Debian's "testing" distribution so there can be disruptive changes. This problem (and also i#2083) probably relates to the addition of "--enable-default-pie" in version 6.2.0-7 of gcc-6, changelog dated 18 Oct 2016. Probably other Linux distributions will make the same configuration change, but, because it's a configuration change, you won't be able to tell from the upstream GCC version whether you have the change. However, if you build a trivial program with "gcc t.c" the output from "readelf -l a.out" looks very different.

Old GCC: Elf file type is EXEC (Executable file)

New GCC: Elf file type is DYN (Shared object file)

I'll try to do a try build...

**Comment by derekbruening** [comment]
I would suggest that while we certainly want to support *running* DR on the latest distros, it may not be worth the effort to support *building* on bleeding edge setups.
