### ISSUE TITLE
Problem with SHOW_RESULTS

### ISSUE THREAD

**Issue by egrimley** [DynamoRIO/dynamorio#2087]
With i#2083 and i#2084 fixed, there's still a bunch of failures on Debian arm64 Stretch, but only without DEBUG:

```
The following tests FAILED:
	105 - code_api|sample.bbsize (Failed)
	107 - code_api|sample.memtrace_simple (Failed)
	108 - code_api|sample.instrace_simple (Failed)
	109 - code_api|sample.wrap (Failed)
	110 - code_api|sample.signal (Failed)
	111 - code_api|sample.syscall (Failed)
	112 - code_api|sample.inline (Failed)
	113 - code_api|sample.inscount (Failed)
	114 - code_api|sample.inscount.cleancall (Failed)
	115 - code_api|sample.inscount.prof-pcs.cleancall (Failed)
	116 - code_api|sample.stl_test (Failed)
```

The problem can be fixed with this daft patch:

```
--- a/api/samples/CMakeLists.txt
+++ b/api/samples/CMakeLists.txt
@@ -86,12 +86,12 @@ else (BUILD_TESTS)
   set(SHOW_RESULTS_DEFAULT ON)
 endif (BUILD_TESTS)
 
-option(SHOW_RESULTS
+option(SHOW_RESULTZ
   "Display client results in pop-up (Windows) or console message (Linux)"
   ${SHOW_RESULTS_DEFAULT})
-if (SHOW_RESULTS)
+if (SHOW_RESULTZ)
   add_definitions(-DSHOW_RESULTS)
-endif (SHOW_RESULTS)
+endif (SHOW_RESULTZ)
 
 option(SHOW_SYMBOLS "Use symbol lookup in clients that support it" ON)
 if (SHOW_SYMBOLS)
```

So it looks as though the name "SHOW_RESULTS" is somehow special, perhaps used by cmake itself or some other component. However, I can't discover how or why. Any ideas?

**Comment by derekbruening** [comment]
Are you sure this isn't just an artifact of enabling BUILD_TESTS in an already-configured build dir that didn't have it enabled before, or something like that?  I.e., does this really happen in a clean dir.  Also, please verify the actual test failure reasons.

**Comment by egrimley** [comment]
Yes, it must have been something like that because I'm not seeing the problem today. Closing.
