### ISSUE TITLE
drrun finds executable in current directory but not on PATH

### ISSUE THREAD

**Issue by egrimley** [DynamoRIO/dynamorio#2097]
```
$ cp -i /usr/bin/uptime date
$ date
Wed  7 Dec 18:09:04 GMT 2016
$ bin64/drrun -- date
 18:09:07 up 84 days,  5:13,  3 users,  load average: 4.92, 3.76, 2.23
$
```

Bug in how drdeploy.c uses drfront_get_absolute_path()?

**Comment by derekbruening** [comment]
drdeploy.c first does search_env() on PATH and if that fails it does drfront_get_absolute_path().  This is coming from a Windows perspective -- though IIRC on Windows it should actually be in the other order.

On UNIX the abs-path should only be done if the given app string starts with a "." (whether "./" or "../").

However, the behavior shown simply should not happen: why didn't search_env() find date in /usr/bin?

**Comment by egrimley** [comment]
Shouldn't it do the same as execvp (see man page): if no '/' in the filename, look at PATH; if PATH not defined, use confstr(_CS_PATH)? Of course, since execvp does all this for you, you could compile a little execvp wrapper and run that wrapper under DynamoRIO... (not a serious suggestion)

**Comment by egrimley** [comment]
Is there a good reason for drfront_access using stat, and faffing around with geteuid, rather than just using access/faccessat?

**Comment by derekbruening** [comment]
> Is there a good reason for drfront_access using stat, and faffing around with geteuid, rather than just using access/faccessat?

Not sure, I did not write that code: is access not available on Mac or Android, perhaps?

**Comment by egrimley** [comment]
Yes, this is a duplicate of i#2109, which provides a more detailed proposal.

**Comment by derekbruening** [comment]
Please use the labels: Status-Duplicate
