### ISSUE TITLE
add decoder support for SMAP instructions STAC and CLAC

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#2103]
Haswell has a new Supervisor Mode Access Prevention (SMAP) feature which
introduces two new instructions, STAC and CLAC, to set and clear a bit in
CR4.

**Comment by dolanzhao** [comment]
(#5505) The kernel instruction traces contain STAC and CLAC instructions. Not sure if ignoring these two types of instructions will affect synthetic kernel memory addresses.
