### ISSUE TITLE
uCRT/LoadLibrary advapi32

### ISSUE THREAD

**Issue by 0vercl0k** [DynamoRIO/dynamorio#2120]
I've noticed recently in one binary the following code that I believe is from the uCRT (the new CRT with VS2015):

```c
HMODULE __cdecl sub_10003E7D(int a1)
{
[...]
    v4 = (&lpLibFileName)[2 * a1];
    v5 = LoadLibraryExW(v4, 0, 0x800u);
    if ( v5 || (GetLastError() != 87 ? (v5 = 0) : (v5 = LoadLibraryExW(v4, 0, 0)), v5) )

```

Where the `lpLibFileName` array is defined like this:

```text
.rdata:1000C88C ; LPCWSTR lpLibFileName
.rdata:1000C88C lpLibFileName   dd offset aAdvapi32     ; DATA XREF: sub_10003E7D:loc_10003EA5r
.rdata:1000C88C                                         ; "advapi32"
.rdata:1000C890                 dd offset aApiMsWinCoreFi ; "api-ms-win-core-fibers-l1-1-1"
.rdata:1000C894                 dd offset aApiMsWinCoreSy ; "api-ms-win-core-synch-l1-2-0"
.rdata:1000C898                 dd offset aKernel32     ; "kernel32"
```

The issue I've observed is when this code gets invoked by the target application, the `LoadLibrary` call will get hooked by `redirect_LoadLibraryExW` and finally end-up in `privload_locate_and_load` to actually load the library.

The issue here is that the original version of `LoadLibrary` will successfully load the library even if it's not suffixed by ".dll", which `redirect_LoadLibraryExW` will fail to do.

The result of this is I get the message box notifying me that the `LoadLibrary` call failed throw by DR at the end of the function. I'm working around this by having a valid `advapi32` file in the current directory, but it sounds like I could suffix the library name by ".dll" if it's not there already. I could provide a PR for this if you guys are down.

Lemme know what do you think!

Cheers

**Comment by derekbruening** [comment]
Thank you for the detailed analysis.  I think you mean s/application/client/ as it's the client's library loads that are redirected, not the app's.  I can reproduce this with a VS2015-built client.

**Comment by 0vercl0k** [comment]
That's what I meant indeed!

Cheers

2017-01-19 10:08 GMT-08:00 derekbruening <notifications@github.com>:

**Comment by 0vercl0k** [comment]
Thanks Derek!

2017-02-02 21:31 GMT-08:00 derekbruening <notifications@github.com>:
