### ISSUE TITLE
unit_tests failing: kernel32_file.c:2378 test_file_times

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#2121]
http://dynamorio.org/CDash/testDetails.php?test=178469&build=16800

http://dynamorio.org/CDash/testDetails.php?test=178476&build=16801

EXPECT failed at D:\derek\dr\nightly\src\core\win32\drwinapi\kernel32_file.c:2378 in test test_file_times: memcmp(&st_ours, &st_native, sizeof(st_ours))

There were no commits recently and the failure was on Dec 31.  Perhaps there's some end-of-year issue: maybe a bug in redirect_FileTimeToSystemTime() in computing the year.

**Comment by egrimley** [comment]
Yes, it looks like a bug in convert_millis_to_date() that affects Dec 31 in a leap year: after "time %= DAYS_IN_4_YEARS" time will equal 4 * 365, so (time / 365) is 4 and "time %= 365" sets time to 0, so it's treated as Jan 1 of the following year. If we're seriously worried about performance here (there's a "move to a uint" comment that suggests that performance perhaps does matter) there are formulae like https://en.wikipedia.org/wiki/Zeller's_congruence which might be faster than reading days_per_month_normal[] in a loop.

Date conversion bugs are so perennial. Sadly, the 2016 leap second seems not to be implicated.

**Comment by egrimley** [comment]
Fix here: https://codereview.appspot.com/311540043/
