### ISSUE TITLE
ASSERT in native_exec_init() fires when recent clang incorrectly removes extern address comparison

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#2124]
Building with a very recent clang results in this assert firing at DR init time:

```
Internal Error: DynamoRIO debug check failure: core/native_exec.c:72 retstub_end == retstub_start + MAX_NATIVE_RETSTACK * BACK_FROM_NATIVE_RETSTUB_SIZE
(Error occurred @0 frags)
```

The condition is true, but the compiler is removing the comparison completely, resulting in the assert always firing!  Only the checklevel compare is left.

Prior clang had two compares:

```
   0x00000000007a0e55 <+485>:	mov    0x263404(%rip),%rax        # 0xa04260
   0x00000000007a0e5c <+492>:	cmpl   $0x1,0x224(%rax)
   0x00000000007a0e66 <+502>:	jb     0x7a0ea7 <native_exec_init+567>
   0x00000000007a0e6c <+508>:	mov    0x2a9c1d(%rip),%rax        # 0xa4aa90 <retstub_end>
   0x00000000007a0e73 <+515>:	mov    0x2a9c1e(%rip),%rcx        # 0xa4aa98 <retstub_start>
   0x00000000007a0e7a <+522>:	add    $0x28,%rcx
   0x00000000007a0e81 <+529>:	cmp    %rcx,%rax
   0x00000000007a0e84 <+532>:	je     0x7a0ea7 <native_exec_init+567>
   0x00000000007a0e8a <+538>:	lea    0x20626a(%rip),%rdi        # 0x9a70fb <.L.str>
   0x00000000007a0e91 <+545>:	mov    $0x48,%esi
   0x00000000007a0e96 <+550>:	lea    0x2062c6(%rip),%rdx        # 0x9a7163 <.L.str4>
   0x00000000007a0e9d <+557>:	callq  0x60c2f0 <internal_error>
```

Recent clang has just one, for checklevel:

```
   0x0000000000744233 <+483>:   lea    0x2d0efe(%rip),%rax        # 0xa15138 <dynamo_options>
   0x000000000074423a <+490>:   cmpl   $0x1,0x224(%rax)
   0x0000000000744241 <+497>:   jb     0x744264 <native_exec_init+532>
   0x0000000000744247 <+503>:   lea    0x261fdc(%rip),%rdi        # 0x9a622a <.L.str>
   0x000000000074424e <+510>:   mov    $0x48,%esi
   0x0000000000744253 <+515>:   lea    0x26204e(%rip),%rdx        # 0x9a62a8 <.L.str.4>
   0x000000000074425a <+522>:   callq  0x8550d0 <internal_error>
```

A bisect over LLVM commits found the culprit, in tools/clang, which seems to be expanding const evaluation:

https://reviews.llvm.org/rL290297
https://reviews.llvm.org/D14274

**Comment by derekbruening** [comment]
I can reproduce the problem via:

```
#include <stdio.h>
extern void * asm_label;
extern void * asm_label2;
int main() {
  __asm("asm_label: asm_label2:");
  void **local = &asm_label;
  if (local != &asm_label2)
    puts("bug w/ local");
  else
    puts("no bug w/ local");
  if (&asm_label != &asm_label2)
    puts("bug w/ direct ref");
  else
    puts("no bug w/ direct ref");
  return 0;
}
```

# /usr/bin/clang clangbug.c -o clangbug && ./clangbug
no bug w/ local
bug w/ direct ref
# /usr/bin/gcc clangbug.c -o clangbug && ./clangbug
no bug w/ local
no bug w/ direct ref

Even older clang reproduces the bug on a direct compare.

The new clang is only needed to get a bug on comparing static const vars
set to point to the extern values.  I can't seem to repro that in the
reproducer though: only in native_exec.c.

A workaround is shown: storing even just one side into a (non-static-const) var.

**Comment by derekbruening** [comment]
Adding a link for easier access as I plan to point at this from the clang bug: https://github.com/DynamoRIO/dynamorio/blob/master/core/native_exec.c#L74

**Comment by derekbruening** [comment]
Filed as clang bug https://llvm.org/bugs/show_bug.cgi?id=31675

**Comment by egrimley** [comment]
Presumably that work-around (storing into a variable) relies on optimisation being disabled, which is the normal situation when ASSERT is enabled. A more robust work-around might be to use inline assembler, something like:

```
static inline char *id(char *x) { __asm("" : "+r"(x)); return x; }
int f(void) { return id(a) == id(b); }
```

Here `id` is an "opaque identity function": a low-overhead identity function (no extra code), but the compiler cannot detect that it is an identity function (one hopes). Are there other, better ways of achieving this?
