### ISSUE TITLE
APP CRASH (antiRE.exe) new_method == get_syscall_method() arch.c

### ISSUE THREAD

**Issue by Simorfo** [DynamoRIO/dynamorio#2140]
With version 6.2.0-2 of DynamoRio
The latest build does not solve the problem

On Windows 7, with a 32 bit application, antiRE.exe from Daniel Plohmann and Christopher Kannen : it is another tool to test reverse engineering tools such as dynamorio [see](https://bitbucket.org/fkie_cd_dare/simplifire.antire)

I run it with (no client)
C:\rio\bin32\drrun.exe -- antiRE.exe

With flags -debug -msgbox_mask 0xf, I get the failed assert new_method == get_syscall_method() in arch.c

The expected output is some lines ending with "All tests finished. Successful Tests : X. Failed Tests : Y"
Instead we get an application end.

The comment above the assertion states
`/* we assume only single method; else need multiple do_syscalls */`
This assumption is wrong with antiRE.exe using both syscall and int 2e

To get it working, we also need to get the strange behavior of int 2e
Here is a patch
```
diff --git a/dynamorio/core/win32/syscall.c b/dynamorio/core/win32/syscall.c
index eaab6d2..15b9e0f 100644
--- a/dynamorio/core/win32/syscall.c
+++ b/dynamorio/core/win32/syscall.c
@@ -2766,7 +2766,20 @@ pre_system_call(dcontext_t *dcontext)
     dcontext->sys_param3 = sys_param(dcontext, param_base, 3);
 #endif
 
-    if (sysnum == syscalls[SYS_Continue]) {
+    // see int2e list here http://vxheaven.org/lib/vzo25.html
+    if (sysnum > 0x199) {
+        //TODO should check for int 2e syscall
+        PEB *peb = get_own_peb();
+        //set next point
+        if (get_os_version() == WINDOWS_VERSION_7) {
+            // 0x4c is only win7
+            //TODO should include some tests about readability
+            dcontext->next_tag = ((app_pc *) peb->KernelCallbackTable)[0x4c] ;
+        }
+        LOG(THREAD, LOG_SYSCALLS|LOG_ASYNCH, 1, "syscall: no int 2e %p next="PFX"\n", peb->KernelCallbackTable, dcontext->next_tag);
+        execute_syscall = false;
+    }
+    else if (sysnum == syscalls[SYS_Continue]) {
         CONTEXT *cxt = (CONTEXT *) sys_param(dcontext, param_base, 0);
         /* FIXME : we are going to read and write to cxt, which may be unsafe */
         int flag = (int) sys_param(dcontext, param_base, 1);
```

**Comment by Simorfo** [comment]
I did not manage to reproduce the bug with int 2e with the current version of dynamorio

**Comment by derekbruening** [comment]
On Linux 32-bit both sysenter and int 0x80 are used and it ends up working though I don't recall the details of how the method is handled.

**Comment by derekbruening** [comment]
Looks like #432 covers the same assert and the same underlying problem of not handling multiple simultaneous syscall methods so let's close this to collapse to a single issue.
