### ISSUE TITLE
Build instructions need improvement

### ISSUE THREAD

**Issue by olignyf** [DynamoRIO/dynamorio#2141]
Hi,
I followed the steps from top and it fails at "assembler not found: required to build"
![dynamorio-asm](https://cloud.githubusercontent.com/assets/1154566/21998574/a9fc71ac-dc03-11e6-9a8d-8eeb3c845e79.png)
Please help me how to fix and I will make a pull request with modified docs.
I used latest CMake cmake-3.7.2-win64-x64.msi and Visual Studio 2013
Thanks
Francois

**Comment by derekbruening** [comment]
Are you sure your shell is configured for building with Visual Studio?  Please try from a Visual Studio Command Prompt.

**Comment by olignyf** [comment]
Yes that worked! Thanks

**Comment by derekbruening** [comment]
Good. That is in the docs IIRC.

Note that questions like this should generally go to the users list. Once
an actual bug is found then an issue is opened.
