### ISSUE TITLE
Four scratch registers are not enough for ARMv8.1 stolen register mangling

### ISSUE THREAD

**Issue by egrimley** [DynamoRIO/dynamorio#2142]
In `mangle_stolen_reg()` there is a call to `pick_scratch_reg()` to find an unused register, but only `SCRATCH_REG0`, ..., `SCRATCH_REG3` (which are X0, X1, X2, X3) are considered. ARMv8.1 added the instruction CASP, with five register operands, so this can fail in the worst case:

```
        .global f
f:
        str     x28, [sp, #-16]!
        mov     x28, x4
        casp    x0, x1, x2, x3, [x28]
        ldr     x28, [sp], #16
        ret
```

```
typedef unsigned long long u64;

void f(u64, u64, u64, u64, void *);

int main()
{
    u64 x[2];
    f(0, 0, 0, 0, x);
    return 0;
}
```

```
gcc -march=armv8.1-a casp.c casp1.s
bin64/drrun -steal_reg 28 -- ./a.out
```

```
Internal Error: DynamoRIO debug check failure: /.../dynamorio/core/arch/aarchxx/mangle.c:1855 tmp != REG_NULL
```

Is there a good reason why only certain registers are used as scratch registers? I am thinking about applying mangle_stolen_reg to a block of instructions, in which case the number of registers in use could be much larger than five. So why not allow any general-purpose register as a scratch register?

**Comment by derekbruening** [comment]
The reason is that there are only spill slots available for 4 regs r0..r3.

**Comment by egrimley** [comment]
It seems that the only reason for having scratch registers that correspond to spill slots is for certain optimisations which aren't implemented for AArch64 in any case. The patch below makes it pick any GPR and spill it to TLS_REG0_SLOT. It seems to work.

(We now have 6 spill slots on AArch64. So using all 6 would fix this particular bug, involving CASP. Another work-around for this particular bug would be to use a different set of four scratch registers, because CASP cannot use an arbitrary set of five registers; each register pair must be even-odd and consecutive.)

```
index 7c35174..a0c70b4 100644
--- a/core/arch/aarchxx/mangle.c
+++ b/core/arch/aarchxx/mangle.c
@@ -1850,6 +1850,7 @@ mangle_stolen_reg(dcontext_t *dcontext, instrlist_t *ilist,
     }
 #endif
 
+#ifndef AARCH64
     /* move stolen reg value into tmp reg for app instr execution */
     tmp = pick_scratch_reg(dcontext, instr, false, &slot, &should_restore);
     ASSERT(tmp != REG_NULL);
@@ -1862,6 +1863,42 @@ mangle_stolen_reg(dcontext_t *dcontext, instrlist_t *ilist,
     /* restore tmp if necessary */
     if (should_restore)
         PRE(ilist, next_instr, instr_create_restore_from_tls(dcontext, tmp, slot));
+#else
+    /* Silence tedious warnings. */
+    (void)should_restore;
+    (void)restore_tls_base_to_stolen_reg;
+    (void)restore_app_value_to_stolen_reg;
+    (void)pick_scratch_reg;
+
+    /* Pick scratch reg and slot. */
+    for (tmp = DR_REG_X0; tmp <= DR_REG_X29; tmp++) {
+        if (!instr_uses_reg(instr, tmp))
+            break;
+    }
+    ASSERT(tmp <= DR_REG_X29);
+    slot = TLS_REG0_SLOT;
+
+    PRE(ilist, instr, instr_create_save_to_tls(dcontext, tmp, slot));
+    PRE(ilist, instr, XINST_CREATE_move(dcontext,
+                                        opnd_create_reg(tmp),
+                                        opnd_create_reg(dr_reg_stolen)));
+    if (instr_reads_from_reg(instr, dr_reg_stolen, DR_QUERY_INCLUDE_ALL)) {
+        PRE(ilist, instr, instr_create_restore_from_tls(dcontext, dr_reg_stolen,
+                                                        TLS_REG_STOLEN_SLOT));
+    }
+    /* -- app instr executes here -- */
+    if (instr_writes_to_reg(instr, dr_reg_stolen, DR_QUERY_INCLUDE_ALL)) {
+        PRE(ilist, next_instr, XINST_CREATE_store
+            (dcontext, opnd_create_base_disp(tmp, REG_NULL, 0,
+                                             os_tls_offset(TLS_REG_STOLEN_SLOT),
+                                             OPSZ_PTR),
+             opnd_create_reg(dr_reg_stolen)));
+    }
+    PRE(ilist, next_instr, XINST_CREATE_move(dcontext,
+                                             opnd_create_reg(dr_reg_stolen),
+                                             opnd_create_reg(tmp)));
+    PRE(ilist, next_instr, instr_create_restore_from_tls(dcontext, tmp, slot));
+#endif
 }
 
 /* replace thread register read instruction with a TLS load instr */
```

**Comment by derekbruening** [comment]
> It seems that the only reason for having scratch registers that correspond to spill slots is for certain optimisations which aren't implemented for AArch64 in any case. The patch below makes it pick any GPR and spill it to TLS_REG0_SLOT. It seems to work.

No, scratch registers are assumed to correspond to spill slots for state translation on a fault.  Mixing them up will fail to properly restore.

**Comment by derekbruening** [comment]
Elaborating on that: please note that it's not just for a fault.  State translation is used for synchronous reset and flushing, so it's needed independently of whether an instruction can raise a fault.

The translation code could be augmented to figure out which slot is being used, but it would add complexity (and in general mixing them up may make it confusing to debug and have interactions with other components we're not thinking of right now -- I don't think it affects clients or drreg).  That's all better than adding yet more spill slots, but if A64 already has 2 extra ones, isn't that sufficient rather than mixing slots?

**Comment by egrimley** [comment]
The problem I'm really worried about is i#1698, where any trivial program can turn into an infinite loop. The only idea I have for fixing that is to build a "macro-instruction" containing the whole load/store exclusive loop. This loop could easily use more than 6 registers (though probably in most cases it doesn't), and it contains those load/store instructions, so it could fault (though I wouldn't expect a fault to occur here in practice). Perhaps I could spill a non-standard register only as a last resort. A slight risk of a bad state translation is better than an internal error or an infinite loop...

**Comment by derekbruening** [comment]
Well we wouldn't put in code that knowingly fails to translate: we'd fix the spill or the translation.  That part need not have any risk.  It's ldrex...strex where it may not be feasible to get a 100% solution that supports all instrumention -- let's discuss that in #1698.

**Comment by egrimley** [comment]
I'll try to fix this bug by having 6 scratch registers on AArch64 to match the 6 spill slots.

(By the way, is i#2072 worth mentioning here? It might be a state mistranslation.)

**Comment by derekbruening** [comment]
> (By the way, is i#2072 worth mentioning here? It might be a state mistranslation.)

You mean, is it related to this issue?  I don't think so.  Maybe it should be Holist-Release though.
