### ISSUE TITLE
HANG (petite22-hostname.exe) reset of direction flag 

### ISSUE THREAD

**Issue by Simorfo** [DynamoRIO/dynamorio#2155]
With version 6.2.0-2 of DynamoRio
The latest build does not solve the problem

On Windows 7, with a 32 bit application, petite22-hostname.exe the classic hostname software packed with petite22

I run it with (no client)
C:\rio\bin32\drrun.exe -- petite22-hostname.exe

The expected output is a line with the hostname.
Instead we get an endless loop.

The problem seems to come from sandboxing mode from dynamorio not taking care of direction flag with this basic block 
```
interp: start_pc = 0x010051b2
  0x010051b2  8b 44 24 18          mov    0x18(%esp)[4byte] -> %eax
  0x010051b6  fd                   std
  0x010051b7  8b f0                mov    %eax -> %esi
  0x010051b9  8b f8                mov    %eax -> %edi
  0x010051bb  03 73 04             add    0x04(%ebx)[4byte] %esi -> %esi
  0x010051be  03 7b 08             add    0x08(%ebx)[4byte] %edi -> %edi
  0x010051c1  f3 a5                rep movs %ds:(%esi)[4byte] %esi %edi %ecx -> %es:(%edi)[4byte] 
  0x010051c3  83 c3 0c             add    $0x0000000c %ebx -> %ebx
  0x010051c6  fc                   cld
  0x010051c7  eb e1                jmp    $0x010051aa
end_pc = 0x010051c9
```

The interesting instructions are : std, some stuff, a rep instruction (which could be a self modification), more stuff, cld, and then a jump to end the basic block.
Because there a could be a self modification by the rep movs instruction, we enter a new basic block at 0x010051c3
Because we are in sandboxing mode, dynamorio executes sandbox_top_of_bb to "add check at top of ilist that compares actual app instructions versus copy we saved"
To do so, it uses "repe cmpsb" without ensuring that the direction flag has the correct value.
Because there is the wrong flag value, the comparison finds a difference, and keeps forever reentering this basic block at 0x010051c3

The following patch solves the problem for this case but is not generic enough
```
diff --git a/dynamorio/core/arch/x86/mangle.c b/dynamorio/core/arch/x86/mangle.c
index 0332dab..77bf607 100644
--- a/dynamorio/core/arch/x86/mangle.c
+++ b/dynamorio/core/arch/x86/mangle.c
@@ -3865,6 +3865,8 @@ sandbox_top_of_bb(dcontext_t *dcontext, instrlist_t *ilist,
             INSTR_CREATE_mov_imm(dcontext, opnd_create_reg(REG_XSI),
                                  OPND_CREATE_INTPTR(end_pc)));
         PRE(ilist, instr, forward);
+        //before a rep, we should have the good direction flag
+        PRE(ilist, instr, INSTR_CREATE_cld(dcontext));
         PRE(ilist, instr, INSTR_CREATE_rep_cmps_1(dcontext));
     }
     PRE(ilist, instr, check_results);
```

**Comment by Simorfo** [comment]
The example was a specific case.

The generic problem is when a sandboxed basic block is entered with direction flag set.

The sandboxing code added by `sandbox_top_of_bb` does not take well into account the limits of the basic block.
Hence the transparent solution is not to clear the direction flag, but rather to get the correct limits for the basic block.

**Comment by derekbruening** [comment]
To clarify: the sandboxing code, including `sandbox_top_of_bb` and `sandbox_rep_instr`, *does* take into account both values of the direction flag.  It checks which way cmps is going and handles both forward and backward.  (The comments above made it sound like there was no consideration or handling at all of a backward direction.)  It sounds like what is happening here is that there is an off-by-one bug in the sandboxing code that handles the backward direction.

**Comment by Simorfo** [comment]
Exactly :-)

**Comment by derekbruening** [comment]
This comment above is incorrect:

> To do so, it uses "repe cmpsb" without ensuring that the direction flag has the correct value.

It does check the direction flag and has two different loops: backward or forward.  (But has the fencepost error.)

**Comment by Simorfo** [comment]
Yes, I was mistaken since adding a `cld` instruction fixed the first case.
Should I update the comment ?
