### ISSUE TITLE
APP CRASH (telock99-hostname.exe) debug register breakpoints

### ISSUE THREAD

**Issue by Simorfo** [DynamoRIO/dynamorio#2163]
With version 6.2.0-2 of DynamoRio
The latest build does not solve the problem

On Windows 7, with a 32 bit application, telock99-hostname.exe the classic hostname software packed with telock99
This behavior can be reproduced with the following minimized [code](https://simorfo.com/files/except-debugreg.c)

I run it with (no client)
C:\rio\bin32\drrun.exe -- telock99-hostname.exe

The expected output is a line with the hostname.
Instead we get a message box indicating a CRC error.

The problem comes from the setting of hardware breakpoints with debug registers.
How telock99 does it is well described here
http://piotrbania.com/all/articles/pbania-dbi-unpacking2009.pdf

The solution I came up with was 
- to add a field `app_pc debugRegisterBreakpoints[4];` in `struct _dcontext_t`
- to set them in `intercept_nt_continue`
- to check for these fields in `mangle_bb_ilist` 
- in case an instruction's address is equal to the value of a debug register, insert before a clean call to a function doing just `os_forge_exception(pc, EXCEPTION_SINGLE_STEP);`

**Comment by Simorfo** [comment]
Should not this issue be closed after #2569 ?

**Comment by derekbruening** [comment]
You mean you meant to put "Fixes #2569" in the commit message?

**Comment by Simorfo** [comment]
Indeed I forgot
