### ISSUE TITLE
drcov2lcov fails to handle code in ELF segments past a gap

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#2243]
Xref #2213.  drmodtrack now supports ELF libraries with gaps, but while
drcov2lcov will now not think one library covers other libraries inside it,
it will miss code present in other than the first segment.  It creates a
hashtable by path and stores the size, which is now just the 1st segment
size.  We can't simply change the table to store by start address, though,
b/c we'd have to redo enumerate_line_info which walks the htable and calls
drsym_enumerate_lines() on each path, passing a single bitmap.  It will
take some work to support multiple segments.

**Comment by Popkornium18** [comment]
I'm running into an issue with drcov2lcov and I'm not entirely sure whether it is this issue or something else.

Basically drcov2lcov produces the expected results for my binary when I build it with GCC but no results at all if I build it with Clang.

With GCC the module table contains 2 entries per library:
```
2,   2, 0x00007faa28fdc000, 0x00007faa28fe8000, 0x00007faa28fe0be0, 0000000000000000,  /path/to/binary
3,   2, 0x00007faa28fe8000, 0x00007faa28fea000, 0x00007faa28fe0be0, 000000000000bba8,  /path/to/binary
```
While with Clang there are 3 entries per library:
```
0,   0, 0x0000000000200000, 0x0000000000208000, 0x0000000000208000, 0000000000000000,  /path/to/binary
1,   0, 0x0000000000208000, 0x0000000000210000, 0x0000000000208000, 0000000000008000,  /path/to/binary
2,   0, 0x0000000000210000, 0x0000000000213000, 0x0000000000208000, 0000000000010000,  /path/to/binary
```

As drcov2lcov ignores all entries but the first the resulting report says that no lines where executed in the binary built with Clang while the GCC output looks as expected.

Is this the same issue or is it something else?
In any case: I would like to fix this (or help fixing it) but I don't really know what changes would be necessary as I haven't worked on anything drcov/lcov related previously.

**Comment by derekbruening** [comment]
To confirm it's this issue: does your library have code in the 2nd or 3rd entry rather than the 1st?  Normally .text is in the first which is why this has not been a common problem.  Use something like `readelf -l`.

**Comment by Popkornium18** [comment]
The .text section seems to be in the 2nd segment for gcc and in the 3rd for clang.

[segments-gcc.txt](https://github.com/DynamoRIO/dynamorio/files/4718040/segments-gcc.txt)
[segments-clang.txt](https://github.com/DynamoRIO/dynamorio/files/4718041/segments-clang.txt)

Drcov2lcov works for the gcc-built binary although .text is not in the 1st segment. But maybe I'm just misinterpreting the readelf output.

**Comment by derekbruening** [comment]
For gcc `.text` is in the 1st *loaded* (labeled `LOAD`) program header (reading down the program headers: 0=PHDR, 1=INTERP, 2=(1st) LOAD).  For clang `.text` is in the 2nd loaded segment: it has a read-only data segment first.  So this indeed is this issue.

That would be great if you could take a stab at fixing this.

**Comment by derekbruening** [comment]
TBH I don't know this code very well but can try to answer questions.  The code had an assumption that a library ("module") occupied a single contiguous piece of memory.  I would imagine we would want to change its library-oriented hashtable into a segment-oriented table, or else add a list of segments to each library entry.

**Comment by derekbruening** [comment]
@zhaoqin if you are able to provide any advice here that would be appreciated

**Comment by derekbruening** [comment]
This is showing up on gcc on Ubuntu20 now and so blocking the upgrade in #4953
