### ISSUE TITLE
"DR_REG_R10" in instr_shared.c and translate.c

### ISSUE THREAD

**Issue by egrimley** [DynamoRIO/dynamorio#2255]
There are suspicious references to DR_REG_R10 in instr_shared.c and translate.c. Perhaps these should be dr_reg_stolen. It's hard to know as the code is not tested. Replacing the "#ifdef ARM" in instr_is_reg_spill_or_restore_ex() with "#if 0", or incrementing "value" just after it is set in translate_walk_restore(), causes no test to fail.

Does this code imply something missing for AArch64?

**Comment by derekbruening** [comment]
Looks like your 7ee7189b30d14911660b60c9184047f06388ef57 failed to update that code.  See the comment that was removed there which pointed at those two pieces of code.

**Comment by derekbruening** [comment]
For the record, no, they should not be dr_reg_stolen: the stolen reg was moved to r10 to survive the concern over the kernel clobbering it.

**Comment by egrimley** [comment]
Yes, that looks right. The references to something happening in mangle_syscall_arch(), which doesn't happen there any more, are a good clue. Shall I prepare a patch to remove the no-longer-relevant code in instr_shared.c and translate.c?

**Comment by derekbruening** [comment]
Seems like the next step, yes.
