### ISSUE TITLE
AArch64 instruction decoder should set flags used by instructions properly

### ISSUE THREAD

**Issue by fhahn** [DynamoRIO/dynamorio#2263]
On AArch64 the instruction decoder currently sets the flags used by each instruction to 0.

**Comment by egrimley** [comment]
The FIXME is in decode_eflags_usage().

**Comment by derekbruening** [comment]
This is breaking use of drreg in drreg-test: http://dynamorio.org/CDash/testDetails.php?test=243700&build=21899 and others

**Comment by egrimley** [comment]
These are, I hope, the A64 instructions that read or write NZCV:
```
# Instructions that read NZCV:

MRS Xt,NZCV
B.cond
ADC, ADCS, SBC, SBCS
CSEL, CSINC, CSINV, CSNEG
CCMN, CCMP
FCSEL

# Instructions that write NZCV:

MSR NZCV,Xt
ADCS, ADDS, SBCS, SUBS
ANDS, BICS
CCMN, CCMP
FCCMP, FCCMPE, FCMP, FCMPE
```
