### ISSUE TITLE
linux.signal_race failing on debug-internal-64

### ISSUE THREAD

**Issue by egrimley** [DynamoRIO/dynamorio#2274]
This is on a branch, but the changes on the branch are supposed to be AArch64-specific, and, although it happened twice on the branch, it didn't happen every time.

https://travis-ci.org/DynamoRIO/dynamorio/jobs/208557176

https://travis-ci.org/DynamoRIO/dynamorio/jobs/208545718

Internal Error: DynamoRIO debug check failure: /home/travis/build/DynamoRIO/dynamorio/core/link.c:1787 !TEST(FRAG_LINKED_OUTGOING, f->flags)

See also i#2071.

**Comment by derekbruening** [comment]
This is a dup of #2066 isn't it?

**Comment by egrimley** [comment]
That one is with linux.signal_racesys rather than linux.signal_race, but it's probably the same bug.
