### ISSUE TITLE
selfmod-big test does not build on Debian amd64 Stretch

### ISSUE THREAD

**Issue by egrimley** [DynamoRIO/dynamorio#2290]
The error is:
```
/usr/bin/ld: CMakeFiles/security-common.selfmod-big.dir/selfmod-big.c_asm.asm.o: relocation R_X86_64_32S against undefined symbol `big' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
```
The same error message is quoted in i#1958, where there is a link to a link to a possible fix.

Debian Stretch was frozen on 5 Feb 2017 (https://lists.debian.org/debian-devel-announce/2017/02/msg00001.html). Recent freezes have lasted between 171 and 308 days (https://wiki.debian.org/DebianReleases#Release_statistics). That suggests a release date for Stretch in the second half of 2017.

**Comment by fhahn** [comment]
Which compiler/versions cause the failure? If it is GCC6 (which seems to be available in Stretch https://packages.debian.org/stretch/gcc-6), this probably isn't a Debian specific problem, but a GCC6 problem, as raised in #1958

**Comment by egrimley** [comment]
It's gcc version 6.3.0 20170205 (Debian 6.3.0-6). It might be a GCC 6 thing, but it could also have to do with the version of binutils. It's probably not Debian-specific; if we don't fix it we'll probably see it on other distributions eventually. It seems to be related to assembler code rather than the C++ stuff in the initial description of i#1958. The referenced fix mentions i#2050, which mentions "gcc version 5.4.0", for what it's worth.

**Comment by egrimley** [comment]
(There are also other tests that don't build, but you can build DynamoRIO without the tests.)

**Comment by derekbruening** [comment]
I'm assuming that 7bb03fe fixed this selfmod-big failure
