### ISSUE TITLE
ASSERT signal.c:3806 info->interrupted == NULL || info->interrupted == f

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#2328]
Running an app that links DR statically and does an internal attach hits this assert maybe 1 in 10,000 runs, after attach is finished.

```
<Attached to 97 threads in application >
<Application .  Internal Error: DynamoRIO debug check failure: core/unix/signal.c:3806 info->interrupted == NULL || info->interrupted == f
(Error occurred @11002 frags)
internal version, custom build
```

**Comment by derekbruening** [comment]
My theory is that this is coming from the "dropping 3rd pending alarm signal" path which does not clear info->interrupted.  If so, it's easy to fix, and it's innocuous: release build simply replaces info->interrupted.  However, I don't see that "dropping 3rd" message in some saved output from prior instances.

**Comment by derekbruening** [comment]
Looking closer: the "dropping 3rd" drops an older one and keeps 
the new one, so it's not the culprit.

Another way it could happen: if a signal arrives in the IBL we guess at the
target fragment and we could get it wrong.  It seems unlikely though.

In an instance I got in the debugger, the interrupted PC is at the fcache entry.
so it does look like the gencode path.
It could be a signal in fcache_return, and we used asynch_target but had
just exited that fragment?

If that's the case, do we leave it unlinked forever?  Does dispatch notice and relink?
Seems like we should relink where this assert is as a fallback.

**Comment by derekbruening** [comment]
I ruled out fcache_return and we still had some incorrect guesses: but there are other ibl spots where the same behavior could happen.  I added a flag indicating the guess and relaxed the assert when set.

I also put in a relink whenever replacing the interrupted fragment.

**Comment by derekbruening** [comment]
I'm going to relax the assert for these guessing situations, and put in the relinking change, and a clone_record_t stack alignment fix that blocked the other changes by crashing AArch64, but the underying issue with having to guess is that we can have unbounded delay delivering signals.  I'm going to make that under #2042 for clarity.

Also xref #2019

**Comment by derekbruening** [comment]
It turns out all the cases here are clean_call_{save,restore}.  I will add handling and re-instate the assert to help find any other missing cases.

**Comment by ksco** [comment]
@derekbruening Hi, I know this is a very old issue, but I hit a similar one on RISC-V ~1/5 times when I run `linux.signal0001` but can't figure out what it's trying to check.

The assert failing on my side today is https://github.com/DynamoRIO/dynamorio/blob/183f14e8/core/unix/signal.c#L4954 (`info->interrupted` is not null and it's not equal to `f` under gdb).

If I uncomment the assert, then I will get a `<dropping 3rd pending alarm signal>` sometimes, but the result is correct.

Could you explain a bit more about what this assert is checking, or maybe you have some guesses on what is wrong?

**Comment by derekbruening** [comment]
If a thread is inside a fragment and gets interrupted by an asynchronous signal, DR unlinks the fragment and lets it run to the bottom and since it's now unlinked it goes back to dispatch and DR can cleanly deliver the signal at a block boundary.  But it has to remember to re-link, which is what `info->interrupted` is remembering.  If another signal arrives before it has relinked, and that signal arrives in a fragment, it has to be the same fragment: because how could it reach another fragment when the first was unlinked?  That's the assert.

**Comment by ksco** [comment]
Thank you very much for the clear explanation! Now I understand the intent of this assertion and found the real cause. Submitted a fix PR above.
