### ISSUE TITLE
support restartable regions for per-cpu critical regions

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#2350]
This issue covers support for Linux kernel extensions for restartable regions for per-cpu critical regions.  Xref https://lwn.net/Articles/649288/

**Comment by derekbruening** [comment]
This is finally coming to the official kernel: https://github.com/torvalds/linux/commit/d82991a8688ad128b46db1b42d5d84396487a508

**Comment by derekbruening** [comment]
The best approach that we've come up with to support instrumentation of restartable regions is to run them twice: first, run them instrumentated in the code cache, but with their memory stores removed (but still instrumented); then, at the committing store point, invoke the sequence from its start point natively.  This requires some assumptions on identifying the committing store (this actually gets easier with the implementation being pushed to mainline Linux) and is not ideal with mixing in native execution, but it is much faster than the 2nd-best approach of serializing all restartable sequences that operate on the same data structures (which requires app knowledge...else lumping all sequences together) with a global lock, which also has as assumption that the current cpu is not read twice during the sequence.

**Comment by derekbruening** [comment]
Xref the #1698 load-store exclusive problem which is from a high level a similar type of platform issue complicating instrumentation by restricting what can happen within a PC range.

**Comment by Carrotman42** [comment]
I wrote a doc as a summary of the current state of the world: https://github.com/DynamoRIO/dynamorio/wiki/Restartable-Sequences

**Comment by compudj** [comment]
Please refer to the two following upstream Linux selftests commits, which are relevant for DR. They replace the __rseq_table with a more complete alternative:

commit 4fe2088e164d2ec44530fe2840f6be5906fbc650
Author: Mathieu Desnoyers <mathieu.desnoyers@efficios.com>
Date:   Mon Apr 29 11:27:53 2019 -0400

    rseq/selftests: Add __rseq_exit_point_array section for debuggers
    
    Knowing all exit points is useful to assist debuggers stepping over the
    rseq critical sections without requiring them to disassemble the content
    of the critical section to figure out the exit points.

commit a3e3131f94aa1daeb978ed66d0b4e61156ef2c2a
Author: Mathieu Desnoyers <mathieu.desnoyers@efficios.com>
Date:   Mon Apr 29 11:27:54 2019 -0400

    rseq/selftests: Introduce __rseq_cs_ptr_array, rename __rseq_table to __rseq_cs
    
    The entries within __rseq_table are aligned on 32 bytes due to
    linux/rseq.h struct rseq_cs uapi requirements, but the start of the
    __rseq_table section is not guaranteed to be 32-byte aligned. It can
    cause padding to be added at the start of the section, which makes it
    hard to use as an array of items by debuggers.
    
    Considering that __rseq_table does not really consist of a table due to
    the presence of padding, rename this section to __rseq_cs.
    
    Create a new __rseq_cs_ptr_array section which contains 64-bit packed
    pointers to entries within the __rseq_cs section.

**Comment by derekbruening** [comment]
https://github.com/DynamoRIO/dynamorio/wiki/Restartable-Sequences contains a writeup of the implementation details in the series of commits above for the run-twice solution.

There are a number of corner cases left to cover, but they are lower priority.  These are things like:
+ Invoking the 2nd execution on a sequence midpoint exit (maybe leveraging __rseq_exit_point_array)
+ Handling indirect branch exits out of a sequence
+ Remove the -rseq_assume_call option once we're satisfied we'll never go back to it
+ Add more sanity checks for existing requirements/assumptions

**Comment by derekbruening** [comment]
We are currently ignoring the flags which indicate which triggers (out of preempt, signal, and migrate) should cause the abort handler to be called.  We blindly run a second time even the preempt and migrate bits are not set, which the application may not expect without a signal arriving or may expect to only happen in a fatal error condition.

**Comment by derekbruening** [comment]
I'm marking this as completed since it is working well in practice. 
 I split the corner cases listed in https://github.com/DynamoRIO/dynamorio/issues/2350#issuecomment-532401625 off to #4315.  I filed #4316 on adding aarch64 support.
