### ISSUE TITLE
add lint rules for automated code style checks

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#2369]
Today we have some simple hand-written checks in runsuite such as for tabs,
but we could use a linter for automated checks of more code style
conventions.

**Comment by derekbruening** [comment]
Unfortunately there's no great solution here.  Some thoughts:

- Using clang-format kind of requires reformatting the entire code base which I'm not sure we want to commit to at this point, and it still doesn't check things like variable names.  It's kind of an all-or-nothing solution.
- Tools like vera++ and kwstyle have limited sets of checks and their parsing is not as powerful as something like clang-format.  At first glance it seems like our own simple regex matching rules may work just as well which leads to...
- We could just add some more regex checks to runsuite.cmake.  I spent a few minutes adding some and it's not too hard to check some of the rules, though distinguishing cmake from C and ignoring comments is a pain just within cmake's limited regex.  If we go this route I would also want to make the error reports more like a build or test failure where we can ignore for exceptions.

**Comment by derekbruening** [comment]
> If we go this route I would also want to make the error reports more like a build or test failure where we can ignore for exceptions.

This would also allow a dev to run the style checks outside of runsuite.  We would also want to shift the existing checks (tabs, NOCHECKIN, etc.) to also follow this format.

**Comment by derekbruening** [comment]
This does add a minute or so to the Travis build times but we can live with that.  On Travis it only runs on 64-bit builds as the vera package bails out on 32-bit.

**Comment by derekbruening** [comment]
Now that the vera++ infrastructure is in place we may want to try to add further rules, though they are not all easy w/ just a lexer and not a C++ parser.  Candidates:

- [ ] no CamelCase: rule written but too many false positives
- [X] break after function def return type
- [ ] align under open paren
- [ ] indent nested ifdefs
- [ ] static for non-exported functions
- [ ] 4-space indent
- [ ] "XXX i#"
- [X] {} multi-line body
- [X] line length
- [X] space after control keyword, not after func call
- [ ] typdef _t

**Comment by fhahn** [comment]
I'm working on a patch for indent of nested ifdefs. I've discovered plenty of violations all over the place. I'll fix them and put up a patch tomorrow hopefully.

**Comment by derekbruening** [comment]
The rule to indent one space was not there in the beginning and there is probably a lot of code that indents two spaces.
