### ISSUE TITLE
Reduce drmemtrace/drcachesim overhead

### ISSUE THREAD

**Issue by zhaoqin** [DynamoRIO/dynamorio#2398]
`drcachesim` is the online cache/TLB simulation tool and `drmemtrace` is the client collects execution memory trace for `drcachesim`. This issue covers ideas and efforts for reducing the `drcachesim` and `drmemtrace` overhead.

**Comment by derekbruening** [comment]
Is this a duplicate of #2001?

**Comment by zhaoqin** [comment]
Yes, close this one.
