### ISSUE TITLE
add reuse time tool to drmemtrace

### ISSUE THREAD

**Issue by s-kanev** [DynamoRIO/dynamorio#2399]
Xref #2300 

This issue covers creating a "reuse time" tool, which just calculates # references between consecutive accesses to the same address, not # unique addresses in between. Could either be a separate (and cheaper) tool, or just an option to reuse_distance_t.

Most importantly, there should be a programatic way to access the output, so we can use it in downstream tools outside of the DR framework. I can take a stab at the implementation, but I'm not sure what's the best interface change to analysis_tool_t to allow for this. Any ideas?

**Comment by derekbruening** [comment]
> Which just calculates # references between consecutive accesses to the same address, not # unique addresses in between.

The existing reuse distance tool computes the classic stack distance, which _is_ the number of unique references in between.  What makes you say that it's not the # of unique addresses?

**Comment by s-kanev** [comment]
> What makes you say that it's not the # of unique addresses?

It absolutely is. But I also want to calculate reuse time (just # references in between, unique or not). The internal tools I've been developing operate on reuse time + approximations, and I want to use drmemtrace data to interoprate with (and validate) them.

**Comment by derekbruening** [comment]
I see, it's how your initial entry here is worded, it says "Xref #2300 which just calculates # references...".  You can see how that is interpreted as describing the existing tool.

**Comment by s-kanev** [comment]
Oh yeah, sorry about that. Was just trying to fit in by starting a DR issue with Xref :)
