### ISSUE TITLE
opnd_compute_address() is not fully implemented on ARM or AArch64

### ISSUE THREAD

**Issue by egrimley** [DynamoRIO/dynamorio#2433]
On ARM `opnd_compute_address_priv()` does not take account of `DR_OPND_NEGATED`, and on AArch64 the extension and shift are ignored. The API function `opnd_compute_address()` is not tested.

**Comment by derekbruening** [comment]
Dr. Memory uses opnd_compute_address() extensively.  However there is no test inside DR's own test suite.

**Comment by AssadHashmi** [comment]
#4529
