### ISSUE TITLE
ASSERT in memval_simple client

### ISSUE THREAD

**Issue by mcgrady1** [DynamoRIO/dynamorio#2449]
Hi all,
I  tried to use memval_simple.c, and got the error:
Data file /home/ubuntu/Dynamorio/dynamorio/bin32/../api/bin/memval_simple.xxxx.03169.0000.log created
ASSERT FAILURE: /home/ubuntu/Dynamorio/dynamorio/api/samples/memval_simple.c:147: write_base <= write_ptr ()

I compiled the source code on ubuntu 14.04, 32bit

write_base buffer is used to store the value of memory address?

Anyone can help me solve the problem?

**Comment by zhaoqin** [comment]
On Sun, May 28, 2017 at 7:13 AM, mcgrady1 <notifications@github.com> wrote:

> Hi all,
> I tried to use memval_simple.c, and got the error:
> Data file /home/ubuntu/Dynamorio/dynamorio/bin32/../api/bin/
> memval_simple.xxxx.03169.0000.log created
> ASSERT FAILURE: /home/ubuntu/Dynamorio/dynamorio/api/samples/memval_simple.c:147:
> write_base <= write_ptr ()
>

https://github.com/DynamoRIO/dynamorio/blob/ec8c19e58558c882d1c121e317ded836c8e5173f/api/samples/memval_simple.c#L134
It looks like the write_base is used to pointing to the current base for
writing memref info.
And it goes too far, beyond the write_ptr.
It is likely there are too many memrefs to be written out.
Can you check the content of the fprintf in the last few iterations, which
would help us to better understand the cause?

Qin

**Comment by mcgrady1** [comment]
0xff8d7e0c: mov  4 f772f938
0xff8d7df0: mov  4 ff8d7e58
0xff8d7e08: mov  4 00000001
0xff8d7e04: mov  4 00000000
0xff8d7e00: mov  4 00000001
0xff8d7dfc: mov  4 ef3b6628
0xff8d7dec: mov  4 0804862c
0xff8d7de8: mov  4 ff8d7e50
0xff8d7de4: call  4 f771777a
0xff8d7de0: push

last ten lines of the log file.

**Comment by toshipiazza** [comment]
If I remember correctly, `memval` was ported to using a non-buffering `fprintf`, which is why it looks like you're missing a bit of the log file (i.e. the stuff after `push`). 

The only thing that comes to mind for this assert to occur, is if we see many large writes in succession, overflowing the circular buffer. Do you by chance have the application you originally ran `memval` under (or another app with the same issue) that you'd be willing to share?

**Comment by mcgrady1** [comment]
I think the problem is size of some memory operands is more than 4 bytes in x86 platform

**Comment by toshipiazza** [comment]
In a perfect world, large-sized memory operands should be correctly accounted for with the call to `drx_buf_insert_buf_memcpy` in the sample. This will, for 1, 2 and 4-byte writes generate a simple register move, but for larger operands generate a `memcpy` operation that works for arbitrary-size writes. Do you have in mind an instruction you think may be triggering the crash?

**Comment by mcgrady1** [comment]
for example, MOVDQU, memcpy may use this instruction to copy data.

**Comment by derekbruening** [comment]
The DR test suite runs memval_simple on our common.eflags app which has movdqu inside it, and it works fine with no assert.

Please provide a minimized application that triggers this assert so we can reproduce it.

**Comment by mcgrady1** [comment]
How can i send my test program to you, only binary, or need source code?

**Comment by derekbruening** [comment]
Minimizing is the most important: the smallest possible program that demonstrates the problem.  Source code (along with which compiler and build settings) is better than binary; pure assembly source with precise machine instructions would be best, though that is not always easy to arrive at if it depends on some larger context.  You have some reason to think it involves movdqu so I assume you've narrowed it down to some particular code region.

**Comment by mcgrady1** [comment]
I’m not sure that results from movdqu, just guess.
Log file doesn't contain movdqu, only has **fstp**
0xfff95da0: mov  4 00000003
0xfff95da8: mov  4 fff95e34
0xfff95da4: mov  4 fff95e24
0xfff95d9c: call  4 f7796d57
0xfff95d98: call  4 f7498ab5
0xf753931c: fstp  8 4000000000000000
close to the last line of log file.
I used pintool to analyse my demo program, and guess the large scale memory copy may result the program.
So how to debug it, or send the demo program to you, 
run it on ubuntu 14.04 x86-32bit, u will see the assert.

**Comment by toshipiazza** [comment]
I'm on Ubuntu 14.04, and a simple `fstp` application worked for me, compiled for elf32, though we'll have a more definitive answer once you've sent the demo program.

As for sending the demo program, if you zip it up you should be able to just drag it into the GitHub text box in your browser, and it'll automatically create a link for you.

If interested, the simple fstp application I tested, which worked, was:

```asm
bits 32
section .bss
dump: resb 8

section .text
  global _start
_start:
  fstp qword [dump]
  mov eax, 1
  int 0x80
```

**Comment by mcgrady1** [comment]
[demo.zip](https://github.com/DynamoRIO/dynamorio/files/1049440/demo.zip)
Run the demo with bin32/drrun.
Thanks.

**Comment by mcgrady1** [comment]
I have run the demo on two virtual machine, both of them "assert failure",
chmod +x "demo program", then you can run it

**Comment by mcgrady1** [comment]
when i check the log file, i found these record, which close to the assert point:
pc , type, x,x, memory_address,size
**b73bd9f8**,add,0,0,0xbffc97d4, 4
b73bd9f8,add,0,0,0xbffc97d4, 4
b73bda0e,add,0,0,0xbffc97e0, 4
b73bd97e,mov,0,0,0xbffc97d4, 4
b73bd9f8,add,0,0,0xbffc97d4, 4
b73bd9f8,add,0,0,0xbffc97d4, 4
b73bd9f8,add,0,0,0xbffc97d4, 4
b73bda0e,add,0,0,0xbffc97e0, 4

b73bd9f8 is in libc-2.19.so

libc:
1259f4:	8d 74 26 00          	lea    0x0(%esi,%eiz,1),%esi
**1259f8:**	83 44 24 04 04       	**addl**   $0x4,0x4(%esp)
1259fd:	83 c0 10             	add    $0x10,%eax

maybe it results the problem

**Comment by mcgrady1** [comment]
Anyone can solve the problem, thanks

**Comment by toshipiazza** [comment]
Am looking at this currently, but unfortunately the binary is large and it seems to have also been instrumented with AFL (correct me if I'm wrong). There's a little more information to be had by running under debug mode:

```
$ drrun -debug -32 -c /XXX/libmemval_simple.so -- ./memval_demo input.zip mem.tif
...
<(1+x) Handling our fault in a TRY at 0x567e3f81>
<Application /XXX/memval_demo (42286) DynamoRIO usage error : meta-instr faulted?  must set translation field and handle fault!>
<Usage error: meta-instr faulted?  must set translation field and handle fault! (/XXX/dynamorio/core/translate.c, line 723)
...
```

Same assert, even when running without program arguments. I'm assuming that this means that the crash happens somewhere before main, maybe in `__libc_csu_init` judging by the log file I was able to recover. Will continue looking.

**Comment by toshipiazza** [comment]
Attached is a *much* smaller test case with seemingly the same problem. It's a simple C++ hello world application, compiled and run like so:

```
$ afl-clang++ foo.cpp -m32
$ drrun -debug -32 -c ~/Build/drb/samples/bin32/libmemval_simple.so -- ./a.out
(same crash as above)
```

Oddly no crash occurs when compiling `foo.cpp` for 64-bit AFL. Neat.

[crash.zip](https://github.com/DynamoRIO/dynamorio/files/1050815/crash.zip)

**Comment by mcgrady1** [comment]
Hi toshipiazza,
I compiled it with afl， you are right。
"drrun -c /XXX/libmemval_simple.so -- ./memval_demo input.zip **mem.tiff**"
It will run into the main function.
Do you need the full trace？

**Comment by mcgrady1** [comment]
I don't know why i cannot upload zip file, can i send it to you email?

**Comment by mcgrady1** [comment]
Hi , toshipiazza,
You said " for larger operands generate a memcpy operation that works for arbitrary-size writes",
but i didn't find the code to do memory copy,
https://github.com/DynamoRIO/dynamorio/blame/0a775c0945c54bf0f402c27784c57d59cd73a64d/ext/drx/drx_buf.c#L655
Thanks.

**Comment by toshipiazza** [comment]
@mcgrady1, the memcpy occurs in drx_buf_insert_buf_memcpy(). If the operand
is "small enough" to fit in a general-purpose register, we load the memory
into a register and store that reg. If it's too large, we end up inserting
a clean call directly into our own safe and drx_buf-compatible version of
memcpy, see
https://github.com/DynamoRIO/dynamorio/blame/0a775c0945c54bf0f402c27784c57d59cd73a64d/ext/drx/drx_buf.c#L722
.

Sorry for the delay these past two days. I will have more time to look into
the problem fully tomorrow.

**Comment by mcgrady1** [comment]
Hi toshipiazza,
https://github.com/DynamoRIO/dynamorio/blob/ec8c19e58558c882d1c121e317ded836c8e5173f/api/samples/memval_simple.c#L221
I think the pc address should be written into write_buffer

**Comment by toshipiazza** [comment]
This only occurs for call instructions. Recall that on x86, `call` instructions push `eip` of the next instruction onto the stack. We handle them specially--normally we push the written memory onto the `drx_buf` data structure *after* it has been written (i.e. after the current instruction - see `instrument_post_write`) but this does not work for `call` instructions because it redirects control flow and we'll see things in the `write_buffer` out of order. We prevent this by simulating the call instruction before it occurs, pushing `eip` of the next instruction onto `write_buffer`.

**Comment by toshipiazza** [comment]
Think I found the bug.

When testing on a binary compiled with `afl-g++`, I noticed a crash at  `/usr/lib/i386-linux-gnu/libstdc++.so.6.0.23+0x86c50`, more specifically `std::locale::_Impl::_Impl(unsigned int)+3776`. The (abbreviated) instrumentation of this basic block is shown below:

```
TAG  0xf7c71c41
...
 +58   L3              89 4d b8             mov    %ecx -> 0xffffffb8(%ebp)[4byte]
 +61   m4 @0x49d8f9b4  64 a1 68 00 00 00    mov    %fs:0x00000068[4byte] -> %eax
 +67   m4 @0x49d914b8  8b 36                mov    (%esi)[4byte] -> %esi
 +69   m4 @0x49d8d31c  89 30                mov    %esi -> (%eax)[4byte]
 +71   m4 @0x49d8ff58  8d 40 04             lea    0x04(%eax) -> %eax
 +74   m4 @0x49d8e87c  64 a3 68 00 00 00    mov    %eax -> %fs:0x00000068[4byte]
 +80   m4 @0x49d8dce8  8d 04 83             lea    (%ebx,%eax,4) -> %eax
 +83   m4 @0x49d8da3c  64 8b 35 64 00 00 00 mov    %fs:0x00000064[4byte] -> %esi
 +90   m4 @0x49d8d5c8  c7 46 04 4d 1c c7 f7 mov    $0xf7c71c4d -> 0x04(%esi)[4byte]
 +97   m4 @0x49d917b0  66 c7 46 02 38 00    mov    $0x0038 -> 0x02(%esi)[2byte]
 +103  m4 @0x49d9250c  66 c7 06 04 00       mov    $0x0004 -> (%esi)[2byte]
 +108  m4 @0x49d1278c  8d 76 08             lea    0x08(%esi) -> %esi
 +111  m4 @0x49d8e5d0  64 89 35 64 00 00 00 mov    %esi -> %fs:0x00000064[4byte]
 +118  m4 @0x49d92c60  64 a3 5c 00 00 00    mov    %eax -> %fs:0x0000005c[4byte]
 +124  m4 @0x49d064f8  64 a1 58 00 00 00    mov    %fs:0x00000058[4byte] -> %eax
 +130  L3              89 14 83             mov    %edx -> (%ebx,%eax,4)[4byte]
 +133  m4 @0x49d9029c  64 a1 5c 00 00 00    mov    %fs:0x0000005c[4byte] -> %eax
 +139  m4 @0x49d8f754  64 8b 35 68 00 00 00 mov    %fs:0x00000068[4byte] -> %esi
 +146  m4 @0x49d0d8ec  8b 00                mov    (%eax)[4byte] -> %eax
 +148  m4 @0x49d0d8a0  89 06                mov    %eax -> (%esi)[4byte]
 +150  m4 @0x49d0dc7c  8d 76 04             lea    0x04(%esi) -> %esi
 +153  m4 @0x49d8d0bc  64 89 35 68 00 00 00 mov    %esi -> %fs:0x00000068[4byte]
 +160  m4 @0x49d8d3b4  64 8b 35 54 00 00 00 mov    %fs:0x00000054[4byte] -> %esi
...
END 0xf7c71c41
```

The crash is happening in the instrumentation belonging to the next app instruction (+130). Our meta-instrumentation access the address of the next app instruction like so:

```
+80   m4 @0x49d8dce8  8d 04 83             lea    (%ebx,%eax,4) -> %eax
```

Note that this routine (specifically, `drutil_insert_get_mem_addr`) relies on the app value of each register in the source operand (i.e. `%ebx` and `%eax`) to be preserved. However, it turns out `drreg` gave us `%eax` to mangle as well (i.e. it corresponds to `reg_tmp` in source).

Normally, this is not a problem (see `memtrace_simple`), since `drreg` only saves `%eax` but does not destroy the app value contained inside. However, `memval_simple` is different as it inserts instrumentation before *and* after the current instruction, so `drreg` can potentially elide the save and restore of `%eax`, so that we no longer have the app value of `%eax` stored there.

That seems to be the case in this particular basic block. The following patch exhibits no crash when run under `afl-g++` of the given `memval_test` application:

```diff
diff --git a/api/samples/memval_simple.c b/api/samples/memval_simple.c
index 281e755..d0ad469 100644
--- a/api/samples/memval_simple.c
+++ b/api/samples/memval_simple.c
@@ -170,6 +170,17 @@ instrument_mem(void *drcontext, instrlist_t *ilist, instr_t *where, opnd_t ref)
         return DR_REG_NULL;
     }
 
+    /* i#2449: In the situation that instrument_post_write, instrument_mem and ref all
+     * have the same register reserved, drutil_insert_get_mem_addr will compute the
+     * address of an operand using an incorrect register value, as drreg will elide the
+     * save/restore.
+     */
+    if (drreg_get_app_value(drcontext, ilist, where, reg_tmp, reg_tmp)
+        != DRREG_SUCCESS) {
+        DR_ASSERT(false);
+        return DR_REG_NULL;
+    }
+
     /* We use reg_ptr as scratch to get addr. Note we do this first as reg_ptr or reg_tmp
      * may be used in ref.
      */
@@ -403,7 +414,7 @@ event_exit(void)
 DR_EXPORT void
 dr_client_main(client_id_t id, int argc, const char *argv[])
 {
-    drreg_options_t ops = {sizeof(ops), 3 /*max slots needed*/, false};
+    drreg_options_t ops = {sizeof(ops), 3 /*max slots needed*/, true};
 
     dr_set_client_name("DynamoRIO Sample Client 'memval_simple'",
                        "http://dynamorio.org/issues");
```

Unfortunately, this patch is a bit pessimistic, as it will always restore the register, at least once and at most twice, even when unnecessary. I'll send a PR.

**Comment by mcgrady1** [comment]
Hi toshipiazza,
The problem has been solved by you.
Thanks very much.

**Comment by derekbruening** [comment]
We shouldn't need to lose performance set drreg_options_t.conservative.  Discussion is in the already-linked PR.
