### ISSUE TITLE
code_api|tool.drcachesim.filter and code_api|tool.drcacheoff.filter broken on AArch64

### ISSUE THREAD

**Issue by fhahn** [DynamoRIO/dynamorio#2469]
One of the latest changes to drcachesim seems to have broken AArch64. Unfortunately the AArch64 nightly builds are currently down due to a power failure, but they should be back soon.

    09:56:04.879 132/149 Test #134: code_api|tool.drcachesim.filter .................***Failed  Required regular expression not found.Regex=[^Hello, world!
    09:56:04.879 ---- <application exited with code 0> ----
    09:56:04.879 Cache simulation results:
    09:56:04.879 Core #0 \(1 thread\(s\)\)
    09:56:04.879   L1I stats:
    09:56:04.879     Hits:                         *[0-9,\.]*
    09:56:04.879     Misses:                       *[0-9,\.]*.
    09:56:04.879 .*   Miss rate:                   *[1-9][0-9][,\.]..%
    09:56:04.879   L1D stats:
    09:56:04.879     Hits:                         *[0-9,\.]*
    09:56:04.879     Misses:                       *[0-9,\.]*.
    09:56:04.879 .*   Miss rate:                   *[1-9][0-9][,\.]..%
    09:56:04.879 Core #1 \(0 thread\(s\)\)
    09:56:04.879 Core #2 \(0 thread\(s\)\)
    09:56:04.879 Core #3 \(0 thread\(s\)\)
    09:56:04.879 LL stats:
    09:56:04.879     Hits:                         *[0-9,\.]*.
    09:56:04.879     Misses:                       *[0-9,\.]*..
    09:56:04.879 .*   Local miss rate:             *[1-9][0-9][,\.]..%
    09:56:04.879     Child hits:                   *[0-9,\.]*.
    09:56:04.879     Total miss rate:              *[1-9][0-9][,\.]..%
    09:56:04.879 $
    09:56:04.879 ]  0.20 sec
    09:56:04.879 <Internal Error: Failed to encode instruction: 'lsrv   %x30 $0x06 -> %x30'
    09:56:04.879 >
    09:56:04.879 <Application /var/lib/go-agent/pipelines/dynamorio-verification/build_debug-internal-64/suite/tests/bin/simple_app (27354).  Internal Error: DynamoRIO debug check failure: Not implemented @/var/lib/go-agent/pipelines/dynamorio-verification/dynamorio/core/arch/aarch64/encode.c:172 (0)

    09:56:04.880 135/149 Test #141: code_api|tool.drcacheoff.filter .................***Failed    0.60 sec
    09:56:04.880 Running |/usr/bin/cmake;-E;remove_directory /var/lib/go-agent/pipelines/dynamorio-verification/build_debug-internal-64/suite/tests/drmemtrace.simple_app.26405.1511.dir|
    09:56:04.880 Running cmd |/var/lib/go-agent/pipelines/dynamorio-verification/build_debug-internal-64/bin64/drrun;-s;90;-quiet;-debug;-killpg;-stderr_mask;0xC;-dumpcore_mask;0;-code_api;-t;drcachesim;-offline;-L0_filter;--;/var/lib/go-agent/pipelines/dynamorio-verification/build_debug-internal-64/suite/tests/bin/simple_app|
    09:56:04.880 Running postcmd |/var/lib/go-agent/pipelines/dynamorio-verification/build_debug-internal-64/clients/bin64/drcachesim;-indir;/var/lib/go-agent/pipelines/dynamorio-verification/build_debug-internal-64/suite/tests/drmemtrace.simple_app.27371.4030.dir|
    09:56:04.880 CMake Error at /var/lib/go-agent/pipelines/dynamorio-verification/dynamorio/suite/tests/runmulti.cmake:99 (message):
    09:56:04.880   *** postcmd failed (1): ERROR: Failed to parse module file
    09:56:04.880   /var/lib/go-agent/pipelines/dynamorio-verification/build_debug-internal-64/suite/tests/drmemtrace.simple_app.27371.4030.dir/raw/modules.log
    09:56:04.880 
    09:56:04.880 
    09:56:04.880   ***
    09:56:04.880 
    09:56:04.880 Call Stack (most recent call first):
    09:56:04.880   /var/lib/go-agent/pipelines/dynamorio-verification/dynamorio/suite/tests/runmulti.cmake:111 (process_cmdline)
    09:56:04.880   
    09:56:04.880 
    09:56:04.880 
    09:56:04.880

**Comment by egrimley** [comment]
The problem is with `XINST_CREATE_slr_s`. Probably this should see whether `s` is a constant or a register and use `OP_ubfm` or `OP_lsrv`, respectively. There is a similar thing with `opnd_is_reg(rm_or_imm)` elsewhere in the same file. (Neither affects the flags, so change the platform-independent description to "may affect the status flags".)

**Comment by derekbruening** [comment]
I'm afraid that this kind of problem may keep happening in the future, until aarch64/instr_create.h is complete (#2440) and there are exhaustive tests for the IR (#2443) -- with no A64 setup to test on and no shift macros available I had to guess, and with no CDash failures in the next day there was no indication that anything was wrong.
