### ISSUE TITLE
problem of memval_sample client

### ISSUE THREAD

**Issue by mcgrady1** [DynamoRIO/dynamorio#2475]
HI all,
When I checked memory value trace generated by memval_sample client, I found a new problem.

trace fragment as follow:
instruction  write/read address opcode size value
**0xf7728bc3 0 0xf773b558 call 4**
0xf771b120 1 0xffb92758 call 4 f771b125
0xf7732764 0 0xffb92758 mov 4
0xf7732767 0 0xffb92758 ret 4

memval_sample doesn't log the first call, i found the instruction in lib,
ebc3:	ff 93 58 05 00 00    	**call   *0x558(%ebx)**
ebc9:	8b 30                	mov    (%eax),%esi

I guess that memval client forgets to trace this kind of call instruction.  

I have tested original version of memval client, it doesn't record this call instruction.

How to solve this problem?

Thanks.

**Comment by toshipiazza** [comment]
Do you have a sample program which demonstrates the problem (preferably a small, static binary)? 

Although this call instruction is `%ebx`-relative, which is common for PIC libraries and PIE binaries, it should still be respected by `memval_simple` (hopefully). Is the `call` instruction simply not appearing in the trace? The trace you uploaded isn't the default trace format from the original `memval` sample. Could you upload a trace of the original `memval` sample on this particular binary/library?

**Comment by derekbruening** [comment]
@mcgrady1 please explain the reason for closing this?

**Comment by mcgrady1** [comment]
I analysed the problem and found it results from my code.
Sorry.
