### ISSUE TITLE
Current status of dr_insert_clean_call on ARM

### ISSUE THREAD

**Issue by techvoltage** [DynamoRIO/dynamorio#2483]
Hi,
I see that dr_insert_m(c)br_instrumentation is disabled for ARM(Not yet implemented). But can I make use of the functionality provided by dr_insert_clean_call or there's still some work to be done? 
I would specifically like to implement an indirect call and return tracing plugin on ARM. Could anyone point me to an existing sample that does this? Thanks!

**Comment by derekbruening** [comment]
The issue tracker is for filing specific bug reports and feature requests.  Please use the mailing list http://groups.google.com/group/dynamorio-users for questions.
