### ISSUE TITLE
DynamoRIO still randomizes even with ASLR disabled

### ISSUE THREAD

**Issue by algrant-arm** [DynamoRIO/dynamorio#2508]
DynamoRIO internally randomizes its address layout even when ASLR is disabled. This can lead to erratic behavior.

It probably ought to disable randomization if ASLR has been disabled (e.g. with "setarch -R"). Failing that, command-line options to disable randomization, and to override the seed, could help in tracking down intermittent faults.

(There's an API function dr_set_random_seed() but this is only really a solution if you want to disable randomness in a client, when actually what you want is to disable randomness independently of what clients/tools are being used.)

**Comment by derekbruening** [comment]
DR's internal ASLR need not have any relationship to the app's ASLR.  DR is transparent enough that app addresses remain identical to a native run and its internal workings shouldn't be controlled by application-level settings.  There are already DR runtime options to control the precise randomness of the vmm region base (-vm_max_offset).  To disable, pass `-vm_max_offset 0x0`.  If you're agreed that that's sufficent, let's close this issue?

**Comment by algrant-arm** [comment]
I guess so, although an option to supply the seed for the random generator would be of greater utility in diagnosing intermittent fails.

**Comment by derekbruening** [comment]
That already exists: `-prng_seed`.  The options are all in https://github.com/DynamoRIO/dynamorio/blob/master/core/optionsx.h and a simple search for "seed" shows it right away.

**Comment by derekbruening** [comment]
There are many internal options, and only a few are documented to users in the doxygen docs: perhaps these could be added to those docs?

**Comment by algrant-arm** [comment]
Should this be in "drrun -help"?

**Comment by derekbruening** [comment]
The DR runtime option docs are at http://dynamorio.org/docs/using.html#sec_options (api/docs/intro.dox in sources).
drrun -help lists the drrun (front-end launcher) options, the rest are passed through to DR (or the client).

**Comment by derekbruening** [comment]
If someone would like to auto-generate the DR docs as a text list to add to drrun -help that might be nice (or might be too much output, maybe just a link)
