### ISSUE TITLE
Segmentation fault in some clients with __clear_cache

### ISSUE THREAD

**Issue by algrant-arm** [DynamoRIO/dynamorio#2509]
On AArch64 some dynamic code operations cause a crash in (or with) clients:
```
#include <stdlib.h>
int main(void) {
    void *page;
    posix_memalign(&page, 4096, 4096);
    __builtin___clear_cache(page, (char*)page + 4096);
    return 0;
}
```
this gets a segmentation fault with simple clients like libbbcount and libopcodes. The debug build says
```
<Application tried to execute from unreadable memory 0x0000000000000000.
```
We know DR on AArch64 traps IC IVAU in order to handle dynamic code, so maybe there's some interaction between that and the instrumentation that these clients are putting in.

**Comment by derekbruening** [comment]
To clarify, without any client there is no problem?

**Comment by derekbruening** [comment]
What about with libempty.so?

**Comment by algrant-arm** [comment]
It works with no client, with libempty.so and with libinscount.so.

I'd thought libinscount.so would be sufficiently similar to libopcodes.so so as to trigger the same issue, but it's got this comment:
```
/* Only insert calls for in-app BBs */
if (user_data == NULL)
    return DR_EMIT_DEFAULT;
```
Does a BB dynamically generated count as an in-app BB?

**Comment by derekbruening** [comment]
See the comment at the top of inscount.cpp:

```
 * The runtime options for this client include:
 *   -only_from_app  Do not count instructions in shared libraries.
```

**Comment by algrant-arm** [comment]
Yes but a dynamically generated (JIT) BB wouldn't be "in" a shared library either - whether it was generated by the app or by one of its shared libraries. If the approach to excluding shared libraries also excludes JITted code that could be missing some code that is logically part of the application.

In any case the problem here is a crash on cache clearing.

**Comment by egrimley** [comment]
My simple-minded way of debugging this sort of thing is to insert an unallocated encoding into the app. On AArch64, DynamoRIO treats `.inst 0` the same as it would `add x0, x0, #1`: it copies it across into the fragment cache. So when you run it under a debugger and it stops on the SIGILL you can see exactly how the code has been mangled.

So here's my minimised test program:
```
        .global _start
_start:
        mov     x0, sp
        ic      ivau, x0
        bl      1f
        mov     w0, #0
        mov     w8, #94
        svc     0
        nop
1:
        .inst   0
        isb
        ret
```

And here's what I see under GDB:
```
   0x51d3107c:  ldr     x0, [x28,#8]
   0x51d31080:  str     x1, [x28,#272]
   0x51d31084:  str     x2, [x28,#280]
   0x51d31088:  mov     x1, #0x1490
   0x51d3108c:  movk    x1, #0x7201, lsl #16
   0x51d31090:  ldr     x2, [x1]
   0x51d31094:  add     x2, x2, #0x1
   0x51d31098:  str     x2, [x1]
=> 0x51d3109c:  .inst   0x00000000 ; undefined
   0x51d310a0:  isb
   0x51d310a4:  str     x0, [x28]
   0x51d310a8:  mov     x0, #0x2b20
   0x51d310ac:  movk    x0, #0x559c, lsl #16
   0x51d310b0:  movk    x0, #0x55, lsl #32
   0x51d310b4:  ldr     w0, [x0]
   0x51d310b8:  cbz     w0, 0x51d310d8

   0x51d310bc:  stp     x1, x2, [x28,#8]
   0x51d310c0:  mov     x2, #0x3bb4
   0x51d310c4:  movk    x2, #0x5587, lsl #16
   0x51d310c8:  movk    x2, #0x55, lsl #32
   0x51d310cc:  mov     x1, #0x0               // PROBLEM
   0x51d310d0:  mov     x0, x28
   0x51d310d4:  br      x2

   0x51d310d8:  ldr     x0, [x28]

   0x51d310dc:  ldr     x1, [x28,#272]
   0x51d310e0:  ldr     x2, [x28,#280]
   0x51d310e4:  str     x2, [x28,#16]
   0x51d310e8:  mov     x2, x30
   0x51d310ec:  b       0x51d310f0
   0x51d310f0:  stp     x0, x1, [x28]
   0x51d310f4:  mov     x0, #0x55b8
   0x51d310f8:  movk    x0, #0x51d0, lsl #16
   0x51d310fc:  movk    x0, #0x0, lsl #32
   0x51d31100:  movk    x0, #0x0, lsl #48
   0x51d31104:  ldr     x1, [x28,#120]
   0x51d31108:  br      x1
```

I've indicated where I think the problem is. This instruction is generated by `mangle.c:3055`:
```
        insert_mov_immed_arch(dcontext, NULL, NULL, (ptr_int_t)pc,
                              opnd_create_reg(DR_REG_X1), ilist, instr, NULL, NULL);
```

The `pc` comes from `get_app_instr_xl8(next_instr)` at `mangle_shared.c:903`.

So the client causes the code to be mangled in such a way that the original PC can no longer be provided to the code that mangles ISB. But what's the fix?

**Comment by egrimley** [comment]
Replacing `get_app_instr_xl8(next_instr)` with `get_app_instr_xl8(instr) + 4` seems to fix it for me. Al, do you have any other test cases to hand?

**Comment by algrant-arm** [comment]
That fixes my failing JIT cases, thanks.
