### ISSUE TITLE
Remove #ifndef AARCH64 from drx_buf-test.dll.c

### ISSUE THREAD

**Issue by fhahn** [DynamoRIO/dynamorio#2520]
Split from #1569

All missing XINST macros are available now, so the test builds with the ifndefs removed, but fails during execution:

    ~/projects/dynamorio-work/build-debug/bin64/drrun "-s" "90" "-quiet" "-debug" "-killpg" "-stderr_mask" "0xC" "-dumpcore_mask" "0" "-code_api" "-c" "~/projects/dynamorio-work/build-debug/suite/tests/bin/libclient.drx_buf-test.dll.so" "--" "~projects/dynamorio-work/build-debug/suite/tests/bin/client.drx_buf-test"
    Starting drx_buf threaded test
    <ERROR: using undefined symbol!>

**Comment by toshipiazza** [comment]
Did you remove the ifndef's around `drx_buf_insert_buf_memcpy()` as well, in `drx_buf.c`?

**Comment by egrimley** [comment]
When I removed from "drx_buf.c" and "drx_buf-test.dll.c" each `#ifndef AARCH64` (and the corresponding `#else`...`#endif`) and also replaced `IF_AARCH64_ELSE(0, 2)` with `2`, all tests passed for me.

(I think there are also some nested preprocessor macros whose indentation ought to be adapted.)

**Comment by fhahn** [comment]
Yep I just tried that too! I'll put up a patch.
