### ISSUE TITLE
Re-check tests on new AMD ryzen under wow64

### ISSUE THREAD

**Issue by baremetaldude** [DynamoRIO/dynamorio#2524]
Please check your tests on newest AMD processors
Windows 10 x64, running any 32-bit exe using 32-bit drrun (64-bit drrun is OK)

drrun version 7.0.0 -- build 1

```
c:\Program Files\DynamoRIO-Windows-7.0.0-RC1\bin32>drrun -t drcov -- drrun
<Application c:\Program Files\DynamoRIO-Windows-7.0.0-RC1\bin32\drrun.exe (6852).  DrCov internal crash at PC 0x69fcfb6b.  Please report this at http://dynamorio.org/issues.  Program aborted.
0xc0000005 0x00000000 0x69fcfb6b 0x69fcfb6b 0x00000003 0x00000000
Base: 0x69f00000
Registers: eax=0x00000000 ebx=0x004ff388 ecx=0x80217d84 edx=0x00000000
        esi=0x1ac6a280 edi=0x1ac698a0 esp=0x004ff3a8 ebp=0x004ff458
        eflags=0x00010202
version 7.0.0, build 1
-no_dynamic_options -client_lib 'c:\Program Files\DynamoRIO-Windows-7.0.0-RC1\tools\lib32\release\drcov.dll;0;' -code_api -probe_api -stack_size 56K -nop_initial_bblock -max_elide_jmp 0 -max_elide_call 0 -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct -no_aslr_dr -
0x004ff458 0x69faa31e
0x1ac6a274 0x00000000>
```

**Comment by derekbruening** [comment]
We do not have access to such a processor.  What does debug build say?

**Comment by derekbruening** [comment]
What happens without drcov?

**Comment by ncatlin** [comment]
I'm assuming this is the same issue

C:\Users\nia>C:\devel\libs\dynamorio\DynamoRIO-Windows-7.0.0-RC1\bin32\drrun.exe -debug -c C:\devel\libs\dynamorio\DynamoRIO-Windows-7.0.0-RC1\samples\bin32\inscount.dll -- C:\tracing\testdllloader.exe
<WARNING: Running on unsupported Windows 10+ version>
<Starting application C:\tracing\testdllloader.exe (5572)>
<Application C:\tracing\testdllloader.exe (5572).  Internal Error: DynamoRIO debug check failure: D:\dynamorio_package\core\win32\callback.c:3716 instr_get_opcode(&instr) == OP_lea && (opnd_get_disp(instr_get_src(&instr, 0)) == 0x10 || opnd_get_disp(instr_get_src(&instr, 0)) == 0x2dc)
(Error occurred @0 frags)
version 7.0.0, build 1
-no_dynamic_options -client_lib 'C:\devel\libs\dynamorio\DynamoRIO-Windows-7.0.0-RC1\samples\bin32\inscount.dll;0;' -code_api -probe_api -stack_size 56K -max_elide_jmp 0 -max_elide_call 0 -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct -no_aslr_dr -pad_jmps_mark_no
0x012fed3c 0x14497e84
0x012fee74 0x1466f2d4
0x012feefc 0x14676947
0x012fef3c 0x143dc33d
0x012ff800 0x14628d51
0x012ff860 0x14629718>

**Comment by derekbruening** [comment]
Probably this is the same as #4091?  Though this is older, the other has much more information, so dup-ing in that direction.
