### ISSUE TITLE
drcacheoff.filter fails on AArch32

### ISSUE THREAD

**Issue by fhahn** [DynamoRIO/dynamorio#2532]
It fails during the nightly builds on a machine with a native AArch32 OS.

```
Running |/usr/bin/cmake;-E;remove_directory /home/pi/dynamorio-space/nightly/run/build_release-external-32/suite/tests/drmemtrace.simple_app.25802.1407.dir|
Running cmd |/home/pi/dynamorio-space/nightly/run/build_release-external-32/bin32/drrun;-s;90;-quiet;-killpg;-stderr_mask;0xC;-dumpcore_mask;0;-code_api;-t;drcachesim;-offline;-L0_filter;--;/home/pi/dynamorio-space/nightly/run/build_release-external-32/suite/tests/bin/simple_app|
CMake Error at /home/pi/dynamorio-space/nightly/src/suite/tests/runmulti.cmake:99 (message):
  *** cmd failed (11): ***

Call Stack (most recent call first):
  /home/pi/dynamorio-space/nightly/src/suite/tests/runmulti.cmake:108 (process_cmdline)
```

This looks like a genuine failure rather than flakiness.

**Comment by fhahn** [comment]
CDash link http://dynamorio.org/CDash/testDetails.php?test=318027&build=26311

**Comment by egrimley** [comment]
I think that same test was failing on AArch64 on some of our test machines though it never failed on a machine I log on to. It might have something to do with the named pipe rather than anything more interesting.

**Comment by egrimley** [comment]
I'll mark this as "Status-Duplicate" and close it as it seems to have the same cause as #2533.
