### ISSUE TITLE
code_api|tool.drcachesim.filter fails on AArch32

### ISSUE THREAD

**Issue by fhahn** [DynamoRIO/dynamorio#2533]
It fails during the nightly builds on a machine with a native AArch32 Linux. The generated output does not match the expected pattern. It looks like the following additional lines are generated:

```
    Prefetch hits:                       0
    Prefetch misses:                    21
```

http://dynamorio.org/CDash/testDetails.php?test=318024&build=26311

**Comment by egrimley** [comment]
No, I think the problem is "application exited with code 11" and no "Hello, world!".

**Comment by fhahn** [comment]
Agreed!

**Comment by egrimley** [comment]
I think this failure (and #2532) is caused by DynamoRIO not realising that ADC reads C. I'll make a patch later.

I wonder how many similar bugs lurk. Is finding these included under #1686?

**Comment by fhahn** [comment]
Confirmed fixed by latest nightly build http://dynamorio.org/CDash/viewTest.php?onlyfailed&buildid=26473

**Comment by fhahn** [comment]
Thanks Edmund!
