### ISSUE TITLE
runsuite.cmake does not print result summary for AArch32

### ISSUE THREAD

**Issue by fhahn** [DynamoRIO/dynamorio#2544]
It looks like running runsuite.cmake does not print the result summary at the end, e.g. see http://64.28.99.135:8080/job/DynamoRIO-AArch32-Precommit/7/console .

runsuite_wrapper.pl cannot ignore known failures because of that.

Any ideas @derekbruening ?

**Comment by derekbruening** [comment]
The code is in runsuite_common_post.cmake, is something different in your setup resulting in the xml files either having different paths or different contents?

**Comment by fhahn** [comment]
The problem was that scp was not installed.
