### ISSUE TITLE
Compile problem

### ISSUE THREAD

**Issue by Clcanny** [DynamoRIO/dynamorio#2548]
I use window 10 + vs 2013 + cmake 2.8.10
but when I enter in drmemory/build and type "cmake-gui ..", I configure Visual Studio 9
And I get error:  Error in configuration process, project files may be invalid.
Can anyone one help me solve this?

**Comment by fhahn** [comment]
Does this happen for dynamoRIO too? Your report only mentions drmemory

**Comment by Clcanny** [comment]
en, sorry for that.
I think that drmemory is under dynamoRIO, so come here to ask for here.

**Comment by derekbruening** [comment]
I assume you filed https://github.com/DynamoRIO/drmemory/issues/2011??

**Comment by Clcanny** [comment]
yep, thank you.
