### ISSUE TITLE
How can I get the time of syscall spent?

### ISSUE THREAD

**Issue by Clcanny** [DynamoRIO/dynamorio#2553]
This is the source code.

```c
#include "dr_api.h"
#include "drmgr.h"
#include "drsyscall.h"
#include <time.h>
#include <Windows.h>
#include "dr_tools.h"
#include <inttypes.h>

static bool event_filter_syscall(void *, int);
static bool event_pre_syscall(void *, int);
static void event_post_syscall(void *, int);
static void event_exit(void);
static int get_write_sysnum(void);

static int write_sysnum;
clock_t begin;
uint64 beginTime;


DR_EXPORT void
dr_client_main(client_id_t id, int argc, const char *argv[])
{
  dr_set_client_name("sys_call_time'", "");
  drmgr_init();
  // write_sysnum = get_write_sysnum();
  // dr_fprintf(STDOUT, "write_sysnum is %d\n", write_sysnum);
  // dr_register_filter_syscall_event(event_filter_syscall);
  drmgr_register_pre_syscall_event(event_pre_syscall);
  drmgr_register_post_syscall_event(event_post_syscall);
  dr_register_exit_event(event_exit);
}

static bool
event_filter_syscall(void *drcontext, int sysnum)
{
  if (sysnum == write_sysnum)
  {
    return true;
  }
  return false;
}

static bool
event_pre_syscall(void *drcontext, int sysnum)
{
  begin = clock();
  // dr_fprintf(STDOUT, "\nsyscall begin.\n");
  // dr_fprintf(STDOUT, "syscall %d begin at %lf.\n", sysnum, (double)begin);
  // Sleep(3000);
  dr_fprintf(STDOUT, "%"PRIu64"\n", dr_get_milliseconds());
  return true;
}

static void
event_post_syscall(void *drcontext, int sysnum)
{
  clock_t end = clock();
  // dr_fprintf(STDOUT, "syscall %d end at %lf.\n", sysnum, (double)end);
  double time_spent = (double)(end - begin);
  // dr_fprintf(STDOUT, "syscall %d spent %lf millseconds.\n", sysnum, time_spent);
  dr_fprintf(STDOUT, "%"PRIu64"\n", dr_get_milliseconds());
  dr_fprintf(STDOUT, "\n");
  // dr_fprintf(STDOUT, "\nsyscall end.\n");
}

static void event_exit(void) {
  drmgr_exit();
}

static int
get_write_sysnum(void)
{
    /* XXX: we could use the "drsyscall" Extension from the Dr. Memory Framework
     * (DRMF) to obtain the number of any system call from the name.
     */
#ifdef UNIX
    return SYS_write;
#else
    byte *entry;
    module_data_t *data = dr_lookup_module_by_name("ntdll.dll");
    DR_ASSERT(data != NULL);
    entry = (byte *) dr_get_proc_address(data->handle, "NtWriteFile");
    DR_ASSERT(entry != NULL);
    dr_free_module_data(data);
    return drmgr_decode_sysnum_from_wrapper(entry);
#endif
}
```

And this is the tested program:
```c
#include <iostream>
#include <fstream>
#include <string>

void sayHelloWorld()
{
	std::cout << "H" << std::endl;
}

int main()
{
	sayHelloWorld();
}
```

The command is
```
D:\MyDynamoRIO\DynamoRIO\bin32\drrun.exe -root D:\MyDynamoRIO\DynamoRIO -c D:\MyDynamoRIO\DynamoRIO\build\bin\sys_call_time.dll -- D:\MyDynamoRIO\HelloWorld.exe
```

but i found that the time of pre and post is same. It's strange.

I am using vs2013 + cmake 2.8.10 + DynammoRIO latest.

**Comment by derekbruening** [comment]
Please be more specific:  What is the same?  dr_get_milliseconds() or clock()?  What is the precise value that is the same: please show the output.  Are you sure "PRIu64" is defined properly?  What does `"%" UINT64_FORMAT_CODE` print?

The title of this issue sounds like what should be an email to the users list, not an issue tracker entry.  Please describe the bug being filed in the issue title, or if it's not clear it's a bug it's probably best to send to the users list before filing in the tracker.

**Comment by Clcanny** [comment]
I use `dr_get_millseconds()` and `dr_get_microseconds()`, the result are the same.
the output is that: almost the time before and after syscall is the same.
Can you sure that `event_post_syscall` is called by DR after the syscall return?
Thanks.

**Comment by Clcanny** [comment]
And you guy may be have some good way to calculate CPU time of a sys-call or function-call?

**Comment by derekbruening** [comment]
You still never provided actual numbers or actual output.  You say "the result are the same" but then "almost...the same".  A single system call these days takes less than a microsecond, so having the milliseconds or even microseconds be identical or nearly identical is not surprising, even with the extra work to raise DR's events.  You need to use a finer-grained counter to measure a single syscall.

There seems to be no bug here in DR so I am closing this.  The issue tracker is meant for specific bugs or API feature requests.  Please use the dynamorio-users mailing list for general questions.

**Comment by Clcanny** [comment]
Thank you.
