### ISSUE TITLE
Allow code cache pre-population when instrumentation is already initialized

### ISSUE THREAD

**Issue by atrosinenko** [DynamoRIO/dynamorio#2561]
Recently the PR #2505 introduced an API to pre-populate the code cache before the instrumentation starts. It would be useful sometimes to pre-translate some BBs inside, for example, an annotation handler. One example is a forkserver like in American Fuzzy Lop: the parent process just spins in the infinite loop and spawns new processes that are fed with the test data. In the qemu_mode variant of instrumentation they implemented an approach, when children send parent information about basic blocks executed, so parent can translate them once for all the subsequent children.

Looks like an existing code can work in such a setup with a small trick:
```c
void *drcontext = dr_get_current_drcontext();
dr_prepopulate_cache(tags, count);
dr_switch_to_dr_state_ex(drcontext, DR_STATE_GO_NATIVE);
```
because after the `dr_prepopulate_cache` the context is **unconditionally** switched to the application.

**Comment by derekbruening** [comment]
Right, the swap to the app is to work with the documented usage model for dr_prepopulate_cache(): being called between dr_app_setup() and dr_app_start().

I think the usage here is closer to #1594 which is more of an incremental model of asking for one or more bbs to be built at multiple points during execution of the app.  Perhaps we can merge these issues?  I'll go ahead and mark this a dup of the older issue and I'll quote your code here (thanks for providing it) in #1594.  Please cc yourself there (this tracker doesn't have first-class duplicate support, and it feels odd to dup the other direction of older to newer).  If you'd like to contribute a patch for this usage we would welcome that.

**Comment by atrosinenko** [comment]
> an incremental model of asking for one or more bbs to be built at multiple points during execution of the app
Yes, it is exactly what I mean. My mistake, I just searched the tracker on "pre-population" keyword and did not found that issue.

Unfortunately, now I'm not familiar even with the DR's public API, so I am currently unable to submit so internal patch. Currently, I just can think of checking `dr_using_app_state()` prior to switching the context for the first time, but I don't know if it will not break the original use case or can introduce some more tricky issues like thread-safety ones.

Meanwhile, a silly question: what is exactly expected by the `bool dr_prepopulate_cache(app_pc *tags, size_t tags_count)` function: raw addresses of the first instructions of bbs (that are somehow adjusted for ASLR) or tags passed to bb instrumentation event? I am a bit confused by the `app_pc *tags` argument and `app_pc dr_fragment_app_pc(void *tag)` signature (specifically, by the fact that `tag` is represented by `void *` and PC by the `app_pc` typedef, while in the prepopulation function signature they are mixed).
