### ISSUE TITLE
vmarea and heap exit flags not reset on re-init

### ISSUE THREAD

**Issue by s-kanev** [DynamoRIO/dynamorio#2571]
This came up in the following case:
- static attach with a client (drmemtrace), which detaches with dr_app_stop_and_cleanup().
- later, from the same process, invoke raw2trace_t, which uses dr_init_standalone() to map modules and decode instructions.
Mapping modules then fails because [`update_dynamo_areas_on_release()`](https://github.com/DynamoRIO/dynamorio/blob/77899b019a203be77aad3bd46676510290b480da/core/heap.c#L1877) doesn't remove VM areas thinking it's exiting, because both `vm_areas_exited` and `heap_exiting` are still set.

The fix is simple, don't statically initialize them, but use the proper _init() functions.

**Comment by derekbruening** [comment]
Re-initializing the same DR library instance is not fully supported yet: #2157 covers the main feature and initial work for full (non-standalone) re-attach.

**Comment by s-kanev** [comment]
Understood, I'm guessing the standalone case is much simpler than #2157 because it touches on fewer static variables.
