### ISSUE TITLE
reduce per-thread memory usage on UNIX

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#2575]
We've optimized memory usage for each thread on Windows in the past, but not on UNIX.

After some investigation this is what we have for each thread for x86_64:
+ dstack, 64K w/ guards
+ DR TLS, 12K w/ guards (so 4K wasted with 16K vmm blocks): os_tls_init
+ privlib TLS, 16K w/ guards: privload_tls_init (from os_tls_app_seg_init, os_tls_init)
+ local_heap, 32K w/ guards
+ nonpersistent_heap, 32K w/ guards
+ signal special heap, 32K w/ guards
+ alt sig stack, 64K w/ guards

So that's 7 requests, 2 of which are 64K == 9 32K == 18 16K units == 288K per
thread.  That's too much: a large app with 1000 threads will need 288M which
will likely be much more memory than for its code cache or heap.

Where is the gencode?  Private gencode never created for x86_64.
Where is thread-private cache?  Never created b/c no traces and no inlined syscalls?

Things to consider:

+ turn off guard pages by default to save memory??
  robustness-performance tradeoff: maybe let users make that decision, and document the -guard_pages option

+ if reset is disabled, don't split nonpersistent heap
+ combine the 2 TLS into one
  or, -vmm_block_size 4K (see below): no kernel min size forcing us to add code complexity to share allocs like there is on Windows

+ shrink vmm unit to 4K to avoid waste and making it easy to shrink other things incrementally?
What is cost of smaller block size?  Extra space+time for vmm block data struct?
    bitmap_element_t blocks[BITMAP_INDEX(MAX_VMM_HEAP_UNIT_SIZE / MIN_VMM_BLOCK_SIZE)];
So hardcoded for max + min no matter the runtime options.
It was 512*1024K/16K = 32K / 32 = 1024 uints = 4K space.
With 4K min block size it's a 16K array.
vmm_dump_map is 4x bigger in the logfile.
We could do 8K instead of 4K: only the DR TLS would waste a page right now, but
we want to shrink the thread heap down to 4K too.

+ shrink local heap: almost always only used for IR, right?  plus, will just make new unit if need more
Measure how much is used?  Clients would be expected to not use much, and a new
unit will be made if they really want a lot.
I would think 4K should be plenty.
But make that Linux-only?  Windows should take 64K and commit one page at a time (pretty sure it's already doing that).
+ shrink signal heap or stack?
What is size of signal frame on skylake?  Size of sigpending_t?
+ shrink dstack: that's up to client

**Comment by derekbruening** [comment]
While looking at the local heap I found that the trace head table is still allocated when traces are disabled, and it takes up 4400 bytes (so over one page).  I will put in code to avoid that space as part of this issue.

**Comment by derekbruening** [comment]
Re: combining the 2 TLS: the code complexity is too high and the simpler solution as mentioned is to reduce the vmm block size.

Re: "if reset is disabled, don't split nonpersistent heap": we actually already do that today, except we can't in the presence of clients due to flushing safety issues: https://github.com/DynamoRIO/drmemory/issues/1791

Re: local heap sizes: IR use is actually much higher than my intuition says: at 96 bytes per instr_t, a big client like memtrace can easily have a few hundred instr_t's per bb and use 20-30K right there.  The non-persistent heap, however, does stay small, typically on 3 (4096-sized) pages, so reducing the initial heap unit size from 32K to 12K is worthwhile (it will quickly double back up for IR usage).

**Comment by derekbruening** [comment]
Re: signal heap: today it's sized as:
```
    size_t unit_size = (block_size * 16 > HEAP_UNIT_MIN_SIZE) ?
        (block_size * 16) : HEAP_UNIT_MIN_SIZE;
```
For x86_64, sigpending_t pend_unit_size is 1408 which *16 is 22K, but the heap unit min size is 32K (though I plan to shrink it to 16K as outlined above).

16 seems larger than necessary: 8 seems fine, especially if we add some notification when it's reached that the next one will involve unsafe locks, and we have some checks for nearing it in places where it's safe to acquire locks where we can proactively force a 2nd unit.

We also need to add the ability to specify a size for a special heap allocated this way, and have that size be independent of the regular heap unit size defaults.

**Comment by derekbruening** [comment]
Testing the signal heap:

```
$ bin64/drrun -max_pending_signals 1 -- suite/tests/bin/linux.signal1111
<Starting application /home/bruening/dr/git/build_x64_dbg_tests/suite/tests/bin/linux.signal1111 (23211)>
<Paste into GDB to debug DynamoRIO clients:
set confirm off
add-symbol-file '/home/bruening/dr/git/build_x64_dbg_tests/lib64/debug/libdynamorio.so' 0x00005620642f0c28
>
<Initial options = -no_dynamic_options -code_api -max_pending_signals 1 -stack_size 56K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
<(1+x) Handling our fault in a TRY at 0x0000562064588ea2>
<Application /home/bruening/dr/git/build_x64_dbg_tests/suite/tests/bin/linux.signal1111 (23211).  Reached the soft maximum number (1) of pending signals: further accumulation prior to delivery may cause problems.  Consider raising -max_pending_signals.>
<many pending signals: asking for 2nd special unit>
<potentially unsafe: allocating a new fragile special heap unit!>
Sending SIGUSR2
Sending SIGUSR1
in signal handler
Got SIGUSR1
Sending SIGRTMAX
in signal handler
Got SIGRTMAX
Generating SIGSEGV
in signal handler
Got SIGSEGV
1750007.875459
Got some timer hits!
<Stopping application /home/bruening/dr/git/build_x64_dbg_tests/suite/tests/bin/linux.signal1111 (23211)>
```

**Comment by derekbruening** [comment]
49769cd3ce5a77f8f692d1f99a377eab84f1135a implements the 4K vmm block size for UNIX

**Comment by derekbruening** [comment]
Re: guard pages: 
The proposal is to make guard pages for units inside vmm off by default?  Could add guard pages
just on both ends of the big vmm reservation?  Security-wise guards around the
vmm reservation will stop a linear write originating outside at least.  Removing
from fcache/heap units inside will no longer stop those originating inside, but
today's tools would probably prefer to use less memory.  However, it would be
good to keep a guard page at the bottom of each stack (xref #2592).

On Windows guard pages are cheaper: going to take up 64K of address space
anyway, so they're free for mmaps <=56K, and guards are reserved but not
committed.  (At least with the current VMM model where it relies on OS granularity.)

Re: signal stack: to allow more aggressive shrinking we'll want #2592 which ties into the guard pages.
A signal frame for x86_64 is 1464 bytes.  Below 12K signal stack is not enough for plain DR, and below 20K fails on api.static where libc printf is called from a signal handler.

**Comment by derekbruening** [comment]
Re: Re: local heap sizes: the 12K I listed above only works w/o guard pages: these options have 8K removed from them for guards, meaning we can't tune defaults to work for both
with and w/o guards.  Perhaps we should change that.  In any case for right now my plan is to
at least split the persistent and non-persistent unit size so they can be separately controlled.

**Comment by derekbruening** [comment]
We need to adjust the commit message template to get auto-links here. 
 Manually adding: private heap changes discussed above are in 87c10349b6c844083e328665ac4470cf8240ed42

**Comment by egrimley** [comment]
What kind of memory are you trying to save by switching off guard pages? If you mean virtual address space, then presumably this is an issue only for 32-bit architectures, and even then only for programs that use a lot of it. Perhaps guard pages prevent the use of transparent huge pages in some cases? Do you have a benchmark program to demonstrate a benefit?

Also, what benefit are you expecting from shrinking stack and heap sizes? Again, I can easily see how you might gain if by doing that you get several different stacks or heaps into the same physical page (which might be a transparent huge page or a user-visible 64K page on AArch64). Do you have other benefits in mind?

**Comment by egrimley** [comment]
Physical memory doesn't get allocated until you use the memory allocated by mmap. I've just tried running a little program on my desktop machine that mmaps an amount of memory specified on the command line and then does `for (;;) sleep 1;`. I now have 16 instances of it running, each "using" 32 GiB, and the machine is quite happy, `top` shows nothing out of the ordinary, apart from 16 lines that resemble this one:
```
  304 egrimley  20   0 32.004g    360    284 S   0.0  0.0   0:00.00 a.out       
```

`/proc/sys/vm/overcommit_memory` has `0` here: "heuristic overcommit (this is the default)". Perhaps you have `2`: "always check, never overcommit", or a different kernel version that does all this stuff differently.

Do guard pages count against the quota? I don't see why they should, seeing as `mprotect` can fail with `ENOMEM` just as easily as `mmap`, but perhaps they do. One could test that...

**Comment by derekbruening** [comment]
I assume you're targeting #976 and your comment should probably go there.  Back when we measured things on vanilla Linux systems, we *did* get charged commit space for just mmapping pages.  The Linux kernel has presumably improved since then.

**Comment by egrimley** [comment]
I've just experimented on an AArch64 system with 64K pages with a program that launches a new thread whenever you hit return. The process acquires 8 MiB of virtual memory for each new thread. Real memory usage seems to be about 500 kB per thread, but is hard to measure accurately with `top`.

To improve performance on such systems it would probably be helpful to allocate DynamoRIO's per-thread data in units of less than a page.

**Comment by derekbruening** [comment]
For Windows we also want to more easily share a single 64K kernel granularity among multiple uses within DR.  I filed #2597 for doing this within -vm_reserve.

**Comment by derekbruening** [comment]
The simple things are now done:

+ DR TLS: -4K
+ nonpersistent_heap: -12K
+ signal special heap: -20K
+ alt sig stack: -24K

So down 60K, and with more control over various sizes for user customization.

-no_guard_pages removes another 56K for use cases where that matters, e.g., to stay within -vm_size.

The defaults are as much smaller as they can reasonably be without negative consequences, and there are now enough knobs that things can be tuned with greater control.  Closing.

**Comment by derekbruening** [comment]
Re: the private heap: the non-persistent heap can also be shrunk despite the IR findings above as many threads never create a bb, for the default shared caches.  Leaving that for tuning via options.
