### ISSUE TITLE
drrun with client does not do anything

### ISSUE THREAD

**Issue by bennofs** [DynamoRIO/dynamorio#2612]
I just build DynamoRIO from source and wanted to use the insttrace tool:

```
d-cube:/c/d/build ((release_7_0_0_rc1)) bin64/drrun  -verbose -c $PWD/api/bin/libinstrace_simple.so  -- uname
INFO: client 0 path: /code/dynamorio/build/api/bin/libinstrace_simple.so
INFO: targeting application: "/usr/bin/uname"
INFO: app cmdline:  "uname"
INFO: configuration directory is "/home/.dynamorio"
INFO: will exec /usr/bin/uname
INFO: registering client with id=0 path=|/code/dynamorio/build/api/bin/libinstrace_simple.so| ops=||
```

but it doesn't appear to do anything. Running DynamoRio without any tool works though:

```
d-cube:/c/d/build ((release_7_0_0_rc1)) bin64/drrun uname
Linux
```

I also tested some other clients, they all behave the same way.

**Comment by derekbruening** [comment]
No idea: of course these tools work fine for others so there is something strange here.

Did you try the release package binaries instead of your custom build?

Did you try debug build `-debug`?

What is the exit code from drrun?

What does `strace` say is happening when drrun "doesn't appear to do anything"?

 "/home/.dynamorio" looks strange: if that's not writable then the options will not be propagated, but it should print `ERROR: process uname registration failed: check config dir /home/.dynamorio permissions`

**Comment by bennofs** [comment]
My `$HOME` is `/home` so the path is correct.

Debug output:

```
$ strace -o strace -f ./bin64/drrun -debug -c api/bin/libinstrace_simple.so.debug -- /usr/bin/uname
<Application /usr/bin/uname (13199) DynamoRIO usage error : client library is incompatible with this version of DR>
<Usage error: client library is incompatible with this version of DR (/code/dynamorio/core/lib/instrument.c, line 523)
version 6.2.17200, custom build
-no_dynamic_options -client_lib '/code/dynamorio/build-debug/api/bin/libinstrace_simple.so.debug;0;' -code_api -stack_size 56K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct 
0x00007fff2cff9e30 0x00007f953e71ba90
0x00007fff2cff9e80 0x00007f953e8170e7
0x00007fff2cffaaf0 0x00007f953e8174fd
0x00007fff2cffb320 0x00007f953e692b95
0x00007fff2cffbb50 0x00007f953e90c154
0x00007fff2cffc590 0x00007f953e8c0182>
```

Strace: https://gist.github.com/d6b41b0f897ca23a8d4fdc13edd59442

**Comment by derekbruening** [comment]
Waiting for answers to the other questions (especially about the release package binary version of the client: works fine?  So this whole issue is about some custom build that you have done here?), and adding:

Please explain precisely how this client was built: as this usage message shows there is something wrong with how it's being built vs being run.  How is the client used under strace different from the client used outside?

**Comment by bennofs** [comment]
Yes, I also tried the packaged version, exactly the same problem, with the same error message. 

> How is the client used under strace different from the client used outside?

I don't understand that? I think it is exactly the same client?

**Comment by derekbruening** [comment]
I am skeptical that the packaged client produced an error message "client library is incompatible with this version of DR".

**Comment by bennofs** [comment]
@derekbruening i downloaded the binaries from

**Comment by derekbruening** [comment]
OK I see the cause of this "client library is incompatible" message: you are pointing at the debug info libinstrace_simple.so.debug, instead of the library libinstrace_simple.so.  So we're back to the original post and the questions in the 2nd post.

**Comment by bennofs** [comment]
@derekbruening when using the release binaries and using `-debug`, do I need to use the `libinstrace_simple.so.debug` or `libinstrace_simple.so`?

**Comment by derekbruening** [comment]
Always use the .so.  The .debug file contains only debug information separated out from the library: it is not a library with code in it.  Xref https://sourceware.org/gdb/onlinedocs/gdb/Separate-Debug-Files.html

Xref #2570 on archlinux glibc crashing relocation when used by a client: is this the same thing?

**Comment by bennofs** [comment]
@derekbruening how would I check if it is the same issue?

**Comment by bennofs** [comment]
The full output from the downloaded archive with `-debug`:

```
$ bin64/drrun -debug -verbose -c samples/bin64/libinstrace_simple.so -- /usr/bin/ls
INFO: client 0 path: /home/downloads/DynamoRIO-Linux-7.0.0-RC1/samples/bin64/libinstrace_simple.so
INFO: targeting application: "/usr/bin/ls"
INFO: app cmdline:  "/usr/bin/ls"
INFO: configuration directory is "/home/.dynamorio"
INFO: will exec /usr/bin/ls
INFO: registering client with id=0 path=|/home/downloads/DynamoRIO-Linux-7.0.0-RC1/samples/bin64/libinstrace_simple.so| ops=||
<Starting application /usr/bin/ls (29844)>
<ERROR: master_signal_handler with no siginfo (i#26?): tid=29844, sig=11>
```

**Comment by derekbruening** [comment]
If you build libinstrace_simple with `set(DynamoRIO_USE_LIBC OFF)` does it work?

**Comment by bennofs** [comment]
Yes, seems to be the same issue (the assembly around the crash is equal). 
Will check if it works with `DynamoRIO_USE_LIBC OFF`

**Comment by bennofs** [comment]
It is the same issue.
