### ISSUE TITLE
drrun code coverage: some lines which should be covered are regarded as not covered

### ISSUE THREAD

**Issue by leekerberos** [DynamoRIO/dynamorio#2614]
![uncovered1](https://user-images.githubusercontent.com/12462173/29611650-e02e1d82-8830-11e7-88ac-bbe714896455.png)
![uncovered2](https://user-images.githubusercontent.com/12462173/29611659-e602b9ac-8830-11e7-8ed1-49cd6397a2c0.png)
As shown in picture 1 line 17-29 are not regard as not covered, but the function 'swapbytes' did get called on line 39 and 40.
And picture 2 line 178-179 are not colored which means the 2 lines are excluded from coverage calculate. Why? As I know, delaration of variables or functions should be excluded, because they cannot be hit actually. But both the lines shown in picture are variables assignment.

**Comment by derekbruening** [comment]
Coverage is based on the compiled binary.  You want to look at the binary instruction-to-line mapping to see what is going on.  It is not unusual, especially with high levels of optimization, to have source lines with no corresponding instruction in the binary.  Here, the `swapbytes` function is easily inlined.  Without the disassembly and line mapping, no conclusions can be drawn.  I would suggest dialing down the optimizations and looking at the disassembly.

**Comment by leekerberos** [comment]
Thanks for your reply. There are indeed some compile optimizations args set in my project.  After removing them, the above lines are covered correctly. It did sovle my problem.
