### ISSUE TITLE
Appveyor chocolatey and fig2dev installation issues

### ISSUE THREAD

**Issue by toshipiazza** [DynamoRIO/dynamorio#2616]
Recently on Appveyor we've been seeing installation failures on chocolatey and fig2dev due to internet outages, e.g. [here][appveyor-link]. This issue covers silently discarding these errors so as to at least continue the build and tests, at the expense of missing doxygen documentation for a week.

[appveyor-link]: https://ci.appveyor.com/project/DynamoRIO/dynamorio/build/1.0.1157

**Comment by toshipiazza** [comment]
Hmm, this wasn't properly closed by the commit even though the commit message marked this issue as fixed.

For reference, fixed by 6aa423a19a2aed482be73a0211b7b058d5c657bc

**Comment by derekbruening** [comment]
You have to have another "fixes" to close a 2nd issue:
https://help.github.com/articles/closing-issues-using-keywords/
"To close multiple issues, preface each issue reference with one of the above keywords. You must use the keyword before each issue you reference for the keyword to work."

**Comment by toshipiazza** [comment]
Noted.
