### ISSUE TITLE
instr_get_opcode(ins) doesn't support NEON and VFP instructions

### ISSUE THREAD

**Issue by yuhao** [DynamoRIO/dynamorio#2624]
Instructions like fmul (vector version) or vmla.f32 are not supported. Is there a plan?

**Comment by egrimley** [comment]
FMUL is AArch64 and currently not handled by the decoder. Of the AArch64 instructions that operate on FP/SIMD registers only load/store instructions are decoded, though it should still be possible to execute any instruction. I don't seem to be able to find a specific issue for completing the AArch64 decoder, though there are related issues, such as #2440 and #2443, and there's #1569, of course.

VMLA.F32 is AArch32 and should work, I think.

If "fmul" is a typo for "vmul", please label this issue with OpSys-ARM and explain what doesn't work.

**Comment by derekbruening** [comment]
Right, please clarify which architecture you are looking at.  All Advanced SIMD and floating point instructions for AArch32 in ARMv8, including [vmla.f32](https://github.com/DynamoRIO/dynamorio/blob/master/core/arch/arm/opcode.h#L610), are supported in DR's IR.

**Comment by yuhao** [comment]
I meant FMUL in AArch64. I suppose this is not a bug, but I was curious if the support for AArch64 will be extended to non load/store instructions?

**Comment by egrimley** [comment]
I've created #2626; I hope it's not a duplicate. I'll close this one for now. It can be reopened if there is a problem with vmla.f32.
