### ISSUE TITLE
static detach/reattach: options with append semantics are appended to on subsequent reattaches

### ISSUE THREAD

**Issue by Carrotman42** [DynamoRIO/dynamorio#2661]
For example, when `-client_lib` (a `liststring_t`) is specified in two consecutive attach/detach runs, the second attach will simply append its value for `-client_lib` to the value in the first run instead of overwriting it.

I'm thinking that we should just set the `dynamo_options` back to default values before each time the options are parsed.

**Comment by derekbruening** [comment]
Just to give context: this is only for static library attach/detach.  As a shared library there would be no trouble here as we'd unload and reload the library, naturally resetting its state.

**Comment by derekbruening** [comment]
Perhaps this should just be part of #2157 -- or at least linked to it

**Comment by derekbruening** [comment]
Note that there is a workaround for this: the special prefix `#` will overwrite instead of append.

**Comment by derekbruening** [comment]
I take it back: the `#` prefix is not enough by itself: the config_exit memset of myvals is also needed.

**Comment by derekbruening** [comment]
#4139 is the same issue with droption options
