### ISSUE TITLE
Contribution information is contradictory

### ISSUE THREAD

**Issue by algrant-arm** [DynamoRIO/dynamorio#2667]
https://github.com/DynamoRIO/dynamorio/blob/master/CONTRIBUTING.md says

"If you would like to contribute code to DynamoRIO, you will need to first sign a Contributor License Agreement."

https://github.com/DynamoRIO/dynamorio/wiki/Contributing says

"If you would like to contribute code to DynamoRIO, we do not require a formal contributor license agreement"

Please can this be fixed by whoever is authorised to state the policy?

Otherwise, my intuition would be that the sole point of having CONTRIBUTING.md in the repo is to precisely state the contributions policy, so in the event of a disagreement with other docs, CONTRIBUTING.md would take precedence.

**Comment by derekbruening** [comment]
We no longer require the CLA: the CONTRIBUTING.md needs to be updated.

**Comment by derekbruening** [comment]
We no longer require the CLA: the CONTRIBUTING.md file needs to be updated.
