### ISSUE TITLE
ASSERT: aarch64 instr_encode_arch() fails to honor check_reachable param

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#2681]
This was raised here: https://groups.google.com/forum/#!topic/DynamoRIO-Users/lqxQpY6GllM

Pasting from there:

This looks like a bug in the aarch64 encoder when encoding solely to print, based on looking at your log file.  That's why it's debug-only.  I think the bug is that the aarch64 encoder ignores the parameter "check_reachable" which is set to false for disassembly.  Branch reachability is supposed to be ignored since this is not a real encoding but just a disassembly.

It's not clear why A) it thinks it needs to encode at all, since it's an L3 instr; and B) why this doesn't happen on the prior 2 prints: presumably b/c they realize they don't need to encode.  Probably the final branch is tweaked before the "before mangling" print or sthg and it shows up as needing encoding despite printing L3.

Details from the log:

```
before instrumentation:
TAG  0x0000007f9bd10fc0
 +0    L3                      910003e0   add    %sp $0x0000 lsl $0x00 -> %x0
 +4    L3                      94000cac   bl     $0x0000007f9bd14274
END 0x0000007f9bd10fc0

CLEANCALL: insert clean call to 0x000000000003b690

after instrumentation:
TAG  0x0000007f9bd10fc0
... 
 +436  L3                      910003e0   add    %sp $0x0000 lsl $0x00 -> %x0
 +440  L3                      94000cac   bl     $0x0000007f9bd14274
END 0x0000007f9bd10fc0

bb ilist before mangling:
TAG  0x0000007f9bd10fc0
 ...
 +436  L3                      910003e0   add    %sp $0x0000 lsl $0x00 -> %x0
 +440  L3                      94000cac   bl     $0x0000007f9bd14274
SYSLOG_ERROR: Application ... (15543).  Internal Error: DynamoRIO debug check failure: Not implemented @.../core/arch/aarch64/codec.c:2603 (0)
```

**Comment by egrimley** [comment]
I find the concept of encoding an instruction that cannot, in fact, be correctly encoded a bit weird, but we can presumably do that. Am I right in thinking that this only relates to PC-relative offsets? How should we encode the offset that cannot be correctly encoded? Make the low bits correct, or make the offset zero, which would perhaps make it more obvious that it's not correct? I think I'd go for the latter.

**Comment by derekbruening** [comment]
This would only happen with branches, yes: these branches are in limbo, representing the original branch but encoded in a temporary spot just for disassembly prior to being mangled away.  This could also happen with a user-created L4 branch which will encode once in its final location, but a diagnostic disassembly that wants to include encoded bytes before DR knows the final location would hit the same un-encodable branch scenario.
