### ISSUE TITLE
The --help option for drrun outputs to stderr and has a non-zero exit code

### ISSUE THREAD

**Issue by c-rhodes** [DynamoRIO/dynamorio#2683]
I think it's sensible for the output of `--help` to go to stdout, this allows for uses such as `drrun --help  | less`. This is also recommended by the [GNU Coding Standards](https://www.gnu.org/prep/standards/html_node/_002d_002dhelp.html). I'm happy to provide a patch if others agree.

**Comment by derekbruening** [comment]
> I think it's sensible for the output of --help to go to stdout, this allows for uses such as drrun --help | less. This is also recommended by the GNU Coding Standards.

Sure, sounds good, and a 0 exit code also seems more reasonable.

> I'm happy to provide a patch if others agree.

Yes please.
