### ISSUE TITLE
Support transfer/relocation when using app locks

### ISSUE THREAD

**Issue by Carrotman42** [DynamoRIO/dynamorio#2725]
In order to prevent deadlocks during detach while using application locks in a client, we need a way to pass along the saved mcontext from before a clean call. Without it, the client code waiting to lock a contended lock may never be safe to synch with, and synch_with_all_threads will eventually fail and time out.

**Comment by derekbruening** [comment]
Adding more background: we support clients running code as the app, and using DR-implemented locks in an app context when they are never used in a DR/client context.  We provide API routines like dr_mutex_mark_as_app() to avoid debug-build DR lock checks, but a client still has to call dr_mark_safe_to_suspend() around its invocation of the app lock to avoid hanging during synchall.  dr_mark_safe_to_suspend() does *not* mark as safe to relocate.

There are 2 problems here: first, it seems like *any* use of a lock as an "app lock" should wrap the lock acquisition with dr_mark_safe_to_suspend(): it should be auto-magically done by the *_mark_as_app() call.

The second problem is what's mentioned above: to support detach we need to support relocation while an app lock is held, for which we need a target mcontext to be provided.  This should probably be optional as not all tools have to support detach.

**Comment by derekbruening** [comment]
Xref #779
Xref https://github.com/DynamoRIO/drmemory/issues/900

**Comment by Carrotman42** [comment]
TODO:

* Update release.dox
* Fix ASSERT failure in mutex_delete when a contended lock is destroyed
