### ISSUE TITLE
Slow attach times due to protecting stack/heap allocations

### ISSUE THREAD

**Issue by Carrotman42** [DynamoRIO/dynamorio#2728]
NOTE: the following describes an incorrect solution to the problem of slow attach times. See further down for details about this issue.

During attach on Unix, the thread executing [os_take_over_all_unknown_threads](http://google3/third_party/dynamorio/trunk/core/unix/os.c?l=9839&rcl=177600668):

1) obtains the thread_initexit_lock
2) (does some other stuff)
3) calls thread_signal to all other threads
4) unlocks thread_initexit_lock
5) waits on each threads' "event" one at a time until all threads are suspended

All threads obtain thread_initexit_lock during their attach logic, and I believe signaling all threads and then unlocking the lock causes contention on thread_initexit_lock. With 3000 threads in my simple repro, attaching takes 70 seconds whereas the following implementation finishes in under a second:

1) obtains the thread_initexit_lock
2) (does some other stuff)
3) unlocks thread_initexit_lock
4) for each thread:
   4.1) signal that thread
   4.2) wait for that thread's "event"

**Comment by Carrotman42** [comment]
Scratch the suggested fix. I was misreading the output of my test program; the modified algorithm takes just about as long as the original algorithm. There must be something in thread initialization that's taking up all of the time.

**Comment by Carrotman42** [comment]
Through more investigation, the long attach times seem to have been caused when we started setting flags related to guard pages internally.

**Comment by derekbruening** [comment]
The culprit is 240b75d61 for #2592 which used make_unwritable which does a query.  We already know the prior permissions though and can avoid that query by calling set_protection.
