### ISSUE TITLE
Unclear instructions how create a pull request using Windows as development environment

### ISSUE THREAD

**Issue by vbaderks** [DynamoRIO/dynamorio#2753]
Hi, 

I am trying to create a pull review request for review, using the instructions on the wiki. My development environment is Windows (using MINGW64 for the git and .sh commands).

When I am trying to execute git review I get:
$ git review
Pushing iX-cpp-compile-improvements-1 to remote.  Please visit https://github.com/DynamoRIO/dynamorio
and create a pull request to compare iX-cpp-compile-improvements-1 to master.
remote: Permission to DynamoRIO/dynamorio.git denied to vbaderks.
fatal: unable to access 'https://github.com/DynamoRIO/dynamorio.git/': The requested URL returned error: 403

Do I need first to clone this repo to my own github account? and then do a local clone?

**Comment by derekbruening** [comment]
The wiki instructions assume you have commit access to https://github.com/DynamoRIO/dynamorio.
I just updated both https://github.com/DynamoRIO/dynamorio/wiki/Contributing and
https://github.com/DynamoRIO/dynamorio/wiki/Code-Review to make this more clear.

For a non-project member (i.e., without write access to the repository), yes, you would clone into your personal github, develop there, and then do a pull request back to the master here.  Xref https://github.com/DynamoRIO/dynamorio/wiki/Code-Reviews#submitting-a-change-as-a-non-project-member.

Thank you for your interest and looking forward to your patch.  I believe the docs issue here has been addressed: closing.
