### ISSUE TITLE
Filtering memory range in memtracer

### ISSUE THREAD

**Issue by Coder5555** [DynamoRIO/dynamorio#2768]
Hey guys,

I want to enhance the simple memtracer (memtrace_simple.c in api/samples), such that it is able
to filter the instrumented addresses **on the fly**. (My hope is to gain performance with this 
measure, especially when only a small memory range should be traced).

How is it possible to get the address of the currently instrumented operand?
Unfortunately, `opnd_get_addr(instr_get_src(instr, i))` method gets NULL
when I call it inside the if statement
of the following code snippet:
```
        for (i = 0; i < instr_num_dsts(instr); i++) {
            if (opnd_is_memory_reference(instr_get_dst(instr, i)))
            {
                uint* addr = (uint*) opnd_get_addr(*instr_get_dst(instr, i));
                if(5000 <= *addr && *addr <= 10000)
                {
                    instrument_mem(drcontext, bb, instr, tmp, true);
                }
            }
        }
```
Why is there no address for this opnd? 
By using the if statement, it should be assured to be a memory reference...
How is it possible to retrieve the address of a memory reference operand? (opnd_t)

Best regards,

**Comment by derekbruening** [comment]
This seems like a question for the [users list](https://groups.google.com/forum/#!forum/DynamoRIO-Users), not something to file in the issue tracker, which is for specific bugs or specific interface feature requests.  Please ask on the list and we will reply there.
