### ISSUE TITLE
Codeing Style needs guideline how to resolve conflicts between global and local variables

### ISSUE THREAD

**Issue by vbaderks** [DynamoRIO/dynamorio#2776]
The dynamorio projects has functions that use the name option_string as parameter name or as local variable. This causes compiler warnings such as "C4459 declaration of 'option_string' hides global declaration". 

There are main 2 ways to resolve this warning:
- rename the global variable with a global prefix, for example g_
- rename the local parameter or variable with a postfix, for example _param or _local.

The Code Style page on the Wiki provides no guidance how to name global variables and/or guidance what to do when the name conflicts with a local name.

**Comment by derekbruening** [comment]
Given that there are no conventions for prefixes or suffixes on any variables the shadowing should be avoided by simply renaming the local or inner scope variable with a different name.  I'm not sure this needs to be explicitly stated but I added such a rule to the wiki page.
