### ISSUE TITLE
`xsavec` instruction not supported

### ISSUE THREAD

**Issue by rocallahan** [DynamoRIO/dynamorio#2793]
http://www.felixcloutier.com/x86/XSAVEC.html
This was introduced in Skylake.

**Comment by rocallahan** [comment]
glibc 2.24 started using it: https://sourceware.org/ml/libc-stable/2017-10/msg00049.html

**Comment by fhahn** [comment]
Adding `good first issue` as I think this should be quite straight forward, see 67032180c54d5e8243eb7d3a99d13b1dbc503 for a recent commit that added support for a couple of AVX2 instructions.

**Comment by rocallahan** [comment]
Yeah, I wrote that :-).

**Comment by rocallahan** [comment]
I have a patch for this which I will upstream when I get a chance.

**Comment by fhahn** [comment]
Great, thank you very much! [This page](Code-Reviews) describes the code review process.

**Comment by derekbruening** [comment]
#1312 already covers this
