### ISSUE TITLE
undefined symbol `abort` in libdynamorio.so

### ISSUE THREAD

**Issue by lucjaulmes** [DynamoRIO/dynamorio#2869]
Commit d169227e seems to introduce a compilation error:

```
  *** Error:
  dynamorio/lib64/debug/libdynamorio.so
  has undefined symbol: GLOBAL DEFAULT UND abort
```

this is the `readelf -s` output that causes the check to fail:

```
> readelf -s lib64/debug/libdynamorio.so | grep -w UND
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND 
     1: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND abort
     0: 0000000000000000     0 NOTYPE  LOCAL  DEFAULT  UND 
  2823: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND abort
```

**Comment by derekbruening** [comment]
Given that this passed on Travis, it's clearly limited to certain compiler/linker versions: please provide your toolchain info.  This also doesn't make much sense to me: A) there is no call to abort related to this -- where is your reference to abort coming from (which .o)?; and B) why would this happen on this commit and not the other uses of REPORT_FATAL_ERROR_AND_EXIT?

**Comment by lucjaulmes** [comment]
Hmmm... I ran the bisect which gave me this commit, but upon going back to it I can't reproduce this myself. Well, no bug is good news I guess.
