### ISSUE TITLE
ARM undefined symbol __aeabi_ldivmod

### ISSUE THREAD

**Issue by egrimley** [DynamoRIO/dynamorio#2901]
After fixing a couple of trivial things, I got this build error on Debian armhf unstable, but only without DEBUG:

```
CMake Error at /.../dynamorio/core/CMake_readelf.cmake:94 (message):
  *** Error: /.../dynamorio-build/lib32/release/libdynamorio.so has
  undefined symbol: GLOBAL DEFAULT UND __aeabi_ldivmod
```

**Comment by TomSie** [comment]
Hey,

I was able to resolve this with the following patch:

--- dynamorio/third_party/libgcc/arm/lib1funcs.S	2018-10-12 13:06:12.458365850 +0000
+++ dynamorio/third_party/libgcc/arm/lib1funcs.S	2018-10-12 13:12:49.997977443 +0000
@@ -1992,6 +1992,9 @@
 #ifndef __ARM_ARCH_6M__
 #include "ieee754-df.S"
 #include "ieee754-sf.S"
+#ifdef L_udivsi3
+#define L_aeabi_ldivmod
+#endif
 #include "bpabi.S"
 #else /* __ARM_ARCH_6M__ */
 #include "bpabi-v6m.S"

it's not a nice and clean solution but it works :)
