### ISSUE TITLE
error C2065: 'LOG_ALL': undeclared identifier

### ISSUE THREAD

**Issue by yoava333** [DynamoRIO/dynamorio#2903]
I'm trying to compile [WinAFL](github.com/ivanfratric/winafl) on the latest build (cronbuild-7.0.17614) I'm getting an error which didn't happen on previous versions:
```
C:\work\fuzzing\winafl\winafl.c(671): error C2065: 'LOG_ALL': undeclared identifier [C:\work\fuzzing\winafl\build32\winafl.vcxproj]
```

the target file is https://github.com/ivanfratric/winafl/blob/master/winafl.c.

It builds correctly on 7_0_0_rc1 and 6_2_0 releases.
Thanks

**Comment by derekbruening** [comment]
LOG_xxx was renamed to DR_LOG_xxx to avoid name conflicts. 
 There is a compatibility option in place but these cronbuilds are >7.0 versions so it's not there by default for those. 
 See https://github.com/DynamoRIO/dynamorio/commit/5ed020292c90fab634ebd1f42e82f9d623cf92f8

**Comment by derekbruening** [comment]
If you put 7.0 or earlier in the target version of your find_package(), or define DynamoRIO_LOG_COMPATIBILITY directly, the old defines will be there.  But using an unspecified version in find_package() pulls in the latest.

**Comment by yoava333** [comment]
Thanks, it worked!
