### ISSUE TITLE
Error: drcachesim -offline -use_physical 

### ISSUE THREAD

**Issue by arkodutt** [DynamoRIO/dynamorio#2912]
Hi,

I am very new to exploring dynamorio. So these might seem pretty basic queries. I am trying to create a readable memory trace file from any application containing the physical address translations from pagemap virtual addresses. I found the dynamorio useful for creating such an output by using drcachesim client. Got an error while executing 
**"./bin64/drrun -t drcachesim -offline -use_physical -- ls"**   

Assert failure Error **: /dynamorio/clients/drcachesim/tracer/instru_offline.cpp:192: false ().**

Two queries - 
1) I saw this type of issue reported before, but couldn't decipher how to fix it. How to fix it?
2) I wish to have an understandable/readable text-mode file containing the physical addresses, and not binary trace dump. Is there any existing way of getting it?

Thanks,
Arko

**Comment by fhahn** [comment]
A bit of additional information would be helpful:
* What version of DynamoRIO are you using? Did you build it yourself? If so, what toolchain did you use?
* What OS & architecture are you using? X86_64? AArch64?

**Comment by arkodutt** [comment]
1. Dynamorio version 7.02. Yes, I built it. I followed the installation toolchain from this website - https://github.com/DynamoRIO/dynamorio/wiki/How-To-Build

2. OS - Ubuntu 16.04, Architecture - x86_64. I would like to the solution for both architectures mentioned, if possible.

Thanks,
Arko

**Comment by arkodutt** [comment]
- It fails using the release build DynamoRIO-Linux-7.0.0-RC1 as well. Similar assert failure
ASSERT FAILURE: /dynamorio_package/clients/drcachesim/tracer/instru_offline.cpp:101: false ()

- Thanks for sharing this info. I use **bin64/drrun -tracedump_binary -t drcachesim -use_physical -- ls** and gather the binary trace in logs. Then I would follow the link you directed to create the custom text format trace. I just need to assure - using -use_physical option dumps all available physical addresses  to the tracefile, right ?

**Comment by arkodutt** [comment]
- successful execution after disabling the assert in the new build.

- thanks for the clarification of tracedump_binary

- I could see addresses with drcachesim execution with -use_physical option for 'ls' application. I printed  memref.data.addr to console (and csv) from cache_simulator.cpp (got output after building the modified version just to print the addresses). I expected these physical addresses to be quite lower in count than without use_physical option, since there shall be a much higher no of virtual addresses (cache + main memory accesses) than physical addresses (only main memory accesses) for any small application like 'ls'. So, I just have a few quick questions: 

1. do these physical addresses map to the main memory? 
2. if not, does simulator type TLB gives the mapped physical addresses to main memory?

While using dynamorio, one of my main goals is to find out all main-memory accesses (with  physical addresses ) for any application.

Thanks,
Arko

**Comment by derekbruening** [comment]
I think there's a misunderstanding here: these traces of physical addresses that were loaded and stored are identical to traces of virtual addresses, except each virtual address has been translated to its corresponding physical address.  Generally a cache simulator would be used on the resulting trace to analyze memory access patterns for a given cache configuration, and you would only want physical addresses for such a task if you are simulating physically-addressed caches.  If you want to simulate, say, L2 and higher as physically addressed, you could use the online first-level-cache filtering option to filter out (by virtual addresses) hits in L1 and then translate the misses to physical.  (The filter option is named "L0" to fit with the provided online simulator which always says "L1".)

**Comment by derekbruening** [comment]
Looks like #2437 was already filed on `-offline -use_physical` hitting this assert.  Normally we'd close the more recent one but there's more discussion here so I'm closing the other one.

**Comment by arkodutt** [comment]
So these are not physical addresses of the main memory. Is there any way to retrieve physical addresses mapped to main memory (by using pagemap of the process), beyond all cache levels for a specific application ? If there are cases of executables operating on bigger datasets, it may be good to know this figure. 

However, while trying to run an example python executable operating on alexnet with **bin64/drrun -t drcachesim -use_physical -- python ../alexnet.py**, I encountered the following error [although this error could have been lodged onto another issue]: 

`<Application /usr/bin/python3.5 (5669).  DynamoRIO Cache Simulator Tracer internal crash at PC 0x00007f1c604c8990.  Please report this at http://dynamorio.org/issues.  Program aborted.
Received SIGBUS at pc 0x00007f1c604c8990 in thread 5669
Base: 0x00007f1c603fb000
Registers:eax=0x00000000000e061c ebx=0x00007f1c58ea9348 ecx=0x0000000000000000 edx=0x0000000000000000
	esi=0x0000000000000000 edi=0x00007f1c58ea9348 esp=0x0000000055df6cd8 ebp=0x000000000000000f
	r8 =0x0000000000000000 r9 =0x0000000000000000 r10=0x00007f1c58e6d000 r11=0x00000000000050e8
	r12=0x0000000000000005 r13=0x0000000000000078 r14=0x0000000000000060 r15=0x000000005609d7d8
	eflags=0x0000000000010202
version 7.0.0, build 1
-no_dynamic_options -client_lib '/home/arkodutt/DynamoRIO-Linux-7.0.0-RC1/bin64/../tools/lib64/release/libdrmemtrace.so;0;' -code_api -stack_size 56K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
---- <application exited with code 65280> ----
Core #0 (3 thread(s))
  L1I stats:
    Hits:                    1,947,417,302
    Misses:                     14,182,695
    Miss rate:                        0.72%
  L1D stats:
    Hits:                      811,248,092
    Misses:                     15,902,920
    Prefetch hits:                       0
    Prefetch misses:                     8
    Miss rate:                        1.92%
Core #1 (4 thread(s))
  L1I stats:
    Hits:                        2,701,855
    Misses:                          2,624
    Miss rate:                        0.10%
  L1D stats:
    Hits:                        1,060,555
    Misses:                          6,245
    Miss rate:                        0.59%
Core #2 (3 thread(s))
  L1I stats:
    Hits:                          146,730
    Misses:                            154
    Miss rate:                        0.10%
  L1D stats:
    Hits:                           52,508
    Misses:                            208
    Miss rate:                        0.39%
Core #3 (3 thread(s))
  L1I stats:
    Hits:                          150,606
    Misses:                            152
    Miss rate:                        0.10%
  L1D stats:
    Hits:                           53,840
    Misses:                            163
    Miss rate:                        0.30%
LL stats:
    Hits:                       28,363,801
    Misses:                      1,731,360
    Prefetch hits:                       8
    Prefetch misses:                     0
    Local miss rate:                  5.75%
    Child hits:              2,762,831,488
    Total miss rate:                  0.06%
`

The error persisted for both the release and cron builds. 

Thanks,
Arko

**Comment by derekbruening** [comment]
Physical addresses are obtained from pagemap and are addresses in physical memory.  There is no indication of whether the load or store hit in one of the caches, though, as that information is not feasible to obtain while tracing.

Please file this issue with python as a separate issue in the tracker.  This issue here is about the `-offline -physical` combination not working.

General questions should go to the users list.

**Comment by arkodutt** [comment]
Thanks Derek, sure I will lodge a separate issue for it.

**Comment by derekbruening** [comment]
There are deep problem with combining -offline and -use_physical.  #4014 covers those.  The assert in this issue is fixed.  Closing as a dup of #4014.
