### ISSUE TITLE
drmgr callback behavior

### ISSUE THREAD

**Issue by raghuncstate** [DynamoRIO/dynamorio#2925]
Hello,

I'm using drmgr to register for callbacks during the 4 passes to understand the pattern of callbacks. I'm seeing behavior that i'd like explanation for since i'm not able to explain it by looking at source code.

In a callback registered with drmgr_register_bb_app2_app_event(),  i'm interested in a particular basic block, whose address i already know out of band. In the callback, i check to see if the event received is for a block im interested in, and if so i print something out on screen. Now, if i just print something, I see the event being called once for basic block creation and once for trace creation and never again. Note that the block I'm interested in, is constantly executed and pretty much takes up 99% of program execution. However, if i prepend an instruction(nop in my case) during both basic block creation and trace, to the start of the basic block im interested in, i see the event being triggered all the time with for_trace being set. Is there some smarts in DR, that knows if the basic block was modified or not ? If so where can i look up the code for this ? Why is the event being called for trace creation over and over again ?

**Comment by raghuncstate** [comment]
[upload.tar.gz](https://github.com/DynamoRIO/dynamorio/files/1953198/upload.tar.gz)

Attached minimized test case. hello.c is the test application running under the client. test_client.cpp is the client. README contains how hello.c was compiled while reproducing the issue and also the commit at which DR libraries were built from github.

Additional info and refinement to the issue. I see the described behavior above, if i insert an application/non-meta instruction. If i insert a meta instruction, i see one call for basic block creation and one for addition to the trace.

See line 102 and 108 of test_client.cpp.

**Comment by derekbruening** [comment]
Always run in debug build to help diagnose problems: you will see that your code is failing to set the translation of the app instruction, which messes up trace building.  Also note that adding meta instructions in the app2app phase is not recommended.

**Comment by derekbruening** [comment]
As for the repeated trace building, it refuses to build the trace due to the illegal translation address, but keeps trying over and over.  Perhaps the failure should be fatal in release build.
