### ISSUE TITLE
Record the physical offset of each segment in modules.log

### ISSUE THREAD

**Issue by snehasish** [DynamoRIO/dynamorio#2939]
In order to support internal symbolization tools we would like to record the physical offset of each mapped segment. drmodtrack combines multiple adjacent segments into a single contiguous blob so multiple physical offsets could be mapped to the entry in the modules.log file. Since the modules.log format may already contain multiple entries for non contiguous mapped regions, clients should already handle the case of multiple entries for a single module.

**Comment by derekbruening** [comment]
The #2940 PR for this failed to use this issue number and was committed as 8c90e2dc81eb9b9dfdcf2313bdf91b02f12c4de4 so manually linking and closing here.
