### ISSUE TITLE
ASSERT memval_simple "invalid size parameter"

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#2946]
Failures in the sample.memval_simple test on Fedora 27:

Release build:
http://dynamorio.org/CDash/testDetails.php?test=518423&build=35316
```
ASSERT FAILURE: /work/dr/nightly/src/ext/drx/drx_buf.c:680: (0) ()
```

Debug build:
http://dynamorio.org/CDash/testDetails.php?test=518361&build=35314
```
<Application /work/dr/nightly/run/build_debug-internal-64/suite/tests/bin/common.eflags (14583) DynamoRIO usage error : reg_32_to_opsz: invalid size parameter>
<Usage error: reg_32_to_opsz: invalid size parameter (/work/dr/nightly/src/core/arch/opnd_shared.c, line 2041)
```

**Comment by derekbruening** [comment]
`OPSZ_VAR_REGLIST` is for the memory used by an ARM register list to avoid having to hardcode the list size.

**Comment by derekbruening** [comment]
> I can take a look at this after my semester ends.

OK, thanks, it is only making CDash red and not Travis so a few weeks won't block anyone.

Some thoughts:

For live DR on Linux we could use the xsave size we determined in
signal_arch_init().  But what about drdecode which may have a different host
and target cpu?

This is going through drutil_opnd_mem_size_in_bytes(): maybe that could
query cpuid.

**Comment by hgreving2304** [comment]
xref #3456

**Comment by hgreving2304** [comment]
Patch above was incorrectly classified as "Issue" instead of "Fix". Closing this issue, the referenced patch is a fix incl. Window.

**Comment by derekbruening** [comment]
The solution is not completely accurate though due to dynamic size variances.  Is there an issue on solving that (would need a new API) to xref here?

**Comment by hgreving2304** [comment]
> The solution is not completely accurate though due to dynamic size variances. Is there an issue on solving that (would need a new API) to xref here?

In this case, let's leave this issue open in order to address this. Re-opening.

**Comment by derekbruening** [comment]
I think in the PR I suggested filing an issue on something parallel to instr_compute_address() which takes in an mcontext.  I would say let's open a separate feature issue.

**Comment by hgreving2304** [comment]
xref #3467

**Comment by derekbruening** [comment]
I filed #3473.  That leaves this as unresolved: 

> But what about drdecode which may have a different host and target cpu?

I think we just bail on that: if you want precision in dynamic memory ranges you can't get it from static decoding.

**Comment by hgreving2304** [comment]
I had already filed #3467

**Comment by derekbruening** [comment]
#3467 looks to be about handling the xsave memory accesses as multiple distinct blobs of memory instead of a single blob, right?  And it's about instr_compute_address_ex() and talks only about addresses, not about sizes.  #3473 is about sizes.
