### ISSUE TITLE
Provide ISA versioning API to clients

### ISSUE THREAD

**Issue by fhahn** [DynamoRIO/dynamorio#2960]
We could provide an API for clients to check if a given ISA version supports a given encoding. For example, half precision floating point arithmetic was only added in Armv8.2 and those instructions are not supported by earlier architecture versions.

I am not entirely sure how such an API should look like so it is flexible enough for a wide range of clients but can also be implemented efficiently.

**Comment by derekbruening** [comment]
Merge into #431?

**Comment by fhahn** [comment]
Move text to a comment in #431
