### ISSUE TITLE
Java JVM JIT support

### ISSUE THREAD

**Issue by raghuncstate** [DynamoRIO/dynamorio#2968]
Does DynamoRIO support running a Java application on the JVM with JIT enabled? I understand it wasn't supported very well in the past based on looking up github issues and google forums for dynamorio users. Has that changed recently?
I am attempting to run the Java JVM binary under DR with a java application and am seeing crashes unless i turn off the JIT with the -XInt option. This is on x86-64

**Comment by derekbruening** [comment]
This seems like a question that should go to the users list.  The issue tracker is for specific bug reports.

**Comment by raghuncstate** [comment]
Apologize. Moved to google users group.
