### ISSUE TITLE
have CDash share the flaky/ignore test list with CI

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#2984]
Today we have the _FLAKY test name mechanism and a list of tests to ignore in runsuite_wrapper.pl, but CDash takes direct test results.  This issue covers getting CDash to use the same flaky/ignore-failure mechanism as Travis and Appveyor CI.

**Comment by derekbruening** [comment]
#2204's retry of flaky tests could be an alternative or additional step here.

**Comment by derekbruening** [comment]
The retry won't work for tests that are flaky on particular platforms, rather than being generally non-deterministic: e.g., api.static_maps_mixup_novars_FLAKY fails every time on Fedora 27.

**Comment by derekbruening** [comment]
The Fedora CDash results have been green with no emails!
http://dynamorio.org/CDash/index.php?project=DynamoRIO

**Comment by AssadHashmi** [comment]
> The Fedora CDash results have been green with no emails!
> http://dynamorio.org/CDash/index.php?project=DynamoRIO

I need to do the same for AArch64.
