### ISSUE TITLE
add ARM and AArch64 cronbuilds to the weekly build releases

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#3002]
For #1967 I set up weekly "cronbuilds" for several platforms but not for ARM or AArch64. 
 This issue covers adding such builds.

**Comment by fhahn** [comment]
Should we do that on the ARM/AArch64 builders via Jenkins?

**Comment by derekbruening** [comment]
The simplest should be to use the existing cronbuild process and cross-compile on Travis -- maybe just setting DEPLOY=yes in .travis.yml will work?  I don't remember why I didn't consider aarch when I set up #1967 or whether there's any reason that single change wouldn't work.

**Comment by vielmetti** [comment]
Hi @fhahn @derekbruening - is there some specific help that could move this item forward?
