### ISSUE TITLE
exclusive store workaround fails on some AArch64 hardware with multi-block sequences

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#3005]
Splitting from #1698 for the purpose of finding a quick workaround.

Focusing on memtrace_simple, though other tools like drmemtrace are similar:

The workaround we're currently using, which worked on the ARM hardware we tested on, of skipping the adding of a clean call before an exclusive store, is not sufficient on some AArch64 hardware.  I'm seeing spinning when adding a clean call in front of the OP_ldaxr in the 3rd block in this sequence:

```
interp: start_pc = 0x0000ffff80ba53e8
  0x0000ffff80ba53e8  a9bc7bfd   stp    %x29 %x30 %sp $0xffffffffffffffc0 -> -0x40(%sp)[16byte] %sp
  0x0000ffff80ba53ec  52800021   movz   $0x0001 lsl $0x00 -> %w1
  0x0000ffff80ba53f0  910003fd   add    %sp $0x0000 lsl $0x00 -> %x29
  0x0000ffff80ba53f4  a90153f3   stp    %x19 %x20 -> +0x10(%sp)[16byte]
  0x0000ffff80ba53f8  d0000893   adrp   <rel> 0x0000ffff80cb7000 -> %x19
  0x0000ffff80ba53fc  f90013f5   str    %x21 -> +0x20(%sp)[8byte]
  0x0000ffff80ba5400  aa0003f5   orr    %xzr %x0 lsl $0x00 -> %x21
  0x0000ffff80ba5404  91286260   add    %x19 $0x0a18 lsl $0x00 -> %x0
  0x0000ffff80ba5408  b9003fbf   str    %wzr -> +0x3c(%x29)[4byte]
  0x0000ffff80ba540c  885ffc02   ldaxr  (%x0)[4byte] $0x1f $0x1f -> %w2
  0x0000ffff80ba5410  7100005f   subs   %w2 $0x0000 lsl $0x00 -> %wzr
  0x0000ffff80ba5414  54000061   b.ne   $0x0000ffff80ba5420
end_pc = 0x0000ffff80ba5418

interp: start_pc = 0x0000ffff80ba5418
  0x0000ffff80ba5418  88037c01   stxr   %w1 $0x1f -> (%x0)[4byte] %w3
  0x0000ffff80ba541c  35ffff83   cbnz   $0x0000ffff80ba540c %w3
end_pc = 0x0000ffff80ba5420

interp: start_pc = 0x0000ffff80ba540c
  0x0000ffff80ba540c  885ffc02   ldaxr  (%x0)[4byte] $0x1f $0x1f -> %w2
  0x0000ffff80ba5410  7100005f   subs   %w2 $0x0000 lsl $0x00 -> %wzr
  0x0000ffff80ba5414  54000061   b.ne   $0x0000ffff80ba5420
end_pc = 0x0000ffff80ba5418
```

**Comment by derekbruening** [comment]
I see the spinning on a TX1 just running hello,world:

```
bin64/drrun -c api/bin/libmemtrace_simple.so -- suite/tests/bin/simple_app
```

**Comment by derekbruening** [comment]
Just adding "insr_get_opcode(instr) != OP_ldaxr" to the existing
"!instr_is_exclusive_store(instr)" and avoiding a clean call is not
sufficient: it still loops (crashes after filling up trace buffer: no
matter how large) -- so the mem instru is problematic too and not just the
large # of memrefs in the clean call.

**Comment by egrimley** [comment]
What about with  `-unsafe_build_ldstex`?

**Comment by derekbruening** [comment]
That does work: `bin64/drrun -unsafe_build_ldstex -c api/bin/libmemtrace_simple.so -- suite/tests/bin/simple_app`

**Comment by fhahn** [comment]
I was planning to setup the TX1 to run the tests with `-unsafe_build_ldstex ` for now, but did not get around to it yet. A few test still fail even with  `-unsafe_build_ldstex `, but I think it would be a good start to have some testing for it.

**Comment by Desperado1985** [comment]
Greetings,

I seem to have this problem with the recent DynamoRIO-AArch64-Linux-7.91.18342 build for an application with 150+ threads and drcov. Adding the -unsafe_build_ldstex flag to the drrun parameters doesn't help, in fact it has problems reading the -root parameter if I add it before that. Do you have any further recommendations? Regards.

**Comment by derekbruening** [comment]
> I seem to have this problem with the recent DynamoRIO-AArch64-Linux-7.91.18342 build for an application with 150+ threads and drcov. Adding the -unsafe_build_ldstex flag to the drrun parameters doesn't help

If it doesn't help, maybe that's not what you're hitting?  Did you verify in the log file or gdb that you are hitting a ldrex..strex infinite loop?

> in fact it has problems reading the -root parameter if I add it before that.

That is because it cannot go there.  The drrun usage message explains the two types of options.

**Comment by Desperado1985** [comment]
Which log do you need? How do I enable it? Which log level? For which patterns should I look in the logfile?

**Comment by derekbruening** [comment]
> Which log do you need? How do I enable it? Which log level? For which patterns should I look in the logfile?

See https://github.com/DynamoRIO/dynamorio/wiki/Logfiles

What I would do, if the app run is short enough, is run `-loglevel 4` and wait long enough for the hang to happen (that verbosity will slow it down substantially though).  Then I would attach gdb to see where the threads are, looking up each code cache pc in the logfiles to see its surrounding code and whether it's in a ldrex..strex loop.  If no thread in is the cache and they're all at syscalls (futex or sthg), the hang is almost certainly not related to exclusive stores.

**Comment by Desperado17** [comment]
Hello,

attaching gdb is not possible at the end because system is too busy. 

Going beyond loglevel 2 will make the system spend forever somewhere after a log message of type
<(1+x) Handling our fauilt in a TRY at 0x..... >

**Comment by derekbruening** [comment]
> Edit 3: Ok, it still seems to be doing something...but it has bursts where it spends large amounts of time in sched_yield. Might be correlated with the growing numbers of threads during upstart.

The callstacks would be needed to know what it is doing.  We are routinely running large apps with 1000 threads on x86 so a few hundred is not an inherent problem.

**Comment by Desperado17** [comment]
Ok, attaching gdb might work right now. What do you need? One thread apply all bt full?

**Comment by derekbruening** [comment]
When you see no progress (un-changing callstacks or a cycle I suppose) yes for all threads would be best.

**Comment by Desperado17** [comment]
If I run it without debug/loglevel it seems like the whole system is suddenly under full load. I cannot even top anymore.

**Comment by Desperado17** [comment]
Ok, I managed to make a perf trace. It seems that the library work itself to death inside the output_trace method, more specifically in a syscall of type sys_sched_yield.

Will this help?

**Comment by derekbruening** [comment]
> Ok, I managed to make a perf trace. It seems that the library work itself to death inside the output_trace method, more specifically in a syscall of type sys_sched_yield.
> 
> Will this help?

Are you sure you had the right symbols?  `output_trace` is never executed, unless you pass one of the -tracedump_* options.

**Comment by Desperado17** [comment]
I used the one from the debug folder of the lib64 folder of release_7.91.18342. 
eu-unstrip libdynamorio.so libdynamorio.so.debug
( I use Hotspot which has problems with debug symbols separate from binaries)
If you can provide me a correct unstripped libdynamorio.so for this release, I'd be grateful.
I tried again with perf top. It sees large cpu footprints in
d_r_read_lock and dynamorio_syscall.

**Comment by Desperado17** [comment]
Should we discuss this here further or should I create a new ticket?

**Comment by derekbruening** [comment]
I have seen no evidence that you are hitting the problem this issue concerns, which as already stated involves a hang **in application code in the code cache**.  So yes please move further questions elsewhere.  And please provide more information: if you think you are hitting some kind of deadlock in DR code, callstacks of **all** of the threads involved will be needed, captured **multiple times** if there's a loop, to prove repeated state and no progress.  All the usual questions apply as well: do smaller apps run fine on this hardware; can this app be minimized; does this happen without drcov; etc.

**Comment by derekbruening** [comment]
536cbd0a2f895294b9efa08d5bc35129f9bc2b8b enabled conversion to compare-and-swap by default which should solve this (modulo issues with app behavior fidelity with CAS).
