### ISSUE TITLE
Unable to instrument executable loaded as DLL

### ISSUE THREAD

**Issue by mxmssh** [DynamoRIO/dynamorio#3015]
Hi there,

My application dynamically loads executable as a DLL (I just changed one bit in the PE header to let Windows load this exe as DLL) and then calls some exported functions from this executable (LoadLibrary/GetProcAddress). It works fine, I can call functionality from this exe. I want to instrument this executable (the moment it is loaded using drmgr_register_module_load_event and then bbls). However, it seems that DR doesn't properly handle such situation. 

I know that Windows is not high priority now but have you guys ever seen such situations before ? If yes, how can I handle it ?

Environment: Windows 7 x64, latest DynamoRIO release build, 32 bit executable, 32 bit DLL.

**Comment by derekbruening** [comment]
I don't see why DR wouldn't handle it: we've seen plenty of weird things with apps doing partial PE maps, etc.  Without details on "DR doesn't properly handle" it's hard to say more.

**Comment by mxmssh** [comment]
So, basically, I am trying to do fuzzing using WinAFL. I have an executable that loads another executable and calls specific function with potentially malformed parameters. WinAFL relies on DynamoRIO functionality to provide coverage back into fuzzer. 
The author of WinAFL uses `drmgr_register_module_load_event(event_module_load)` to instrument module loading event. 
The [event_module_load](https://github.com/ivanfratric/winafl/blob/be18e8cbd6f63d24e73f08614ea36fae9a26aa1b/winafl.c#L561) functions starts with the following code:

```
static void
event_module_load(void *drcontext, const module_data_t *info, bool loaded) {
    const char *module_name = info->names.exe_name;
    app_pc to_wrap = 0;

    if (module_name == NULL) {
        // In case exe_name is not defined, we will fall back on the preferred name.
        module_name = dr_module_preferred_name(info);
    }
```

It works fine for all modules except dynamically loaded executable. I don't see the name of executable in the module_name. So, WinAFL doesn't instrument it and can't provide coverage.

It is strange because I used to use DR for malware analysis and it usually handles fine such situtations. It might be a bug in WinAFL.

**Comment by mxmssh** [comment]
Ok, looks like my mistake. I renamed my executable from XXX.exe into XXX_lib.dll and tried to instrument XXX_lib.dll. However, ```info->names.exe_name == NULL``` and ```dr_module_preferred_name(info)``` returns XXX.exe.
