### ISSUE TITLE
Crash disassembling

### ISSUE THREAD

**Issue by 1982Dmitry** [DynamoRIO/dynamorio#3039]
I've the following code, it calls "clean_code' for each instruction, but it crashes.
I don't understamd why

https://pastebin.com/q24LiDmv

**Comment by 1982Dmitry** [comment]
outout:
https://pastebin.com/7JCGGMJ3

**Comment by derekbruening** [comment]
IR objects like instr_t are not persistent: you have to clone it if you want a copy to stick around after encoding.

**Comment by 1982Dmitry** [comment]
try same, but with `instr_clone` before passing instr to `dr_inster_clean_call`:

`   instr_t* inst_cp = instr_clone(drcontext, inst);

   dr_insert_clean_call(drcontext, bb, inst, clean_call, false, 1, opnd_create_instr(inst_cp));`

but getting error:
` DynamoRIO usage error : instrlist_clone: operand instr not in instrlist>`
