### ISSUE TITLE
Record key function traces in drcachesim

### ISSUE THREAD

**Issue by Louis-Ye** [DynamoRIO/dynamorio#3048]
Add mechanism to collect traces for specified/key functions in drcachesim. The traces should integrate with memory accesses traces.
The new traces should include following information for each function:
1. function invocation arguments
2. function return address
3. function return value

**Comment by derekbruening** [comment]
Pasting in some design comments from #3057:

I think we want to be able to dynamically specify which functions to record: perhaps via a config file eventually, though we could start with a runtime option. We just need the name and number of args if all we support is recording pointer-sized arg values. You could imagine sthg like:

```
-record_function malloc 1 -record_function realloc 2
```

If we decide heap allocation is very common and we want to have built-in support, I would say it should be under a separate option like -record_function_malloc or -record_heap_allocs or sthg.

We need to get a function ID of some kind in there for the markers to point at: with the options it's not clear the best way.  Have the user specify and complain on duplicates??  So there's an ID and number of args?

```
-record_function malloc 42 1
```

Alternatively, we could expose an interface to write metadata into the trace and structure all of this as a separate client from the memory address tracer.

**Comment by derekbruening** [comment]
We may want the callstack rather than just the return address, to handle functions whose immediate caller may not be useful if it is often invoked through utility function layers.
