### ISSUE TITLE
Issues trying to perform standard unix system installation from source

### ISSUE THREAD

**Issue by zougloub** [DynamoRIO/dynamorio#3066]
While trying to install DR on my system I noticed the following issues, that prevent a "clean" installation on UNIX systems:

- Sandbox violations linked to usage of ``file(WRITE`` and ``file(MAKE_DIRECTORY`` that don't consider the ``DESTDIR`` environment variable (easy fix is to prepend ``\$ENV{DESTDIR}`` to ``\${CMAKE_INSTALL_PREFIX}``).  
A package manager would first stage the installation in a temporary directory, then perform an inventory, then package or install to the final destination.  
The installation shouldn't directly touch that final destination.
- ``INSTALL_BIN`` and ``INSTALL_LIB`` are not configurable (``/usr/bin`` is kind of the standard)
- README, License.txt and ACKNOWLEDGEMENTS go to ``${CMAKE_INSTALL_PREFIX}`` directly, should be configurable to go to ``${CMAKE_INSTALL_PREFIX}/share/docs/`` for example
- cmake files go to ``${CMAKE_INSTALL_PREFIX}/usr/cmake`` not ``${CMAKE_INSTALL_PREFIX}/usr/lib*/cmake``
- libraries wanting to go to ``${CMAKE_INSTALL_PREFIX}/usr/lib64/release/``, this is kind of useless
- includes go to ``${CMAKE_INSTALL_PREFIX}/usr/include`` and given the presence of the ``annotations`` subfolder they should probably go to ``${CMAKE_INSTALL_PREFIX}/usr/include/DynamoRIO``, with cmake exports handling the include path
- tools get installed in ``${CMAKE_INSTALL_PREFIX}/tools/`` in bin/lib subfolders, this doesn't seem to be configurable

**Comment by derekbruening** [comment]
If you have a patch to improve installation we are happy to review a pull request
