### ISSUE TITLE
Windows 10 1803 support?

### ISSUE THREAD

**Issue by woodruffw** [DynamoRIO/dynamorio#3090]
Would work on Windows 1803 support be welcome? I'm not a Windows kernel person, but I should be able to mostly follow the work in #2698 and the updated syscall table here: https://github.com/tinysec/windows-syscall-table/blob/master/10.0.17134-sp0-windows-10-rs4-1803/ssdt.md.

I'll probably need some help with `NtAllocateVirtualMemoryEx`, since that probably needs to be intercepted like `NtAllocateVirtualMemory` currently is.

**Comment by derekbruening** [comment]
> Would work on Windows 1803 support be welcome?

Yes, absolutely!  Thank you for offering.

Xref https://github.com/DynamoRIO/drmemory/issues/2102 for Dr. Memory.

**Comment by woodruffw** [comment]
Thanks for the reference! I'll have some initial work on this done by tomorrow.
