### ISSUE TITLE
Directing critical errors to stdout

### ISSUE THREAD

**Issue by yoava333** [DynamoRIO/dynamorio#3095]
Version: DynamoRIO 7.0.0-RC1
Platform: Windows 10 x64 (build 1803)

I'm using DynamoRIO there are a few applications that I'm running that allocate a lot of memory, enough to cause DynamoRIO to fail to allocate. The problem is that on Windows DynamoRIO creates a message box that doesn't belong to the executing process to report this issue & waits until it's acknowledged.
Is there a standard switch / API call that make so it will not create the messagebox or redirect it to console?

**Comment by derekbruening** [comment]
See the notification options `-msgbox_mask` and `-stderr_mask`: http://dynamorio.org/docs/using.html#op_msgbox_mask
