### ISSUE TITLE
Drrun: drrun.exe was crashed by the unintersted exception in the target application

### ISSUE THREAD

**Issue by mingfure** [DynamoRIO/dynamorio#3110]
When I debug the target x86_64 application vmx.exe in WinDbg, exception c000096 will be detected and the vmx.exe will catch it. And the target will run normally.
But when I use the `DynamoRIO-Windows-7.0.0-RC1`  (actually I need to use the drrun.exe before winafl. ) on Windows 10 with following command:
 ```
e:\winafl\DynamoRIO\bin64\drrun.exe -c winafl.dll -target_module vmware-vmx.exe -target_offset 0x1920 -fuzz_iterations 10 -nargs 2 --  vmware-vmx.exe in\test.txt
```
I can not get the expected result. Beacause drrun.exe will crashed by the same exception in the target. 
here is the log:
```
Module loaded, dynamorio.dll
...
Module loaded, rasadhlp.dll
Module loaded, fwpuclnt.dll
In OpenFileW, reading D:\VMware\VMware Workstation\\messages\vmware.vmsg
Exception caught: c0000096
crashed
```
So, how could I avoid this? How to make the drrun.exe run normally when it meets these uninterested exceptions?

**Comment by derekbruening** [comment]
What was the resolution?  We'd prefer an explanation on the record in case someone else hits something similar.

**Comment by mingfure** [comment]
Well, I havn't solve this problem actually, but when I comment out this line of code, my target could run normally alongside Winafl.

**Comment by derekbruening** [comment]
What line of code?  Why are you deleting the text from the original post?  This is not helpful.

Normally DR passes exceptions on to the app just fine, including 0xc0000096 (STATUS_PRIVILEGED_INSTRUCTION).  We have regression tests for this (e.g., https://github.com/DynamoRIO/dynamorio/blob/master/suite/tests/common/decode-bad.c#L187) and it works fine in those tests.  So there is something unusual here.

**Comment by mingfure** [comment]
Yes, you're right. It was caused by the unsuitable exception handling in WinAFL. 
winafl.c:
```
**drmgr_register_exception_event**(onexception);
***
bool onexception(){
if((exception_code == EXCEPTION_PRIV_INSTRUCTION)|| // comment here
    (exception_code == ***)||
    ***) {
           crashed;
```
So I change the exception handling in Winafl, and it's not an issue of Drrun in fact. 
Thanks a lot!

**Comment by derekbruening** [comment]
Thank you for the update.
