### ISSUE TITLE
tool.drcachesim.missfile-config-file failing on Appveyor

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#3136]
https://ci.appveyor.com/project/DynamoRIO/dynamorio/build/1.0.2507

tool.drcachesim.missfile-config-file failed on Appveyor.  c3d5b47b0fc45aac8184cca9f7c795b8bf6e22a9 was just committed which changes the missfile behavior -- yet it doesn't seem like it could cause this failure as it doesn't change the simulator output, and this test passed in its own testing.

**Comment by derekbruening** [comment]
Happened again: https://ci.appveyor.com/project/DynamoRIO/dynamorio/build/1.0.2537

**Comment by kharbutli** [comment]
Fixed in [6c773a1](https://github.com/DynamoRIO/dynamorio/commit/6c773a1cefa04854888e3fe1b45f3b3fdd5a5e93).
