### ISSUE TITLE
instr_operands_valid missing from dr_ir_instr.h

### ISSUE THREAD

**Issue by byron-hawkins** [DynamoRIO/dynamorio#3158]
Building the master branch today, the API function `instr_operands_valid()` that is declared in `core/arch/instr.h` is no longer exported to `<build>/include/dr_ir_instr.h`. My build is configured like this:

    cmake -G Ninja -DDEBUG=ON ../src

The `DR_API` tag is still present on the missing function, so it looks like some other change in the preprocessing has somehow alienated this function. A simple workaround is to checkout from tag `release_7_0_0_rc1`.

**Comment by derekbruening** [comment]
It looks like clang-format shifted it over and genapi.pl has ^DR_API in its regex:

```
#ifdef AVOID_API_EXPORT
INSTR_INLINE /* hot internally */
#endif
    DR_API
    /** Returns true iff \p instr's operands are up to date. */
    bool
    instr_operands_valid(instr_t *instr);
```
