### ISSUE TITLE
Use C++11 definitions for [u]int64, when compiling on 64 bit 

### ISSUE THREAD

**Issue by mtrofin** [DynamoRIO/dynamorio#3170]
Currently, uint64 is defined as unsigned long int. That type is 64 bit if we compile with -m64, however, it's not the same type as unsigned long long: the former is "guaranteed to be at least 32 bits" (and happens to be 64 if -m64), the latter is 64 bits.

This causes linking problems in 64-bit projects linking a DR library exposing a function typed with uint64, if also the importing projects uses -DDR_DO_NOT_DEFINE_uint64: the importing project will compile the DR headers with their own (presumably, unsigned long long) uint64, and the mangled name of the import will differ from the mangled name of the definition.

**Comment by derekbruening** [comment]
I think using "unsigned long" is the more common way to define a 64-bit type for an LP64 compiler, because it's in C99's stdint.h:

```
#if __WORDSIZE == 64
typedef unsigned long int       uint64_t;
#else
__extension__
typedef unsigned long long int  uint64_t;
#endif
```
