### ISSUE TITLE
Resolve hard-coded libdynamorio name in memquery.

### ISSUE THREAD

**Issue by hgreving2304** [DynamoRIO/dynamorio#3201]
At least in Linux.

Currently, the library name is hard-coded as DYNAMORIO_LIBRARY_NAME and is used in compares in memquery. If the actual name diverts from this, the loader bails / takes the wrong path (i.e. falsely detecting app maps overlap). 

Support drrun -use_dll ./randomname.so -- <app>
and drrun -use_dll ./libdynamorio.so -- <app> w/ libdynamorio.so being symlink to randomname.so.

**Comment by derekbruening** [comment]
Windows still has a hardcoded DYNAMORIO_LIBRARY_NAME, and the old preinject still has a hardcoded name, but let's open a separate issue if it becomes a priority to tackle those.
