### ISSUE TITLE
cmake CMP0026, eliminate the use of LOCATION

### ISSUE THREAD

**Issue by hgreving2304** [DynamoRIO/dynamorio#3218]
LOCATION is obsolete. We need to re-factor the makefiles such that there is no use of LOCATION. The target location in future cmake versions will be supported in generator expressions $<TARGET_FILE:target>, etc.

The different systems require different support, e.g. location_suffix in Windows (multi-config generator).

**Comment by derekbruening** [comment]
Isn't this a duplicate of #1557?

**Comment by hgreving2304** [comment]
Duplicate of #1557

**Comment by hgreving2304** [comment]
Forgot there's one for each CMP already.
I am going to submit a pull request with an incremental patch for i#1557,
but it doesn't eliminate it yet. I ran it on my own Windows machine and it
seems to work AFAI can tell. I'd like to run it on AppVeyor
I am going to look at i#2868 next to not only spend time on cmake
