### ISSUE TITLE
hook_vsyscall fails on x86

### ISSUE THREAD

**Issue by TomSie** [DynamoRIO/dynamorio#3248]
Hello everybody,
I am trying to run **x86** dynamorio on a  Ubuntu 18.04.1 LTS (4.15.0-29).

My problem is that "hook_vsyscall" segfaults at 

"memcpy(pc, vsyscall_sysenter_return_pc, VSYS_DISPLACED_LEN);"

This seems to be due to the fact that the vdso.so on my system is larger than one PAGE_SIZE. Even vsyscall_sysenter_return_pc seems to be 4189, and therefore larger than one PAGE_SIZE (which is 4096).

This turns out to be a problem as only the first PAGE_SIZE of the vdso.so  is set as writeable:

"set_protection(vsyscall_page_start, PAGE_SIZE, prot|MEMPROT_WRITE);"

My suggested fix: 
instead of making one PAGE_SIZE writeable make  (vsyscall_sysenter_return_pc/PAGE_SIZE +1)*PAGE_SIZE bytes writeable.

**Comment by derekbruening** [comment]
#2945 added support for the vsyscall not being on the first page of a multi-page vdso.  vsyscall_page_start is *not* the vdso base: it is the base of the page containing the vsyscall.  A vsyscall code sequence that spans two pages may be an issue, but the more important thing here is that vsyscall_sysenter_return_pc is an absolute pc, not a size: if it has a value of just 4189 that's a problem.  How did it get set to an invalid address?

**Comment by TomSie** [comment]
Hey,
thank you for your quick reply. Maybe the information I provided was a little inprecise.

Before the call to set_protection the memory map of my process looks like this:
...
f7f10000-f7f13000 r--p 00000000 00:00 0                                  [vvar]
f7f13000-f7f15000 r-xp 00000000 00:00 0                                  [vdso]
f7f15000-f7f3b000 r-xp 00000000 fd:00 26476996                           /lib/i386-linux-gnu/ld-2.27.so
...

after the call to set_protection it looks like this:
...
f7f10000-f7f13000 r--p 00000000 00:00 0                                  [vvar]
f7f13000-f7f14000 rwxp 00000000 00:00 0                                  [vdso]
f7f14000-f7f15000 r-xp 00000000 00:00 0                                  [vdso]
f7f15000-f7f3b000 r-xp 00000000 fd:00 26476996                           /lib/i386-linux-gnu/ld-2.27.so
...

As you can see, only the first PAGE_SIZE (4096) bytes are made writable.

Some instructions later, when the "memcpy(pc, vsyscall_sysenter_return_pc, VSYS_DISPLACED_LEN);" call is made, my program segfaults as it tries to write to 0xf7f1405d - which is in the non writeable part of the vdso.

Therefore the patch could be (sorry for my mistake in the original bug report):
instead of making one PAGE_SIZE writeable, make (((vsyscall_sysenter_return_pc-vsyscall_page_start)/PAGE_SIZE) +1)*PAGE_SIZE bytes writeable.

**Comment by derekbruening** [comment]
It does seem like the current code does not correctly handle a vsyscall sequence that crosses a page boundary (though the fix should limit to the vdso bounds in case there is no further vdso page).  Is your vsyscall code at the end of the f7f13000 page and it spills over onto f7f14000?  Could you disassemble the dozen instructions from `vsyscall_syscall_end_pc`?

**Comment by TomSie** [comment]
Hey derek,
 0xf7f1405d-0xf7f13000 = 0x105D. I attached a screenshot of my vdso.so at offset 0x105D. Imho it looks like the correct address.

![image](https://user-images.githubusercontent.com/16607413/48119621-07cead80-e270-11e8-9e68-d598a94e38a0.png)


Furthermore, I attached a screenshot of the page boundary (offset 0x1000).

Where is vsyscall_syscall_end_pc?
![image](https://user-images.githubusercontent.com/16607413/48119618-04d3bd00-e270-11e8-997e-f7eaef07547a.png)

**Comment by derekbruening** [comment]
So 3 things don't add up:

1) For int 80 there's no need to hook the vsyscall code: that's only needed for sysenter.

2) I don't see any page crossing: if the vsyscall code is entirely on the 2nd page why did it make the 1st page writable?

3) Why is `vsyscall_sysenter_return_pc` pointing at offset 0x105D which is the nops between functions?

`vsyscall_syscall_end_pc` is a global variable in DR that points to the address after the system call instruction in the vsyscall code sequence.  What is its value?  And who triggered the vsyscall hook: that should only happen upon seeing sysenter.  There must be a sysenter instruction on the 1st page of the vdso somewhere?  But if so, why is vsyscall_sysenter_return_pc on the 2nd page.

**Comment by TomSie** [comment]
Hello,
I tried to create a step-by-step guide on how you could reproduce this issue on your machine.
While doing so, I discovered that while the issue is 100% reproducable in the dynamorio version I used (git checkout from 2018-03-13), it is NOT REPRODUCABLE in the current git version.

So it looks like you guys already fixed it. Sorry for wasting your time!

Best regards

**Comment by derekbruening** [comment]
Sound like you did not have the aforementioned #2945 fix 60203db0d70b24157ad03032ed972e3dbbdf3477.
