### ISSUE TITLE
drwrap_wrap() is missing the function call

### ISSUE THREAD

**Issue by expend20** [DynamoRIO/dynamorio#3281]
Hi, 
I had found some issue and I think it's a bug. I'm trying to instrument this function in the binary:
```
.text:00401140 ; int __usercall ParseData@<eax>(char *buf@<ecx>, unsigned int i)
.text:00401140 ?ParseData@@YAHPADI@Z proc near         ; CODE XREF: _main+11F↓p
.text:00401140
.text:00401140 var_C           = std::invalid_argument ptr -0Ch
.text:00401140 i               = dword ptr  8
.text:00401140
.text:00401140 buf = ecx
.text:00401140                 push    ebp
.text:00401141                 mov     ebp, esp
...
```
With following code in the client:
```
static
void module_load_event(void *drcontext, const module_data_t *mod, bool loaded)
{
    static int isSet = 0;

    if (!isSet) {
        rwrap_wrap((app_pc)((size_t)mod->handle + 0x1140), wrap_pre, wrap_post);
        isSet = 1;
    }

}
```
But when I run it, `drrun.exe -c client.dll -- baby-fuzz2.exe 123.txt` the `wrap_pre` and `wrap_pre` functions are never called, but the function `ParseData` is actually called. The sources of the client are [here](https://pastebin.com/ky1hyx7H) (and binary is [here](https://github.com/expend20/expend20.github.io/blob/master/tmp/baby-fuzz2.exe) also) and it's almost the same as in the [manual](http://dynamorio.org/docs/samples/wrap.c).

Btw, If I will instrument the nearest function at 0x401200 offset (it's `main()` function), it will work just fine, without any issues. Why this is happening?

**Comment by derekbruening** [comment]
Are you sure you're wrapping the executable and not some library?  Your code snippet wraps the 1st module without checking what it is.

**Comment by expend20** [comment]
Yep, I'm pretty sure, checked it in a debugger, the first module seems always the main application. But if you are insisting, I had double check it with code:
```
static
void module_load_event(void *drcontext, const module_data_t *mod, bool loaded)
{

    if (!strcmp(mod->names.file_name, "baby-fuzz2.exe")) {
        if (!drwrap_wrap((app_pc)((size_t)mod->handle + 0x1140), wrap_pre, wrap_post)) {
            dr_printf("drwrap_wrap() returns fail\n");
        }
        else {   
            dr_printf("drwrap_wrap() returns ok\n");
        }
    }
}
```
The problem is the same. 
Let me remind you, that if I will choose offset = 0x1200 it will work well. The only visible difference between 0x1140 and 0x1200 is call convention.

**Comment by expend20** [comment]
Any suggestions would be great, this problem is crucial to me because it affects other places of more complex code.

**Comment by derekbruening** [comment]
drwrap checks for the target callee pc on every instruction in every basic block, so it does not seem possible for the target to be executed under DR and not have its pre-wrap function called.  How do you know the target was executed from the precise pc passed to drwrap when run under DR?  I would suggest running debug build with `-loglevel 3` and confirming that the target function is in fact reached.

**Comment by expend20** [comment]
@derekbruening thank you. I compiled debug build, just as you suggested and used dr_log to deliver debug messages, it works fine! Previously I had used __debugbreak() & windbg to verify that wrapped callbacks are called. It seem there are a lot debugging issues, and you can't use windbg and even OutputDebugString(). Btw why OutputDebugString() is not working in client's dll?

**Comment by derekbruening** [comment]
OutputDebugString inside a debugger causes DR to lose control: #2389
