### ISSUE TITLE
link error: duplicate symbol: memcpy

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#3315]
The private version of memcpy and other routines in x86_shared.asm are linked into drfrontendlib which is statically linked into various "regular" applications.  Some users have reported duplicate symbol errors with some toolchains: details will be added here.  We can likely solve by adding `WEAK(memcpy)`, etc. into x86_shared.asm.

**Comment by derekbruening** [comment]
@hgreving2304 -- I remember you hit this somewhere?  Could you supply details on what platform/toolchain it was?

**Comment by hgreving2304** [comment]
@derekbruening , I think that was in Google3 when the -nostdlib compiler (driver, not linker) switch was missing.

**Comment by derekbruening** [comment]
This is the plan:

Core DR's copies of memset and memcpy were placed into drhelper for
#1504, to avoid glibc-versioned symbols in drrun and other shipped
binaries.  They are linked into the static drfrontendlib and
drinjectlib libraries.  They are also in core DR when built as a
static library.  In these static library cases they can conflict with
symbols of the same name elsewhere in the linking application.

To solve this, we first separate memset and memcpy from drhelper into
their own library, drmemfuncs.  We simply avoid linking it into static
core DR, and into drdecode.  For static core DR we assume that
whatever versions the application or glibc provides will be
re-entrant.

We can't avoid linking it into drfrontendlib and drinjectlib (we hit
the glibc versioning problem), but we reduce the chance of conflicts
with these libraries by marking memset and memcpy as weak.

**Comment by derekbruening** [comment]
There is a downside to having static DR use glibc memcpy.  It lets sanitizers or other interceptors override
DR's memcpy.  However, we already have interoperability concerns with sanitizers, so I was assuming we could live with that.

**Comment by TACIXAT** [comment]
Running into this issue on Windows.
