### ISSUE TITLE
linux.syscall_pwait failing on Android.

### ISSUE THREAD

**Issue by hgreving2304** [DynamoRIO/dynamorio#3336]
Test output was 

handlers for signals: 10, 12
signal blocked: 10
Testing epoll_pwait
signal received: 12
signal received: 10
Testing pselect
signal received: 12
Testing ppoll
signal received: 12
Testing epoll_pwait failure
Testing pselect failure
Testing ppoll failure

Seems that the SIGUSR1 signals were not received.

http://dynamorio.org/CDash/testDetails.php?test=584315&build=40410

**Comment by derekbruening** [comment]
I discovered one reason SIGUSR1 may not be delivered through code inspection:
Looking at the code for handle_pre_extended_syscall_sigmasks(): it fails to call check_signals_pending() so it won't deliver a pending signal like handle_sigprocmask() will.
That call should be added.  However, it's not clear why that would be Android-specific.
