### ISSUE TITLE
Handle nested p* system calls if necessary

### ISSUE THREAD

**Issue by hgreving2304** [DynamoRIO/dynamorio#3344]
We are currently not able to handle - and won't be even after fix for #3336 - nested calls of ppoll, pselect6, epoll_pwait, e.g. if the app makes such a system call in the signal handler and the kernel supports it.

The future fix for #3336 will have to save the app's sigmask pre-syscall since we're not executing everything atomically. Nesting will not be supported.

**Comment by hgreving2304** [comment]
Closing manually, github didn't pick up ("original commit message" problem..)

**Comment by derekbruening** [comment]
> Closing manually, github didn't pick up ("original commit message" problem..)

No, that is not the problem: that cannot have a negative effect, it can only close additional issues if there's a "Fixes #NNN" in the PR original description.

The problem is that your commit message syntax is incorrect: each issue needs a "Fixes" in front of it.

**Comment by derekbruening** [comment]
And needs to be on its own line.  See the DR wiki or the Github docs on this.
