### ISSUE TITLE
How to write a CMakeLists.txt correctly?

### ISSUE THREAD

**Issue by lerendo** [DynamoRIO/dynamorio#3367]
Hello! I wrote a client based on inscount.cpp (with same dependencies). Could you help create CMakeLists.txt fir this? 
.
├── build
└── myclient
    ├── CMakeLists.txt
    └── record_bbs.cpp
CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.2)

add_library(myclient SHARED record_bbs.cpp)
find_package(DynamoRIO)
if (NOT DynamoRIO_FOUND)
  message(FATAL_ERROR "DynamoRIO package required to build")
endif(NOT DynamoRIO_FOUND)
configure_DynamoRIO_client(myclient)
```

> export DYNAMORIO_HOME=/root/Desktop/dynamorio/build/
> cmake -DDynamoRIO_DIR=$DYNAMORIO_HOME/cmake ../myclient
> make

I got:
`myclient/record_bbs.cpp:49:19: fatal error: drmgr.h: No such file or directory`

**Comment by derekbruening** [comment]
Please use the users list https://groups.google.com/forum/#!forum/DynamoRIO-Users for questions.  The issue tracker is for filing bugs.
