### ISSUE TITLE
client.annotation-concurrency.prof-pcs.thread-private failing on Travis

### ISSUE THREAD

**Issue by hgreving2304** [DynamoRIO/dynamorio#3369]
edb2eed6b74646dcf927 has introduced flakiness to test:

```
<Application /home/travis/build/DynamoRIO/dynamorio/build_debug-internal-64/suite/tests/bin/client.annotation-concurrency (23003).  Internal Error: DynamoRIO debug check failure: /home/travis/build/DynamoRIO/dynamorio/core/unix/signal.c:5248 dcontext == NULL || dcontext == GLOBAL_DCONTEXT || frame->uc.uc_stack.ss_sp == ((thread_sig_info_t *)dcontext->signal_field)->sigstack.ss_sp
(Error occurred @3403 frags)
```

Seems to be related to the new TLS magic check.

**Comment by hgreving2304** [comment]
xref #1968

**Comment by derekbruening** [comment]
This is failing on Travis in both code_api|client.annotation-concurrency.prof-pcs and 	code_api|client.annotation-concurrency.prof-pcs.thread-private in my PR: https://github.com/DynamoRIO/dynamorio/pull/3370, https://travis-ci.com/DynamoRIO/dynamorio/jobs/176239802.  So it seems to not be rarely occurring at all.

**Comment by hgreving2304** [comment]
Looks like there is a small window in signal_thread_exit where the alt stack is switched back, but before the thread's sig_info altstack pointer is destroyed. If an asynch signal hits in that window, in this case an alarm signal, the pointers mismatch and the assertion fires.
