### ISSUE TITLE
tool.drcachesim.missfile-config-file failing on AArch64 CDash

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#3486]
Failed here, and IIRC it's failed multiple times before (though did not search CDash history):
http://dynamorio.org/CDash/testDetails.php?test=646798&build=41906

**Comment by derekbruening** [comment]
Friendly ping.  This is still failing on a regular basis.  E.g.:
http://dynamorio.org/CDash/testDetails.php?test=673546&build=43198

**Comment by egrimley** [comment]
It looks as though the template is expecting miss rates to be printed, but the code only prints them if they are non-zero.
