### ISSUE TITLE
vinserti128 has the wrong operand size in decoder/encoder.

### ISSUE THREAD

**Issue by hgreving2304** [DynamoRIO/dynamorio#3517]
As suggested in #3513 

Should be

  {OP_vinserti128,0x663a3818,"vinserti128",Vqq,xx,Hqq,Wqq,Ib,mrm|vex|reqp,x,END_LIST},/*57*/
  {OP_vinserti128,0x663a3818,"vinserti128",Vqq,xx,Hqq,Wdq,Ib,mrm|vex|reqp,x,END_LIST},/*57*/

The instructions's operand is 16 bytes.

**Comment by hgreving2304** [comment]
Filed on behalf of @khuey , thanks for finding the bug.

**Comment by derekbruening** [comment]
I think what you wrote as "Should be" is the buggy one.

**Comment by khuey** [comment]
Did you open this to have an issue on file for a PR or was there some other motivation for it?

Wondering for next time ...

**Comment by hgreving2304** [comment]
For record, tracking and commit message.
Thanks again for the fix
