### ISSUE TITLE
safe_read magic unstable during detach from threaded app.

### ISSUE THREAD

**Issue by hgreving2304** [DynamoRIO/dynamorio#3535]
Following happens with a small reproducer that we produced off Google code.

1) DR is attached to app running threaded code. The app is sending PROF signals (but type of signal doesn't matter, as long as it is asynchronous and process-directed).
2) The app starts a detach via start/stop API (with_cleanup() path).
3) Detach syncs and all threads go native. At this point, the thread's TLS (DynamoRIO's) has been removed.
4) Main thread is not done cleaning up, signal handlers are still DR's.
5) PROF signal comes in, child thread receives it. Signal handler calls safe_read_tls_magic().
<=>
6) Corner case: main thread removes signal handlers and restores the app's handlers.
7) safe_read_tls_magic() segfaults because no TLS.
8) SIGSEGV is delivered to app.

**Comment by hgreving2304** [comment]
Still verifying if the SIGSEGV was really caused by a safe_read_tls_magic in the signal handler, or from somewhere else..

**Comment by hgreving2304** [comment]
xref #26

**Comment by derekbruening** [comment]
I am hitting this while adding signal mask testing to the new api.detach_signal test.  The mask testing distinguishes the app handler from DR's handler b/c DR's blocks more signals.
