### ISSUE TITLE
Aggressive inlining breaks static detach

### ISSUE THREAD

**Issue by Carrotman42** [DynamoRIO/dynamorio#3549]
For static detach, we decide when to stop interpretting and start running code natively based on whether the App PC the next basic block to run is in a static set of PCs:

https://github.com/DynamoRIO/dynamorio/blob/ff837d4f64c0dfb0fab73d65d8884941dc9f4bae/core/dispatch.c#L249-L276

Unfortunately, when DR is compiled statically and link-time-optimizations are enabled, the application is not guaranteed to  actually run that code at that location: internally we call dr_app_stop_and_cleanup_with_stats in a helper function, and in some cases it is inlined into our helper function, causing our helper to be the one who calls directly into detach_on_permanent_stack. This ends up causing self-interp and crashes when we hit a TLS action while using drcachesim.

My first thought is to disable inlining for all of the relevant stopping points.

**Comment by derekbruening** [comment]
We might want to switch from a function call where we look for a PC to instead use annotations to identify stopping points.  I will file a separate issue on that idea.
