### ISSUE TITLE
cmake -G"Visual Studio 10" .. fails on VS2013 update 5

### ISSUE THREAD

**Issue by dvfdr43** [DynamoRIO/dynamorio#3559]
I've freshly installed VS2013 update 5 and doing everything as in "How to Build" section but still getting error:

![image](https://user-images.githubusercontent.com/49196211/56440788-1cf93f00-62da-11e9-9e25-baa022621061.png)
...
`error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.`

**Comment by derekbruening** [comment]
The title says "Visual Studio 10".  Is that what you ran?  That requests VS2010.

Please show the full output, not just a narrow window.  My first reaction is that this some mis-configuration with msbuild that has nothing to do with DynamoRIO.  Are you in a VS2013 developer console?

Please supply the exact command line used, which shell it was run in, the version of CMake.

I would not recommend using msbuild.  IMHO -GNinja is the only usable command line builder on Windows.  Ninja is what our automated tests use and all developers.  If you'd like to use msbuild you are probably on your own.  We would be happy to accept a pull request to make it work if something has regressed on our side, but I don't see evidence of that here yet.

**Comment by dvfdr43** [comment]
My mistake, I was using `-G"Visual Studio 10"` from VS2013 console instead of `-G"Visual Studio 12"`

**Comment by derekbruening** [comment]
Good to hear it works now.  Thank you for the explanation.  I noticed our wiki build page had old commands listed with "Visual Studio 10" which was probably confusing.  I updated those.
