### ISSUE TITLE
Get a crashing reason of a client

### ISSUE THREAD

**Issue by dvfdr43** [DynamoRIO/dynamorio#3561]
My client crashes but don't know the reason, as I know I should use debug build of drrun.exe with -debug argument, but I don't have a debug build (building from source crashes/fails for different reasons).
Is there debug build to download?
or is there other way to get more information why a client crashes?

**Comment by derekbruening** [comment]
Please use the users list
https://groups.google.com/forum/#!forum/DynamoRIO-Users for general questions, as it will reach a wider audience of people who might have an answer, and it will reach other users who may find the information beneficial.  The issue tracker is more for specific detailed bugs.

**Comment by johnfxgalea** [comment]
I know this is more of a nit-pick, but since this is happening quite often, perhaps bumping "Obtaining Help" to the second section in the ReadMe file may help.

**Comment by derekbruening** [comment]
> I know this is more of a nit-pick, but since this is happening quite often, perhaps bumping "Obtaining Help" to the second section in the ReadMe file may help.

Hmm, that just feels too early to me... I did update http://dynamorio.org/issues.html to talk about using the users list.
