### ISSUE TITLE
Incorrect syscall numbers [using the latest build]

### ISSUE THREAD

**Issue by dvfdr43** [DynamoRIO/dynamorio#3566]
I'm using following code to get syscall number:
```
auto entry = (PBYTE)(dr_get_proc_address(ntdll_handle, function_name));
DR_ASSERT(entry != NULL);
auto syscall_number = drmgr_decode_sysnum_from_wrapper(entry);
```
After that, I'm printing syscall numbers and seems like some of them are incorrect, for example _NtWriteFile_ and _NtClose_:
![image](https://user-images.githubusercontent.com/49196211/56460176-188e5e00-638e-11e9-91f1-5f5b0f96dfe9.png)

**Comment by dvfdr43** [comment]
I guess the reason is that it's x86 ntdll

**Comment by derekbruening** [comment]
You're not showing which Windows version you're on but 0x1a0008 is the correct number for WOW64 for several recent win10 versions:
https://github.com/DynamoRIO/drmemory/blob/master/drsyscall/drsyscall_numx.h#L2111

So it looks like you are disassembling a different library than your client is looking at.

**Comment by derekbruening** [comment]
I messed up the number: all the w^x cross-refs here should go to #3556
