### ISSUE TITLE
reg_id_t width check broken by OPSZ_NA=0

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#3567]
I noticed that 053f6b6ad69dce472b47b4cade62d192cb4cbb1c PR #3497 broke this check:
```
     * The reg_id_t type is now wider, but for x86 we ensure our values
     * all fit via an assert in d_r_arch_init().
```
That PR set OPSZ_NA to 0, which broke the check, which I believe is this:
```C
    IF_X86(ASSERT(CHECK_TRUNCATE_TYPE_byte(OPSZ_LAST)));
```

**Comment by hgreving2304** [comment]
How do I reproduce / what's broken? This assert seems to check whether the OPSZ enum fits into ushort. Nothing has changed since 053f6b6 in this regard.

**Comment by derekbruening** [comment]
> How do I reproduce / what's broken? This assert seems to check whether the OPSZ enum fits into ushort. 

Where are you seeing ushort??  It is `CHECK_TRUNCATE_TYPE_byte`!  Your commit separated the reg_id_t values from the OPSZ_ values, so now this assert does not check the reg_id_t values.  Thus it is not checking that they fit in the byte-sized instr_info_t.*_size fields.

**Comment by hgreving2304** [comment]
ushort from reg_id_t.
I see, opnd_size_t is byte.
I see now what this assertion was for. It is still checking whether all OPSZ enums fit into a byte, but it doesn't check the formerly overlapping regs anymore. The part not clear to me: do we ever put REG_ enums into byte sized fields, i.e. do we need an assertion for this? Looking at it.

**Comment by derekbruening** [comment]
Yes we do. Remember the discussion re: setting OPSZ start to 0 which
covered some of this.
