### ISSUE TITLE
TYPE_K_REG missing in disassembler.

### ISSUE THREAD

**Issue by hgreving2304** [DynamoRIO/dynamorio#3579]
When pulling in binutils tests I ran into the disassembler failing to print the new AVX-512 kmov instructions because TYPE_K_REG is missing from opnd_disassemble_noimplicit.

xref #3574

**Comment by derekbruening** [comment]
Wouldn't this just be part of #1312?  It's still in progress so we're not filing each small piece as a separate issue, right?

**Comment by derekbruening** [comment]
This is just a missing piece from #1312's very recent commit 6e24fb09a91b2d8cba07929dcbcf7bf8c06789b4
