### ISSUE TITLE
decode_table: vsqrtsd operand size wrong (AVX).

### ISSUE THREAD

**Issue by hgreving2304** [DynamoRIO/dynamorio#3582]
{OP_vsqrtsd, 0xf20f5110, "vsqrtsd", Vdq, xx, Hsd, Wsd, xx, mrm|vex, x, END_LIST}

Operand 2 of vsqrtsd is xmm. I think it should be Hdq.

**Comment by derekbruening** [comment]
Only half of that xmm register is read, though, which presumably is the reason it's OPSZ_8_of_16 (top half though...).

**Comment by derekbruening** [comment]
Agreed?  Close?  The only issue IMHO is the top vs bottom half but I think the IR does not get that precise.

**Comment by derekbruening** [comment]
Intel Vol 2D A-9 also lists it as Hsd.

**Comment by hgreving2304** [comment]
I see, I misinterpreted the field. Closing.
