### ISSUE TITLE
TEB for a callback and for a current thread

### ISSUE THREAD

**Issue by dvfdr43** [DynamoRIO/dynamorio#3589]
I've a callback function for the syscall event named syscall_hook_function(void*).
Is TEB same for syscall_hook_function and for target syscall function NtClose or NtCreateFile, etc.?

Are they run in same thread?

**Comment by dvfdr43** [comment]
just check threadID s, they are identical.

**Comment by derekbruening** [comment]
Please use the users list https://groups.google.com/forum/#!forum/DynamoRIO-Users for questions, as it will reach a wider audience of people who might have an answer, and it will reach other users who may find the information beneficial.  The issue tracker is for specific detailed bugs.
