### ISSUE TITLE
adox/adcx decode table entries are wrong?

### ISSUE THREAD

**Issue by khuey** [DynamoRIO/dynamorio#3592]
#2615 added adox/adcx support. Both instructions take two operands and store to the first operand.  Since the first operand is both a source and a destination, shouldn't the table entries be

```
    {OP_adox,      0xf338f618, "adox",    Gy, xx, Gy, Ey, xx, mrm, (fWO|fRO), END_LIST},
    {OP_adcx,      0x6638f618, "adcx",    Gy, xx, Gy, Ey, xx, mrm, (fWC|fRC), END_LIST},
```

rather than what's there today
```
    {OP_adox,      0xf338f618, "adox",    Gy, xx, Ey, xx, xx, mrm, (fWO|fRO), END_LIST},
    {OP_adcx,      0x6638f618, "adcx",    Gy, xx, Ey, xx, xx, mrm, (fWC|fRC), END_LIST},
```
?

**Comment by hgreving2304** [comment]
@kuey, that looks correct. Would you want to set up a PR? You will also have to fix the existing api.ir x86 test and move the adox/adcx create macros to the 3 args list of instructions.

**Comment by derekbruening** [comment]
Note that our convention is to list the destination *after* the source-only operand.

**Comment by hgreving2304** [comment]
Should we add some enforcement for this, or file an issue to consider doing this? LLVM has something like tying operands for register allocation. In our case, we could enforce that registers are identical e.g. for instr_create macros.
