### ISSUE TITLE
Dynamo RIO Cache Simulator Tracer internal crash at PC  0x00007fdaabf0fc4f (app exits with code 65280)

### ISSUE THREAD

**Issue by rkgithubs** [DynamoRIO/dynamorio#3598]
I'm seeing the following crashes with Dynamo RIO (4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux).  Application exited with code 65280. I'm seeing the same issue with both 18019 and 17998 builds. 

root@fmx190:~/DynamoRIO-x86_64-Linux-7.90.18019-0/bin64# ./drrun -t drcachesim -- sar -P ALL 1 100
<Application /usr/bin/sar.sysstat (6987).  DynamoRIO Cache Simulator Tracer internal crash at PC 0x00007fdaabf0fc4f.  Please report this at http://dynamorio.org/issues.  Program aborted.
Received SIGSEGV at pc 0x00007fdaabf0fc4f in thread 6987
Base: 0x00007fdaabe3f000
Registers:eax=0x0000000000000000 ebx=0x0000000000000000 ecx=0x00007fda67cc8460 edx=0x00007fda67cc8458
        esi=0x0000000000000000 edi=0x0000000000000000 esp=0x00007fda67cc83f0 ebp=0x00007fda67cc8460
        r8 =0x0000000000000000 r9 =0x00007fdaac1c5e80 r10=0x0000000000000000 r11=0x00007fdaac1a5240
        r12=0x00007fda67cc8458 r13=0x0000000000000001 r14=0x00007fda67cc8710 r15=0x0000000000000000
        eflags=0x0000000000010246
version 7.90.18019, custom build
-no_dynamic_options -client_lib '/root/DynamoRIO-x86_64-Linux-7.90.18019-0/bin64/../tools/lib64/release/libdrmemtrace.so;0;' -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code 
0x00007fda67cc8460 0x0000010603f10000>
---- <application exited with code 65280> ----

~/DynamoRIO-x86_64-Linux-7.90.18019-0/bin64# ./drrun -t drcachesim -- sleep 20
<Application /bin/sleep (6985).  DynamoRIO Cache Simulator Tracer internal crash at PC 0x00007fe0ad28dc4f.  Please report this at http://dynamorio.org/issues.  Program aborted.
Received SIGSEGV at pc 0x00007fe0ad28dc4f in thread 6985
Base: 0x00007fe0ad1bd000
Registers:eax=0x0000000000000000 ebx=0x0000000000000000 ecx=0x00007fe08d03e460 edx=0x00007fe08d03e458
        esi=0x0000000000000000 edi=0x0000000000000000 esp=0x00007fe08d03e3f0 ebp=0x00007fe08d03e460
        r8 =0x0000000000000000 r9 =0x00007fe0ad543e80 r10=0x0000000000000000 r11=0x00007fe0ad523240
        r12=0x00007fe08d03e458 r13=0x0000000000000001 r14=0x00007fe08d03e710 r15=0x0000000000000000
        eflags=0x0000000000010246
version 7.90.18019, custom build
-no_dynamic_options -client_lib '/root/DynamoRIO-x86_64-Linux-7.90.18019-0/bin64/../tools/lib64/release/libdrmemtrace.so;0;' -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code 
0x00007fe08d03e460 0x0000010603f10000>
---- <application exited with code 65280> ----

**Comment by hgreving2304** [comment]
@rkgithubs thanks for the bug. Could you please provide as much info as you can? E.g. run w/ debug if you haven't yet. Please also try loglevel 3 and post results or link here.

**Comment by rkgithubs** [comment]
this is fixed so closing

**Comment by derekbruening** [comment]
Please describe what the problem was, in case someone else hits it.
