### ISSUE TITLE
droption bytesize_t does not support >32-bit literals (pre-suffix-expansion)

### ISSUE THREAD

**Issue by rkgithubs** [DynamoRIO/dynamorio#3605]
For an application i'm trying to collect traces with -trace_after_instr and -exit_after_tracing options. 
I'm trying to cut out the warm up phase, according to 'perf stat -e instructions -a' it took ~90B instructions. 
 perf stat -e instructions -a ^C
 Performance counter stats for 'system wide':
 92,106,941,277      instructions                                                
16.751698236 seconds time elapsed

But tracing tool fails due to count being too large. 

/root/DynamoRIO-x86_64-Linux-7.90.18019-0/bin64/drrun -t drcachesim -trace_after_instrs 90000000000 -exit_after_tracing 80000000000 -- /bin/sh /root/specpu2017/bin/runcpu --config=dummy-try2.cfg SPECspeed2017_int_base
Usage error: Option trace_after_instrs value out of range. 

Any suggestions on how does instructions count from perf tool correspond to how DynamoRIO is instruction counting.

**Comment by hgreving2304** [comment]
I think exit_after_tracing would have to be bigger than trace_after_instr.
But regarding your question, the number is > MAX_INT32. Are you running the
32-bit or 64-bit version? Could you file an issue on this, it may or may
not a bug, but somebody will look at it shortly.

*From: *rkgithubs <notifications@github.com>
*Date: *Fri, May 10, 2019 at 2:58 PM
*To: *DynamoRIO/dynamorio
*Cc: *Subscribed

For an application i'm trying to collect traces with -trace_after_instr and

**Comment by derekbruening** [comment]
Looks like the parsing code https://github.com/DynamoRIO/dynamorio/blob/master/ext/droption/droption.h#L587 does not support a raw number like that.  It only supports a suffixed number which is more usable anyway: `-trace_after_instrs 90G`, `-trace_after_instrs 90000M`.  But it should be easy to fix: we would be happy to accept a PR.
