### ISSUE TITLE
AppVeyor failure: debug-internal-64: tool.drcachesim.missfile

### ISSUE THREAD

**Issue by hgreving2304** [DynamoRIO/dynamorio#3624]
Seems to be a flaky failure:

https://ci.appveyor.com/project/DynamoRIO/dynamorio/builds/24622709

Error:
Assertion failed: type_is_instr(cur_ref.instr.type), file ..\..\clients\drcachesim\reader\reader.cpp, line 132

xref #3320

**Comment by derekbruening** [comment]
Dup of #3320
