### ISSUE TITLE
CRASH in notepad on Windows 10 1903

### ISSUE THREAD

**Issue by dvfdr43** [DynamoRIO/dynamorio#3633]
example: `.\bin32\drrun.exe -c .\samples\bin32\countcalls.dll -- notepad`
It creates notepad.exe process but instantly crashes.
Worked before updating to Win10 1903
The latest binaries are from here: https://github.com/DynamoRIO/dynamorio/releases

Same for `drltrace` from Dr.Memory:
`drltrace -- notepad.exe` crashes the notepad process

**Comment by derekbruening** [comment]
We are in need of Windows developers.  If you can help diagnose and fix whatever in 1903 is causing this that would be greatly appreciated.  As usual, the first step is to run debug build.

**Comment by derekbruening** [comment]
Things to investigate: What kind of crash is it?  Does DR report a crash message; is it an app crash where the app exits; is it silent death?  What do the debug logs say about where things were at the time of the crash?  If it's a crash inside DR code, a callstack would help.

**Comment by dvfdr43** [comment]
It was silent death, there was no DR crash report.
drrun creates Notepad, notepad creates WerFault.exe and dies, silently.

P.S. I'm pretty good at Windows internals, but I never had experience with cmake projects, and in my case there is always some problem to build the project with VS2013u5. I'll try to make it work on VS2013 or later versions.

**Comment by deroko** [comment]
Whew, somebody have opened this issue. Issue is in Fls handling in ./core/win32/drwinapi/ntdll_redir.c and kernel32_redir.c . Fls is not anymore held in PEB on 1903 (what used to be Fls is now place holder for 0s to keep PEB size same). It is handled as internal structure inside of ntdll.dll. Fix which I have tested on my machine, and seems to work fine so far are these patches inside on ntdll_redirc.c and also in kernel32_redir.c.

I've fixed it temporarily by checking if peb->FlsBitmap is NULL and then skipping the code for handling Fls. In case of FlsBitmap being 0, I also skip ntdll!RtlFls* hooks and kernel32_redir.c hooks for kernel32!Fls* data.

Hope this helps to fix this issue further.

**Comment by derekbruening** [comment]
Yes, DR makes a private copy of the Fls data structs as part of the private PEB copy to isolate the app from client code and libraries used by clients.  Thank you for the help, @deroko

**Comment by deroko** [comment]
Is there any .exe as a test case for this scenario? I've looked at issue #875 but specified exe I didn't find, specifically `threads.exe`.

**Comment by deroko** [comment]
Just for the record, on winx64 1903 `ntdll.dll`, there is difference between `wow64 ntdll.dll` and `x64 ntdll.dll`. Difference is that `LdrShutdownProcess/Thread` calls on `wow64 RtlProcessFlsData`, while on `ntdll.dll x64 RtlpFlsDataCleanup`. In both cases whole logic of handling FLS is in `RtlpFlsDataCleanup` private/non exported symbol. It doesn't affect way of fixing, but interesting difference.

**Comment by deroko** [comment]
I've pushed commit which will resolve issue temporarily and let code to work with 1903. Ideal solution is not to use Fls data handling in `private_peb`, as Fls* functions are already hooked. I would use something like : 

`redir_FlsBitmap` and other needed fields in `redir_ntdll.c` which will be responsible for handling fls for clients, as all this fls mess comes from the fact that clients are linked against default crt which uses fls in `_CRTDLL_INIT`.

**Comment by derekbruening** [comment]
@deroko if you could make a pull request we can review and merge this fix.

**Comment by derekbruening** [comment]
Sorry, hadn't yet seen #3649, and it wasn't linked here.

**Comment by deroko** [comment]
Sorry, my bad that I didn't do pull correctly :(

**Comment by derekbruening** [comment]
> Is there any .exe as a test case for this scenario? I've looked at issue #875 but specified exe I didn't find, specifically threads.exe.

I believe that app taking in args `A 4` is in suite/tests/client-interface/annotation-concurrency.c (takes in app dll path too today; `ctest -N -V -R annotation-concurrency\$` will show how to run it.

We don't have great tests of private library isolation.  The redir routines have unit tests within their files.
