### ISSUE TITLE
AVX-512: Fix 1-bit mask opcodes and possibly introduce 1-bit mask size type.

### ISSUE THREAD

**Issue by hgreving2304** [DynamoRIO/dynamorio#3662]
Some AVX-512 instructions read only 1 mask bit (e.g. vmovss etc.) To better describe them, we may need a sub-1-byte type to describe a bit. Currently, we're using KEb to describe them.

The opcodes vaddss, vsubss, vmulss are wrong and need to be the new type, or KEb. Thanks @JivanH  for finding.

**Comment by derekbruening** [comment]
> To better describe them, we may need a sub-1-byte type to describe a bit.

Those are already present in the enum: OPSZ_1b, OPSZ_2b, etc.

**Comment by hgreving2304** [comment]
Ok. I'll fix them up in one of the next patches!
