### ISSUE TITLE
Test common.decode x64 fails on Ubuntu 18.

### ISSUE THREAD

**Issue by hgreving2304** [DynamoRIO/dynamorio#3674]
The expected output seems to be different:

13: Testing nops
13: Done with nops
13: Testing SSE3
13: Bad instruction, instance 1
13: Testing 3D-Now
13: Bad instruction, instance 2
13: Testing far call/jmp
13: Bad instruction, instance 3
13: Bad instruction, instance 4
13: Bad instruction, instance 5
13: Bad instruction, instance 6
13: Access violation, instance 7
13: Access violation, instance 8
13: Testing rip-rel ind branch
13: Access violation, instance 9
13: Bad instruction, instance 10
13: All done

The "Access violation, instance 9" is unexpected.

**Comment by hgreving2304** [comment]
Test crashes in 'print' implemenation of DynamoRIO, even when common.decode is running under DynamoRIO.

**Comment by hgreving2304** [comment]
Since GCC 4.5 therer appears to be a de-factor standard for the stack to be aligned at 16-bytes. I am seeing 8-bytes in this test (not sure who messes it up yet).

**Comment by derekbruening** [comment]
#847 is where we decided what to do about the gcc breakage of the ABI.

Also xref other stack issues #2024, #2330

**Comment by hgreving2304** [comment]
Thanks.
