### ISSUE TITLE
Illegal Instruction PEXT

### ISSUE THREAD

**Issue by johnfxgalea** [DynamoRIO/dynamorio#3692]
I am encountering an illegal instruction exception when creating and inlining a **pext** instruction. There seems be a bug in the decoding of the instruction.

Here is a simple test snippet:

```
opnd_t msk_opnd = opnd_create_reg(scratch_reg2);
opnd_t src_opnd = opnd_create_reg(scratch_reg);
opnd_t dst_opnd = opnd_create_reg(scratch_reg3);

instr_t *instr = INSTR_CREATE_pext(drcontext, dst_opnd, src_opnd, msk_opnd);
instrlist_meta_preinsert(bb, where, instr);

instr_disassemble(drcontext, instr, STDERR);
```

The instruction’s entry in the decode table has the following encoding: . 

`{OP_pext,      0x6638f518, "pext",    Gy, xx, Ey, By, xx, mrm|vex, x, END_LIST},`

Shouldn’t the prefix be f3 instead of 66? Ref: https://www.felixcloutier.com/x86/pext 
Is this causing the crash?

With this in mind, I went on to create a patch, replacing, _0x6638f518_ with _0xf338f518_, but this is where things got a bit strange. 
The non-working patch is available here: https://github.com/johnfxgalea/dynamorio/commit/f2e6363a89d4f92486027983f1e5524854a7779c 

With the patch, I am no longer getting a crash, but after some testing, the encoded instruction does not correspond with the operand sequence specified via the INSTR_CREATE_pext macro, and therefore I am getting incorrect functionality.

I attached gdb, and disassembled the instruction. The results is the following (disassembly flavour set to intel):

```
   0x4a625014:	mov    DWORD PTR fs:0x5c,ebx
=> 0x4a62501b:	mov    DWORD PTR ds:0x1,ecx
   0x4a625021:	pext   ebx,edx,ecx
   0x4a625026:	mov    ecx,DWORD PTR fs:0x54
   0x4a62502d:	mov    edx,DWORD PTR fs:0x58
```

But **instr_disassemble**, found in the test case, outputs (also with -syntax intel): 

` pext   ebx, ecx, edx `

Notice that the source operand (the second operand) is swapped with the mask (the third operand). BUT this is not the operand sequence that was specified with INSTR_CREATE_pext. I've confirmed this also with a set of pre and post clean call tests.

May another DR developer try and replicate this crash please just in case I missed something. I'm not sure how to fix this so any help would be greatly appreciated.

Test case may be found here: https://github.com/johnfxgalea/dynamorio/tree/test_pext_branch

Due to other constraints, I am running on a 32-bit Ubuntu System. My CPU **does** support BMI2 instructions (confirmed via proc/cpuinfo). In fact, **pdep** does not cause an illegal instruction crash on my machine. 

I am working on the current head (i.e., c258f5b1)

**Comment by hgreving2304** [comment]
John, looking at it, will get back to you. In case I need to, how can I run
your test?

**Comment by johnfxgalea** [comment]
The test is just a quick hack of the memtrace_x86 api sample for now (not ideal but I'll add a regression once we confirm and identify the bug). Simply clone and checkout to test_pext_branch, and run memtrace. Thanks for helping me!

**Comment by johnfxgalea** [comment]
Forgot to mention, that the branch also applies the non-working patch, so you should be experiencing the second type of behaviour, and not the illegal instr exception.

**Comment by hgreving2304** [comment]
Hi John, your patch is correct.

```
echo "0xc4 0xe2 0x61 0xf5 0x41 0x37" | /usr/bin/llvm-mc-7 -disassemble -triple=x86_64
        .text
<stdin>:1:1: warning: invalid instruction encoding
0xc4 0xe2 0x61 0xf5 0x41 0x37
^
<stdin>:1:21: warning: invalid instruction encoding
0xc4 0xe2 0x61 0xf5 0x41 0x37
                    ^
```

VEX.pp should be 0b10 (0xf3)

```
echo "0xc4 0xe2 0x62 0xf5 0x41 0x37" | /usr/bin/llvm-mc-7 -disassemble -triple=x86_64
        .text
        pextl   55(%rcx), %ebx, %eax
```

Please set up a pull request if you like.

w.r.t. operand order, looks like GNU objdump prints the ModRM:r/m source before the VEX.vvvv one:

```
objdump -Matt -d a.out                                                                                                                                                 
[..]
a.out:     file format elf64-x86-64
Disassembly of section .text:
0000000000000000 <.text>:
   0:   c4 e2 62 f5 41 37       pext   0x37(%rcx),%ebx,%eax
```

```
objdump -Mintel -d a.out                                                                                                                                               
a.out:     file format elf64-x86-64
Disassembly of section .text:
0000000000000000 <.text>:
   0:   c4 e2 62 f5 41 37       pext   eax,ebx,DWORD PTR [rcx+0x37]
```

The internal operand order in DynamoRIO in this case doesn't match Intel's, but this doesn't invalidate the encoding, just switch the operands when calling the create macro. We could swap the operands, but I don't see an urgent need for this. That said, will this work for you?

**Comment by johnfxgalea** [comment]
That works nicely, thanks for confirming. I guess we can modify the INSTR_CREATE_pext and perform the swap there, rather than relying on the user to perform the swap?

**Comment by hgreving2304** [comment]
No, you would leave the INSTR_CREATE macro as-is, it reflects the operand order of DynamoRIO. There are other examples where the operand order doesn't fully match the one that you see in Intel's Specs. E.g. immediate operands are often the first source, even though in Intel's manuals they're often the last. This doesn't result in an invalid encoding of the instruction. In the PEXT case, it looks like (first confused me) that even GNU binutils swaps them around in an unexpected way. I assume we're good here then?

Thanks for finding the prefix bug! Please set up a PR.

**Comment by johnfxgalea** [comment]
Okay, thanks for clearing that up.

**Comment by hgreving2304** [comment]
Sure. Glad this works for you. You're going to set up the patch right? While you're at it, maybe you can go over the other pext derivatives as well and make sure they're correct :)?

**Comment by johnfxgalea** [comment]
Yep, patch coming up.

**Comment by hgreving2304** [comment]
Thanks!

**Comment by johnfxgalea** [comment]
No worries, thanks for taking the time to confirm/clarify the bug.
