### ISSUE TITLE
Make error line_length_content: Line too long: exceeds 90 chars.

### ISSUE THREAD

**Issue by eliodilar** [DynamoRIO/dynamorio#3693]
hello,

I try to install, make, Dynamorio and i have a problem of line size during make.
Someone know how to up the line buffer size?

/home/chapoul/sniper/frontend/Dyndr/dynamorio/CMakeFiles/3.10.2/CompilerIdC/CMakeCCompilerId.c:217: error line_length_content: Line too long: exceeds 90 chars.
/home/chapoul/sniper/frontend/Dyndr/dynamorio/CMakeFiles/3.10.2/CompilerIdC/CMakeCCompilerId.c:339: error line_length_content: Line too long: exceeds 90 chars.
CMakeFiles/style_reports.dir/build.make:121: recipe for target 'vera_report_0.xml' failed
make[2]: *** [vera_report_0.xml] Error 1
make[2]: *** Suppression du fichier « vera_report_0.xml »
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/style_reports.dir/all' failed
make[1]: *** [CMakeFiles/style_reports.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by eliodilar** [comment]
line can't be cut its a or condition

#elif defined(__VISUALDSPVERSION__) || defined(__ADSPBLACKFIN__) || defined(__ADSPTS__) || defined(__ADSP21000__)

**Comment by Carrotman42** [comment]
Let's continue this in the email thread you've already started on our user group. (https://groups.google.com/forum/#!topic/DynamoRIO-Users/m25pTfkRxIo)
