### ISSUE TITLE
installation of X86 dynamorio kit ubuntu18.04

### ISSUE THREAD

**Issue by eliodilar** [DynamoRIO/dynamorio#3705]
Hello,

I use the pin to a x86 simulator, someone know how to build Dynamorio with x86 lib/bin? 
Newbie compilator...

Cordially

**Comment by hgreving2304** [comment]
Have you looked at this page yet?
https://github.com/DynamoRIO/dynamorio/wiki/How-To-Build

**Comment by derekbruening** [comment]
Please use the users list https://groups.google.com/forum/#!forum/DynamoRIO-Users for questions, as it will reach a wider audience of people who might have an answer, and it will reach other users who may find the information beneficial. The issue tracker is for specific detailed bugs.
