### ISSUE TITLE
xstate, proc_num_simd_registers()/saved() not used right.

### ISSUE THREAD

**Issue by hgreving2304** [DynamoRIO/dynamorio#3712]
Most importantly, the current Windows 64-bit AVX context switching doesn't seem right.

We may have to refine our proc_num_simd_registers() , proc_num_simd_saved() API. At least they're not helpful when dealing with xstate's layout.

Both proc_num_simd_registers() and proc_num_simd_saved() suggest that there is always a contiguous sequence of simd registers to be saved. This is not the case for xstate.

For example, 64-bit Window:

We are using proc_num_simd_registers() to iterate through YMMH xstate. This doesn't seem right. In 64-bit Windows, proc_num_simd_registers()  is currently 6. This seems to be coming from xmm state, where xmm7-xmm15 are (oddly enough) callee-saved. However in AVX, the entire YMMH state should be saved.

Another example, AVX-512, zmmh + zmm state components of xstate contain zmm0 - zmm15 upper half, and zmm16 - zmm31 full registers.

Maybe the easiest fix is it add similar functions for the xstate components, and keep using proc_num_simd_registers() and proc_num_simd_saved() everywhere else?

**Comment by derekbruening** [comment]
Dup of #3422?

**Comment by hgreving2304** [comment]
@derekbruening , thanks! I had already seen that. I'll copy comment above to #3422 and close.
