### ISSUE TITLE
Exit event is not called [dr_register_exit_event]

### ISSUE THREAD

**Issue by dvfdr43** [DynamoRIO/dynamorio#3715]
I've registered an exit event and it's called if a target application terminates normally, by itself.
If I kill a target process (force termination) the exit event will not be called.
I'm using `drrun.exe` to inject a client into a target application.
Is it expected behavior?
If so is there a way to force to call exit_event?

**Comment by derekbruening** [comment]
Please use the users list https://groups.google.com/forum/#!forum/DynamoRIO-Users for questions, as it will reach a wider audience of people who might have an answer, and it will reach other users who may find the information beneficial. The issue tracker is for specific detailed bugs. If you are not sure it's a bug, please start by asking on the users list.

**Comment by dvfdr43** [comment]
I opened here because I think it's issue

**Comment by derekbruening** [comment]
Answered on the list: https://groups.google.com/forum/#!topic/DynamoRIO-Users/jVVU8eobtd0
