### ISSUE TITLE
Trigger Low on Memory Event

### ISSUE THREAD

**Issue by johnfxgalea** [DynamoRIO/dynamorio#3717]
The idea is to trigger a client event when DynamoRIO is low on memory to help reduce any non-critical memory space and potentially avoid a crash.

DynamoRIO already has reset features when memory is tight. The event may be triggered when reset is scheduled.

A user had requested this [feature](https://groups.google.com/forum/#!searchin/dynamorio-users/%22out$20of$20memory%22%7Csort:date/dynamorio-users/L4mL3MYY5Uc/DP_rWYY3BQAJ) some years ago.

This issue also covers the implementation of drmgr's wrapper to handling the event.

**Comment by derekbruening** [comment]
Recent changes (primarily the split of "vmcode" from "vmheap": #1132) has reduced the likelihood of OOM substantially, though it is still possible due to the 2G maximum size of vmcode for reachability guarantees.  I'm curious whether you are seeing OOM after those changes?  On 64-bit?  Is your client asking for reachable memory when it could do with non-reachable memory (which has no size limit)?

**Comment by johnfxgalea** [comment]
@derekbruening Re-running experiments so I can reconfirm that this this the case. I'll get back to you.

Im on 32-bit due to other constraints.

**Comment by derekbruening** [comment]
I see, 32-bit is always constrained and the vmcode/vmheap split can't help much with the limited address space.

**Comment by johnfxgalea** [comment]
Okay my client leads to more OOM crashes without the patch. The benchmarks are from the new SPEC CPU 2017 suite (which are claimed to be more computationally intensive than that of 2006).

Since this patch aims to alleviate old problems concerning 32-bit, instead of 64-bit, I do of course understand if this PR is not wanted. Just LMK and I'll move on to the next PR :)

**Comment by derekbruening** [comment]
> I do of course understand if this PR is not wanted

I think there was a misunderstanding if it was my comments above that were taken that way?  The feature seems useful, particularly for 32-bit.  We're happy to take a look at the PR.
