### ISSUE TITLE
After "Process Hollowing" dr_get_main_module returns 0

### ISSUE THREAD

**Issue by secrary** [DynamoRIO/dynamorio#3776]
OS: Windows 10 x64 1803
DynamoRIO: 7.91.18109

Inside _dr_client_main_ function I'm calling _dr_get_main_module_  and printing _full_path_:
```
	const auto target_module = dr_get_main_module();
	const std::string application_full_path = target_module->full_path;
```

But if a target process creates a child process and overwrites the main module of the child process using "process hollowing/process replacement"* (typical for malware samples) _dr_get_main_module_  from the child process fails and returns 0 (nullptr)

*code example for "process hollowing": https://github.com/secrary/InjectProc#process-replacement

**Comment by secrary** [comment]
Since a main module is replaced at run-time, it's impossible to get the module path from a disk but I think EP and other details can be re-parsed

**Comment by derekbruening** [comment]
I don't recall all of the Windows module details in DR, but I believe it walks the address space and parses PE headers when it initializes, so I would expect it to find a synthetic image just fine, so I am surprised by this.  There is code in DR that walks the PEB loader lists but don't think it's used for much.

I would suggest following the module list creation code, e.g. find_executable_vm_areas() in win32/os.c calling process_image() which parses PE headers and calls module_list_add().  That should add the replacement image to the module list.

I would then look at dr_get_main_module: it uses the executable image base stored in the PEB.  Maybe that's the problem and it still points at the old image, and the replacement is at a different address?  That sounds like a bug in the "process replacement" scheme, to not update PEB.ImageBaseAddress.  I would suggest checking whether that's the problem and if it is then some other heuristic needs to be used to handle this incomplete replacement.

**Comment by secrary** [comment]
> calls module_list_add(). That should add the replacement image to the module list.

A main module is not replaced by `LoadLibrary` but it's mapped manually (for example, using `VirtualAlloc`, `WriteProcessMemory`, etc) 

> sounds like a bug in the "process replacement" scheme, to not update PEB.ImageBaseAddress.

`process replacement` is mostly used by a malware, so they don't care about modifying PEB.base_address, they just change EIP/RIP register to point EP of the new module

**Comment by derekbruening** [comment]
> > calls module_list_add(). That should add the replacement image to the module list.
> 
> A main module is not replaced by `LoadLibrary` but it's mapped manually (for example, using `VirtualAlloc`, `WriteProcessMemory`, etc), so I'm not sure if `module_list_add()` is called when the module replacement happens

No, like I said, DR walks the address space and looks for PE headers.

> 
> > sounds like a bug in the "process replacement" scheme, to not update PEB.ImageBaseAddress.
> 
> `process replacement` is mostly used by a malware, so they don't care about modifying PEB.base_address, they just change EIP/RIP register to point EP of the new module

Yes, but one could argue that dr_get_main_module() is supposed to tell you about the PE passed to CreateProcess or the PE pointed at by PEB.ImageBaseAddress, and if that PE has been clobbered then returning NULL is an acceptable outcome.

If you iterate through the modules (dr_module_iterator_start(), etc.) is the replacement module there?  I would expect it to be there.

**Comment by secrary** [comment]
> then returning NULL is an acceptable outcome.
I agree, I realize that after creating the issue

**Comment by derekbruening** [comment]
So the replacement module is in the module list?  If so, then the only issue is dr_get_main_module().  If you would like to augment it with some additional heuristics if PEB.ImageBaseAddress does not point at a module any more, we would be happy to take a PR.  Or if you feel its behavior is fine as-is, we can close the issue.

**Comment by secrary** [comment]
Yes, I think we can close the ticket.
After becoming more familiar with DR I'll create a PR
