### ISSUE TITLE
dr_get_current_drcontext return NULL when using in drwrap_replace

### ISSUE THREAD

**Issue by jinyu00** [DynamoRIO/dynamorio#3779]
I use drwrap_replace to replace a function , 
```
drwrap_replace(mod->start + 0x017B28, (app_pc)hook_log, true);
```
Then in `hook_log` I want get the dcontext, so I use
```
void* dc = dr_get_current_drcontext();
```

but dr_get_current_drcontext always return NULL, how can I get drcontext in replace function?

**Comment by derekbruening** [comment]
As the documentation for drwrap_replace says, "The replacement code will be executed as application code, NOT as client code.".  Application code should not be calling dr_get_current_drcontext().  Maybe you want to use drwrap_replace_native() instead.

Also, please use the users list https://groups.google.com/forum/#!forum/DynamoRIO-Users for questions such as this, as it will reach a wider audience of people who might have an answer, and it will reach other users who may find the information beneficial. The issue tracker is for specific detailed bugs. If you are not sure it's a bug, please start by asking on the users list.
