### ISSUE TITLE
DynamoRIO api - visual studio 2017 errors.

### ISSUE THREAD

**Issue by mrXsys** [DynamoRIO/dynamorio#3784]
Hey everyone, I try to use dynamoRIO api to create my own tools but i get errors everytime when i include "dr_api.h". 

I use : 
1) Visual studio 2017 
2) Windows 10 x64 

`Severity	Code	Description	Project	File	Line	Suppression State
Error	C1189	#error:  Target operating system unspecified: define WINDOWS, LINUX, or MACOS	Project1	c:\users\danie\source\repos\project1\project1\include\dr_defines.h	48	
Error (active)	E0065	expected a ';'	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_annotation.h	56	
Error (active)	E0020	identifier "dr_valgrind_request_id_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_annotation.h	176	
Error (active)	E0020	identifier "dr_valgrind_request_id_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_annotation.h	232	
Error (active)	E0079	expected a type specifier	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_api.h	117	
Error (active)	E0065	expected a ';'	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_config.h	148	
Error (active)	E0169	expected a declaration	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_config.h	171	
Error (active)	E0065	expected a ';'	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_config.h	172	
Error (active)	E0169	expected a declaration	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_config.h	172	
Error (active)	E0169	expected a declaration	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_config.h	173	
Error (active)	E0169	expected a declaration	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_config.h	175	
Error (active)	E0035	#error directive: Target operating system unspecified: define WINDOWS, LINUX, or MACOS	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_defines.h	48	
Error (active)	E0035	#error directive: Target architecture unknown: define X86_32, X86_64, ARM_32, or ARM_64	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_defines.h	69	
Error (active)	E0020	identifier "pid_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_defines.h	253	
Error (active)	E0020	identifier "pid_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_defines.h	254	
Error (active)	E0035	#error directive: NYI	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_defines.h	582	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_events.h	1463	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_events.h	1476	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_events.h	1535	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_events.h	1548	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_events.h	1605	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_events.h	1618	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_ir_instr.h	2434	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_ir_instrlist.h	289	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_ir_opnd.h	3045	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_ir_utils.h	1279	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_ir_utils.h	1290	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_ir_utils.h	1304	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_tools.h	2234	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_tools.h	2239	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_tools.h	2264	
Error (active)	E0020	identifier "ssize_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_tools.h	2270	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_tools.h	2271	
Error (active)	E0020	identifier "ssize_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_tools.h	2277	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_tools.h	2278	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_tools.h	2292	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_tools.h	2299	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_tools.h	2305	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_tools.h	2306	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_tools.h	2314	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_tools.h	2369	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_tools.h	2471	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_tools.h	2482	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_tools.h	2486	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_tools.h	2490	
Error (active)	E0020	identifier "ssize_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_tools.h	2555	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_tools.h	2556	
Error (active)	E0020	identifier "ssize_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_tools.h	2561	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_tools.h	2562	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_tools.h	2735	
Error (active)	E0020	identifier "file_t" is undefined	Project1	C:\Users\danie\source\repos\Project1\Project1\include\dr_tools.h	2739	
`

**Comment by derekbruening** [comment]
As the message says, you did not define the OS:
``
#error: Target operating system unspecified: define WINDOWS, LINUX, or MACOS
```

Please see the documentation: http://dynamorio.org/docs/using.html#sec_build
We recommend using our CMake support which automagically sets defines for you.

In the future, please use the users list https://groups.google.com/forum/#!forum/DynamoRIO-Users for questions like this, as it will reach a wider audience of people who might have an answer, and it will reach other users who may find the information beneficial. The issue tracker is for specific detailed bugs. If you are not sure it's a bug, please start by asking on the users list.

**Comment by mrXsys** [comment]
Thank's! :).

**Comment by Pavel-Durov** [comment]
> Please see the documentation: http://dynamorio.org/docs/using.html#sec_build

 http://dynamorio.org/docs/using.html#sec_build is a dead link

**Comment by jjoonathan** [comment]
Breadcrumbs, for anyone who landed here from google: https://dynamorio.org/page_build_client.html
