### ISSUE TITLE
Add VS2019 support

### ISSUE THREAD

**Issue by baptistapedro** [DynamoRIO/dynamorio#3805]
````find_program(CMAKE_ASM_COMPILER ml64.exe HINTS "${cl_path}" DOC "path to assembler")
    if ("${CMAKE_GENERATOR}" MATCHES "NMake Makefiles")
      set(CMAKE_ASM_COMPILER "ml64.exe")
    endif()
  else (X64)
    find_program(CMAKE_ASM_COMPILER ml.exe HINTS "${cl_path}" DOC "path to assembler")
    if ("${CMAKE_GENERATOR}" MATCHES "NMake Makefiles")
      set(CMAKE_ASM_COMPILER "ml.exe")
    endif()
  endif (X64)
  if (NOT CMAKE_ASM_COMPILER)
    message(FATAL_ERROR "assembler not found: required to build")
  endif (NOT CMAKE_ASM_COMPILER)
  message(STATUS "Found assembler:````


I am doing cmake -G"Visual Studio 16 Win64" ..
and I happen to have an error on the exact line   if (NOT CMAKE_ASM_COMPILER)
    message(FATAL_ERROR "assembler not found: required to build")

I am not sure why it doesnt find the compiler since I'm using the VS with all Build Tools installed, plus the cmake should do it by yourself?

**Comment by derekbruening** [comment]
> I am doing cmake -G"Visual Studio 16 Win64" ..

"Visual Studio 16" is VS2019 which is not supported.  Please see https://github.com/DynamoRIO/dynamorio/wiki/How-To-Build, #2166, and #2924.  I suppose there's no issue yet on VS2019 support but VS2017 #2924 should be addressed first, and there is some ongoing work on that.

**Comment by derekbruening** [comment]
Changing into a feature request to add VS2019 support.  As mentioned, please do not start on this without synchronizing with VS2017 #2924 work first.

**Comment by m-0day** [comment]
Does this support VS 2019 now? I am getting the same error on build...thx

**Comment by derekbruening** [comment]
No, VS2017 should build but has not yet been added to Appveyor.  If you would like to add VS2019 support we are happy to review a PR.

**Comment by firodj** [comment]
I try to install VS2017 on my new installed VM, but currently there is only VS2019 installer so I trying a combination a bit:

### VS2019 with VS2017 (v141 | v14.16):

1. Start command line to use cl.exe from v14.16 not VS 2019 (v142 | v14.24)

```
%comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat" -vcvars_ver=14.16
```

See **xx.16**:
```
cl.exe
Microsoft (R) C/C++ Optimizing Compiler Version 19.16.27034 for x86
```

```
ml.exe
Microsoft (R) Macro Assembler Version 14.16.27034.0
```

2. Run cmake to use v141 toolset

I cannot change the Generator so it always use "Visual Studio 16 2019".

```
cmake -T v141,host=x86,version=14.16 -A Win32 ..
```

3. Build as wiki said:

```
cmake --build . --config RelWithDebInfo
```

### VS2019

1. Start command line as "Developer Command Prompt for VS 2019", or:

```
%comspec% /k "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\Tools\VsDevCmd.bat"
```

2. Run cmake with Win32:

```
cmake -A Win32 ..
```

3. Buils as wiki said:

```
cmake --build . --config RelWithDebInfo
```

### TODO

The error above if we enforce `-A x64` (by default), so need to update `cpp2asm_support.cmake`

**Comment by derekbruening** [comment]
VS2017 is what the automated testing is using.  If you would like to add VS2019 support we are happy to take a pull request.
