### ISSUE TITLE
Incompatible API

### ISSUE THREAD

**Issue by baptistapedro** [DynamoRIO/dynamorio#3807]
I'm having this error while trying to run an .exe  with ddrun.exe 
 (11556). Client library targets an incompatible API version and should be re-compiled.

This is the command I used:
```drrun.exe -c C:\Windows\System32\ole32.dll -target_module  C:\Users\gitim\Desktop\winafl\bin64\in\godoitOle.exe -fuz_iterations 10 -nargs 1 -- C:\Users\gitim\Desktop\winafl\bin64\godoitOle.exe C:\Users\gitim\Desktop\winafl\bin64\in\bmp.png```

I'm not sure what it meant by incompatible API, I'm just using windows.h and calling a single one function from ole32.dll

**Comment by hgreving2304** [comment]
The -c option is for a client library. ole32.dll is not a DynamoRIO client. What are you trying to do?

**Comment by baptistapedro** [comment]
tring to follow this https://github.com/googleprojectzero/winafl/blob/master/readme_dr.md
```path\to\DynamoRIO\bin64\drrun.exe -c winafl.dll -debug
-target_module test_gdiplus.exe -target_offset 0x16e0 -fuzz_iterations 10
-nargs 2 -- test_gdiplus.exe input.bmp```

**Comment by baptistapedro** [comment]
what should I try instead?

**Comment by hgreving2304** [comment]
The new command you posted is different from the first one. Please clarify what exactly you're running and its output, and follow-up on the dynamorio-users mailing list.

**Comment by hgreving2304** [comment]
(Not a bug).

**Comment by hgreving2304** [comment]
(Not a bug).

**Comment by derekbruening** [comment]
@hgreving2304 : generally we use a Status label to indicate the closed status.  I added
Status-UserOrAppError
