### ISSUE TITLE
Add support for drx_expand_scatter_gather() and instr_is_{scatter,gather}() on AArch32

### ISSUE THREAD

**Issue by hgreving2304** [DynamoRIO/dynamorio#3837]
The functions instr_is_scatter() and instr_is_gather() will be added along with a patch shortly. This issue covers support for ARM/AArch64.

**Comment by derekbruening** [comment]
This issue includes arm support for drx_expand_scatter_gather(), right?  Maybe add that to the title.

**Comment by derekbruening** [comment]
Xref #2985 which is the x86 issue.

**Comment by derekbruening** [comment]
This only covers AArch32; #5036 covers AArch64.

**Comment by derekbruening** [comment]
Turns out there are not any AArch32 scatter-gather instructions so we're closing this and leaving just #5036 as it has more discussion/content.
