### ISSUE TITLE
Assert failure when running in Docker: core/unix/rseq_linux.c:283 res == 0

### ISSUE THREAD

**Issue by Carrotman42** [DynamoRIO/dynamorio#3848]
The assert happens on line 283 in rseq_is_registered_for_current_thread, where we get a return value from SYS_rseq that is not EINVAL, ENOSYS, or 0; the comment there suggests "the struct size or sthg changed!":

http://www.github.com/DynamoRIO/dynamorio/blob/d465def/core/unix/rseq_linux.c#L269-L289

I did this based on the cronbuild (on a system without a compiler) so I can't easily add debug logs, and I can't get gdb to work in a container correctly. Here are the reproducer steps while I have them handy:

Step 1: I created a new Virtual Machine in Google Compute Engine; the OS I used was COS (https://cloud.google.com/container-optimized-os/docs/, version R76-12239.60.0)

    ( I did this step in the web UI, so there's no command line reproducer unfortunately; I can get one for the gcloud CLI if requested.)

Step 2: SSH to VM; download and untar the DR distribution (running as root on the VM):

    # mkdir /mnt/stateful_partition/dr
    # cd /mnt/stateful_partition/dr
    # wget https://github.com/DynamoRIO/dynamorio/releases/download/cronbuild-7.91.18151/DynamoRIO-x86_64-Linux-7.91.18151-0.tar.gz
    # tar -xvzf DynamoRIO-x86_64-Linux-7.91.18151-0.tar.gz
    # cat <<EOF >Dockerfile
    FROM ubuntu:18.04
    COPY DynamoRIO-x86_64-Linux-7.91.18151-0 .
    EOF

Step 3: I created a new docker image based on this Dockerfile:

    # docker build .

 Step 4: Run `ls` via drrun in debug mode without any clients:

    # docker run ${IMAGE_HASH_FROM_LAST_STEP} ./bin64/drrun -debug -- ls
    <Starting application /bin/ls (1)>
    <Application /bin/ls (1).  Internal Error: DynamoRIO debug check failure: /home/travis/build/DynamoRIO/dynamorio/core/unix/rseq_linux.c:283 res == 0
    (Error occurred @0 frags)
    version 7.91.18151, custom build
    -no_dynamic_options -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct 
    0x00007ffd492a3880 0x00007f55173ad8a3
    0x00007ffd492a3ad0 0x00007f55175cf1b3
    0x00007ffd492a3b30 0x00007f55175ceca3
    0x00007ffd492a3be0 0x00007f5517586730
    0x00007ffd492a3bf0 0x00007f5517324105
    0x00007ffd492a4420 0x00007f55175bd627
    0x00007ffd492a54d0 0x00007f551756cd07>

**Comment by derekbruening** [comment]
I cannot reproduce this in an Ubuntu 18.04 VMware VM.  I can reproduce in a bare-bones Docker container as you used: investigating.

**Comment by derekbruening** [comment]
Well I went to use gdb and had to turn off seccomp for that and the assert disappeared!

So we have:

```
$ docker run 43bd21de8690 bin64/drrun -debug -- ls
<Starting application /bin/ls (1)>
rseq_is_registered_for_current_thread: res==-1
<Application /bin/ls (1).  Internal Error: DynamoRIO debug check failure: /work/dr/git/src/core/unix/rseq_linux.c:284 res == 0
(Error occurred @0 frags)
version 7.91.18176, custom build
-no_dynamic_options -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct 
0x00007ffde6c85260 0x00007fb9542c695d
0x00007ffde6c854b0 0x00007fb9544ea4d8
0x00007ffde6c85510 0x00007fb9544e9fa0
0x00007ffde6c855c0 0x00007fb9544a05cc
0x00007ffde6c855d0 0x00007fb95423d1eb
0x00007ffde6c85e00 0x00007fb9544d872e
0x00007ffde6c86eb0 0x00007fb954486c0b>
```

Versus:
```
$ docker run --security-opt seccomp=unconfined 43bd21de8690 bin64/drrun -debug -- ls
<Starting application /bin/ls (1)>
rseq_is_registered_for_current_thread: res==0
<Initial options = -no_dynamic_options -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
<Paste into GDB to debug DynamoRIO clients:
set confirm off
add-symbol-file '/lib64/debug/libdynamorio.so' 0x00007f9c6cdfbb90
>
rseq_is_registered_for_current_thread: res==0
<(1+x) Handling our fault in a TRY at 0x00007f9c6d057100>
ACKNOWLEDGEMENTS
License.txt
README
bin
bin64
...
var
<Stopping application /bin/ls (1)>
```

So with seccomp blocking SYS_rseq it returns -EPERM.
