### ISSUE TITLE
Add API function to create VSIB operands

### ISSUE THREAD

**Issue by johnfxgalea** [DynamoRIO/dynamorio#3856]
Feature request to implement a function that creates a VSIB addressing memory operand. Something like` opnd_create_vsib(reg_id_t base_reg, reg_id_t vector_reg, int scale, int disp)` would be great.

**Comment by derekbruening** [comment]
Today you would just use `opnd_create_base_disp()` and pass a SIMD register as the index.  See `opnd_is_vsib()`.  I'm not sure we need a different routine?

**Comment by johnfxgalea** [comment]
Okay makes sense. Perhaps, we can add a line in the documentation. Otherwise, we can close this issue.

**Comment by hgreving2304** [comment]
Only slightly related, xref #2985 , but in case somebody is wondering: the preferred method for clients to inspect VSIB addresses is to expand the instruction in app2app.

**Comment by derekbruening** [comment]
> Perhaps, we can add a line in the documentation.

Maybe you could send a PR and have it close this issue?
