### ISSUE TITLE
Extend reg_is_simd to consider ZMM registers as well.

### ISSUE THREAD

**Issue by johnfxgalea** [DynamoRIO/dynamorio#3867]
Current implementation of reg_is_simd does not consider ZMM as simd. 

```
bool
reg_is_simd(reg_id_t reg)
{
    return reg_is_xmm(reg) /*includes ymm*/ || reg_is_mmx(reg);
}
```

Issue relates to extending reg_is_simd to checking ZMM registers as well.

**Comment by hgreving2304** [comment]
I thought we had a reason why we didn't change this, but couldn't find anything. I would say if you feel like it, please feel free to set up a patch. I suggest to changing to reg_is_strictly_xmm|ymm|zmm().

**Comment by johnfxgalea** [comment]
I am thinking perhaps due to backwards compatibility?

**Comment by hgreving2304** [comment]
Right, but OTOH I don't see how a client could rely strongly on the function returning false for zmm, since until cf1ec32e9b89c1d8a2, AVX-512 wasn't supported at all - and still is marked experimental as #1312 has not been closed. @derekbruening any preference?

**Comment by derekbruening** [comment]
I remember reg_is_xmm being left as xmm or ymm for backward compatibility despite being unusual, and that's why we added the _strictly_ versions.  I don't recall any discussion of reg_is_simd: seems like it needs to include zmm.

**Comment by johnfxgalea** [comment]
Okay, I'll get this in
