### ISSUE TITLE
Introduce instr_reads_from_exact_reg

### ISSUE THREAD

**Issue by johnfxgalea** [DynamoRIO/dynamorio#3872]
Feature request to create a new function, namely instr_reads_from_exact_reg, which returns whether an instruction reads directly and exactly from a given register.

For example: instr_reads_from_exact_reg(instr, xmm0) returns false if the instruction is vmov [m], zmm0, but returns true if the instruction is movdqa [m] xmm0.

**Comment by johnfxgalea** [comment]
Sorry for the botched title, accidentally hit enter.

**Comment by johnfxgalea** [comment]
This function is needed for #8344

**Comment by hgreving2304** [comment]
You probably mean that the function should return false for instr_reads_from_exact_reg(instr, xmm0) vmov [m], zmm0? Or something else? Could you give an example? The function might be easily misunderstood and might be something that could be part of drx internally.

**Comment by johnfxgalea** [comment]
Done

**Comment by hgreving2304** [comment]
But OTOH vmov [m], zmm0 _does_ read from xmm0. Of course I see what you mean, I am just wondering if that is too ambiguous for the API. What about cpuid? Does it read "exactly" from eax and ecx, or not, because it's both registers?

**Comment by johnfxgalea** [comment]
I know what you mean. Let me check again my code to see if it is still necessary.
