### ISSUE TITLE
Support reg_is_vector_simd()

### ISSUE THREAD

**Issue by johnfxgalea** [DynamoRIO/dynamorio#3874]
MMX registers are completely separate registers in relation to SSE's XMM registers. The latter were expanded to larger sizes, namely YMM and ZMM. 

Often, we want to test whether a register is a SIMD extension register but not an MMX register. This issue relates to providing this functionality, i.e., it checks whether the register is either an XMM, YMM or ZMM.  

Looking at the API, I have a hunch that the now deprecated function `reg_is_xmm()` was intended to provide this requested functionality. In fact, the deprecated function currently checks whether a register is either an XMM or YMM. The name of the function just confuses matters.

**Comment by hgreving2304** [comment]
We have reg_is_strictly_xmm(), reg_is_strictly_ymm(), reg_is_strictly_zmm(). reg_is_xmm() was left as-is for backward compatibility.

**Comment by johnfxgalea** [comment]
Hey @hgreving2304, Thanks for your message. So I am aware of those functions, but this function intends to check whether a register is either an XMM, YMM or ZMM. 

It essentially avoids the need to stay performing a series of || checks. I could place this function as a static function in drreg, but I figured that it would be useful if it is included as an API function.

**Comment by Carrotman42** [comment]
When designing the _strictly_ functions we did talk about this case. I
think we talking about people just doing the || line you mentioned, and I
think we talked about adding a new single function which tested for all
three at once.

**Comment by hgreving2304** [comment]
The only downside I see here is that it would be yet another API addition. Theoretical worst case example: Intel adds yet another register class, would we keep reg_is_simd_extension() unchanged for backward compatibility? Other than that it is a convenience method.

**Comment by derekbruening** [comment]
The problem is that back in the day the MMX registers were considered an extension too, so this name doesn't seem to clarify the distinction.

Looking at _extension or _extended already in the API: We have reg_is_extended() and reg_is_avx512_extended() which refer to register set extensions in 64 vs 32-bit.  Nothing else saying _extension.  However, when we add an expanded version of an existing API function, we use the convention of naming it foo_ex() where _ex stands for "_extended" or "_extension", so this seems a little confusing versus that convention.

If there is some other name than just an _extension suffix I would prefer that.  Is there any name that Intel uses to refer to these?

**Comment by hgreving2304** [comment]
> Is there any name that Intel uses to refer to these?

At least on new chips they're often call them vector registers, analog to the area in HW where many of them are going to: VPU (vector processing unit).

**Comment by derekbruening** [comment]
I assume we would not try to shoehorn this into other architectures and an x86-specific name is ok.  Some ideas:

* reg_is_starmm
* reg_is_anymm
* reg_is_sse_simd  (where "sse" implies "sse and later expansions like avx*")
* reg_is_sse_avx_simd
* reg_is_vector_simd

**Comment by johnfxgalea** [comment]
What do you think about reg_is_vector_simd? Do we need to maintain backward compatibility of the function? Would it be okay to add another ||  reg_is_strictly_XXX() to the implementation of this function when Intel introduces another new extension in the future? If so, I think that name is good.

**Comment by hgreving2304** [comment]
We could add a line to the description saying that the function is subject to include any future vector register x86 may add. This way we avoid running into the reg_is_xmm(), reg_is_strictly_xmm() situation we were faced with the other day.

**Comment by derekbruening** [comment]
SGTM to above 2 comments

**Comment by Carrotman42** [comment]
reg_is_vector_simd + extra comment about future changes SGTM as well.
