### ISSUE TITLE
SPEC jbb'15 [jdk8] crash 

### ISSUE THREAD

**Issue by rkgithubs** [DynamoRIO/dynamorio#3878]
#3380 fixed the previously mentioned issues with AVX_ALIGNMENT. 
specjbb'15 now fails to run at the following error:

```
/home/nwpa02/tools/DynamoRIO-x86_64-Linux-7.91.18173-0/bin64/drrun -debug -loglevel 2 -- /home/nwpa02/workloads/JVM/jdk1.8.0_201/bin/java -jar /workloads/SPECjbb2015/jbb102/specjbb2015.jar -m COMPOSITE

SYSLOG_ERROR: Application /home/nwpa02/workloads/JVM/jdk1.8.0_201/bin/java (3682).  Internal Error: DynamoRIO debug check failure: /home/travis/build/DynamoRIO/dynamorio/core/dispatch.c:757 wherewasi == DR_WHERE_FCACHE || wherewasi == DR_WHERE_TRAMPOLINE || wherewasi == DR_WHERE_APP || (dcontext->go_native && wherewasi == DR_WHERE_DISPATCH)
(Error occurred @96716 frags)
```
attached log 
[java.0.3682.txt](https://github.com/DynamoRIO/dynamorio/files/3703801/java.0.3682.txt)

**Comment by derekbruening** [comment]
That assert is #3175.  (Please search the tracker before filing.)

**Comment by derekbruening** [comment]
Note that the log file for the *thread* that hit the assert is what is needed to figure out what it's doing: the global log file does not have per-thread history.  If you could attach that thread logfile to #3175.
