### ISSUE TITLE
Does DynamoRio has any basic support for Cache Load Value Prediction ?

### ISSUE THREAD

**Issue by vikas753** [DynamoRIO/dynamorio#3918]

**Comment by derekbruening** [comment]
Please use the users list https://groups.google.com/forum/#!forum/DynamoRIO-Users for questions, as it will reach a wider audience of people who might have an answer, and it will reach other users who may find the information beneficial. The issue tracker is for specific detailed bugs. If you are not sure it's a bug, please start by asking on the users list.
