### ISSUE TITLE
How to run concurrent Online simulation?

### ISSUE THREAD

**Issue by TolgaSari** [DynamoRIO/dynamorio#3929]
Hi,

I'm trying to analyze some axbench benchmarks with dynamoRIO. And some of the benchmarks take more than days with drcachesim. I tried to get offline traces but the disk gets filled in couple of minutes of the benchmark. I couldn't find anyway to shrink offline traces as it is rolling so, offline simulations are out of option. 

I know that online simulation uses 1 thread. Is there a way to run multiple online simulations with drrun ? I need to run the same benchmark with different configurations. When I try to run a second simulation gives an error and wants me to remove a stale pipe.

Then if I remove this stale pipe the first simulation gives this error 
ASSERT FAILURE: /dynamorio_package/clients/drcachesim/tracer/tracer.cpp:1749: fd != -1 ()

I tried duplicating the dynamoRIO root files and then running a second simulation, same result.
The only other option is duplicating the virtual machines. Which is not viable.

**Comment by derekbruening** [comment]
Please use the users list https://groups.google.com/forum/#!forum/DynamoRIO-Users for questions, as it will reach a wider audience of people who might have an answer, and it will reach other users who may find the information beneficial. The issue tracker is for specific detailed bugs. If you are not sure it's a bug, please start by asking on the users list.
