### ISSUE TITLE
DynamoRIO is missing writes when done inside the kernel

### ISSUE THREAD

**Issue by ZehMatt** [DynamoRIO/dynamorio#3968]
DynamoRIO is missing some cases of (self) modifying code where the kernel is involved writing the memory.

**To Reproduce**
1. Compile below code with Visual Studio 2015+, note that debug builds will not work for this purpose because debug builds have trampolines all around.

```
#include <stdio.h>
#include <stdint.h>
#include <windows.h>
#include <intrin.h>

#pragma section(".jit", execute, read)
#pragma comment(linker,"/SECTION:.jit,ERW")

#pragma code_seg(".jit")
__declspec(dllexport, noinline) int testFunction()
{
	__debugbreak();
	return 0xDEADBEEF;
}

#pragma code_seg(".text")
int main()
{	
	// mov eax, 0xBADC0FFE
	// ret
	constexpr uint8_t payload[] = { 0xB8, 0xFE, 0x0F, 0xDC, 0xBA, 0xC3 };

	HANDLE hRead;
	HANDLE hWrite;
	if (!CreatePipe(&hRead, &hWrite, nullptr, 0x1000))
	{
		printf("CreatePipe failed: %08X\n", GetLastError());
		return -1;
	}

	DWORD bytesWritten = 0;
	if(!WriteFile(hWrite, payload, sizeof(payload), &bytesWritten, nullptr) || bytesWritten != sizeof(payload))
	{
		printf("WriteFile failed: %08X\n", GetLastError());
		return -1;
	}

	// Read payload into testFunction
	DWORD bytesRead = 0;
	if (!ReadFile(hRead, testFunction, sizeof(payload), &bytesRead, nullptr) || bytesRead != sizeof(payload))
	{
		printf("ReadFile failed: %08X\n", GetLastError());
		return -1;
	}

	int res = testFunction();
	printf("Result: %08X\n", res);

	return res;
}
```
I would have assumed that DynamoRIO has some clever ways of detecting when the original memory was modified. I know this is a rather strange way to modify memory but malware and family can easily confuse instrumentation like that. It appears that Intel PIN is also not suited against this variant.

**Comment by Carrotman42** [comment]
Are you saying that the kernel is writing over the user-mode data even though the user-mode data was marked as not writeable?

**Comment by derekbruening** [comment]
DR uses multiple strategies for cache consistency.  If code is in a page marked writable, as it is here, DR will insert checks for consistency at the top of blocks and after writes.  Windows system calls are not inlined, so the ReadFile would be followed by a consistency check.  So I would expect detection and faithful execution for this method of modifying code.

In your pasted code, there is no execution of testFunction before it was modified, so I would expect any system to get it right.  I'm guess that you omitted something there.  Could you double-check that, and paste the exact output you see under DR?

**Comment by ZehMatt** [comment]
Actually it seems to be working, not sure how I managed to get inconsistent results. Also I had a little typo in the test case.
