### ISSUE TITLE
CRASH (7.91.18219) pc is null in decode_sizeof

### ISSUE THREAD

**Issue by TomSie** [DynamoRIO/dynamorio#3978]
**Describe the bug**
I am trying to run a linux x64 application, that I unfortunately cannot publish, in dynamorio.
When I run "drrun -t drcov -- application" dynamorio crashes in "decode_sizeof" as "pc" is "null" (core/arch/x86/decode_fast.c:469) 

Callstack:
decode_sizeof in decode_fast.c:465
decode_cti in decode_fast.c:1314
decode_fragment in  interp.c:7267

The error output is

<pre>
Application application (14798).  DrCov internal crash at PC 0x00000000712564f0.  Please report this at http://dynamorio.org/issues.  Program aborted.
Received SIGSEGV at pc 0x00000000712564f0 in thread 15154
Base: 0x0000000071000000
Registers:eax=0x0000000000000000 ebx=0x0000000000000200 ecx=0x00007fff34045a54 edx=0x00007fff34045a58
        esi=0x0000000000000000 edi=0x00007fff33b45b40 esp=0x00007fff340459d0 ebp=0x00007fff34045a20
        r8 =0x00007fff34045a5e r9 =0x00007fff34045ca4 r10=0x0000000000000000 r11=0x0000000000000246
        r12=0x524409d81dfa1097 r13=0xfdb854c350745776 r14=0x23f6b0b430d5da0f r15=0x4bf3295900c90260
        eflags=0x0000000000010202
version 7.91.18219, custom build
-no_dynamic_options -client_lib '/home/csafuzz/fluffi/persistent/x64/dynamorio/bin64/../clients/lib64/debug/libdrcov.so;0;' -code_api -stack_size 56K -signal_stack_size 32K -nop_initial_bblock -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native
0x00007fff34045a20 0x00000000712571d4
0x00007fff34045ae0 0x0000000071273127
0x00007fff34045c60 0x0000000071270999
0x00007fff34045cf0 0x0000000071186677
0x00007fff34045d40 0x000000007118a0aa
0x00007fff34045f10 0x00000000710c3e83
0x00007fff34045ff0 0x00007fffb3c52f0d
0x00007fff2c025140 0x90789812acf12b15
</pre>

When I run "drrun -- application", I get signal 4 (SIGILL?) in libcrypto.

<pre>
Application application (48921).  Application exception at PC 0x00007ffff68dae60.  
Signal 4 delivered to application as default action.
Callstack:
	0x00007ffff68dae60   libcrypto.so.1.1+0xdce60
	0xcbf6244203b11a7f  

</pre>

The crash seems to be inside the "__bn_postx4x_internal" function. The dissassembly there is 
<pre>
   0x00007ffff68dae50:	mov    0x0(%rbp),%r12
   0x00007ffff68dae54:	mov    0x8(%rbp),%r13
   0x00007ffff68dae58:	mov    0x10(%rbp),%r14
   0x00007ffff68dae5c:	mov    0x18(%rbp),%r15
   0x00007ffff68dae60:	andn   %rax,%r12,%r12
   0x00007ffff68dae65:	lea    0x20(%rbp),%rbp
   0x00007ffff68dae69:	andn   %rax,%r13,%r13
   0x00007ffff68dae6e:	andn   %rax,%r14,%r14
</pre>

**Versions**
I am using dynamorio commit dadb8ff2eeb173e34d9feaef6f6d8da53666a256, with "-DDEBUG=ON"

**Reproducing**
I am aware that most likely you cannot reproduce the issue on your side without me giving you the binary. However, maybe you could tell me how I could extract the info you need to understand the issue.

**Comment by derekbruening** [comment]
Could you supply the raw bytes for the ANDN instruction encoding at  0x00007ffff68dae60?

**Comment by TomSie** [comment]
<pre>
DAE50: 4C 8B 65 00 4C 8B 6D 08  4C 8B 75 10 4C 8B 7D 18 
DAE60: C4 62 98 F2 E0 48 8D 6D  20 C4 62 90 F2 E8 C4 62 
DAE70: 88 F2 F0 C4 62 80 F2 F8  49 F7 D8 4C 13 27 4C 13 
</pre>

**Comment by TomSie** [comment]
now that you mention it, it looks like the disassembly is wrong. Here is what IDA says:
![image](https://user-images.githubusercontent.com/16607413/70541927-2c2e4500-1b68-11ea-85cc-5084c131b6b7.png)

I might be wrong, but to me it looks fishy that rax is negated without having been assigned.

**Comment by TomSie** [comment]
Mhh ... although the assembly is definetively strange, it seems to be correct (see e.g. https://github.com/google/shaka-packager/blob/master/packager/third_party/boringssl/win-
x86_64/crypto/fipsmodule/x86_64-mont5.asm )

**Comment by TomSie** [comment]
Another observation: The same binary seems to contain AVX512 instructions such as "VPSHUFD zmm1 ..."
![image](https://user-images.githubusercontent.com/16607413/70543661-09516000-1b6b-11ea-93db-a8718feb992a.png)

I got it somewhere at the back of my head, that AVX512 is not yet implemented in dynamorio. Is that correct? 

Could it be that the crashes I observe are triggered by this?

**Comment by Carrotman42** [comment]
> I got it somewhere at the back of my head, that AVX512 is not yet implemented in dynamorio. Is that correct?

Comically enough, the commit you link to (dadb8ff) starts with "AVX-512 support" :) If you can recompile DynamoRIO from head, though, it'll be a good verification that whatever problem you're encountering has not already been fixed (not something I'd put money on, but it's always possible): the AVX-512 support is relatively new, but it should be working for your system (x64+Linux) afaik.

**Comment by derekbruening** [comment]
It is a bug in the DR decoder.  I can reproduce by putting those raw bytes into an app:

```
interp: start_pc = 0x0000000000401004
  0x0000000000401004  c4 62 98 f2 e0       andn   %r12 %rax -> %r12
interp: invalid instr at 0x0000000000401004
record_pending_signal(4) from DR at pc 0x0000000000401004
```

Others all agree it's a fine encoding so there is sthg wrong in DR's fast decoder or somewhere:
```
llvm-mc:   0xC4 0x62 0x98 0xF2 0xE0  andnq %rax, %r12, %r12
capstone:  c46298f2e0 andn r12, r12, rax
bfd:       c4 62 98 f2 e0 andn %rax,%r12,%r12
```

**Comment by derekbruening** [comment]
I think this is a regression in decode_cti() from the AVX-512 work.

**Comment by TomSie** [comment]
Great job! The crashes are gone!
