### ISSUE TITLE
App crash on Ryzen/Win10

### ISSUE THREAD

**Issue by kmar** [DynamoRIO/dynamorio#4011]
Due to missing support for AMD's monitorx and mwaitx, used by ntdll when running on recent AMD chips, dr reports an illegal instruction.
see https://github.com/DynamoRIO/drmemory/issues/2233

**Comment by kmar** [comment]
PR here https://github.com/DynamoRIO/dynamorio/pull/4012

**Comment by derekbruening** [comment]
Turns out #3577 already covers these two opcodes so let's mark this as a duplicate of #3577.
