### ISSUE TITLE
ASSERT Failing asserts in vmareas.c on zero-length munmap

### ISSUE THREAD

**Issue by petrochenkov** [DynamoRIO/dynamorio#4031]
If `munmap` syscall has an argument `len == 0`, then an empty memory range (`start == end`) is passed to `vmareas.c`'s `binary_search` and `add_vm_area` from `pre_system_call` and `post_system_call` respectively.

Those functions have asserts checking that the passed range is well-formed (`ASSERT(start < end || end == NULL /* wraparound */);` or `ASSERT(start < end);`) and fire on empty ranges.

Zero-length `munmap`s should always fail with `EINVAL`, but for some reason they still happen in Geekbench for Android.

**Comment by petrochenkov** [comment]
Looks like there are two alternative fixes:
- Relax the asserts to `start <= end`.
It *seems* like the binary search logic in `binary_search` and `add_vm_area` works naturally for empty ranges, but I'm not sure.
- Special-case `len == 0` in `{pre,post}_system_call` for `munmap`. Perhaps we don't need to do any work with vm areas in this case and can just return early.

Any guidance on selecting the right fix is appreciated.

**Comment by derekbruening** [comment]
Either way seems fine to me -- but the first way would want to add to the unit tests at the bottom of vmareas.c to confirm that everything works, and check other routines that may be called such as app_memory_deallocation().  Maybe the 2nd is better since it is simpler.

**Comment by Carrotman42** [comment]
I vote for the second option, given the assertion in the first post:
"Zero-length munmaps should always fail with EINVAL", which is true
according to the manpage I just read. If they should always be EINVAL, I
figure it makes sense to make that happen sooner than later.

**Comment by derekbruening** [comment]
This assert in binary_search is showing up in Mac64: https://travis-ci.com/DynamoRIO/dynamorio/jobs/287035442.  I can't reproduce it locally so it is not clear that it's the start==end case (it could be something worse).  I'm going to go ahead and put in handling for that in binary_search plus a test; hopefully it will fix this issue, which does not reproduce in PR builds very well either.

**Comment by derekbruening** [comment]
Scratch that: it is not the == case as the assert still fires sometimes: https://travis-ci.com/DynamoRIO/dynamorio/jobs/287105079

**Comment by derekbruening** [comment]
But it turns out that case is hit in the drcachesim.delay-simple test:
```
Hit delay threshold: enabling tracing.
XXXXX hit start==end case
Exiting process after ~12284 references.
```

**Comment by derekbruening** [comment]
The delay-simple instance is filed as #4097.  It looks like a real flushing bug with consequences.

**Comment by derekbruening** [comment]
The flush bug makes me hesitant to commit the patch for binary_search handling start==end as it may mask future errors.  OTOH in some cases it does seem natural to handle it.

**Comment by petrochenkov** [comment]
Status update: https://github.com/DynamoRIO/dynamorio/pull/4098 fixed `binary_search`, but a similar assert in `add_vm_area` still remains.

**Comment by petrochenkov** [comment]
The remaining assert is fixed in https://github.com/DynamoRIO/dynamorio/pull/4235.
