### ISSUE TITLE
Add further controls to lazy restoration

### ISSUE THREAD

**Issue by johnfxgalea** [DynamoRIO/dynamorio#4120]
At the moment drreg users do not have control over lazy restoration. In particular, lazy restoration is always done at the end of a basic block.

Advanced drreg users might want finer control, e.g., calling an API function like drreg_restore_all()  that restores at a particular point all spilled registers maintained by drreg. Introducing a property that turns off drreg end-of-block restoration should also be included.

**Comment by derekbruening** [comment]
This already exists.  We already have barriers that the user puts in place to restore all the lazily-not-yet-restored values.  We have already hit several use cases that needed this.

In particular, Dr. Memory is mostly ported to use drreg though that code is still on a branch:
i1795-use-drreg.  I hit several cases there where I had to augment drreg to give Dr. Memory the control it needed.

Today we have these barriers:
* drreg_restore_app_values
* drreg_restore_app_aflags

The notion of a lazy restoration barrier was documented in the user-facing docs by 359f8ee274bfdd10f6538f9db5e58c3421c13b6a

These flags control significant aspects of lazy restoration:
* drreg_bb_properties_t.DRREG_CONTAINS_SPANNING_CONTROL_FLOW
* drreg_options_t.conservative

What we're missing is interaction with DR's core mangling: that is #3798.

Are there still things you're looking for beyond those?

**Comment by johnfxgalea** [comment]
Yes I am aware of those barriers and flags.

I added functionality that provides further control. In particular, rather than waiting for unreserved registers to be restored at the end of basic blocks, the user may call  drreg_restore_all in the middle - essentially starting a fresh spilling and restoration for subsequent instructions.

This is a sub-pr which is required for a future PR that supports multiple bb case handling.

**Comment by derekbruening** [comment]
> I added functionality that provides further control. In particular, rather than waiting for unreserved registers to be restored at the end of basic blocks, the user may call drreg_restore_all in the middle - essentially starting a fresh spilling and restoration process for subsequent instructions.

Could you elaborate on how that is different from drreg_restore_app_values()?

**Comment by johnfxgalea** [comment]
It boils down to granularity. drreg_restore_app_values restores registers only used in the passed opnd. Meanwhile, drreg_restore_all restores all unreserved registers similar to restoration at the end of a basic block.

I hope I explained it well but happy to clarify further.

**Comment by derekbruening** [comment]
No, it restores *all*. Maybe you’re thinking of the version that does not
end in ‘s’?

**Comment by johnfxgalea** [comment]
Docs state: "This is a convenience routine that calls drreg_get_app_value() for every register used by opnd," 

What about regs not used in the operand which are also unreserved? This PR restores also those.

**Comment by derekbruening** [comment]
Was away from computer -- checking now: yes it does take an operand, which is not how I remembered it.  But that interface must have been what all the uses cases needed: many cases in Dr. Memory of needing a barrier, plus several DR instrumentation cases.  So we're agreed that it does not restore others, though maybe you could describe what the use case is that needs that which seems to be different from all the others?  But this seems very familiar: putting a barrier to all the lazy restores before a clean call, e.g.  I thought there was already something for that, or an issue on that.

**Comment by johnfxgalea** [comment]
Yes I have also used this feature to restore all registers prior a clean call. 

Do we agree on the benefits of the feature?

**Comment by derekbruening** [comment]
Yes.

I am still surprised that it does not already exist.  I recall a bunch of cases of internal instrumentation control flow inside one block (many cases in Dr. Memory, some in drcachesim) and clean calls (e.g., https://github.com/DynamoRIO/dynamorio/blob/master/api/samples/modxfer.c#L298) where something like this was needed and am surprised they all had just one operand they cared about.  

All this also reminds of an issue with clean calls in general where it would be nice to have an automated solution -- I think you brought it up here: https://groups.google.com/g/drmemory-users/c/hCmqh5XI9B0/m/ICeGET-RCQAJ but I never followed up.  A separate issue should probably be filed if you would like to do that.

**Comment by johnfxgalea** [comment]
> All this also reminds of an issue with clean calls in general where it would be nice to have an automated solution -- I think you brought it up here: https://groups.google.com/g/drmemory-users/c/hCmqh5XI9B0/m/ICeGET-RCQAJ but I never followed up. A separate issue should probably be filed if you would like to do that.

Yea I did.

When you say automated solution, do you mean that drreg_restore_all()  has to be called implicitly without the user invoking it prior to inserting a clean call?

**Comment by derekbruening** [comment]
> > All this also reminds of an issue with clean calls in general where it would be nice to have an automated solution -- I think you brought it up here: https://groups.google.com/g/drmemory-users/c/hCmqh5XI9B0/m/ICeGET-RCQAJ but I never followed up. A separate issue should probably be filed if you would like to do that.
> 
> Yea I did.

Could you link the issue here?  I didn't see it go by.

> 
> When you say automated solution, do you mean that drreg_restore_all() has to be called implicitly without the user invoking it prior to inserting a clean call?

Or the appropriate restore routine for that particular clean call.  E.g., probably the `drreg_restore_app_values(,, instr, instr_get_target(instr),)` should be called *every time* `dr_insert_mbr_instrumentation` is called.  And as you were pointing out maybe drwrap should be doing something, or at least telling users about it.  For arbitrary clean calls: not sure; maybe speed is best there if the issue is documented, though some users might prefer auto-restore prior to all clean calls.
