### ISSUE TITLE
`dr_get_process_id` doesn't return the expected result in `thread_exit_event` callbacks 

### ISSUE THREAD

**Issue by petrochenkov** [DynamoRIO/dynamorio#4137]
Citing the [documentation](https://dynamorio.org/dynamorio_docs/dr__events_8h.html#a0b0c102bb9a99d67c3e62ea8b3790ff1) of `void dr_register_thread_exit_event	(	void(*)(void *drcontext) 	func	)	
`:
>The passed-in drcontext should be used instead of calling dr_get_current_drcontext(), as the thread exit event may be invoked from other threads, and using dr_get_current_drcontext() can result in failure to clean up the right resources, and at process exit time it may return NULL.

The `dr_get_process_id` API doesn't take a `drcontext` parameter, so it's effectively using "the current context" when being called from thread exit callbacks, which is not recommended.

This can lead to pretty confusing results when DynamoRIO reports different process IDs for the same thread ID at different points.

Possible solution: introduce a version of `dr_get_process_id` taking a `void* drcontext` parameter that would work exactly like `thread_id_t dr_get_thread_id	(	void * 	drcontext	)`, but would return `dcontext->owning_process` rather than `dcontext->owning_thread`.

**Comment by derekbruening** [comment]
Looking at the code, on UNIX, `dr_get_process_id` calls `get_process_id` which calls `dynamorio_syscall(SYS_getpid, 0)`.  I.e., it makes a system call and will return the same value from any thread in the process (though note that a client thread is deliberately in a separate thread group).  On Windows it does indeed use the current TEB, but the ClientId.UniqueProcess field it accesses should be identical for all threads in the process.  AFAICT the code is not using `dcontext->owning_process` here.

So I'm not seeing how `dr_get_process_id` could return anything unusual.  Please provide details on how you observed different pids and their values: OS, app, etc.

**Comment by petrochenkov** [comment]
I'll try to prepare a more detailed reproduction.

The ID mismatch that I observed could be specific to threads killed by `dynamo_other_thread_exit` (e.g. in `cleanup_after_vfork_execve`).

**Comment by derekbruening** [comment]
Right, ok, so there are ways (on UNIX) the app can create a new pid where DR will still treat it as a thread, and we'll have the behavior you described; and the SYS_getpid is indeed in the executing context and not the target thread's context.

So the proposal is a new API routine that would be used in thread exit events?  OK, happy to take a PR for that, hopefully along with a test.

**Comment by petrochenkov** [comment]
The new API is added in https://github.com/DynamoRIO/dynamorio/pull/4234.
