### ISSUE TITLE
Tidy drreg extension .dox

### ISSUE THREAD

**Issue by johnfxgalea** [DynamoRIO/dynamorio#4147]
There is a mistake in the title of drreg's .dox file.

```
***************************************************************************
\page page_drreg Multi-Instrumentation Manager

```

Essentially, the title was not updated to present _drreg_.

**Comment by derekbruening** [comment]
This seems very familiar -- indeed: #2891.  Unfortunately nobody ended up fixing it.  Going to close this one as a dup.
