### ISSUE TITLE
Add parentheses to the NULL_TERMINATE macro found in many samples

### ISSUE THREAD

**Issue by johnfxgalea** [DynamoRIO/dynamorio#4160]
Put parentheses around the parameter concerning the NULL_TERMINATE macro. This macro is found in many samples.

Instead of:
`#define NULL_TERMINATE(buf) buf[(sizeof(buf) / sizeof(buf[0])) - 1] = '\0'`

we need to change to macro to
`#define NULL_TERMINATE(buf) (buf)[(sizeof((buf)) / sizeof((buf)[0])) - 1] = '\0'`

**Comment by johnfxgalea** [comment]
This was first brought up in this PR #4134

**Comment by derekbruening** [comment]
@johnfxgalea -- it looks like your email address in these commits is `@users.noreply.github.com`.  I think maybe you forgot to set it in the git config from the devsetup.sh script.

**Comment by derekbruening** [comment]
OK.  FTR the wiki officially says:
 https://github.com/DynamoRIO/dynamorio/wiki/Workflow#configuring-author-information-and-aliases says "You must also uncheck `Keep my email address private` in the email settings page."

That was to mirror various old-school open-source projects where presumably the idea is to make sure you can contact an author about a particular code patch.  Our project hosted on Github with its separate metadata on which Github user did which commit I suppose makes that not matter as much so it seems reasonable to drop that.
