### ISSUE TITLE
tool.drcachesim.coherence test failed on Travis: "Invalid trace entry type 23 before a bundle"

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#4167]
This happened once on Travis:
https://travis-ci.com/DynamoRIO/dynamorio/jobs/295374252
```
Invalid trace entry type 23 before a bundle
```

23 is (+1 here b/c 1-based):
```
$ grep '^ *TRACE_TYPE' clients/drcachesim/common/trace_entry.h | grep -n . | grep 24
24:    TRACE_TYPE_THREAD_EXIT, /**< A thread exit. */
```

**Comment by derekbruening** [comment]
Happened on `code_api|tool.drcachesim.threads-with-config-file` at http://139.178.82.61:8080/job/DynamoRIO-AArch64-Precommit/2003/consoleFull

**Comment by brettcoon** [comment]
The same issue seems to have happened on `code_api|tool.drcachesim.TLB-threads` at [http://139.178.82.61:8080/job/DynamoRIO-AArch64-Precommit/2744/consoleFull](http://139.178.82.61:8080/job/DynamoRIO-AArch64-Precommit/2744/consoleFull)

**Comment by derekbruening** [comment]
I believe this is the same as #3320.  Closing.
