### ISSUE TITLE
header file issue

### ISSUE THREAD

**Issue by cssaheel** [DynamoRIO/dynamorio#4179]
The header file:
C:\DynamoRIO-Windows-7.1.0-1\include\dr_ir_macros_x86.h

this code snippet:

```
#ifdef X64
/**
 * Create an absolute address operand encoded as pc-relative.
 * Encoding will fail if addr is out of 32-bit-signed-displacement reach.
 */
#define OPND_CREATE_ABSMEM(addr, size) opnd_create_rel_addr(addr, size)
#else
/** Create an absolute address operand. */
#define OPND_CREATE_ABSMEM(addr, size) opnd_create_abs_addr(addr, size)
#endif
```

As far as I understand, in case of x64 OPND_CREATE_ABSMEM should be translated to opnd_create_rel_addr. And in case of x86 OPND_CREATE_ABSMEM should be translated to opnd_create_abs_addr instead. I think the code need to be fixed, I think you should switch the places for the two translation of OPND_CREATE_ABSMEM. Thanks.

**Comment by johnfxgalea** [comment]
Thank you for your question. Hmm, perhaps I am missing something, but the code seems good to me. Can you please provide an example why it is incorrect? Does DynamoRIO output an error?

There are many places in the DynamoRIO that make use of OPND_CREATE_ABSMEM and I don't think we ever encountered any problems.

**Comment by cssaheel** [comment]
I am sorry, my mistake. I ran into issues with building a DynamoRIO client, and modifying that header code for some reason fixed it for me! I understand now there is nothing wrong with DynamoRIO. Thanks.
