### ISSUE TITLE
Enable heap-less IR data structures

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#4180]
DR's IR data structures were designed to have a small size footprint in the average case for DR's  mode of controlling an application without any tool attached.  In that mode, DR does not bother to fully decode all operands of most instructions, caring only about branches and other instructions that need mangling.  A key use case of DR early on was running dozens of 32-bit applications simultaneously, where some of these apps were quite large and took the entire address space, leaving DR to operate within a bounded reservation.  Thus, `instr_t` was designed to only have room for one source built-in (all you need for most branches).

However, today's typical use case is with a tool attached, where DR does decode all the operands for every single instruction.  Plus, most uses are 64-bit, where space is not as critical, and running a single application at a time.  Even more importantly, for the `drdecode` decoding/encoding library that DR exports, it is best to not use *any* heap to allow use within signal handlers and other fragile locations.

This is a feature request to either change the default `instr_t` layout or have a method of creating an `instr_t` that does not use any heap.

**Comment by derekbruening** [comment]
My proposal is to keep the IR for regular DR use the same.
We make an `instr_noalloc_t` struct which is `instr_t` plus max srcs and dsts plus encoding buffer:
```C
typedef struct instr_noalloc_t {
    instr_t instr;
    opnd_t srcs[MAX_SRCS-1];
    opnd_t dsts[MAX_DSTS];
    byte encode_buf[MAX_INSTR_LENGTH];
} instr_noalloc_t;
```

Do the C-style "subclass": add an `instr_t` flag saying whether it's an `instr_noalloc_t`.
For the flag: remove `INSTR_HAS_CUSTOM_STUB` (part if #4045 cleanup).

To use:
```
  instr_noalloc_t inst;
  instr_noalloc_init(dcontext, &inst);
```

One issue is:
```C
private_instr_encode(dcontext_t *dcontext, instr_t *instr, bool always_cache)
{
    /* We cannot use a stack buffer for encoding since our stack on x64 linux
     * can be too far to reach from our heap.  We need reachable heap.
     */
    byte *buf = heap_reachable_alloc(dcontext, MAX_INSTR_LENGTH HEAPACCT(ACCT_IR));
...
        /* if unreachable, we can't cache, since re-relativization won't work */
```

So we can use the stack buffer inside instr_noalloc_t but it won't be kept.  That is one reason to make this no-alloc struct a feature you have to explicitly choose to use, as it is best for decoding only rather than encoding.

**Comment by johnfxgalea** [comment]
hmm, where do you intend to use this? Do you plan to change a lot of instr_t usage in DR with this upper struct and use the flag to guide functionality? The latter seems a bit of an overkill.

In other words, is this more of a convenience struct or will eventually be the primary struct for an instr?

**Comment by derekbruening** [comment]
Given the complications below I am thinking of *not* using the new struct anywhere in core DR:

1. The re-relativization mentioned above; there may be a solution to that for some cases -- I have not delved into the details yet.

2. The size: on ARM you can have 33 sources or 33 dests!  With 16-byte-padded `opnd_t` that's ~1152 or sthg for `instr_noalloc_t`.  That's pretty big by DR standards.

So this would be left as only used by clients or drdecode users who are decoding inside a signal handler, plus maybe general code using drdecode might use it everywhere for simplicity.

**Comment by derekbruening** [comment]
Meant to say that for the ARM size we could do some kind of union since you wouldn't have a big list of sources *and* a big list of dests.  But the struct ends up still being pretty large.   Usage that builds instructions and puts many of them into a list would probably use heap anyway for the struct itself.  Maybe core DR could use this when it's only decoding and has just one struct on the stack.  But again it does not seem simple to change the basic struct used everywhere without downsides.

**Comment by AssadHashmi** [comment]
Just to add that the size of the struct for ARM will increase with the addition of SVE vector and predicate registers, which we plan to add as SVE hardware starts appearing in the mainstream.

**Comment by derekbruening** [comment]
> Just to add that the size of the struct for ARM will increase with the addition of SVE vector and predicate registers, which we plan to add as SVE hardware starts appearing in the mainstream.

I believe you mean AArch64, right?  The ARM with the 33 sources from register lists is 32-bit.  So perhaps AArch64 will grow and approach that number.

**Comment by AssadHashmi** [comment]
> I believe you mean AArch64, right? The ARM with the 33 sources from register lists is 32-bit. 

Oops, sorry, yes! I meant AArch64. Must learn to read comments more diligently, i.e:
> Plus, most uses are 64-bit, where space is not as critical...

Regarding the AArch64 footprint:
> So perhaps AArch64 will grow and approach that number.

Possibly. I don't know enough about the current layout and its limits but I do know that the SVE spec says the largest vector size can be 2048 bits. So with 32 vector registers, that's 8K bytes, not including predicates.

**Comment by derekbruening** [comment]
> > So perhaps AArch64 will grow and approach that number.
> 
> Possibly. I don't know enough about the current layout and its limits but I do know that the SVE spec says the largest vector size can be 2048 bits. So with 32 vector registers, that's 8K bytes, not including predicates.

Not sure I follow these numbers: 2048 is the width of a vector register?  Or the number of named sub-slots where each could be an operand?  Here we're just looking at the list of source and destination operands for an `instr_t`, so the width of a register does not matter, just how many different registers names can be passed to one instruction as separate operands.  32-bit ARM has those register lists where you can have something like `VSTM s0-s31` with 32 operands right there.
