### ISSUE TITLE
AArch64 Jenkins machine is not using the latest runsuite_wrapper.pl

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#4189]
The changes I made recently to runsuite_wrapper.pl in PR #4165 do not seem to be reflected in the Jenkins tests.  When I look at the details such as here http://139.178.83.194:8080/job/DynamoRIO-AArch64-Precommit/1165/console I see a test failing that should be ignored by the wrapper (code_api|tool.drcachesim.invariants).  Looking at the commands run it seems to copy a version of the script from somewhere else:

```
+ cp /home/assad/dynamorio/suite/runsuite_wrapper.pl suite/runsuite_wrapper.pl
+ mkdir build
+ cd build
+ ../suite/runsuite_wrapper.pl travis
```

Hopefully we can just change this to use the checked-in version?

**Comment by AssadHashmi** [comment]
> Hopefully we can just change this to use the checked-in version?
Yes. This mod was a temporary workaround which wasn't removed when it should have been, apologies. I've updated the commands in the precommit config and will keep an eye on the pipeline.

**Comment by derekbruening** [comment]
@AssadHashmi -- this can be closed?

**Comment by AssadHashmi** [comment]
Oops! Yes, closing...
