### ISSUE TITLE
crash in privload_call_lib_func i386 , when use client with drrun.

### ISSUE THREAD

**Issue by hac425xxx** [DynamoRIO/dynamorio#4200]
platform
```
i386 ubuntu 18
```

version
```
https://github.com/DynamoRIO/dynamorio/releases/download/cronbuild-7.91.18319/DynamoRIO-Linux-7.91.18319.tar.gz

master also has this bug.
```

when run drrun with client , it could crash.

```
drrun -c samples/bin32/libinscount.so  -- ./filefuzz
<Application /xxx/filefuzz (101859).  DynamoRIO internal crash at PC 0x00000035.  Please report this at http://dynamorio.org/issues/.  Program aborted.
Received SIGSEGV at unknown pc 0x00000035 in thread 101859
Base: 0xf7d27000
Registers:eax=0x00000000 ebx=0xff8c8e20 ecx=0x00000035 edx=0xf7a82a40
	esi=0xf7f260dc edi=0xff8c8e14 esp=0xff8c8dfc ebp=0xff8c8e1a
	eflags=0x00010282
version 7.91.18319, custom build
-no_dynamic_options -client_lib '/xxxx/samples/bin32/libinscount.so;0;' -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2d

```

this is the backtrace of this bug
```
(gdb) bt
#0  0x00000035 in ?? ()
#1  0xf7f07e59 in privload_call_lib_func (func=0x35) at /home/travis/build/DynamoRIO/dynamorio/core/unix/loader.c:990
#2  privload_call_entry (dcontext=0xf7fb6000, privmod=0xffffcd54, reason=4159886336) at /home/travis/build/DynamoRIO/dynamorio/core/unix/loader.c:619
#3  0x00000000 in ?? ()
(gdb) quit

```

**Comment by hac425xxx** [comment]
It seem's, this commit import the bug
```
https://github.com/DynamoRIO/dynamorio/commit/eab941b43e5aef8447aeb924883c5552aacd9a3e
```

**Comment by johnfxgalea** [comment]
I confirm this happening on my machine too. It seems that this is not just a particular issue of libinscount.so but also other clients.

What I noted is that if I I run it under debug mode it works right?

**Comment by johnfxgalea** [comment]
Also, what gcc version are you using please?

**Comment by hac425xxx** [comment]
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)

**Comment by hac425xxx** [comment]
I comment the assembly code in privload_call_lib_func, and it works
```

static void
privload_call_lib_func(fp_t func)
{
    char dummy_str[] = "dummy";
    char *dummy_argv[2];
    /* FIXME: i#475
     * The regular loader always passes argc, argv and env to libaries,
     * (see libc code elf/dl-init.c), which might be ignored by those
     * routines.
     * we create dummy argc and argv, and passed with the real __environ.
     */
    dummy_argv[0] = dummy_str;
    dummy_argv[1] = NULL;
    func(1, dummy_argv, our_environ);
}

```

**Comment by johnfxgalea** [comment]
@derekbruening any idea what is wrong since it seems that it concerns your commit? If you do not got time, I'll try and have a look at a fix.

**Comment by derekbruening** [comment]
No, the asm looks fine.  Maybe we should go ahead and abandon the 4-byte stack alignment.  Maybe a good time for it if we put out a new DR release afterward (better now that after).

**Comment by derekbruening** [comment]
@johnfxgalea if you have time to switch to 16-byte stack alignment everywhere, and I get #3995 finished, we may be all set then for the 8.0 release (except we have to figure out #4126 which is blocking all package builds including an 8.0 one...)

**Comment by johnfxgalea** [comment]
> everywhere

Sure. What do you mean everywhere? Are there more cases than just the one mentioned by OP?

**Comment by derekbruening** [comment]
See https://github.com/DynamoRIO/dynamorio/issues/3966#issuecomment-558445312

**Comment by derekbruening** [comment]
Interestingly, on my machine I do not see any crashes with 32-bit libinscount.so.  If I remove eab941b then I see the crash at exit #3966 that it fixes.

**Comment by derekbruening** [comment]
I take it back: as @johnfxgalea said, there is no crash in debug build.  In release I can reproduce the up-front crash.  But without eab941b it still crashes, at exit.

@johnfxgalea unless you already have this in a branch I'll take it.  I just did an experiment and doing the proposed switch to 16-byte stack alignment does fix the release build crash on my machine.
