### ISSUE TITLE
DynamoRIO wrapped malloc should guarantee 16-byte heap alignment

### ISSUE THREAD

**Issue by SweetVishnya** [DynamoRIO/dynamorio#4237]
MOVDQA requires 16-byte memory alignment. DynamoRIO malloc does not align by 16 bytes. Unaligned memory access causes a crash. More information can be found in [Google Groups](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/dynamorio-users/BlPaJytSH4o).

**Comment by derekbruening** [comment]
The main issue is third-party malloc where the private loader redirects it.  DR's internal allocator can do whatever is best for DR's own allocs, but the wrapped interface should certainly match what general allocators provide.  For the client-facing allocation interfaces dr_global_alloc and dr_thread_alloc: probably they should align to 16 (for 64-bit at least) as well but it is less clear there where there's history and other solutions.

**Comment by SweetVishnya** [comment]
32-bit code can also use libraries containing MOVDQA instructions.

**Comment by derekbruening** [comment]
32-bit mallocs generally do not guarantee 16-byte alignment: only 64-bit.  32-bit only guarantees 8-byte alignment, for glibc malloc, HeapAlloc, etc. AFAIK.  It seems reasonable for DR to match that.
