### ISSUE TITLE
issue with getting the instruction raw bits

### ISSUE THREAD

**Issue by cssaheel** [DynamoRIO/dynamorio#4266]
hello,

I am running into runtime errors when I try to fetch the instruction raw bytes, basically I would like to retrieve the full instruction (i.e., opcodes and operands) in the form of an array of bytes.

this is my code:
dr_fprintf(STDERR, "instruction name = %s\n", decode_opcode_name(instr_get_opcode(current_instruction)));
    dr_fprintf(STDERR, "instruction raw bits = 0x%08x\n", instr_get_raw_bits(current_instruction));

this is the output:
instruction name = mov
instruction raw bits = 0x00000000

why I am getting 0x00000000? please help, thank you in advance.

**Comment by derekbruening** [comment]
Please use the users list https://groups.google.com/forum/#!forum/DynamoRIO-Users for questions, as it will reach a wider audience of people who might have an answer, and it will reach other users who may find the information beneficial. The issue tracker is for specific detailed bugs. If you are not sure it's a bug, please start by asking on the users list.
