### ISSUE TITLE
AArch64 static DR link error: relocation out of range for unexpected_return

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#4304]
```
ld.lld: error: ..._core_arch_aarch64_aarch64.o:(.text+0x2C): relocation R_AARCH64_CONDBR19 out of range: 1508388 is not in [-1048576, 1048575]; references unexpected_return
>>> defined in ..._core_drlibc_drlibc_xarch.o
```

I can solve by moving `unexpected_return` into aarch64.asm.  It is in fact not referenced in drlibc for A64 (only for x86).

**Comment by derekbruening** [comment]
@AssadHashmi do you have any experience with this relocation linker error?

**Comment by AssadHashmi** [comment]
> @AssadHashmi do you have any experience with this relocation linker error?

I have not seen this linker error before.

**Comment by AssadHashmi** [comment]
@derekbruening could be that by moving target `unexpected_return` into `aarch64.asm` the linker can put branch+target in the same ELF section, whereas it could not do that with target in `asm_defines.asm`?

**Comment by derekbruening** [comment]
`unexpected_return` is currently in drlibc, which is built as a separate static library, which must be part of what triggers this.  To make sure I understand it: because it was a separate library (or perhaps for any separate compilation), it's the linker who's going to notice that a direct branch cannot reach its target, and that will show up as a relocation error like this one with its 1MB range?  I.e., this error is purely a direct branch limited by the ISA to 1MB reach and the linker can't get it close enough, and this is not any kind of linker-loader-toolchain-only problem with using the wrong type of relocation.

Looking more closely we found that we had a similar issue with linking on x86 a year or two ago when drlibc was first separated, and in fact we had to build the drlibc files directly into the final target, instead of making a static library first, to solve it.  The error there was:

```
ld.lld: error: relocation R_X86_64_PC32 cannot be used against symbol unexpected_return; recompile with -fPIC
>>> defined in ..._core_arch_x86_x86.o
>>> referenced by ..._core_arch_x86_x86.o:(.text+0x5A)
```

Everything there was -fPIC.  But maybe that is a separate issue since you'd expect the 2GB reach of `jmp` on x86 to reach.  For that `R_X86_64_PC32` error, @abhinav92003 searched around and found https://bugs.llvm.org/show_bug.cgi?id=38037 which involved a 10GB symbol list, and cases where -fPIC was not present (it is present in our case).

**Comment by AssadHashmi** [comment]
> To make sure I understand it: because it was a separate library (or perhaps for any separate compilation), it's the linker who's going to notice that a direct branch cannot reach its target, and that will show up as a relocation error like this one with its 1MB range? I.e., this error is purely a direct branch limited by the ISA to 1MB reach and the linker can't get it close enough, and this is not any kind of linker-loader-toolchain-only problem with using the wrong type of relocation.

Yes, that is the case AIUI. The `R_AARCH64_CONDBR19` error implies that the branch limit is 19 bit signed immediate.
