### ISSUE TITLE
config-time failure not reported as error by runsuite_wrapper

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#4312]
In a PR #4309 I broke the AArch64 build by forgetting to include a new
file.  But it was reported as green:

39.178.83.194:8080/job/DynamoRIO-AArch64-Precommit/1382/console

```
CMake Error: Cannot determine link language for target "drmemfuncs".
CMake Error in core/CMakeLists.txt:
  Exporting the target "drmemfuncs" is not allowed since its linker language
  cannot be determined
Command exited with the value: 1
Error(s) when configuring the project

CMake Error at /var/lib/jenkins/.jenkins/workspace/DynamoRIO-AArch64-Precommit/suite/runsuite_common_post.cmake:118 (file):
  file failed to open for reading (No such file or directory):

    /var/lib/jenkins/.jenkins/workspace/DynamoRIO-AArch64-Precommit/build/xml:results/___debug-internal-64___Experimental___XML___Build.xml
Call Stack (most recent call first):
  /var/lib/jenkins/.jenkins/workspace/DynamoRIO-AArch64-Precommit/suite/runsuite.cmake:545 (include)

CMake Error at /var/lib/jenkins/.jenkins/workspace/DynamoRIO-AArch64-Precommit/suite/runsuite_common_post.cmake:118 (file):
  file failed to open for reading (No such file or directory):

    /var/lib/jenkins/.jenkins/workspace/DynamoRIO-AArch64-Precommit/build/xml:results/___release-external-64___Experimental___XML___Build.xml
Call Stack (most recent call first):
  /var/lib/jenkins/.jenkins/workspace/DynamoRIO-AArch64-Precommit/suite/runsuite.cmake:545 (include)
```

So it did indeed fail. But the wrapper script fails to detect the
config-time failure as an overall error (too loose in ignoring cross-arch
build attempts in multi-build setup?) and it showed up green.  Xref test
failures not being reported on Mac: #4022, but I think that's completely
different.

**Comment by AssadHashmi** [comment]
> But it was reported as green

Gah! :-(
Do such cmake/config errors also get ignored in other builds?
I'm assuming `runsuite_wrapper.pl` is also used by X86_64.

**Comment by derekbruening** [comment]
I think this is an issue with the underlying runsuite_common_post.cmake and so would indeed show up on the other builds: not something specific to AArch64 or Jenkins.  But I suspect it's some sort of regression, maybe due to a change in how CMake operates, versus CMake 2.x or something, since in the (distant) past this would be reported.  Trying to reproduce locally now.

**Comment by derekbruening** [comment]
Yeah it looks like this comes from CMake 3.x splitting off "generating" as a separate step from "configuring" and the precise string our scripts look for does not match for an error during "generating".
