### ISSUE TITLE
Add AArch64 support for restartable sequences

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#4316]
This covers adding AArch64 support to bring it into parity with x86 for restartable sequence ("rseq") handling which was added as part of #2350.

**Comment by derekbruening** [comment]
Rseq requries a Linux kernel version 4.18+.  Both the TX1 and Jenkins are too old.  I have an internal machine I am currently testing on, but for regression tests it would be best if the Jenkins machine actually had rseq support (the test will still gracefully pass by just doing nothing if rseq is not there).  @AssadHashmi would it be possible to upgrade the Jenkins kernel to 4.18+ for rseq support?

**Comment by AssadHashmi** [comment]
@derekbruening we will shortly be migrating the existing Jenkins to a newer machine: an Ampere Altra!
We would prefer to wait and do such work as part of that migration.
We don't have an accurate ETA yet but the request has been approved and provisioning will be scheduled shortly.
I'll contact them requesting kernel version >4.18.

**Comment by derekbruening** [comment]
Thanks, sounds good.

**Comment by derekbruening** [comment]
I enabled 3 linux.rseq* tests under QEMU because they pass there, but on inspection QEMU is returning ENOSYS for rseq: so they are not testing full functionality.
