### ISSUE TITLE
ARM32 opcode_count returns always zero

### ISSUE THREAD

**Issue by bernhardklein** [DynamoRIO/dynamorio#4326]
Hello together,

thank you for your engagement in the project. I'm new to this project and it is exiting.
However I run into some trouble and maybe some of you can help me out.

When I run a command like:
`./bin32/drrun -c api/bin/libopcode_count.so -opcode 36 -- ls`
I always get:
`0/0 instructions executed`
executed on a arm device, a Raspberry Pi 3B or Pi4. I tried a lot of different opcodes it always looks the same. 
If I instead run it on a a x86 based machine I get plausible results.

Is the opcode_count sample not yet supported for arm devices? Or am I doing something wrong?

Thank you very much!

Best Regards Bernhard

**Comment by AssadHashmi** [comment]
Hi @bernhardklein, which build version of DynamoRIO are you using?

As a sanity test, can you run the following and check that a non-zero value appears for the instruction count:
`./bin32/drrun -c api/bin/libinscount.so -- ls`

Can you run the following and paste the output? We can check whether opcode 36 (cmp) appears in the list at the end of the run:
`./bin32/drrun -c api/bin/libopcodes.so -opcode 36 -- ls`

**Comment by bernhardklein** [comment]
Hi @AssadHashmi thank you for your super fast help :-)

At the moment I work with git commit 8551f131d97490203c2fedfbef2da9314a3ea45a. However, I got the same results with the prebuild DynamoRIO-ARM-Linux-EABIHF-8.0.1841 release.

`libinscount` seems to work, it reports: `613880 instructions executed`

the result of `./bin32/drrun -c api/bin/libopcodes.so -opcode 36 -- ls`:
`Client opcodes is running
Inconsistency detected by ld.so: do-rel.h: 116: elf_dynamic_do_Rel: Assertion map->l_info[VERSYMIDX (DT_VERSYM)] != NULL' failed!
Top 15 opcode execution counts in 32-bit ARM mode:
         10 : stmdb
         10 : uqsub8
         11 : lsl
         13 : rsb
         15 : clz
         15 : mvn
         16 : bl
         50 : sub
         55 : subs
         69 : orr
         77 : str
        132 : ldrb
        133 : ldr
        159 : add
        166 : mov
        312 : b
        463 : cmp`

Yes cmp appears, so I would assume that it should work with `opcode_count` as well.

Thank you!

**Comment by AssadHashmi** [comment]
This implies the Arm 32 bit `opcode_count.cpp` is buggy. Marking this issue appropriately.

However, you should be able to use the working `libopcodes.so` client to get the information you want, e.g. `463 : cmp`.

**Comment by johnfxgalea** [comment]
@bernhardklein @AssadHashmi Thanks for the report. I'm going to look into this now.

**Comment by bernhardklein** [comment]
Ok. Yes I can use it as a workaround. 

Thank you guys!

**Comment by johnfxgalea** [comment]
Okay, I found the root-cause. DRX_COUNTER_LOCK is not yet supported on ARM. I'm going to add a patch now.
