### ISSUE TITLE
Test application on RHEL 7.8 with DynamoRio-Linux 8.0.0 runs out of memory and program gets aborted

### ISSUE THREAD

**Issue by SCVARSH** [DynamoRIO/dynamorio#4334]
We have a 64-bit test application for RHEL 7.8 that can run natively for more 24+ hours. But when it is run under DynamoRio-Linux 8.0.0 without any client, it gets aborted by the RHEL OS in ~10 minutes,

	$  /opt/dr-8.0.0-1/bin64/drrun -version
	drrun version 8.0.0 -- build 1
	$ date ; /opt/dr-8.0.0-1/bin64/drrun -- ./execute ; date
	Wed Jun 24 17:36:13 EDT 2020
	server: got connection from 127.0.0.1 port 59154
	<Out of memory.  Program aborted.>
	Wed Jun 24 17:49:14 EDT 2020

When run under the DynamoRio-Linux 7.1.0 release without any client, it runs out of memory in about 1 hour.

We have examined the memory usage using the "pmap" command at different time intervals. When the application is run natively, the total memory usage does not change. But under, DR 8.0.0 or DR 7.1.0, we notice increasing total memory usage with the time.

We would appreciate any help you can provide in the debug of this problem.

**Comment by SCVARSH** [comment]
The test application executable for a 64-bit RHEL 7.8 system is attached. 
The attached zip file is a collection of the application executable and the support files necessary to run this application.
The zip file will unzip in a "testapp/" sub-directory. 
[testapp_zip.zip](https://github.com/DynamoRIO/dynamorio/files/4828604/testapp_zip.zip)

There is a README.txt file that has instructions to run the application.

$ cat ./testapp/README.txt

This is a test application compiled for a RHEL 7 64-bit system
The test is run on a RHEL 7.8 64-bit VM
The test application waits for a socket connection from another terminal.

Usage Example:

From one terminal:
        $  cd ./testapp
        $  export LD_LIBRARY_PATH=./
        $ ./execute
        <-... the application waits for socket connection from another terminal ...->

From another terminal:
        $ python testrwx.py

**Comment by derekbruening** [comment]
I would first run debug build (`-debug`) and A) confirm the problem reproduces there and B) see whether any debug checks fire which may help and C) debug build enables logging which can provide a ton of information.

Xref https://github.com/DynamoRIO/dynamorio/wiki/Debugging, https://github.com/DynamoRIO/dynamorio/wiki/Logfiles

Statistics on memory usage and general counts of things are available in release build via `-rstats_to_stderr`, and in debug stats are dumped periodically to the global and per-thread logfiles.

If no asserts fire, I would first check how big this app is: does it look like it's just running a ton of code, or does it look like a leak (guessing the latter unless it generates random code of enormous size: but we've tested such apps before).

Something like `-go_native_at_bb_count` could be used to try to zero in on the leak trigger, assuming there's a single trigger, via binary search (get the total count from the stats).

**Comment by SCVARSH** [comment]
Thanks Derek for the suggestions.

I ran the application with "-debug -loglevel 2". It ran for 5+ hours before the application exception was seen. Without debug, it runs out of memory in ~10 minutes.  

The zip file size of the log directory is ~512MBytes. This file is too big to post here. There are logs for 16631 threads. I am not sure what log files to review. Any suggestions will be helpful.

Below is the terminal output of the application running under DR,
------------------------------------------------------------------------
Thu_ Jun 25 13:32:25 EDT 2020
[virsec@redhat7 testapp]$ /opt/dr-8.0.0-1/bin64/drrun -debug -loglevel 2 -rstats_to_stderr -- ./execute ; date
<log dir=/opt/dr-8.0.0-1/bin64/../logs/execute.21793.00000000>
<Starting application /opt/testapp/execute (21793)>
<Initial options = -no_dynamic_options -rstats_to_stderr -loglevel 2 -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
<Paste into GDB to debug DynamoRIO clients:
set confirm off
add-symbol-file '/opt/dr-8.0.0-1/lib64/debug/libdynamorio.so' 0x00007fe466105fe0
>
<CURIOSITY : max_end > mod_base in file /home/travis/build/DynamoRIO/dynamorio/core/unix/module_elf.c line 438
version 8.0.0, build 1
-no_dynamic_options -rstats_to_stderr -loglevel 2 -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct
0x00007ffcc6249150 0x00007fe4663b9ea1
0x00007ffcc6249200 0x00007fe4663ad61d
0x00007ffcc62492b0 0x00007fe46627d165
0x00007ffcc6249310 0x00007fe46627d799
0x00007ffcc6249360 0x00007fe466392daa
0x00007ffcc6249400 0x00007fe466393643
0x00007ffcc62494d0 0x00007fe4662556d1
0x00007ffcc6249580 0x00007fe46611785e
0x00007ffcc6249db0 0x00007fe4663b4c4d
0x00007ffcc624ae60 0x00007fe4663641bd>
<get_memory_info mismatch! (can happen if os combines entries in /proc/pid/maps)
        os says: 0x00007fe3e5e9d000-0x00007fe3e5e9e000 prot=0x00000003
        cache says: 0x00007fe3e5e9d000-0x00007fe3e5e9f000 prot=0x00000003
>
<(1+x) Handling our fault in a TRY at 0x00007fe4663646b2>

server: got connection from 127.0.0.1 port 59314
<writing to executable region.>
^C<Application /opt/testapp/execute (21793).  Application exception at PC 0x00007fe3e586c015.
Signal 2 delivered to application as default action.
Callstack:
        0x00007fe3e586c015   </usr/lib64/libpthread-2.17.so+0x9015>
        0x00007fe3e4a6a050
>
<Stopping application /opt/testapp/execute (21793)>
DynamoRIO statistics:
              Peak threads under DynamoRIO control :                 4
                              Threads ever created :             16633
                                 System calls, pre :             79496
                                System calls, post :             62859
                                 Application mmaps :              8244
                               Application munmaps :              8204
        Synch attempt failure b/c not at safe spot :                65
                   Basic block fragments generated :            215294
                         Trace fragments generated :               628
             Peak fcache combined capacity (bytes) :            651264
                    Peak fcache units on live list :                16
                    Peak fcache units on free list :                 5
                Peak special heap capacity (bytes) :            159744
                      Peak heap units on live list :             16681
                      Peak heap units on free list :                 5
                       Peak stack capacity (bytes) :            417792
                        Peak heap capacity (bytes) :         142913536
                 Peak total memory from OS (bytes) :         555233280
                          Peak vmm blocks for heap :            134972
                         Peak vmm blocks for cache :               336
                         Peak vmm blocks for stack :               120
                  Peak vmm blocks for special heap :                92
                  Peak vmm blocks for special mmap :                35
            Peak vmm virtual memory in use (bytes) :         555233280

[virsec@redhat7 testapp]$ date
Thu Jun 25 18:45:57 EDT 2020
[virsec@redhat7 testapp]$

This is output of the "/proc/meminfo" command
-----------------------------------------------------
$ cat /proc/meminfo ; date
MemTotal:       16155388 kB
MemFree:         6988824 kB
MemAvailable:   15255060 kB
Buffers:          205616 kB
Cached:          8117708 kB
SwapCached:            0 kB
Active:          6601292 kB
Inactive:        1874780 kB
Active(anon):     178464 kB
Inactive(anon):     8808 kB
Active(file):    6422828 kB
Inactive(file):  1865972 kB
Unevictable:       29348 kB
Mlocked:           29348 kB
SwapTotal:       8191996 kB
SwapFree:        8191996 kB
Dirty:                32 kB
Writeback:             0 kB
AnonPages:        182224 kB
Mapped:            55948 kB
Shmem:             29628 kB
Slab:             380032 kB
SReclaimable:     315268 kB
SUnreclaim:        64764 kB
KernelStack:        4112 kB
PageTables:        18616 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    16269688 kB
Committed_AS:     960332 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      176992 kB
VmallocChunk:   34359341052 kB
Percpu:             1408 kB
HardwareCorrupted:     0 kB
AnonHugePages:     83968 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       75712 kB
DirectMap2M:     5056512 kB
DirectMap1G:    11534336 kB
Thu Jun 25 18:45:21 EDT 2020


[testapp_zip.zip](https://github.com/DynamoRIO/dynamorio/files/4834513/testapp_zip.zip)

**Comment by SCVARSH** [comment]
With "logelevel 1", the "**Internal Error: DynamoRIO debug check failure**:" occurred in ~ 23 hours,

$ date ; /opt/dr-8.0.0-1/bin64/drrun -debug -loglevel 1 -rstats_to_stderr -- ./execute ; date
Fri Jun 26 10:17:11 EDT 2020
<log dir=/opt/dr-8.0.0-1/bin64/../logs/execute.7095.00000000>
<Starting application /opt/testapp/execute (7095)>
...
...
server: got connection from 127.0.0.1 port 59434
<writing to executable region.>
<CURIOSITY : (0) && "running low on vm reserve" in file /home/travis/build/DynamoRIO/dynamorio/core/heap.c line 1545
version 8.0.0, build 1
...
...
<proactive reset @ 493918 fragments>
<Application /opt/testapp/execute (7095).  **Internal Error: DynamoRIO debug check failure:** /home/travis/build/DynamoRIO/dynamorio/core/dispatch.c:757 wherewasi == DR_WHERE_FCACHE || wherewasi == DR_WHERE_TRAMPOLINE || wherewasi == DR_WHERE_APP || (dcontext->go_native && wherewasi == DR_WHERE_DISPATCH)
(Error occurred @493918 frags)
version 8.0.0, build 1
-no_dynamic_options -rstats_to_stderr -loglevel 1 -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
Sat Jun 27 09:41:47 EDT 2020

There are logs for 29431 threads. The "Internal Error: DynamoRIO debug" is recorded in 2 files, "execute.0.7095.html" and "log.29430.10795.html". In these 2 files, there are numerous instances of "pad_jmps excess instances failed" and "pad_jmps excess bytes failed" messages, e.g., 
     -pad_jmps excess instances failed to be returned :             13536
     -pad_jmps excess bytes failed to be returned :            171204


The file "execute.0.7095.html" is too large to post here. So, I am posting a truncated version of this file, "truncated-execute.0.7095.html" and also the "log.29430.10795.html" file.

I am not familiar with DR internals. So, I will appreciate any suggestions as to how to debug this error further. PLEASE HELP!

With the debug build, the application runs very slow and it takes too long to reproduce the problem. Whereas with the release build, it takes only ~10 minutes for the problem to occur. Is there a way to run with the debug build but make it run faster by may be reducing the number of checks the debug build is doing?

Thanks.

[DR-8.0.0-Internal-Error-debuglevel-1-after-23hrs-2020-06-27.zip](https://github.com/DynamoRIO/dynamorio/files/4846851/DR-8.0.0-Internal-Error-debuglevel-1-after-23hrs-2020-06-27.zip)
[truncated-execute.0.7095.zip](https://github.com/DynamoRIO/dynamorio/files/4846860/truncated-execute.0.7095.zip)
[log.29430.10795.zip](https://github.com/DynamoRIO/dynamorio/files/4846862/log.29430.10795.zip)

**Comment by derekbruening** [comment]
> Is there a way to run with the debug build but make it run faster by may be reducing the number of checks the debug build is doing?

`-checklevel 0` or `-checklevel 1`.

> I ran the application with "-debug -loglevel 2". It ran for 5+ hours before the application exception was seen.
> Thu_ Jun 25 13:32:25 EDT 2020
> ^C<Application /opt/testapp/execute (21793).  Application exception at PC 0x00007fe3e586c015.
> Signal 2 delivered to application as default action.
> Thu Jun 25 18:45:57 EDT 2020

I don't see an (internally-generated) exception there after the 5+ hours?  It looks like you pressed ^C which sends SIGINT which is the reason for the "Application exception" printout.

>              Peak threads under DynamoRIO control :                 4
>                              Threads ever created :             16633

Is this normal native behavior, to keep killing and generating new threads so that there are never more than 4 at a time but it churns through *thousands* of them, with no client??  That looks suspicious.  Why are those threads exiting (log files should show final syscall)?  Do you expect the server to do this natively?

>                   Basic block fragments generated :            215294
>             Peak fcache combined capacity (bytes) :            651264

So it's not running a ridiculous amount of code: so code is not the source of the OOM.

>                      Peak heap units on live list :             16681
>                        Peak heap capacity (bytes) :         142913536
>                 Peak total memory from OS (bytes) :         555233280

So the heap usage is way high for that much code.  Total mem usage for default configs is often ~10x executed code size but this is way higher.  Where is that memory going?  Look at the heap breakdown in the main logfile which looks like this example from a tiny app:

```
Updated-at-end Process (max is total of maxes) heap breakdown:
BB Fragments: cur=    0K, max=  208K, #=   1931, 1=  280, new=  208K, re=   15K
Coarse Links: cur=    0K, max=    0K, #=      0, 1=    0, new=    0K, re=    0K
...
  Clean Call: cur=    0K, max=    0K, #=      2, 1=   16, new=    0K, re=    0K
       Other: cur=    0K, max=   59K, #=    379, 1=27000, new=   56K, re=    6K

```

**Comment by SCVARSH** [comment]
This is a test application. This application, based on a request received, creates a new thread that mmap's new pages, changes permission to "rwx", writes some code into it,  executes the code,  unmap's the page, and then exits. Each request is served in a new thread.

This application uses a pthread_create() and pthread_join() to serve each request. The new thread after doing the above set of operations uses pthread_exit() to exit the thread. Prior to your previous comment, the thread used to do just return() at the end of thread that implies an implicit call to pthread_exit(). We tried changing the return() to pthread_exit() to terminate the new thread but that does not change the DynamoRio instrumentation behavior of running out of memory and the application getting killed.

Without being instrumented (i.e., running natively), this application can run for days. But when it is running under DR version 8.0.0 release build, it runs out of memory and gets aborted in about 10 minutes. With debug build with "-debug -loglevel 1 -checklevel 0" options, it seems to run out of "vmm_heap_memory" in about 2.5 hours.

See below the terminal output showing the error "vmm_heap_commit:oom" "Out of memory" error with "-debug -loglevel 1 -checklevel 0" run before change to pthread_exit() from return,

$ date ; /opt/dr-8.0.0-1/bin64/drrun -debug -loglevel 1 -checklevel 0 -rstats_to_stderr -- ./execute ; date
Mon Jun 29 18:22:02 EDT 2020
<log dir=/opt/dr-8.0.0-1/bin64/../logs/execute.24655.00000000>
<Starting application /opt/testapp/execute (24655)>
<Initial options = -no_dynamic_options -rstats_to_stderr -loglevel 1 -checklevel 0 -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
<Paste into GDB to debug DynamoRIO clients:
set confirm off
add-symbol-file '/opt/dr-8.0.0-1/lib64/debug/libdynamorio.so' 0x00007fdd7a3d0fe0
>
server: got connection from 127.0.0.1 port 38220
<writing to executable region.>
<proactive reset @ 413948 fragments>
<proactive reset @ 453279 fragments>
<vmm_heap_commit oom: timeout and retry>
<vmm_heap_commit retrying, no luck.  old=0x000000000000000c new=0x000000000000000c
>
<Out of memory - cannot extend commit 4KB. Trying to recover.>
<vmm_heap_commit oom: timeout and retry>
<vmm_heap_commit retrying, no luck.  old=0x000000000000000c new=0x000000000000000c
>
<Out of memory.  Program aborted.>
<OOM Status: C 0x000000000000000c>
Mon Jun 29 20:41:22 EDT 2020
$

Please see the attached truncated process main log file, "truncated-execute.0.7095.zip" and log of the last thread, "log.29430.10795", for detailed statistics.
[log.29430.10795.zip](https://github.com/DynamoRIO/dynamorio/files/4854294/log.29430.10795.zip)
[truncated-execute.0.7095.zip](https://github.com/DynamoRIO/dynamorio/files/4854295/truncated-execute.0.7095.zip)

There is another test running with the "-debug -loglevel 2 -checklevel 0" options. I will post the results when the error occurs.

**Comment by SCVARSH** [comment]
This is the "Out of memory" log of instrumenting with DR 8.0.0 running with the "-debug -loglevel 2 -checklevel 0" options. This took about 4.25 hours to happen. This test run is done with the application change of doing an explicit thread_exit() call instead of an implicit one via return() at th end of thread. Please note that with the DR 8.0.0 release build, the OOM error happens in ~ 10 minutes.

$ date ; /opt/dr-8.0.0-1/bin64/drrun -debug -loglevel 2 -checklevel 0 -rstats_to_stderr -- ./execute ; date
Tue Jun 30 12:57:38 EDT 2020
<log dir=/opt/dr-8.0.0-1/bin64/../logs/execute.5222.00000000>
<Starting application /opt/testapp2/execute (5222)>
<Initial options = -no_dynamic_options -rstats_to_stderr -loglevel 2 -checklevel 0 -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
<Paste into GDB to debug DynamoRIO clients:
set confirm off
add-symbol-file '/opt/dr-8.0.0-1/lib64/debug/libdynamorio.so' 0x00007f9d5093efe0
>
server: got connection from 127.0.0.1 port 46974
background thread is running
<writing to executable region.>
Initiating while loop on the socket
<proactive reset @ 550579 fragments>
<vmm_heap_commit oom: timeout and retry>
<vmm_heap_commit retrying, no luck.  old=0x000000000000000c new=0x000000000000000c
>
<Out of memory - cannot extend commit 4KB. Trying to recover.>
<vmm_heap_commit oom: timeout and retry>
<vmm_heap_commit retrying, no luck.  old=0x000000000000000c new=0x000000000000000c
>
<Out of memory.  Program aborted.>
<OOM Status: C 0x000000000000000c>
Tue Jun 30 17:15:46 EDT 2020
$


For details of the statistics, please see the attached main process log file (only ~last 2000 lines, "truncated_execute.0.5222.zip" and "all_statistics_at_the_end.zip") and log for thread that got OOM error, "log.30821.1222.zip".
[all_statistics_at_the_end.txt](https://github.com/DynamoRIO/dynamorio/files/4854840/all_statistics_at_the_end.txt)
[log.30821.1222.zip](https://github.com/DynamoRIO/dynamorio/files/4854841/log.30821.1222.zip)
[truncated_execute.0.5222.zip](https://github.com/DynamoRIO/dynamorio/files/4854842/truncated_execute.0.5222.zip)

Please let me know if I should repeat the test with another set of DR options and/or supply additional log files?

Thanks.

**Comment by derekbruening** [comment]
Could you try running with these options: `-debug -reachable_heap -checklevel 0`?  Does the OOM disappear and the application  operates successfully?

**Comment by derekbruening** [comment]
I can reproduce memory leaks on thread exit with a simple app that creates and immediately joins a thread over and over in a loop.

The leaks are all cleaned up at process exit, which is why the existing exit-time leak checks don't notice anything.  Memory accumulates in heap vmm blocks, but the global block list lets us clean them up later (and hence a classic reachability-based leak detector would not catch either: so it would be called a reachable accumulation or something).

In debug build there is one leak:
+ missing threadunits_exit for th->reachable_heap: so a regression from the reachable heap split.
  `-reachable_heap` is a workaround.

In release there are more:
+ privload_tls_exit is skipped, so the priv TLS is not unmapped
+ sigaltstack free is skipped, so the sig alt stack is not freed
+ private exit stubs are not freed due to skipping the hashtable walk.
  To solve this:I turned off -separate_private_stubs by default, to avoid the walk for
    shared caches where there are few benefits to separating private stubs.
    -thread_private turns it back on where the benefits probably outweight
    the thread exit costs.
+ Some structures in "local unprotected" heap which is actually stored
  in global units were not being freed.

I ran the app with up to 500K thread creations and no increase in vmm block usage in both debug and release so it looks good now.  I turned my app into a new test api.thread_churn.

**Comment by SCVARSH** [comment]
Thanks Derek for taking the time to write an application to reproduce the OOM issue and then fixing it. Also appreciate the detailed explanation of the fix.

I can also confirm that running with the "**-debug -reachable_heap -checklevel 0**" options, my test application has already run successfully for 8+ hours without exhibiting any signs of memory leak. It seems that the test can now run now indefinitely.

I will retest it when the fix is available in the automated build.

Thanks again.
