### ISSUE TITLE
Allocation of more than 2GB in unreachable heap causes out of memory errror

### ISSUE THREAD

**Issue by SweetVishnya** [DynamoRIO/dynamorio#4335]
# How to reproduce

This reproduces on both Linux x86-32 and x86-64.

Just allocate more than 2GB from `dr_client_main` with `malloc`:

```
    int *tmp = 0;
    int cnt = 0;
    for (int i = 0; i != 4 * 96086; ++i)
    {
        tmp = (int *) malloc(30000);
        ++cnt;
        std::cout << cnt << std::endl;
        for (int j = 0; j != 30000 / sizeof(int); ++j)
        {
            tmp[j] = i * 43;
        }
    }
    std::cout << "Do not optimize out malloc " << tmp[20] << std::endl;
```

Run debug:

```
dynamorio/bin64/drrun -debug -c client.so -- /bin/ls
```

Get an error:

```
<Out of vmheap reservation - reserving 256KB. Falling back onto OS allocation>
<CURIOSITY : (0) && "Out of vmheap reservation" in file /home/vishnya/dynamorio/core/heap.c line 1614
<Out of memory - cannot reserve 256KB. Trying to recover.>
<Out of memory.  Program aborted.>
<OOM Status: R 0x0000000000000001>
```

# What goes wrong

When unreachable memory size reaches first 2GB it tries to ask more memory from system. But [this](https://github.com/DynamoRIO/dynamorio/blob/master/core/heap.c#L2825) code fails and leads to out of memory.

**Comment by derekbruening** [comment]
Certainly beyond-reservation allocations have never been in great shape: they are slow (#2115) and for reachable memory in small-reservation situations they could be improved (#1133).  But they definitely used to work, hence the filing of things like #2115.  Thus the question: is this a regression?  Maybe you could check some older versions.

@SweetVishnya : why does the from-OS allocation fail?  For 32-bit there can actually be no free space left in the address space, but for 64-bit there should be.  You'd think it'd be fairly simple for non-reachable, except again for performance issues like #2115.

**Comment by SweetVishnya** [comment]
I pasted the following into `suite/tests/client-interface/cleancall.dll.c`.

```
DR_EXPORT void
dr_init(client_id_t id)
{
    int *tmp = 0;
    int cnt = 0;
    for (int i = 0; i != 4 * 96086; ++i)
    {
        tmp = (int *) malloc(30000);
        ++cnt;
        dr_printf("%d\n", cnt);
        for (int j = 0; j != 30000 / sizeof(int); ++j)
        {
            tmp[j] = i * 43;
        }
    }
    dr_printf("Do not optimize out malloc %d\n", tmp[20]);
    dr_register_bb_event(bb_event);
    dr_register_thread_init_event(thread_start);
    dr_register_thread_exit_event(thread_exit);
    dr_register_restore_state_event(restore_state_event);
    dr_register_exit_event(app_exit_event);
}
```

And run:

```
ctest -V -R 'client\.cleancall$'
```

I will try to find out the commit when it stopped working.

**Comment by SweetVishnya** [comment]
I am getting various build problems with old DR versions. I will try to debug why OS allocation fails.

**Comment by SweetVishnya** [comment]
It seems like DR actually [tryies](https://github.com/DynamoRIO/dynamorio/blob/master/core/heap.c#L1548) to make unreachable heap reachable.

**Comment by derekbruening** [comment]
> It seems like DR actually [tries](https://github.com/DynamoRIO/dynamorio/blob/master/core/heap.c#L1548) to make unreachable heap reachable. `os_heap_reserve_in_region` returns `NULL`.

So you found the problem: the initial unreachable reservation is placed anywhere, but allocations from the OS once that reservation is used up are given the constraints.  We would be happy to look at a pull request to fix if you would like to submit one.

**Comment by SweetVishnya** [comment]
I'll try to fix it today.

**Comment by SweetVishnya** [comment]
Submitted a merge request #4353

**Comment by derekbruening** [comment]
The other path can be reproduced with `-no_enable_reset`, but it should also be able to happen without that option by using enough persistent memory that a reset does not remove it.
