### ISSUE TITLE
Replace insensitive option and variable names

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#4366]
Both DR and Dr. Memory have options and variables with the terms "whitelist" and "blacklist".  This option covers replacing them with "allowlist" and "blocklist".

**Comment by derekbruening** [comment]
Dr. Memory is done as linked above.  DR remains.

**Comment by derekbruening** [comment]
There is also the Jenkins auto-add phrase: @AssadHashmi if you could change that to "add to allowlist"

**Comment by AssadHashmi** [comment]
> There is also the Jenkins auto-add phrase: @AssadHashmi if you could change that to "add to allowlist"

Done.
