### ISSUE TITLE
x86 IR has instances of missing or extra implicit operands not caught by tests: pabsb

### ISSUE THREAD

**Issue by johnfxgalea** [DynamoRIO/dynamorio#4377]
INSTR_CREATE_pabsb incorrectly creates a 1 dst, 2 src IR instruction. PABSB and variants have only one source and therefore  instr_create_1dst_1src should be used.

Currrent code:

`#define INSTR_CREATE_pabsb(dc, d, s) instr_create_1dst_2src((dc), OP_pabsb, (d), (s), (d))
`

Ref: https://www.felixcloutier.com/x86/pabsb:pabsw:pabsd:pabsq

**Comment by johnfxgalea** [comment]
INSTR_CREATE_vmovlpd and variants incorrectly creates an instr via instr_create_1dst_1src, when it should use instr_create_1dst_2src.

```
#define INSTR_CREATE_vmovlps(dc, d, s) instr_create_1dst_1src((dc), OP_vmovlps, (d), (s))
#define INSTR_CREATE_vmovlpd(dc, d, s) instr_create_1dst_1src((dc), OP_vmovlpd, (d), (s))
```

Ref: https://www.felixcloutier.com/x86/movlpd

**Comment by derekbruening** [comment]
The IR tests would fail if the INSTR_CREATE macros did not match the decoding tables: so the decoding tables must be wrong for these.  And that means the tests against other decoders must not include cases of these instrutions?  But I do see them in those tests:

```
third_party/binutils/test_decenc/drdecode_decenc_x86.expect: c4 e2 79 1c f4       vpabsb %xmm4, %xmm6
third_party/binutils/test_decenc/drdecode_decenc_x86.expect: c4 e2 79 1c 21       vpabsb (%ecx), %xmm4
```

Is it that we use Intel syntax for the binutils comparison and so it will never catch an extra implicit operand?

**Comment by johnfxgalea** [comment]
@derekbruening I didn't check vpabsb yet, only pabsb so not sure. Will let you know when I get some time.

**Comment by derekbruening** [comment]
Meant to do what you had reported but the grep found vpabsb too.  pabsb is the same: certainly present in the tests (just a handful pasted here...there are more):
```
third_party/binutils/test_decenc/drdecode_decenc_x86.expect: 66 0f 38 1c f4       pabsb  %xmm4, %xmm6
third_party/binutils/test_decenc/drdecode_decenc_x86.expect: 66 0f 38 1c 21       pabsb  (%ecx), %xmm4
third_party/binutils/test_decenc/drdecode_decenc_x86.expect: 0f 38 1c 01          pabsb  (%ecx), %mm0
third_party/binutils/test_decenc/drdecode_decenc_x86.expect: 0f 38 1c c1          pabsb  %mm1, %mm0
```

So the conclusion is that while we have good internal-consistency testing (INSTR_CREATE == decoder == encoder == fast decoder == size-only decoder), and we have reasonable ground-truth testing of opcode and explicit operands, our lack of implicit operand testing means we may have a bunch of this type of bug.

**Comment by derekbruening** [comment]
Of course it is not easy to add ground-truth implicit operand testing: we'd have to either compare at the IR level to some other decoder that creates an IR with implicit operands, or do actual execution and sthg like for memory operands point at unreadable and unwritable pages and see if we get a read fault or just a write fault??

**Comment by johnfxgalea** [comment]
hmm, so for the vmovlpd, there is another entry, namely  INSTR_CREATE_vmovlps_NDS, which seems to be correct. So we should use  INSTR_CREATE_vmovlps_NDS. However, I still do not understand why we also got the other variant.

```
/* NDS means "Non-Destructive Source" */
#define INSTR_CREATE_vmovlps_NDS(dc, d, s1, s2) \
    instr_create_1dst_2src((dc), OP_vmovlps, (d), (s1), (s2))
#define INSTR_CREATE_vmovlpd_NDS(dc, d, s1, s2) \
    instr_create_1dst_2src((dc), OP_vmovlpd, (d), (s1), (s2))
```

**Comment by derekbruening** [comment]
NDS means "Non Destructive Source": i.e., the source does not have to be the same as the destination b/c there's an extra explicit source operand vs the implicit-source-equals-dest versions.

Glancing in the manual: there are several variants of `vmovlpd`, including 1-source-1-dest variants.

So perhaps pabsb is the only one found so far with problems?

**Comment by derekbruening** [comment]
Although `vmovlpd` is a pure move, not an ALU instruction: so it wouldn't have a destroyed source anyway?  Worth another look when someone gets some time.

**Comment by johnfxgalea** [comment]
> NDS means "Non Destructive Source": i.e., the source does not have to be the same as the destination b/c there's an extra explicit source operand vs the implicit-source-equals-dest versions.
> 
> Glancing in the manual: there are several variants of `vmovlpd`, including 1-source-1-dest variants.
> 
> So perhaps pabsb is the only one found so far with problems?

Ah yes, I missed the implicit-source-equals-dest version of vmovlpd. So it seems that vmovlpd issue was a false alarm from my end. 

I understand pabsb seems to be the only issue left.
