### ISSUE TITLE
ASSERT meta-instr faulted?  must set translation field and handle fault! on aarch64 linux

### ISSUE THREAD

**Issue by Eliana-Xie** [DynamoRIO/dynamorio#4385]
**Describe the bug**
DynamoRIO usage error : meta-instr faulted?  must set translation field and handle fault!>
<Usage error: meta-instr faulted?  must set translation field and handle fault! (/home/travis/build/DynamoRIO/dynamorio/core/translate.c, line 913)
version 8.0.0, build 1

**To Reproduce**
1. aarch64 gcc multi-thread app
2. modify sample/instrace_simple.c :  if (!instr_is_app(instr)) -> if (!instr_is_app(instr) || !instr_is_cti(instr))
2. drrun -c bin/libinstrace_simple.so -- xxx
3. Exact output or incorrect behavior. segmental fault

Please also answer these questions:
 - What happens when you run without any client? run correct
 - What happens when you run with debug build ("-debug" flag to drrun/drconfig/drinject)? 

**Expected behavior**
record branch instructions

**Screenshots or Pasted Text**
If applicable, add screenshots to help explain your problem.  For text, please cut and paste the text here, delimited by lines consisting of three backtics to render it verbatim, like this:
<pre>
```
<Application xxx (104914) DynamoRIO usage error : meta-instr faulted?  must set translation field and handle fault!>
<Usage error: meta-instr faulted?  must set translation field and handle fault! (/home/travis/build/DynamoRIO/dynamorio/core/translate.c, line 913)
version 8.0.0, build 1
-no_dynamic_options -client_lib '.../DynamoRIO-AArch64-Linux-8.0.0-1/samples/build/bin/libinstrace_simple.so;0;' -code_api -stack_size 64K -signal_stack_size 64K -max_elide_jmp 0 -max_elide_call 0 -vmm_block_size 64K -initial_heap_unit_size 192K -initial_heap_nonpers_size 192K -initial_global_heap_unit_size 1
0x0000fffb9b6daa50 0x0000fffc1b5a43e8
0x0000fffb9b6dabf0 0x0000fffc1b6dd284
0x0000fffb9b6dac30 0x0000fffc1b6df774
0x0000fffb9b6dad20 0x0000fffc1b6dfd44
0x0000fffb9b6db450 0x0000fffc1b6b2c94
0x0000fffb9b6db490 0x0000fffc1b80ff34
0x0000fffb9b6db4f0 0x0000fffc1b815040
0x0000fffb9b6db860 0x0000fffc1b8183b8
0x0000fffb9b6ddbc0 0x0000fffc1b7efcc4
0x0000fffb9b6dfff0 0x0000000000400c30
0x0000ffffe29811e0 0x0000fffb9af80b20
0x0000ffffe2981270 0x0000000000400fa8
.../DynamoRIO-AArch64-Linux-8.0.0-1/samples/build/bin/libinstrace_simple.so=0x0000000072000000
/usr/lib64/libc.so.6=0x0000fffb9b2b0000
/usr/lib/ld-linux-aarch64.so.1=0x0000fffb9b250000
.../DynamoRIO-AArch64-Linux-8.0.0-1/ext/lib64/debug/libdrx.so=0x0000000077000000
.../DynamoRIO-AArch64-Linux-8.0.0-1/ext/lib64/debug/libdrreg.so=0x0000000078000000
.../DynamoRIO-AArch64-Linux-8.0.0-1/ext/lib64/debug/>
```
</pre>

**Versions**
 - What version of DynamoRIO are you using?
 - Does the latest build from
https://github.com/DynamoRIO/dynamorio/wiki/Latest-Build solve the problem?
- What operating system version are you running on? (Linux 4.19)
- application 64-bit

**Comment by Eliana-Xie** [comment]
<Application xxx (104914) DynamoRIO usage error : meta-instr faulted?  must set translation field and handle fault!>
<Usage error: meta-instr faulted?  must set translation field and handle fault! (/home/travis/build/DynamoRIO/dynamorio/core/translate.c, line 913)
version 8.0.0, build 1
-no_dynamic_options -client_lib '.../DynamoRIO-AArch64-Linux-8.0.0-1/samples/build/bin/libinstrace_simple.so;0;' -code_api -stack_size 64K -signal_stack_size 64K -max_elide_jmp 0 -max_elide_call 0 -vmm_block_size 64K -initial_heap_unit_size 192K -initial_heap_nonpers_size 192K -initial_global_heap_unit_size 1
0x0000fffb9b6daa50 0x0000fffc1b5a43e8
0x0000fffb9b6dabf0 0x0000fffc1b6dd284
0x0000fffb9b6dac30 0x0000fffc1b6df774
0x0000fffb9b6dad20 0x0000fffc1b6dfd44
0x0000fffb9b6db450 0x0000fffc1b6b2c94
0x0000fffb9b6db490 0x0000fffc1b80ff34
0x0000fffb9b6db4f0 0x0000fffc1b815040
0x0000fffb9b6db860 0x0000fffc1b8183b8
0x0000fffb9b6ddbc0 0x0000fffc1b7efcc4
0x0000fffb9b6dfff0 0x0000000000400c30
0x0000ffffe29811e0 0x0000fffb9af80b20
0x0000ffffe2981270 0x0000000000400fa8
.../DynamoRIO-AArch64-Linux-8.0.0-1/samples/build/bin/libinstrace_simple.so=0x0000000072000000
/usr/lib64/libc.so.6=0x0000fffb9b2b0000
/usr/lib/ld-linux-aarch64.so.1=0x0000fffb9b250000
.../DynamoRIO-AArch64-Linux-8.0.0-1/ext/lib64/debug/libdrx.so=0x0000000077000000
.../DynamoRIO-AArch64-Linux-8.0.0-1/ext/lib64/debug/libdrreg.so=0x0000000078000000
.../DynamoRIO-AArch64-Linux-8.0.0-1/ext/lib64/debug/>

**Comment by derekbruening** [comment]
> modify sample/instrace_simple.c : if (!instr_is_app(instr)) -> if (!instr_is_app(instr) || !instr_is_cti(instr))

This will cause the clean call to *never* be inserted (unless there is a bb consisting only of a branch so that the `drmgr_is_first_instr` is satisfied) and you will overflow the buffer.  It would be expected to crash.
