### ISSUE TITLE
Build failure / ARM undefined symbol __aeabi_dcmple

### ISSUE THREAD

**Issue by BOBpen** [DynamoRIO/dynamorio#4387]
I'm trying to build DynamoRIO for arm, but  which resulted in the following error
CMake Error at ..../dynamorio/core/CMake_readelf.cmake:100 (message):
  *** Error:  ...../build_arm/lib32/release/libdynamorio.so has
  undefined symbol: GLOBAL DEFAULT UND __aeabi_dcmple

Any help is appreciated, thank you!

**Comment by derekbruening** [comment]
Sounds like you're targeting gnueabi, while what is supported is gnueabihf.

**Comment by BOBpen** [comment]
You're right, I'm using a cross-compilation tool which is like gnueabi for my own special CPU version. So you mean Dynamorio doesn't support gnueabi？Oh, you mean set -DTARGET_ABI in toolchain-arm32.cmake?

**Comment by derekbruening** [comment]
Yes you need every component using the same ABI.  gnueabi worked at some point (if you search the releases: I see DynamoRIO-ARM-Linux-EABI-6.0.0-6 from 2015) but there is no regular testing of it so it may have bit-rotted.

**Comment by BOBpen** [comment]
I think I have to use my cross-compilation tool to recompile all, and I noticed that the 'drsyms' extension uses bundled of  copies of libelf which has been compiled. So, I need to recompile them by my cross-compilation tool?

**Comment by BOBpen** [comment]
And what I want to ask is that I noticed when I compile libdynamorio.so, which depends on third_party/libgcc. It has some *.S file,  which seems to implement some functions, so these files will affect the result of cross-compilation? Thank you very much for your help!

**Comment by derekbruening** [comment]
> I think I have to use my cross-compilation tool to recompile all, and I noticed that the 'drsyms' extension uses bundled of copies of libelf which has been compiled. So, I need to recompile them by my cross-compilation tool?

Yes, if ext/drsyms/libelftc-arm/lib32-eabi/ won't work.

> And what I want to ask is that I noticed when I compile libdynamorio.so, which depends on third_party/libgcc. It has some *.S file, which seems to implement some functions, so these files will affect the result of cross-compilation?

They're compiled in, yes.  It's possible you would need some additional asm functions not present.

**Comment by BOBpen** [comment]
I'm sorry that it still ended with the same error after I set -DTARGET_ABI=linux-gnueabi on the command line. So, I think it may have some issues in the third_party/*.S
