### ISSUE TITLE
[AArch64] proc_get_cache_line_size returns incorrect size

### ISSUE THREAD

**Issue by abhinav92003** [DynamoRIO/dynamorio#4446]
On my AArch64 machine, `proc_get_cache_line_size` returns 32, whereas `cat /sys/devices/system/cpu/cpu0/cache/index0/coherency_line_size` shows 128. 

proc_get_cache_line_size needs to be ported to give correct cache line size for AArch64.

**Comment by abhinav92003** [comment]
Unfortunately, `getconf LEVEL1_DCACHE_LINESIZE` doesn't give this information on AArch64.

We can probably read DminLine from the ctr_el0 system register to get this.
https://developer.arm.com/docs/ddi0595/h/aarch64-system-registers/ctr_el0

**Comment by derekbruening** [comment]
@AssadHashmi is DminLine the best solution here?  DR can read that from userspace?

**Comment by AssadHashmi** [comment]
> @AssadHashmi is DminLine the best solution here? DR can read that from userspace?

Yes, using the MRS instruction.
