### ISSUE TITLE
event_module_load in drcovlib will cause deadlock？

### ISSUE THREAD

**Issue by kenyyy** [DynamoRIO/dynamorio#4450]
In dynamorio/ext/drcovlib/modules.c:
event_module_load will call drvector_lock and drvector_get_entry. but in drvector_get_entry, dr_mutex_lock will be called if  (vec->synch). I think this will cause deadlock in this case.

**Comment by derekbruening** [comment]
As you can see, `vec->synch` is *not* set for drcovlib's vector.
