### ISSUE TITLE
[AArch64] Inline instr counting for trace_after_instrs in drcachesim

### ISSUE THREAD

**Issue by abhinav92003** [DynamoRIO/dynamorio#4487]
Today for AArch64, instr counting for the `-trace_after_instrs` option in drcachesim is not inlined. Instead it's done using a clean call. https://github.com/DynamoRIO/dynamorio/blob/5cbe8113c919b557f7bfc3daafffc9b1fef7938c/clients/drcachesim/tracer/tracer.cpp#L1430

We should inline it for better performance.

**Comment by derekbruening** [comment]
This involves implementing drx_insert_counter_update() for 64-bit counters for AArchXX which was previously under the general #1551.
