### ISSUE TITLE
ASSERT failure using `reset_at_nth_thread 2` on test app

### ISSUE THREAD

**Issue by abhinav92003** [DynamoRIO/dynamorio#4496]
**Describe the bug**
DR crashes with an assert failure with the `-reset_at_nth_thread 2` option. The assert failure is different on AArch64 and x86.

**To Reproduce**
`bin64/drrun -enable_reset -reset_at_nth_thread 2  -- suite/tests/bin/linux.thread`

**Screenshots or Pasted Text**
On AArch64:
```
<proactive reset @ 1309 fragments>
Sideline thread started
<Application build/dynamorio/suite/tests/bin/linux.thread (33389).  Internal Error: DynamoRIO debug check failure: Not implemented @src/dynamorio/core/unix/signal_linux_aarch64.c:53 (0)
(Error occurred @1327 frags)
version 8.0.18562, custom build
-no_dynamic_options -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -enable_reset -reset_at_nth_thread 2 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
```

On x86:
```
 <proactive reset @ 1736 fragments>
<Application build/dynamorio/suite/tests/bin/linux.thread (2261478).  Internal Error: DynamoRIO debug check failure: src/dynamorio/core/dispatch.c:751 wherewasi == DR_WHERE_FCACHE || wherewasi == DR_WHERE_TRAMPOLINE || wherewasi == DR_WHERE_APP || (dcontext->go_native && wherewasi == DR_WHERE_DISPATCH)
(Error occurred @1736 frags)
version 8.0.18563, custom build
-no_dynamic_options -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -reset_at_nth_thread 2 -early_inject -emulate_brk -no_inline_ignored_syscalls -native_exec_default_list '' -no_native_exec_managed_code -no_indcall2direct >
```

**Versions**
Working on PR #4491 

**Additional context**
The same issue comes up with `-reset_at_created_thread_count 2` (this is a new flag tried while working on the above PR; this flag resets when created thread count reaches 2, unlike `reset_at_nth_thread` which checks the active thread count). But the failure does not come up with `-reset_at_created_thread_count 3`.
(Note that `reset_at_nth_thread 3` doesn't invoke the failing path at all)

**Comment by abhinav92003** [comment]
@derekbruening About the `ASSERT_NOT_IMPLEMENTED` in `save_fpstate` for AArch64: Do we need special handling for fpstate on AArch64/ARM? 

DR documentation[1] mentions 
```
On ARM/AArch64, DynamoRIO saves and restores all the registers, including the SIMD/FP registers, during a context switch away from the application. The functions proc_save_fpstate and proc_restore_fpstate are provided, but do nothing.
```
Does the same thing at [2] apply to `save_fpstate` and `dr_insert_save_fpstate` too (I see TODOs with #1569, but that might just be a general TODO added initially for AArch64 support).

Also, in another code location, I see that `save_fpstate` is performed only for x86[3]. Do we want similar behaviour at [4] too? 


[1]: http://dynamorio.org/dynamorio_docs/transparency.html
[2]: https://github.com/DynamoRIO/dynamorio/blob/6dea75659134018d0796e7c923b62db03fcc6cf2/core/arch/aarch64/proc.c#L151
[3]: https://github.com/DynamoRIO/dynamorio/blob/6dea75659134018d0796e7c923b62db03fcc6cf2/core/unix/signal.c#L5575
[4]: https://github.com/DynamoRIO/dynamorio/blob/6dea75659134018d0796e7c923b62db03fcc6cf2/core/unix/signal.c#L2684

**Comment by derekbruening** [comment]
> @derekbruening About the `ASSERT_NOT_IMPLEMENTED` in `save_fpstate` for AArch64: Do we need special handling for fpstate on AArch64/ARM?

I don't think so: dr_mcontext.simd[] should hold all the direct values (i.e., it's not like x86 where the x87 state is not in dr_mcontext_t *at all*).  Maybe there are status registers or sthg though?  I remember this coming up recently in some issue or PR and Assad was not sure -- I can't find the issue though: recent ones are #4467, #4488.

@AssadHashmi -- if you could comment.

**Comment by AssadHashmi** [comment]
> > @derekbruening About the `ASSERT_NOT_IMPLEMENTED` in `save_fpstate` for AArch64: Do we need special handling for fpstate on AArch64/ARM?
> 
> I don't think so: dr_mcontext.simd[] should hold all the direct values (i.e., it's not like x86 where the x87 state is not in dr_mcontext_t _at all_). Maybe there are status registers or sthg though? I remember this coming up recently in some issue or PR and Assad was not sure -- I can't find the issue though: recent ones are #4467, #4488.
> 
> @AssadHashmi -- if you could comment.

Apologies for the late response @abhinav92003 and @derekbruening, this slipped under the mat.

I don't know enough about DR's state save implementation and the consequences for FP state to be able to comment with enough confidence. I do know that we've not had any issues related too `save_fpstate` so far. Possibly because of this:
https://github.com/DynamoRIO/dynamorio/issues/2629#issuecomment-328069463
