### ISSUE TITLE
Dynamorio not loading stolen register value into mcontext on AArch64

### ISSUE THREAD

**Issue by gregcawthorne** [DynamoRIO/dynamorio#4508]
On AArch64 the value of the stolen register isn't loaded into the mcontext object for later instrumentation, due to an ifdef only allowing this functionality on ARM (non AArch64), in instrument.c, dr_get_mcontext_priv().

This causes errors when addresses need to be calculated based on the value of contents the stolen register.

Issue is present on the current latest build: cronbuild-8.0.18565

Fix is to change this one line ifdef to #ifdef AARCHXX
https://github.com/DynamoRIO/dynamorio/blob/420adb01d466e134037b1db6ed7023749c3f8034/core/lib/instrument.c#L6802

Will submit the fix very soon.

**Comment by derekbruening** [comment]
My test for #4495 is hitting this as it wants to test the stolen register in a clean call.
