### ISSUE TITLE
ASSERT in every app on ARM: opnd_t size changed

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#4520]
I assume this is a regression from PR #4467 3a408a034b841d036c53d972eff0c9cbe75d7cbe.  Lack of ARM CI tests is really an issue.
```
95: <Application /home/derek/dr/git/build_dbg_tests/suite/tests/bin/client.signal (16492).  Internal Error: DynamoRIO debug check failure: /home/derek/dr/git/src/core/arch/arch.c:668 sizeof(opnd_t) == EXPECTED_SIZEOF_OPND
```

**Comment by AssadHashmi** [comment]
> Lack of ARM CI tests is really an issue.

It is. I'm in the process of acquiring AArch32 instances similar to the `packet.net` machines we already have for AArch64 pre-commit and development.

**Comment by AssadHashmi** [comment]
Which ARM test(s) exposed this?

**Comment by derekbruening** [comment]
#4522 is another regression on ARM not caught at commit time.

**Comment by derekbruening** [comment]
> Which ARM test(s) exposed this?

All of them: if the compiler lays out opnd_t to not match the "black box" binary interface version, every test will fail at init time.

I'm wondering why x86 32-bit Linux doesn't fail the same way: I would expect the compiler to pad the double to align it to 8 in the same way.

**Comment by derekbruening** [comment]
>  I'm in the process of acquiring AArch32 instances similar to the packet.net machines we already have for AArch64 pre-commit and development.

Awesome!  Would we be able to set up Jenkins on them?

**Comment by AssadHashmi** [comment]
> Awesome! Would we be able to set up Jenkins on them?

Depends what h/w we end up getting. If it's enough to run Jenkins, we'll do it.

**Comment by derekbruening** [comment]
This issue covers just fixing the immediate ARM breakage.  #4488 covers potentially changing the opnd_t layout to get the double field properly aligned to 8.
