### ISSUE TITLE
AVX-512 broadcast memory operand sizes incorrect

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#4534]
DR's IR is not representing AVX-512 broadcast memory operand sizes correctly.  It ignores the broadcast bit EVEX.b and portrays the size as though there were no broadcast.  This was noticed here: https://github.com/DynamoRIO/dynamorio/pull/4533#discussion_r523430591

**Comment by khuey** [comment]
There are several issues here:

- Instructions that do not accept EVEX.b at all (e.g. vpaddb and everything else in the E4.nb/E4NF.nb subclasses) should fail to decode
- Instructions that accept EVEX.b to enable broadcasting (e.g. vorpd) need appropriate memory operand sizing when EVEX.b=1.
- Instructions that accept EVEX.b to control rounding (e.g. vsqrtss) need the current behavior.

And note that there are instructions that fall into categories 2 and 3 depending on whether the relevant operand is a memory operand or a register operand (e.g. vsubpd).

Handling category 1 instructions can be done by adding a REQUIRES_EVEX_B_0 flag (a la REQUIRES_VEX_L_0).

The broadcast operand size depends on the lane width of the operation so there are full size operations with both 64 and 32 bit broadcasts (e.g. vcvtps2dq and vcvtpd2qq) as well as half size operations with 32 bit broadcasts (e.g. vcvtps2pd). Adding new OPSZ codes for these would require 3 additions (e.g. OPSZ_16_vex32_evex64_bcst64, OPSZ_16_vex32_evex64_bcst32, and OPSZ_half_16_vex32_evex64_bcst32). So we could do that and then teach the relevant code to check for EVEX.b when encoding/decoding these OPSZs.

Thoughts?

**Comment by derekbruening** [comment]
SGTM.  The only code I saw that looks at the broadcast bit is for the compressed displacement scaling (and I wonder if that would not be necessary if the size were correct, b/c the scaling is the memory size (always?)) so it sounds right that the other pieces you mention are all missing.  Thanks for looking into the details!
