### ISSUE TITLE
AArch64 ASSERT failure core/unix/signal.c:5591 get_sigcxt_stolen_reg(sc) != (reg_t)*get_dr_tls_base_addr()

### ISSUE THREAD

**Issue by abhinav92003** [DynamoRIO/dynamorio#4535]
**Describe the bug**

Running drcachesim on a proprietary AArch64 app hits the assert at core/unix/signal.c:5591 `get_sigcxt_stolen_reg(sc) != (reg_t)*get_dr_tls_base_addr()`.
This happens immediately after `Hit delay threshold: enabling tracing.`, so it's probably during the `dr_flush_region` call in `drcachesim/tracer/tracer.cpp`

This starts at 7d5124a1c4ee50eddb4c360366c6f92cb13e54cc (PR #4517), which introduced the assert. Yet to figure out the root cause.

**Comment by abhinav92003** [comment]
Similar assert is hit on continuing after the one above: core/unix/signal.c:6388 `get_sigcxt_stolen_reg(sc) != (reg_t)*get_dr_tls_base_addr()`

**Comment by derekbruening** [comment]
These are asserts I added to help detect more stolen register bugs after it took so much effort to figure out the root cause of #4460.

**Comment by abhinav92003** [comment]
The assert failure happens in the thread that called `dr_flush_region_ex`[3] previously to change drcachesim instrumentation. It happens while receiving a pending `SIGPROF`, which was recorded for later processing at [2].

The `mcontext_to_ucontext` call at [1] copies the interrupted context to the frame's context. The stolen reg value seems to be set to the tls base addr at this call (the saved stolen reg value in sigpending was not tls base). I guess this only points to the obvious -- that the stolen reg app value was not restored at some point.

[1]: https://github.com/DynamoRIO/dynamorio/blob/c34afc01ae46dae6dd919e28214c622de69bbf7f/core/unix/signal.c#L5589
[2]: https://github.com/DynamoRIO/dynamorio/blob/c34afc01ae46dae6dd919e28214c622de69bbf7f/core/unix/signal.c#L4459
[3]: https://github.com/DynamoRIO/dynamorio/blob/c34afc01ae46dae6dd919e28214c622de69bbf7f/clients/drcachesim/tracer/tracer.cpp#L1402

**Comment by abhinav92003** [comment]
I'm seeing that the value of the stolen reg`x28` is the thread's tls base at [`check_instr_count_threshold`](https://github.com/DynamoRIO/dynamorio/blob/c34afc01ae46dae6dd919e28214c622de69bbf7f/clients/drcachesim/tracer/tracer.cpp#L1419), which is invoked using a clean call by drcachesim. But it's (always) a different value before the clean call. Checking if `dr_insert_clean_call` loads`x28` with tls base without restoring the app value.

**Comment by derekbruening** [comment]
If it's an mcontext acquired inside a clean call via dr_get_mcontext, it is probably #4508.  @gregcawthorne if you could get your fix in: more people are hitting this and losing time debugging...

**Comment by gregcawthorne** [comment]
Hi Sorry Derek, will get on with it

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by abhinav92003** [comment]
Thanks for the xref Derek. I tried the fix suggested in #4508: changing this[1] to AARCHXX. It indeed resolves this issue too. 

Thanks Greg for finding and working on the fix. I'll look for further updates on PR #4513.

[1]:  https://github.com/DynamoRIO/dynamorio/blob/420adb01d466e134037b1db6ed7023749c3f8034/core/lib/instrument.c#L6802

**Comment by abhinav92003** [comment]
Closed by PR #4513.
