### ISSUE TITLE
vpermb is missing

### ISSUE THREAD

**Issue by khuey** [DynamoRIO/dynamorio#4539]
Looks like the other vperm variants are all present.

**Comment by khuey** [comment]
Actually vpermb gets decoded as vpermw.

```
khuey@minbar:~/dev/dynamorio/obj$ ./clients/bin64/drdisas -syntax intel 62 f2 ed 48 8d cb
 62 f2 ed 48 8d cb    vpermw zmm1 {k0}, zmm2, zmm3
khuey@minbar:~/dev/dynamorio/obj$ ./clients/bin64/drdisas -syntax intel 62 f2 6d 48 8d cb
 62 f2 6d 48 8d cb    vpermw zmm1 {k0}, zmm2, zmm3
```

**Comment by derekbruening** [comment]
Should we add a new label to group all the decode/IR issues?

**Comment by derekbruening** [comment]
> Should we add a new label to group all the decode/IR issues?

https://github.com/DynamoRIO/dynamorio/labels/Component-IR
