### ISSUE TITLE
Migrate ASAP from Travis CI as it no longer offers free OSS CI and will stop working very soon

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#4549]
Announced here: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

We have been burning through our 10K credit for the last two weeks.  When it runs out everything will just stop working unless we sign up for a paid account, but those do not look nearly as nice as what we had: $69/month gets just one concurrent job!

There seems to be a way to apply for a certain number of free OSS minutes every month but it sounds like we'd have to re-apply each month and it is not clear what the chance is of getting them nor whether we'd get enough to cover our usage.

I can't seem to find a way to view the current credit, so it's not clear when we'll run out, but I would imagine any minute.

Xref #4131 which lists possible alternatives of Github Actions and CircleCI.  Or Appveyor in a reversal of that issue.

**Comment by derekbruening** [comment]
Github Actions looks like the best choice as it has high concurrency limits and seems to have similar features to (the old) Travis.

https://docs.github.com/en/free-pro-team@latest/actions/reference/usage-limits-billing-and-administration
20 concurrent jobs, incl 5 macos

Migration docs:
https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/migrating-from-travis-ci-to-github-actions

**Comment by derekbruening** [comment]
Here's a quick tasklist for migration from Travis CI to Github Actions to help track progress and help parallelize the effort.  Maybe when someone starts on one of these they can edit this comment and put their name at the end of its line or sthg?  Each of these includes investigation into the options and syntax plus testing.  Maybe each of us working on it would make a branch with changes and we can merge them at some point.

Base setup:
- [ ] Xenial
- [ ] trigger on PR or on master push
- [ ] notify dynamorio-devs on failures
- [ ] log access

Duplicate each of the 7 current Travis test jobs and ensure the right
software is installed (different VM's have different base software) and the
tests are green (different OS/libs/etc. can cause different failures):
- [ ] 32-bit Linux gcc + tests
- [ ] 64-bit Linux gcc + tests
- [ ] aarchxx cross-compile
- [ ] android arm cross-compile
- [ ] 64-bit Linux clang-9 + format check
- [ ] 64-bit OSX clang + tests
- [ ] A64-on-x86 gcc + tests

Ditto for the package cronjobs:
- [ ] x86
- [ ] aarch64
- [ ] arm
- [ ] Android

Other package steps:
- [ ] include Dr. Memory in cronbuilds
- [ ] tag (ensure it triggers Appveyor)
- [ ] deploy release package
- [ ] deploy gh-pages
- [ ] schedule Fri evening cronjobs
- [ ] document how to trigger manual cronjob

**Comment by derekbruening** [comment]
If we are happy with Github Actions and their Windows support matches our needs, we could then consider moving Appveyor there too, which would be #4131

**Comment by derekbruening** [comment]
We hit the limit.  PR 4552 failed to run any Travis jobs, and https://travis-ci.com/github/DynamoRIO/dynamorio/pull_requests says:

> Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the Plan page to replenish your credit balance or alter your Consume paid credits for OSS setting.

**Comment by abhinav92003** [comment]
> We hit the limit.

I've got 4/7 package test jobs working on PR #4551, pending resolution of some review comments. I'll try to get the other 3 done today itself.

**Comment by derekbruening** [comment]
I renamed the `Hotlist-Travis` issue label to `Hotlist-ContinuousIntegration`

**Comment by derekbruening** [comment]
I have now moved drmemory completely to GA, including the package building and gh_pages deployment.  I'll do the same package steps modeled after drmemory (it took some effort to get the right steps and parallel-plus-serial steps and find which gh_pages actions actually work w/ a separate repo) for DR, but I figure it's simpler to first complete #4131, as otherwise we'll have to do the tagging slightly differently to trigger Appveyor.

**Comment by derekbruening** [comment]
I've updated https://github.com/DynamoRIO/dynamorio/wiki/New-Release#trigger-a-package-build for the step "document how to trigger manual cronjob"

**Comment by derekbruening** [comment]
The only thing left is "notify dynamorio-devs on failures": having merge-to-master failures notify not just the person who did the merge.

**Comment by derekbruening** [comment]
So for our Friday cronbuild action, whoever happened to have last pushed to the repo gets notified?  So if a new one-time contributor happened to have something merged and ignores a probably seemingly-weird email about some cronbuild, the rest of us may never know the cronbuild failed unless we actively go look?

**Comment by abhinav92003** [comment]
> So for our Friday cronbuild action, whoever happened to have last pushed to the repo gets notified? So if a new one-time contributor happened to have something merged and ignores a probably seemingly-weird email about some cronbuild, the rest of us may never know the cronbuild failed unless we actively go look?

Yes, that seems to be the case for crons too (https://github.community/t/how-to-control-notifications-for-cron-triggered-workflows/117652). (I had earlier misunderstood https://github.community/t/no-email-notification-on-schedule-cron-job-failure/119638  to mean that repo watchers will get the notification, but it probably means that the triggering user must also be watching the repo?)

I think I'll go ahead and test the send email action, and also create an email for notifications.dynamorio or something.

**Comment by derekbruening** [comment]
cronbuilds now work:
https://github.com/DynamoRIO/dynamorio/actions/runs/436138276
https://github.com/DynamoRIO/dynamorio/releases/tag/cronbuild-8.0.18617
