### ISSUE TITLE
drcachesim.delay-simple test failing on A64

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#4571]
The delay-simple test is now failing every time on A64:

```
====> FAILURE in debug-internal-64 <====
	code_api|tool.drcachesim.delay-simple =>  Application /var/lib/jenkins/.jenkins/workspace/DynamoRIO-AArch64-Precommit/build/build_debug-internal-64/suite/tests/bin/simple_app (16772).  Internal Error: DynamoRIO debug check failure: /var/lib/jenkins/.jenkins/workspace/DynamoRIO-AArch64-Precommit/core/heap.c:1961 IF_WINDOWS(doing_detach ||) vmh-num_free_blocks == vmh-num_blocks - unfreed_blocks || ((ever_beyond_vmm IF_WINDOWS(|| get_os_version() = WINDOWS_VERSION_8_1))  vmh-num_free_blocks = vmh-num_blocks - unfreed_blocks) 
	code_api|api.static_sideline_FLAKY 

====> FAILURE in release-external-64 <====
release-external-64: 51 tests passed, **** 2 tests failed, of which 1 were flaky, but ignoring 0 for i#2417: ****
	code_api|tool.drcachesim.delay-simple 
```

@abhinav92003 since you recently change how that works (the flush type, etc.) could you take a look?  I think the leak assert reproduces on the TX1.

Xref analysis of when it started failing: https://github.com/DynamoRIO/dynamorio/pull/4529#issuecomment-734293283

**Comment by abhinav92003** [comment]
The timing of the failures is definitely weird. 

PR #4491 changed the flush type, but there are lots of successes after 1783 (the Jenkins invocation for that PR) on http://139.178.83.194:8080/job/DynamoRIO-AArch64-Precommit/buildTimeTrend. Also PR #4559 (1870  on the Jenkins dash) shouldn't really have affected Jenkins at all, but it seems to have.

I'll trying to reproduce the issue on Tx1.

**Comment by abhinav92003** [comment]
I confirmed locally that the failures in `tool.drcachesim.delay-simple` indeed start at commit 893c06c2605eb8423ef4a4b33185d0fef9c75257.  Not sure why it didn't show up on the Jenkins run for PR #4491 though (http://139.178.83.194:8080/job/DynamoRIO-AArch64-Precommit/1783/consoleFull).

**Comment by derekbruening** [comment]
Unless we have a very imminent fix we should probably revert 893c06c since this is causing every single PR to have a red CI.

**Comment by derekbruening** [comment]
Or maybe mark the test as ignore, assuming nothing else breaks that test before the fix is in.

**Comment by abhinav92003** [comment]
I've created PR #4578 to ignore this test for now, to unblock other contributors. I'll try to fix it ASAP so that we don't have to revert any old commits. 

I see that one of my recent PRs #4551 also had this test passing after synching with master: http://139.178.83.194:8080/job/DynamoRIO-AArch64-Precommit/1864/consoleFull, http://139.178.83.194:8080/job/DynamoRIO-AArch64-Precommit/1865/

Curious why the failure is coming up now. Anyway, sorry for the breakage.

**Comment by abhinav92003** [comment]
`./bin64/drrun -unsafe_build_ldstex -t drcachesim -trace_after_instrs 30000   suite/tests/bin/simple_app` works fine, but `-trace_after_instrs 20000` hits the assert.

**Comment by abhinav92003** [comment]
Oh, there's actually a `SIGSEGV` first, which triggers the `vmh_exit` path to the assert.

```
<(1+x) Handling our fault in a TRY at 0x000000007131afd8>
Hit delay threshold: enabling tracing.
<Application /home/abhinavas/dr/build/i4571-1_debug/suite/tests/bin/simple_app (1565).  Application exception at PC 0x0000ffffaff8a134.  
Signal 11 delivered to application as default action.
Callstack:
	0x0000ffffaff8a134   </lib/aarch64-linux-gnu/ld-2.24.so+0xf134>
	0x0000ffffaff8a4d8   </lib/aarch64-linux-gnu/ld-2.24.so+0xf4d8>
	0x0000ffffaff7c41c   </lib/aarch64-linux-gnu/ld-2.24.so+0x141c>
	0x0000ffffaff88a44   </lib/aarch64-linux-gnu/ld-2.24.so+0xda44>
	0x0000ffffaff7e394   </lib/aarch64-linux-gnu/ld-2.24.so+0x3394>
	0x0000ffffaff8fa68   </lib/aarch64-linux-gnu/ld-2.24.so+0x14a68>
	0x0000ffffaff7c3bc   </lib/aarch64-linux-gnu/ld-2.24.so+0x13bc>
	0x0000ffffaff7c65c   </lib/aarch64-linux-gnu/ld-2.24.so+0x165c>
	0x0000ffffaff7bcc8   </lib/aarch64-linux-gnu/ld-2.24.so+0xcc8>
>
<Stopping application /home/abhinavas/dr/build/i4571-1_debug/suite/tests/bin/simple_app (1565)>
<Application /home/abhinavas/dr/build/i4571-1_debug/suite/tests/bin/simple_app (1565).  Internal Error: DynamoRIO debug check failure: /home/abhinavas/dr/src/i4571-1/core/heap.c:1961 IF_WINDOWS(doing_detach ||) vmh->num_free_blocks == vmh->num_blocks - unfreed_blocks || ((ever_beyond_vmm IF_WINDOWS(|| get_os_version() >= WINDOWS_VERSION_8_1)) && vmh->num_free_blocks >= vmh->num_blocks - unfreed_blocks)
(Error occurred @872 frags)
version 8.0.18590, custom build
-no_dynamic_options -client_lib '/home/abhinavas/dr/build/i4571-1_debug/bin64/../clients/lib64/debug/libdrmemtrace.so;0;-trace_after_instrs 20000' -client_lib64 '/home/abhinavas/dr/build/i4571-1_debug/bin64/../clients/lib64/debug/libdrmemtrace.so;0;-trace_after_instrs 20000' -client_lib32 '/home/abhinavas/dr/build/i4571-
```

**Comment by abhinav92003** [comment]
The `SIGSEGV` is happening in an app instruction:
```
Before instrumentation:
TAG  0x0000ffffa821012c
 +0    L3 @0x0000fffd642f12a8  f9400781   ldr    +0x08(%x28)[8byte] -> %x1
 +4    L3 @0x0000fffd642f1378  aa0103e0   orr    %xzr %x1 lsl $0x00 -> %x0
 +8    L3 @0x0000fffd642f11c8  39400021   ldrb   (%x1)[1byte] -> %w1 <- SIGSEGV happens here
 +12   L3 @0x0000fffd64263270  350000c1   cbnz   $0x0000ffffa8210150 %w1
END 0x0000ffffa821012c
```
`x1`'s value is 0 when the instr faults. Note that `x1` is loaded from `x28` which is the stolen reg.  Looking at the instrumented code below, the stolen reg's app value is indeed restored before the load; maybe there's some place where stolen reg app value isn't saved properly?
```
After instrumentation:
+64   m4 @0x0000fffd642f1310  f9000380   str    %x0 -> (%x28)[8byte]
 +68   m4 @0x0000fffd64260a60  aa1c03e0   orr    %xzr %x28 lsl $0x0000000000000000 -> %x0
 +72   m4 @0x0000fffd64261dc8  f9401b9c   ldr    +0x30(%x28)[8byte] -> %x28 <- restore app value of stolen reg
 +76   L3 @0x0000fffd64263410  f9400781   ldr    +0x08(%x28)[8byte] -> %x1
<no-intervening write to %x1>
 +188  L3 @0x0000fffd64263680  39400021   ldrb   (%x1)[1byte] -> %w1
 +192  m4 @0x0000fffd64262130  f940a382   ldr    +0x0140(%x28)[8byte] -> %x2
```

Also, I see that tracing works fine with `-steal_reg 29`.

**Comment by abhinav92003** [comment]
This issue is another instance of #4508. Verified in Jenkins run on draft PR #4579. PR #4513 is already working on the fix.
