### ISSUE TITLE
Implement attach for windows

### ISSUE THREAD

**Issue by raefko** [DynamoRIO/dynamorio#4601]
Hello,

I'm trying to finish this PR [3328](https://github.com/DynamoRIO/dynamorio/pull/3328) because I need to be able to attach DynamoRIO to an executed process (i use it for fuzzing with winAFL).
I fixed everything and I can compile now.
I just need some help to test it because I don't really get which process I have to run, but since Summershrimp added the -attach to DRCONFIG it's probably with drconfig.exe?

Thank you and have a nice day!

**Comment by derekbruening** [comment]
Not sure why an issue was opened?  #725 is the issue for attach on Windows so this is a duplicate: will close.
To ask a question about a PR, please just post a comment on the PR itself.

That said, we welcome help in finishing off the attach PR #3328.  It's on our list of items but we have not had a chance to get to it ourselves.

I pasted your question into the PR and answered there: https://github.com/DynamoRIO/dynamorio/pull/3328#issuecomment-742712927
