### ISSUE TITLE
ARM-M4

### ISSUE THREAD

**Issue by Sirin-il** [DynamoRIO/dynamorio#4786]
Hello,

Please I would like to ask you if we could run DynamoRIO on a system that doesn't support an operating system or not, e.g., ARM-M4 ??

Thank you in advance

**Comment by abhinav92003** [comment]
Hi. Thank you for your interest in using DynamoRIO. For questions about the tool, please use the discussion list: https://groups.google.com/g/dynamorio-users. The Github issue tracker is reserved for feature requests, bug reports, and the like.
