### ISSUE TITLE
Fix long suite tests

### ISSUE THREAD

**Issue by abhinav92003** [DynamoRIO/dynamorio#4845]
The long test suite is being enabled in i#4800. While this is going to improve regular testing coverage by adding a significant number of tests, there are some new tests that are failing as of now. This issue is to track those fixes. 

The observed failing tests from https://github.com/DynamoRIO/dynamorio/issues/4800#issuecomment-812699336 are being added to ignore list in PR #4832.

**Comment by derekbruening** [comment]
The original issue for this is #1807 where apparently we shrunk all the option cases down to just `^common`.

**Comment by abhinav92003** [comment]
Closing this issue as it's a duplicate of #1807.
