### ISSUE TITLE
Feature Request:  Add a count for total number of instruction for filtered trace

### ISSUE THREAD

**Issue by vicwlee** [DynamoRIO/dynamorio#4857]
When traced in filtered mode, the total number of records does not equal to the number of instructions executed during tracing.   It would be very useful to have accurate instruction count for filtered trace. At the minimum, it should provide a total number of instructions executed during the tracing period.   Additional details such as # of instructions per thread, or # of instructions since last record (i.e. for every filtered miss) would great with the understanding that these will add additional overhead in speed and size.

This feature would be extremely useful to try to correlate filtered trace with unfiltered trace and would enable filtered trace be more useful for cache studies.

**Comment by derekbruening** [comment]
To add context, this is about drcachesim/drmemtrace traces, not core traces.

**Comment by derekbruening** [comment]
A prototype (after hitting and fixing #4861) implementing per-miss count markers
and measured on bzip2 with local SSD storage (which with -L0_filter is cpu-bound):

+ Incrementing a counter per instruction is too expensive (1.5x to 1.9x w/o
  any extra i/o), but per block (fixup should be possible in raw2trace) is
  not bad (1.0x to 1.07x).
+ Per-miss i/o is 50% more output and pushes this to be no longer purely
  cpu-bound. i+d is a 1.26x time hit.
+ Jumping to 512K filter caches reduces per-miss i/o to 1.06x time and
  1.08x space: so it does not completely outweigh the overhead of per-miss
  but does shrink it.
+ Squishing the bottom 12 bits of the counter into the existing i/o
  (relying on BMI2) shrinks the 1.26x to 1.05x. But that's w/o overflow
  checks. Not sure this is worth the complexity.

The decision is to abandon per-miss entries and just have a single count marker on thread exit.
The counter is incremented once per block.

**Comment by derekbruening** [comment]
More frequent count entries in the traces is desirable.  Re-opening to add the count to each buffer, which should be very low overhead.
