### ISSUE TITLE
Update drcachesim and sample tracers to record original, not emulation, instruction sequences

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#4865]
With #3112 we have support for marking emulation sequences where the original application code is distinct from what is executed on the machine.  In addition to emulation for features from different generations of architectures, we plan to have emulation markers for rep string expansion and scatter-gather expansion.  This issue covers changing the drcachesim/drmemtrace tracer and all our sample tracers to record the original, rather than emulation, sequences.  We already have hardcoded special cases for rep string expansion in drcachesim; we should be able to eliminate that and replace with general handling.

**Comment by derekbruening** [comment]
For rep str expansion and scatter gather expansion, our tools should look at the original instruction for instruction tracing, but the emulation sequence for recording data addresses (and/or values) in traces.

But does that hold for all emulation sequences?  There aren't many examples to look at (xref #3173).  @AssadHashmi does this generalization seem reasonable for all of the various emulations used by ArmIE, or would most of them want the *original* instruction's data address?  And if so do we need a flag indicating whether an emulation sequence is a tool-simplification-expansion versus a true emulation?

**Comment by derekbruening** [comment]
Note that the rep str and scatter gather expansions are today using the translation field to point at the original insruction, which makes instruction tracing mostly do the right thing: the original instruction address, with the emulation data addresses/values.  However, the rep str expansion ends up with 3 app instructions instead of 1, messing up instruction counters; plus I believe it has the wrong instruction size.  This is why we wanted to use the emulation markers there.

**Comment by derekbruening** [comment]
(The instruction counting problem shows up in things like #4857 and today are solved with hardcoded checks for a rep str expansion.)

**Comment by AssadHashmi** [comment]
> But does that hold for all emulation sequences? There aren't many examples to look at (xref #3173). @AssadHashmi does this generalization seem reasonable for all of the various emulations used by ArmIE,  

@derekbruening to clarify, when you say
> or would most of them want the _original_ instruction's data address?

Do you mean the instruction to be emulated and its address as it appears in the subject binary execution space? If so, the answer is yes.

> And if so do we need a flag indicating whether an emulation sequence is a tool-simplification-expansion versus a true emulation?

Does this mean an emulation sequence of native instructions will either include instrumentation instructions or it won't as indicated by the flag?

**Comment by derekbruening** [comment]
> > And if so do we need a flag indicating whether an emulation sequence is a tool-simplification-expansion versus a true emulation?
>
> Does this mean an emulation sequence of native instructions will either include instrumentation instructions or it won't as indicated by the flag?

No, the flag would tell a client (such as memtrace_simple or drmemtrace) whether to instrument the original native to-be-emulated instruction or to instrument the replacement emulation sequence instructions (or rather the ones in the sequence that are marked as app instructions).  It seems we have two cases:

1) Instrument the original instruction in every way (e.g., ArmIE emulation).
2) Instrument the original instruction for instruction observation, but instrument the emulation sequence for data load/store observation (e.g., x86 rep string expansion, or all-platform scatter/gather expansion: expansions solely for convenience to unroll or make explicit loops or complex sequences of loads/stores for simpler instrumentation).

**Comment by AssadHashmi** [comment]
> No, the flag would tell a client (such as memtrace_simple or drmemtrace) whether to instrument the original native to-be-emulated instruction or to instrument the replacement emulation sequence instructions (or rather the ones in the sequence that are marked as app instructions). It seems we have two cases:
> 
> 1. Instrument the original instruction in every way (e.g., ArmIE emulation).
> 2. Instrument the original instruction for instruction observation, but instrument the emulation sequence for data load/store observation (e.g., x86 rep string expansion, or all-platform scatter/gather expansion: expansions solely for convenience to unroll or make explicit loops or complex sequences of loads/stores for simpler instrumentation).

In that case if I understand correctly we do need the flag.

**Comment by derekbruening** [comment]
From https://github.com/DynamoRIO/dynamorio/issues/4866#issuecomment-828864737 this is the proposal, with the new DR_EMULATE_DATA flag for the two types of emulation, and new convenience routines drmgr_in_emulation_region and DR_EMULATE_FIRST_INSTR to avoid the client having to keep state about what emulation labels it saw:

```C
event_bb_insert(instr_t *exec_instr) {
  emulated_instr_t emulation;
  if (drmgr_in_emulation_region(&emulation)) {
    if (TEST(DR_EMULATE_FIRST_INSTR, emulation.flags)) {
      record_instr_fetch(emulation.instr);
      if (TEST(DR_EMULATE_DATA, emulation.flags))
        record_data_addresses(emulation.instr);
    } // Else skip further instr fecthes until outside emulation region.
    if (instr_is_app(exec_instr) && !TEST(DR_EMULATE_DATA, emulation.flags))
      record_data_addresses(exec_instr);
  } else if (instr_is_app(exec_instr)) {
    record_instr_fetch(exec_instr);
    record_data_addresses(exec_instr);
  }
}
```

However, if many clients want to use this scheme, that is a little complex.  Could we change the drmgr events to make it easier?  We want an iterator over instructions and a separate iterator over data addresses?

**Comment by derekbruening** [comment]
Xref drcachesim offline trace reconstruction where the raw2trace post-processor assumes it can figure out from a static decoding how many memory references each instruction contains.  If that is not possible without runtime mask values for scatter-gather instructions we should figure out whether the general proposal here needs to change, or whether this is a specific problem with drcachesim+raw2trace and it needs to insert a memref count entry or something to tell raw2trace how many of the subsequent memrefs belong to the scatter/gather (or, have raw2trace assume there's nothing else in the block due to block isolation).

**Comment by derekbruening** [comment]
Re: the prior comment: after discussion it seems we do not need to change the emulation iteration proposal above for scatter-gather and have raw2trace assume it's the only instruction in the block will suffice.

Re: making new drmgr events for simpler iteration: if the typical observational client does want to iterate only over the original being-emulated instructions, maybe we should make new drmgr events for them?
Something like an insertion event for instruction observation and a separate insertion event for data observation, where for a scatter the former is called once and the latter N times?

**Comment by derekbruening** [comment]
@AssadHashmi -- a heads up for ArmIE that the new emulated_instr_t.flags field must be initialized.  Binary compatibility is maintained, but upon rebuilding the field may be uninitialized w/o a source code change.

**Comment by derekbruening** [comment]
Whoops meant to keep open for the new events.

**Comment by derekbruening** [comment]
> Re: making new drmgr events for simpler iteration: if the typical observational client does want to iterate only over the original being-emulated instructions, maybe we should make new drmgr events for them?
> Something like an insertion event for instruction observation and a separate insertion event for data observation, where for a scatter the former is called once and the latter N times?

I started implementing these new events as something like this:

```C
DR_EXPORT
/**
 * Registers callback functions for the second and third
 * instrumentation stages: application analysis and instrumentation
 * insertion, where instrumentation insertion is further split into
 * application instruction fetch and operand observation.  These split
 * events are emulation-aware and pass the original, being-emulated
 * instruction as appropriate, rather than the being-executed
 * instruction stream.
 *
 * The same restrictions described in drmgr_register_bb_instrumentation_event()
 * for the second and third stages apply here.  The same ARM predication behavior
 * applies as well.
 *
 * The \p analysis_func, \p instr_fetch_func, and \p instr_operands_func share the
 * same priority.  The \p user_data parameter can be used to pass data from the
 * analysis stage to the insertion stage.
 *
 * All instrumentation must follow the guidelines for
 * #dr_register_bb_event().
 *
 * \return false if the given priority request cannot be satisfied
 * (e.g., \p priority->before is already ordered after \p
 * priority->after) or the given name is already taken.
 *
 * @param[in]  analysis_func   The analysis callback to be called for the second stage.
 *                             Can be NULL if \p instr_fetch_func is non-NULL, in which
 *                             case the user_data passed to \p instr_fetch_func is NULL.
 * @param[in]  instr_fetch_func The application instruction callback to be called as part
 *                             of the third stage for processing the instruction fetch.
 * @param[in]  instr_operands_func The application instruction callback to be called as
 *                                 part of the third stage for processing the
 *                                 instruction's operands.
 * @param[in]  priority        Specifies the relative ordering of both callbacks.
 *                             Can be NULL, in which case a default priority is used.
 */
bool
drmgr_register_bb_app_observation_event(drmgr_analysis_cb_t analysis_func,
                                        drmgr_app_cb_t instr_fetch_func,
                                        drmgr_app_cb_t instr_operands_func,
                                        drmgr_priority_t *priority);
```

I took memtrace_simple.c and split its insertion event into two,

However, while implementing the drmgr logic, I'm realizing that adding a new event model complicates other libraries: e.g., drbbdup has its own insertion callback, and we would have to add a version with the two separate fetch and operand versions there as well.

Taking a step back, I'm considering instead a solution that keeps the existing insertion event and simplifies the complex drmgr_in_emulation_region conditionals from above, which was like this:
```C
    const emulated_instr_t *emulation;
    if (drmgr_in_emulation_region(drcontext, &emulation)) {
        if (TEST(DR_EMULATE_FIRST_INSTR, emulation->flags)) {
            record_instr_fetch_orig(emulation->instr);
            if (!TEST(DR_EMULATE_INSTR_ONLY, emulation->flags))
                record_data_addresses_orig(emulation->instr);
        } /* Else skip further instr fetches until outside emulation region. */
        if (instr_is_app(inst) && TEST(DR_EMULATE_INSTR_ONLY, emulation->flags))
            record_data_addresses_derived(inst);
    } else if (instr_is_app(inst)) {
        record_instr_fetch_unchanged(inst);
        record_data_addresses_unchanged(inst);
    }
```
What if that looked like this:
```C
    instr_t *instr_fetch = drmgr_orig_app_instr_for_fetch(drcontext);
    if (instr_fetch != NULL)
        record_instr_fetch(instr_inst);
    instr_t *instr_operands = drmgr_orig_app_instr_for_operands(drcontext);
    if (instr_operands_valid != NULL)
        record_data_addresses(instr_operands);
```

**Comment by derekbruening** [comment]
Here's my local test, which I will turn into an automated suite test:

Before:
```
$ bin64/drrun -c api/bin/libmemtrace_simple.so -- suite/tests/bin/allasm_repstr
$ cat `ls -1td api/bin/*.log|head -1`
Format: <data address>: <data size>, <(r)ead/(w)rite/opcode>
0x401018:  1, movs
0x40200e:  1, r
0x402000:  1, w
0x401018:  1, movs
0x40200f:  1, r
0x402001:  1, w
0x401018:  1, movs
0x402010:  1, r
0x402002:  1, w
0x401018:  1, movs
0x402011:  1, r
0x402003:  1, w
0x401018:  1, movs
0x402012:  1, r
0x402004:  1, w
```
After:
```
Format: <data address>: <data size>, <(r)ead/(w)rite/opcode>
0x401018:  2, rep movs
0x40200e:  1, r
0x402000:  1, w
0x401018:  2, rep movs
0x40200f:  1, r
0x402001:  1, w
0x401018:  2, rep movs
0x402010:  1, r
0x402002:  1, w
0x401018:  2, rep movs
0x402011:  1, r
0x402003:  1, w
0x401018:  2, rep movs
0x402012:  1, r
0x402004:  1, w
```

**Comment by derekbruening** [comment]
#4948 covers changing the rep string expansion to remove the "rep movs" instrs from all but the 1st iteration.
