### ISSUE TITLE
APP CRASH - Application crashes when new process should be created (tested for ShellExecuteW).

### ISSUE THREAD

**Issue by N0fix** [DynamoRIO/dynamorio#4897]
**Describe the bug**
An application that calls ShellExecuteW crashes ("application stop responding" textbox appears) when being instrumented with any DynamoRIO client dll. This does not happen with drcov and other prebuilt tools shipped with DynamoRIO.

**To Reproduce**
1. Have a 32 bits DynamoRIO client dll that does nothing. (empty `dr_client_main`).
```C
#include "dr_api.h"
DR_EXPORT void
dr_client_main(client_id_t id, int argc, const char* argv[])
{
}
```
2. Have an application that executes something with ShellExecuteW:
```C
int main(int argc, char** argv)
{
    MessageBoxA(0, "smth", "smth", MB_OK); // normal conditions, this textbox will show up twice
    if(CopyFileA("TestApp.exe", "TestApp2.exe", true)) { // the original executable is named "TestApp.exe"
       ShellExecuteW(0, 0, L"TestApp2.exe", 0,0,0);
	ExitProcess(0);
    }
    return 0;
}
```
3. Run the application under `drrun.exe`:
```
> .\dynRIO\bin32\drrun.exe -c .\dummyDLL_32.dll -- .\TestApp.exe
```
When running any client (except prebuilt tools such as `drcov`), the application crashes in `ShellExecuteW`, `TestApp2.exe` is never executed (the process is not getting spawned at all. `TestApp.exe` crashes before reaching `ExitProcess`.), and a popup shows up telling that `TestApp.exe` has stopped working.

**Expected behavior**
Running `TestApp.exe` without any client copies TestApp.exe to TestApp2.exe and executes it. Under normal circumstances we should see the 2 textboxes named "smth" appear.

**Versions**
This behavior seems to occur since [build 18663](https://github.com/DynamoRIO/dynamorio/commit/9be64f004ece3fdcf3f91f7ead9c72f688b9ed1b). I have tested some DynamoRIO versions >= 8.0.0.1 and prior to build 18663, and they work as intended. 
I have successfully reproduced this behavior on Windows 7 SP1 6.1.7601 and on Windows 10 Build 18363.

**Additional notes**
I did not test this behavior on x64.

**Comment by derekbruening** [comment]
Does `set(DynamoRIO_USE_LIBC OFF)` in the cmake for the empty client make the problem go away?

**Comment by derekbruening** [comment]
The obviously-Windows-affecting changes between build 18655 and 18663 from the list https://github.com/DynamoRIO/dynamorio/compare/cronbuild-8.0.18655...cronbuild-8.0.18663 seem to be:

- PR #4701 
- PR #4702 
- PR #4703

**Comment by N0fix** [comment]
> Does `set(DynamoRIO_USE_LIBC OFF)` in the cmake for the empty client make the problem go away?

This had no effect.
I've been trying to create an empty project all over again and test it all out. Everything works no matters DynRIO version. Problems occurs when using external library such as [fmt](https://github.com/fmtlib/fmt). 
As specified in the [documentation](https://dynamorio.org/using.html#sec_extlibs), `set(DynamoRIO_USE_LIBC OFF)` should be enough not to make things crash. From my module loading logger, I can notice that the crash seems to occur when loading something in ntdll.

So to make things clear : the problem comes from dynamoRIO, as different versions of `drrun.exe` has different outcomes. The problem also comes from external libraries. I am investigating the issue but I am not sure where the problem comes from and what I should do to fix it.

**Comment by derekbruening** [comment]
I'm confused:

> > Does `set(DynamoRIO_USE_LIBC OFF)` in the cmake for the empty client make the problem go away?
> 
> This had no effect.

So an empty client still crashes.  I would expect this to have made the difference, since that is likely the main difference between the prebuilt drcov and other libraries and a new client built locally.

> I've been trying to create an empty project all over again and test it all out. Everything works no matters DynRIO version. 

?  You mean the problems all went away?

> Problems occurs when using external library such as [fmt](https://github.com/fmtlib/fmt) (which does not use alertable system calls).

So an empty client *does* work fine?

> As specified in the [documentation](https://dynamorio.org/using.html#sec_extlibs), `set(DynamoRIO_USE_LIBC OFF)` should be enough not to make things crash. From my module loading logger, I can notice that the crash seems to occur when loading something in ntdll.

Note that ntdll.dll is loaded by the kernel and DR's private loader does not make a separate copy, but instead tries to redirect problematic imports.  Probably you mean when *calling* an ntdll function -- which one?

> A possible explanation for this crash is a conflict between the external lib runtime and dynamoRIO's one.
> I also tried to compiled the external lib statically, and it did not change anything on the outcome : a crash occurs on `ShellExecuteW`.
> 
> So to make things clear : the problem comes from dynamoRIO, as different versions of `drrun.exe` has different outcomes. The problem also comes from external libraries. I am investigating the issue but I am not sure where the problem comes from and what I should do to fix it.

To make sure we understand:
+ Empty clients or clients not using external libraries like `fmt` work fine with the latest DR version
+ A client using `fmt` hits problems in ShellExecuteW, but only with DR 8.0.18663 or later

Right?

I would suggest seeing which of the 3 PR's listed at https://github.com/DynamoRIO/dynamorio/issues/4897#issuecomment-834458538 makes the difference as it might help pinpoint the problem.

I would also look at all of the imports of `fmt`.  Is it merely loading `fmt` or calling some function that triggers problems?  If it's merely loading, I would look at all its imported-from dll's and figure out which one of those is problematic: by either using those instead of `fmt`, or disabling their init routines.

**Comment by N0fix** [comment]
> I'm confused:
> 
> > > Does `set(DynamoRIO_USE_LIBC OFF)` in the cmake for the empty client make the problem go away?
> > 
> > 
> > This had no effect.
> 
> So an empty client still crashes. I would expect this to have made the difference, since that is likely the main difference between the prebuilt drcov and other libraries and a new client built locally.

Let me clarify my mistake : the app is not empty, and crashes only in case I use an external library, staticaly built or not. E.G:
```C
#include "dr_api.h"
#include "fmt/core.h"
DR_EXPORT void
dr_client_main(client_id_t id, int argc, const char* argv[])
{
dr_fprintf(STDERR, fmt::format(stderr, "Something\n").c_str()); // does print, but ShellExecuteW is never executed/crashes.
}
```
In the case of a fully standalone client (no external lib), `ShellExecuteW` gets executed properly, as expected. E.G:
```C
#include "dr_api.h"

DR_EXPORT void
dr_client_main(client_id_t id, int argc, const char* argv[])
{
// works as expected
}
```


> 
> > I've been trying to create an empty project all over again and test it all out. Everything works no matters DynRIO version.
> 
> ? You mean the problems all went away?
> 
> > Problems occurs when using external library such as [fmt](https://github.com/fmtlib/fmt) (which does not use alertable system calls).
> 
> So an empty client _does_ work fine?
> 
An empty project does work fine, my apologies. The problem comes when including external libs.
> > As specified in the [documentation](https://dynamorio.org/using.html#sec_extlibs), `set(DynamoRIO_USE_LIBC OFF)` should be enough not to make things crash. From my module loading logger, I can notice that the crash seems to occur when loading something in ntdll.
> 
> Note that ntdll.dll is loaded by the kernel and DR's private loader does not make a separate copy, but instead tries to redirect problematic imports. Probably you mean when _calling_ an ntdll function -- which one?
> 
I don't know yet, but I could find some time to check this out if this is really relevant, just let me know. 
> > A possible explanation for this crash is a conflict between the external lib runtime and dynamoRIO's one.
> > I also tried to compiled the external lib statically, and it did not change anything on the outcome : a crash occurs on `ShellExecuteW`.
> > So to make things clear : the problem comes from dynamoRIO, as different versions of `drrun.exe` has different outcomes. The problem also comes from external libraries. I am investigating the issue but I am not sure where the problem comes from and what I should do to fix it.
> 
> To make sure we understand:
> 
> * Empty clients or clients not using external libraries like `fmt` work fine with the latest DR version
> * A client using `fmt` hits problems in ShellExecuteW, but only with DR 8.0.18663 or later
> 
> Right?
> 
I have been doing my tests again, and I confirm that clients not using external libraries like `fmt` works fine with the latest DR version, and that a client using `fmt` hits problems in ShellExecuteW, but only with DR 8.0.18663 or later.
> I would suggest seeing which of the 3 PR's listed at [#4897 (comment)](https://github.com/DynamoRIO/dynamorio/issues/4897#issuecomment-834458538) makes the difference as it might help pinpoint the problem.
> 
I will be doing that as soon as I can.
> I would also look at all of the imports of `fmt`. Is it merely loading `fmt` or calling some function that triggers problems? If it's merely loading, I would look at all its imported-from dll's and figure out which one of those is problematic: by either using those instead of `fmt`, or disabling their init routines.
I did not check out its imports but it is supposed to be minimalist and loads perfectly well (and I usually can use it without any problem, except since DR 8.0.18663).

**Comment by N0fix** [comment]
I am coming back with some news. I have been testing [PR #4702](https://github.com/DynamoRIO/dynamorio/pull/4702) and the app-crash behavior previously described occurs: target starts, shows the first MessageBox, and crashes at ShellExecuteW (`msgbox_mask 15` is not showing that the process is exiting properly nor is notifying a new process to be created), only when dynamoRIO client is using external lib such as `fmt`.

**Comment by N0fix** [comment]
Tried this issue again with latest cronbuild and everything seems to work perfectly well, thus closing this issue.
