### ISSUE TITLE
Is DynamoRIO able to instrument a specific basic block if I know the line number or sth of this bb?

### ISSUE THREAD

**Issue by thereAreDemonsNearby** [DynamoRIO/dynamorio#4911]

**Comment by abhinav92003** [comment]
Hi. Thanks for your interest in using DynamoRIO. 

The discussion group for DynamoRIO is https://groups.google.com/g/dynamorio-users. For better visibility to other contributors and users, please use the group for questions about the tool. This issue tracker is reserved for known bugs and feature requests.
