### ISSUE TITLE
drcachesim.phys test fails on AArch64

### ISSUE THREAD

**Issue by AssadHashmi** [DynamoRIO/dynamorio#4922]
Migrating the AArch64 Jenkins CI to an Ampere Altera machine caused  a regression in the `drcachesim.phys` test with:
```
Internal Error: Failed to encode instruction: 'stur   %x30 -> +0x010c(%x3)[8byte]'
```

**Comment by derekbruening** [comment]
Is the instruction malformed, or is this an encoder error?

**Comment by AssadHashmi** [comment]
> Is the instruction malformed, or is this an encoder error?

My initial guess is a malformed instruction because the offset should be a 9 bit signed immediate in the range -256 to 255, and the `+` in the `+0x010c` field along with no leading 1s implies that whatever is generating the instruction is setting offset to 268 rather than e.g. -244 (0xff0c). The unit tests work for values in the legal range and fail as expected otherwise.

@MDevereau will look at this  in detail shortly but any insights particularly about the test would help, e.g. is that offset generated as part of the test or by a compiler? Are newer versions of compiler+libs on the Ampere Altra generating different test instructions from the old Jenkins CI host?

**Comment by derekbruening** [comment]
> @MDevereau will look at this in detail shortly but any insights particularly about the test would help, e.g. is that offset generated as part of the test or by a compiler? Are newer versions of compiler+libs on the Ampere Altra generating different test instructions from the old Jenkins CI host?

One possibility is instrumentation using XINST_CREATE_store which can produce STUR?  But the offset does not look familiar: too big for a trace buffer, and the base would be x28 for a DR slot.

**Comment by AssadHashmi** [comment]
I checked and ran more encoding tests on `INSTR_CREATE_stur()`. I'm pretty sure that the signed immediate offset is encoded correctly within the specified range of -256->255.

AFAICT the `tool.drcachesim.phys` test is using an out-of-range offset. Adding the following `DR_ASSERT`s and `dr_printf`s in `online_instru_t::insert_save_pc()`:
```
@@ -177,6 +177,8 @@ online_instru_t::insert_save_pc(void *drcontext, instrlist_t *ilist, instr_t *wh
                                 reg_id_t base, reg_id_t scratch, app_pc pc, int adjust)
 {
     int disp = adjust + offsetof(trace_entry_t, addr);
+    dr_printf("adjust=%d\n", adjust);
+    dr_printf("offsetof(trace_entry_t, addr)=%d\n", offsetof(trace_entry_t, addr));
 #ifdef X86_32
     ptr_int_t val = (ptr_int_t)pc;
     MINSERT(ilist, where,
@@ -190,6 +192,9 @@ online_instru_t::insert_save_pc(void *drcontext, instrlist_t *ilist, instr_t *wh
     // can skip the top half), just like on ARM.
     instrlist_insert_mov_immed_ptrsz(drcontext, (ptr_int_t)pc, opnd_create_reg(scratch),
                                      ilist, where, NULL, NULL);
+    dr_printf("disp=%d\n", disp);
+    DR_ASSERT(disp >= -256);
+    DR_ASSERT(disp <= 255);
     MINSERT(ilist, where,
             XINST_CREATE_store(drcontext, OPND_CREATE_MEMPTR(base, disp),
                                opnd_create_reg(scratch)));
```
Exposes the failure:
```
171: adjust=252
171: offsetof(trace_entry_t, addr)=4
171: disp=256
171: ASSERT FAILURE: /path/to/dynamorio/clients/drcachesim/tracer/instru_online.cpp:197: disp <= 255 ()
171: ---- <application exited with code 65280> ----
171: Cache simulation results:
```

**Comment by abhinav92003** [comment]
Looks like we need to reduce `MAX_NUM_DELAY_INSTRS` at https://github.com/DynamoRIO/dynamorio/blob/becdaf77e158d174d3fc29604ad7c68313215075/clients/drcachesim/tracer/tracer.cpp#L135

**Comment by abhinav92003** [comment]
`XINST_CREATE_store` chooses `stur` (which requires -256 <= offset <= 255), instead of `str` (which requires 0 <= offset <= 32760). This is because not all of our writes are aligned to the write-size. Particularly, the 8-byte write for the pc may happen at offsets that are not 8-byte aligned. This is because the `struct _trace_entry_t` is 12 bytes.

We have two options:
- ensure that all writes are aligned, by padding `struct _trace_entry_t` with 4 bytes, before the pc field.
- reduce `MAX_NUM_DELAY_INSTRS` so that we never go beyond the 255 disp limit of `stur`.

The first options seems a waste of space, but it allows larger `MAX_NUM_DELAY_INSTRS`.

**Comment by abhinav92003** [comment]
I'm assuming that we want to avoid the overhead of using a register offset, which would add another instruction in the instrumentation by `insert_save_pc` and `insert_save_addr` (the two 8 byte writes).

**Comment by abhinav92003** [comment]
The impact of reducing `MAX_NUM_DELAY_INSTRS` is essentially more occurrences of the drreg_reserve -> load buf_ptr -> drreg_unreserve sequence, right? And this will impact the cases where we have many consecutive instrs with no memory refs.

I'm also trying to find why we don't hit this case without `-use_physical`, as the `num_delay_instrs` buffer should fill up the same in both cases.

**Comment by abhinav92003** [comment]
> I'm also trying to find why we don't hit this case without -use_physical, as the num_delay_instrs buffer should fill up the same in both cases.

Ah that's just because `instrment_ibundle` writes data only when the ibundle is full or we are at the last instruction.

**Comment by derekbruening** [comment]
> > I'm also trying to find why we don't hit this case without -use_physical, as the num_delay_instrs buffer should fill up the same in both cases.
> 
> Ah that's just because `instrment_ibundle` writes data only when the ibundle is full or we are at the last instruction.

Not following: I thought -use_physical went through and modified the addresses when the buffer was full, but didn't otherwise affect things?

**Comment by abhinav92003** [comment]
> Not following: I thought -use_physical went through and modified the addresses when the buffer was full, but didn't otherwise affect things?

We disable instruction bundling with `-use_physical`.
https://github.com/DynamoRIO/dynamorio/blob/192c14388f9e5f994afdcf6452ddba1304e3408b/clients/drcachesim/tracer/tracer.cpp#L673. Without instruction bundling, we write more data to the buffer (and not just when the ibundle is full). That's perhaps the reason why we haven't seen this issue already.

Another simple solution would be to update the buf_ptr when we're about to reach the 255 offset limit. `tracer.cpp` would be depending on some implementation details of `instru_online.cpp` so it's not perfect, but I don't see a simpler solution.
