### ISSUE TITLE
drsym_init crashes on Windows 10

### ISSUE THREAD

**Issue by SweetVishnya** [DynamoRIO/dynamorio#4926]
Hi!

I call
```
drmgr_init();
drsym_init(0);
```
in `dr_client_main`. And `drsym_init` crashes:
```
<Application C:\test\sydr\build-debug\hello.exe (10980).  Internal Error: DynamoRIO debug check 
failure: C:\test\sydr\dynamorio\core\win32\loader.c:771 !is_dynamo_address(dcontext->app_fls_dat
a)
```

What can it be?

**Comment by johnfxgalea** [comment]
Thanks for letting us know about the above. If you have the time to dig deeper and identify the root cause, that would be great. Otherwise, kindly wait until a DR dev can take a closer look.

**Comment by SweetVishnya** [comment]
https://github.com/DynamoRIO/dynamorio/blob/master/ext/drsyms/drsyms_windows.c#L207

This line crashes.

**Comment by derekbruening** [comment]
"Windows 10" is not specific enough: each update for 10 is as different from each other as 10 is from 8.1, from DR's point of view.  

This certainly does not reproduce on the regression tests nor on other developers' machines: otherwise such a simple crash would have been hit before.  Likely it is a particular version on this machine, or possibly other software on the machine, triggering the problem.

**Comment by SweetVishnya** [comment]
I have Windows 10 Pro N 20H2 19042.1023 Windows Feature Experience Pack 120.2212.2020.0

**Comment by SweetVishnya** [comment]
Also, this reproduces only on our CI QEMU Windows 10. Maybe VS links other dll there.

**Comment by SweetVishnya** [comment]
I have VS Community 2017 15.9.36

**Comment by derekbruening** [comment]
What is the dbghelp.dll version?  Does a different version have different behavior?

**Comment by SweetVishnya** [comment]
> What is the dbghelp.dll version? Does a different version have different behavior?

Installing [Debugging Tools for Windows](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/) solved my issue. Seems that DR does not work with the system dbghelp.dll. Thank you for assistance!
