### ISSUE TITLE
tool.drcachesim threads tests fail on AArch64

### ISSUE THREAD

**Issue by AssadHashmi** [DynamoRIO/dynamorio#4928]
Migrating the AArch64 Jenkins CI to an Ampere Altera machine caused a regression in the `tool.drcachesim.threads` and `tool.drcachesim.TLB-threads` tests failing with timeout messages.

**Comment by derekbruening** [comment]
I think there are multiple hangs here, in fact.  I found one with plain DR and fixed it but dr$sim online still hangs.  Will add more details later.  The one I found is related to #2502.

**Comment by derekbruening** [comment]
Looks like the libc write() contains calls to pthread cancel code.  This pthread code must eventually involve a futex, and it must interact with application resources (we aren't currently able to separate pthread state or support a private libpthread: #956).

The simplest solution is to have the private loader redirect `write` to `os_write`.  May was well do the same for `read`; and may as well redirect `open` to `os_open_protected` (thought we were already doing that: I guess it was just `dr_open_file`) for file descriptor isolation.

With that in place: there is no hang!

I also tested other related issues:

+ #4928: drcachesim.threads and drcachesim.TLB-threads
+ #2417: drcachesim.coherence
+ #4954: drcachesim.threads-with-config-file

```
derek@dynamorio:~/dr/build_rel$ for i in sim.threads\$ sim.TLB-threads sim.coherence sim.threads-with; do echo $i; ctest --repeat-until-fail 20000 -R $i > RUN-$i 2>&1; done
sim.threads$
sim.TLB-threads
sim.coherence
sim.threads-with
derek@dynamorio:~/dr/build_rel$ grep -c Passed RUN-*
RUN-sim.coherence:20000
RUN-sim.threads$:20000
RUN-sim.threads-with:20000
RUN-sim.TLB-threads:20000
derek@dynamorio:~/dr/build_rel$ grep failed RUN-*
RUN-sim.coherence:100% tests passed, 0 tests failed out of 1
RUN-sim.threads$:100% tests passed, 0 tests failed out of 1
RUN-sim.threads-with:100% tests passed, 0 tests failed out of 1
RUN-sim.TLB-threads:100% tests passed, 0 tests failed out of 1
```

Looks like PR #5367 plus this `write` redirect solve all the hangs!

**Comment by edeiana** [comment]
code_api|tool.drcachesim.TLB-threads flaky on #6805
