### ISSUE TITLE
[drreg] drreg_reserve_aflags failed to reserve/restore for the condition instructions on x86 platform

### ISSUE THREAD

**Issue by JerryYouxin** [DynamoRIO/dynamorio#4940]
**Description**

On x86 platform, `drreg_reserve_aflags`/`drreg_unreserve_aflags` failed to reserve/restore the arithmetic flags for the condition instructions (e.g., `cmovcc`, `sbb`, e.t.c.). Similarly, `drreg_aflags_are_dead` also results in the wrong estimation, where the condition instructions will read/use the arithmetic flags and DRReg still estimates the arithmetic flags are dead. This is the root cause of the failure of `drreg_reserve_aflags` to properly reserve the arithmetic flags.

**To Reproduce**
To reproduce the bug,  I write a minimal client tool and an example target program in this [gist post](https://gist.github.com/JerryYouxin/58fd5a24113f3eea69b4264919afda88). The minimal client tool uses `drx_aflags_are_dead` to find out whether the drreg's liveness estimation is correct or not. For this minimal example, we can detect the arithmetic flag liveness estimation given by drreg and drx differs for `cmovnz` condition instruction, where drreg estimates the arithmetic flags are dead (wrong estimation). This is also happens when building with -debug supports.

**Expected behavior**
`drreg_reserve_aflags`/`drreg_unreserve_aflags` should correctly reserve/restore the arithmetic flags for the condition instructions like `cmovcc`, where the arithmetic flags should not be affected before and after the instrumented codes of client tools.

**Versions**
 - The `master` branch of Dynamorio repository.
- OS: Ubuntu 20.04 LTS with kernel 5.8.0-53-generic, x86_64

**Comment by derekbruening** [comment]
Is this limited to use of drreg outside of the insertion phase?   The PR title talks about the forward analysis, which is only used outside the insertion phase, and thus I believe the bug would not affect any existing clients in the DR repository?

**Comment by JerryYouxin** [comment]
Yes, the root cause of this bug is inside the forward analysis, so I believe it only affects the analysis phase (which I have tested).

**Comment by derekbruening** [comment]
> Yes, the root cause of this bug is inside the forward analysis, so I believe it only affects the analysis phase (which I have tested).

Curious as to why the analysis phase: officially new instructions are not supposed to be added there, so `drreg_reserve_aflags` would not normally be used there.  I would expect this to involve the app2app or instru2instru phases.

**Comment by JerryYouxin** [comment]
> Application analysis passes in the second stage are not allowed to add to or change the instruction list other than adding label instructions, and are intended for analysis of application code either for immediate use or for use by the third stage.

Oh, I read the doc in detail and it is not allowed to do instrumentation in the analysis pass. But `drmgr` actually does not check for these constrain and the `drcctprof` library I'm using also uses the analysis pass for instrumentation, and it works well, too.

> I would expect this to involve the app2app or instru2instru phases.

Yes, I think this bug also exists in app2app and instru2instru phases like the analysis phase.
