### ISSUE TITLE
ASSERT (opnd_create_immed_int: value too large for 8-bit size) in offline tracer when running with L0_filter and if application has basic block longer than 256 insts

### ISSUE THREAD

**Issue by prasun3** [DynamoRIO/dynamorio#4943]
**Describe the bug**
The assert occurs if we have a basic block longer than 256 instructions. The assert goes away if I change `OPND_CREATE_INT8(ud->bb_instr_count)));` to `OPND_CREATE_INT16(ud->bb_instr_count)));`

```
   1051        if (op_L0_filter.get_value()) {
   1052            // Count dynamic instructions per thread.
   1053            // It is too expensive to increment per instruction, so we increment once
   1054            // per block by the instruction count for that block.
   1055            if (drmgr_is_first_nonlabel_instr(drcontext, app)) {
   1056                // On x86 we could do this in one instruction if we clobber the flags: but
   1057                // then we'd have to preserve the flags before our same-line skip in
   1058                // insert_filter_addr().
   1059                dr_insert_read_raw_tls(drcontext, ilist, where, tls_seg,
   1060                                       tls_offs + sizeof(void *) * MEMTRACE_TLS_OFFS_ICOUNT,
   1061                                       reg_ptr);
   1062                MINSERT(ilist, where,
  >1063                        XINST_CREATE_add(drcontext, opnd_create_reg(reg_ptr),
   1064                                         OPND_CREATE_INT8(ud->bb_instr_count)));
   1065                dr_insert_write_raw_tls(drcontext, ilist, where, tls_seg,
   1066                                        tls_offs + sizeof(void *) * MEMTRACE_TLS_OFFS_ICOUNT,
   1067                                        reg_ptr);
   1068            }

(gdb) p ud->bb_instr_count
$5 = 257
```
**To Reproduce**
Run offline tracer with the L0_filter option and an application that has a basic block longer than 256 instructions.

`drrun -t drcachesim -offline -L0_filter -- <app>`

**Expected behavior**
The assert should not fail.

**Screenshots or Pasted Text**

```
opnd_create_immed_int: value too large for 8-bit size
```

**Versions**
 - What version of DynamoRIO are you using? cronbuild-8.0.18752
 - Does the latest build from https://github.com/DynamoRIO/dynamorio/releases solve the problem? No
- What operating system version are you running on? Ubuntu 18.04.5 LTS
- Is your application 32-bit or 64-bit? ELF 64-bit LSB executable

**Additional context**
None

**Comment by derekbruening** [comment]
But `max_bb_instrs` is 256 (https://github.com/DynamoRIO/dynamorio/blob/master/core/optionsx.h#L909), so how are there 257 app instructions?   Could you provide the instruction listing for this block?  @abhinav92003 -- could a scatter/gather expansion have >256 instructions marked as app instructions?

**Comment by abhinav92003** [comment]
Expansion of vpgatherdd with ymm has 121 app instrs: https://gist.github.com/abhinav92003/637c07bac785428550f05c18319f80c2. With zmm it may have 241 I think (still working on verifying). So it's close to the limit, but should be under it.

@prasun3 Can you check the pre-instrumentation contents of the basic block where the assertion is hit? Is that a scatter/gather instr?

**Comment by derekbruening** [comment]
I guess a user could also run with a custom lower value of `-max_bb_instrs` and DR would honor it but scatter expansion would ignore it -- maybe it should just have an abort-if-too-low check or sthg (and similarly this tracer code should have had some checks that nobody raised the value).

**Comment by prasun3** [comment]
It does seem like an off by one error. I see this in the log:

```
reached -max_bb_instrs(256): 257, stopping
page boundary crossed
end_pc = 0x00000000002b9218
```

**Comment by abhinav92003** [comment]
> Wondering whether the max_bb_instrs ends up with an off-by-one -- seeing a > check instead of >= in the interp.c code.

Yeah, I see that too: https://github.com/DynamoRIO/dynamorio/blob/2e6190850e6c389661437deeb9da3caaa8e49e2a/core/arch/interp.c#L3518

This should probably be just `total_instrs < cur_max_bb_instrs`. @prasun3 does that fix the issue on your app?

> I guess a user could also run with a custom lower value of `-max_bb_instrs` and DR would honor it but scatter expansion would ignore it

Agree. Will send out a PR to abort if too low `max_bb_instrs` in `drx_expand_scatter_gather`.

> and similarly this tracer code should have had some checks that nobody raised the value

The tracer issue can be fixed by switching to `OPND_CREATE_INT16` though right?

**Comment by prasun3** [comment]
Changing to `total_instrs < cur_max_bb_instrs` did not help.

Yes, using `OPND_CREATE_INT16` also works as mentioned in the description.

This change fixes the issue:

```
core/arch/interp.c
3911c3911
<         if (total_instrs > DYNAMO_OPTION(max_bb_instrs)) {
---
>         if (total_instrs == DYNAMO_OPTION(max_bb_instrs) - 1) {
```
