### ISSUE TITLE
tool.drcachesim.threads-with-config-file occasional timeout on A64 Jenkins

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#4954]
Hit a timeout in PR #4952 on tool.drcachesim.threads-with-config-file: took 90.00s:
http://139.178.84.19:8080/job/DynamoRIO-AArch64-Precommit/98/consoleFull

```
$
] 90.00 sec

    -------------------------------------------------------------------
     Performance for solving AX=B Linear Equation using Jacobi method
     Running on DynamoRIO
     Client version (null)
    ...................................................................

     Matrix Size :  64
     Threads     :  4


     Started iteration 1 of the computation...

     Finished computing current solution distance in mode 0.
     Mode changed to 0.

     Started iteration 2 of the computation...

     Finished computing current solution distance in mode 0.
     Mode changed to 0.

     Started iteration 3 of the computation...
```

It ends there, in iteration 3.

This happened on PR #4949 too: http://139.178.84.19:8080/job/DynamoRIO-AArch64-Precommit/95/

It passed on re-running and took very little time:
```
41/50 Test #177: code_api|tool.drcachesim.threads-with-config-file ...............   Passed    0.30 sec
```

So it seems like it's not just always close the time limit and it's maybe an actual hang or something?

**Comment by derekbruening** [comment]
The coherence test hit the same hang.  It runs the same app so likely the same problem:

http://139.178.84.19:8080/job/DynamoRIO-AArch64-Precommit/126/consoleFull
```
50/50 Test #178: code_api|tool.drcachesim.coherence ..............................***Timeout 150.02 sec

    -------------------------------------------------------------------
     Performance for solving AX=B Linear Equation using Jacobi method
     Running on DynamoRIO
     Client version (null)
    ...................................................................

     Matrix Size :  64
     Threads     :  4


     Started iteration 1 of the computation...

     Finished computing current solution distance in mode 0.
     Mode changed to 0.

     Started iteration 2 of the computation...
```

**Comment by johnfxgalea** [comment]
We hit this again: http://139.178.84.19:8080/job/DynamoRIO-AArch64-Precommit/147/console

**Comment by derekbruening** [comment]
Xref #3971 where coherence hung on Windows.

Hung again on AArch64 Jenkins: http://139.178.84.19:8080/job/DynamoRIO-AArch64-Precommit/161/consoleFull

**Comment by abhinav92003** [comment]
I think we should add this test ignore list. Failures have become very frequent. It's blocking #4941 right now.

I see the original issue was a timeout, but we're seeing a regex mismatch too now: http://139.178.84.19:8080/job/DynamoRIO-AArch64-Precommit/178/console, http://139.178.84.19:8080/job/DynamoRIO-AArch64-Precommit/234/

**Comment by derekbruening** [comment]
Hit again on coherence test on Jenkins: http://139.178.84.19:8080/job/DynamoRIO-AArch64-Precommit/271/consoleFull

**Comment by derekbruening** [comment]
There may be just one underlying hang bug causing all of these failures: this one, #4928, #2417
