### ISSUE TITLE
drbbdup diagram

### ISSUE THREAD

**Issue by johnfxgalea** [DynamoRIO/dynamorio#4965]
The diagram included in the documentation of drbbdup is no longer being shown.

Doc: https://dynamorio.org/page_drbbdup.html
Image: https://github.com/DynamoRIO/dynamorio/blob/master/api/docs/images/drbbdup_image.svg

**Comment by derekbruening** [comment]
`Failed to load resource: the server responded with a status of 404 ()`

@johnfxgalea IIRC there was some shift to put images into a subdir but it was a manual process: if you could add the image to the images/ dir of dynamorio.github.io that should solve it

**Comment by johnfxgalea** [comment]
@derekbruening Does the diagram need to be removed from the main repo?

**Comment by derekbruening** [comment]
> @derekbruening Does the diagram need to be removed from the main repo?

No, I think doxygen will complain if it's not there.  (Yes, non-ideal duplication...maybe moving out of images/ would solve?  IMHO not worth messing with at this point.)

**Comment by johnfxgalea** [comment]
https://github.com/DynamoRIO/dynamorio.github.io/pull/24

**Comment by derekbruening** [comment]
I ran the ci-docs Action to regenerate ahead of next week's cronjob so the live page is now fixed.
