### ISSUE TITLE
drcachesim should support any associativity

### ISSUE THREAD

**Issue by algrant-arm** [DynamoRIO/dynamorio#4996]
drcachesim currently only supports power-of-2 associatvities. This is not an inherent property of set-associative caches, and it is not uncommon for production silicon to feature e.g. 3-way or 5-way for L1, or perhaps 12-way or 24-way for outer caches. The size is related to the associativites and hence also might not be a power of 2, e.g. 48K for a 3-way L1.

For correlation against this silicon, and to get more data points in cache studies, it would be useful to support these associativities.

This looks fairly straightforward, it needs some minor adjustments to option validation, and uses of assoc_bits or masking need to change.

**Comment by derekbruening** [comment]
Non-power-of-2 sizes is #4489

**Comment by algrant-arm** [comment]
Ok, we have a pull request almost ready, should we do it under this issue or #4489?

Also, it looks like the "blocks_per_set" variable is misnamed (blocks per set is simply the associativity), propose to change this to "blocks per way".

**Comment by derekbruening** [comment]
Maybe simplest to close this as a duplicate?
