### ISSUE TITLE
CRASH (8.0.18789 SingleStepTest.exe)

### ISSUE THREAD

**Issue by miburt** [DynamoRIO/dynamorio#5018]
**Describe the bug**
My test app (Visual Studio 2017 project/code is attached to this bug: [SingleStepTest.zip](https://github.com/DynamoRIO/dynamorio/files/6826040/SingleStepTest.zip)) sets the trap (single step) flag in the EFLAGS register and continues execution. This causes the CPU to trigger an exception (STATUS_SINGLE_STEP). My code catches the exception, prints “Success” and continues. At least that is what happens without DR. In pseudo code:
```
Print “Single step test…”;
try
{
    TriggerSingleStep();
    Print “Failure!”;
}
except
{
    Print “Success!”;
}
```

The moment I run it under DR, the app crashes with an access violation in dynamic DR code, while it is dealing with the single step exception. A sample DR log file is attached here as well: [log.0.43984.html.zip](https://github.com/DynamoRIO/dynamorio/files/6826089/log.0.43984.html.zip)

**To Reproduce**
1)	Pointer to a minimized application:
	o	Build and run the attached Visual Studio (2017) project. As depicted above, the code is straight forward. A couple of printf() statements, a __try/__except and a few lines of assembler code to set the TF flag.
2)	Precise command line for running the application: 
	o	None for the app itself.
	o	It doesn’t matter what options/parameters I use when running drrun.exe, the outcome is always the same. The app crashes while DR is working on processing the single step exception. 
	o	No dump file is created (even though I specify "-dumpcore_mask 0x8bff") but EventViewer shows that the app crashed with an access violation. Here are 2 command line samples I used to test with:
			drrun.exe -- SingleStepTest.exe
			drrun.exe -debug -loglevel 3 -msgbox_mask 0xF -syntax_intel -dumpcore_mask 0x8bff -- SingleStepTest.exe
	o	According to the DR log file, DR detects and processes the single-step exception but while doing so something seems to go wrong, which eventually leads to an AV in dynamically created DR code.
3)	Exact output or incorrect behavior:
	o	The app start-up code runs just fine, including the “Single step test...” I print out. Then the process just dies due to the (unhandled) AV (access violation) that occurs while the single-step exception is being process in the DR code.

Please also answer these questions:
-	What happens when you run without any client?
	o	I never even tried running it *with* a client.
-	What happens when you run with debug build ("-debug" flag to drrun/drconfig/drinject)?
	o	Doesn’t matter what flags I use for drrun.exe, the outcome always seems to be the same.

**Expected behavior**
“Single step test...” should be printed out followed by “Success!”. The single step exception in between ought to be caught by the app/code and should simply be absorbed.

**Versions**
-	What version of DynamoRIO are you using?
	o	8.0.18789
-	Does the latest build from https://github.com/DynamoRIO/dynamorio/releases solve the problem?
	o	No
-	What operating system version are you running on? ("Windows 10" is *not* sufficient: give the release number.)
	o	10.0.19042.1083
-	Is your application 32-bit or 64-bit?
	o	I built both 32 & 64 bit apps. They both crash. The behavior of DR is slightly different and may result in an access violation or stack buffer overrun. At the end the process is simply taken down by the OS. Under 32 bit I’ve seen the following verbose statements from DR at times:
			<Application tried to execute from unreadable memory 0xa743de54.
			This may be a result of an unsuccessful attack or a potential application vulnerability.>
			<non-syscall, non-int2b 0x29 @ 0x009513b1 from 0x009513ae>

**Comment by derekbruening** [comment]
Please see #3783 (is this a duplicate of that?), #2144.  Please analyze how this is different from the support that was added for #2144.  Also xref #4576.

**Comment by miburt** [comment]
Yes, this seems to be a duplicate of [#3783](https://github.com/DynamoRIO/dynamorio/issues/3783). Sorry about that. Still very new to this...

**Comment by derekbruening** [comment]
Np.  Any help you could provide figuring out what the issue is would be appreciated.  Let's move further discussion to the other issue #3783; closing this one.
