### ISSUE TITLE
build failure on Ubuntu21 gcc10.3: drrun has too-recent import: GLOBAL DEFAULT UND stat@GLIBC_2.33

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#5130]
While reproducing DynamoRIO/drmemory#2425 I made an Ubuntu 21.04 VM and it fails to build all of DR:

```
CMake Error at /home/derek/drmemory/git/src/dynamorio/core/CMake_readelf.cmake:146 (message):
  *** Error: /home/derek/drmemory/git/build_x64_dbg/dynamorio/bin64/drrun has
  too-recent import: GLOBAL DEFAULT UND stat@GLIBC_2.33 (3)
```

**Comment by derekbruening** [comment]
Ended up filing this in the DrM tracker accidentally but will leave that open to cover importing the fix: DynamoRIO/drmemory#2429

**Comment by derekbruening** [comment]
Xref the original #1504.  

Possible action items are:

+ Bump the minimum version where drrun is supported (libdynamorio.so itself will run just about anywhere so this is just about the launcher).

+ Have a separate standard for a release package that is expected to work on random old distros versus someone making a one-off build only for local use.  Maybe via the package-building var that is being set somewhere IIRC.

**Comment by derekbruening** [comment]
@mikaellenz if you are interested perhaps you could take a stab at B) -- sthg like have package.cmake set a cmake var and the launcher of this import check passes that to the sub-script which disable this check for non-packages.

**Comment by mikaellenz** [comment]
Hello @derekbruening !
Based on some posts online, I found  lib32-gcc-libs is missing, so I installed libs (maybe it was absolutely unnecessary.

After I got following warning:
/mnt/ramdisk/drmemory/drsyscall/drsyscall_linux.c: In function ‘handle_semctl’:
/mnt/ramdisk/drmemory/drsyscall/drsyscall_linux.c:979:9: error: ‘arg_val’ is used uninitialized [-Werror=uninitialized]
  979 |     arg = *(union semun *) &arg_val;
      |     ~~^~~~~~~~~~~~~~~~~~~~~~~
/mnt/ramdisk/drmemory/drsyscall/drsyscall_linux.c:973:15: note: ‘arg_val’ declared here
  973 |     ptr_int_t arg_val;
      |               ^~~~~


I fixed warning using following edit (I hope it won't crash running drmemory):
   
     ptr_int_t arg_val=0;

    if ( 0 == (arg_val = (ptr_int_t) pt->sysarg[argnum_semid + 3]))
    {
        return;
    }
    
    Regading build err, I just commented out that check in drmemory/dynamorio/core/CMake_readelf.cmake
    @ line 143.
    
    After that everything successfully compiled. But drmemory works very slow (eats almost 100% of single core) - maybe that also works like it should ( I debug relatively huge project).

**Comment by derekbruening** [comment]
This issue in the DynamoRIO tracker is about the glibc import.  If you would like to submit a PR to Dr. Memory please post that on the https://github.com/DynamoRIO/drmemory repository.
