### ISSUE TITLE
Possibly unhandled system calls in Linux kernel 5.10

### ISSUE THREAD

**Issue by abhinav92003** [DynamoRIO/dynamorio#5131]
Found some unhandled system calls while updated Ubuntu CI to 20.04 in #4953.

On my local system, which is Linux kernel 5.10.46, following system calls are new:

x86-64:
```
+#    define __NR_pidfd_send_signal 424
+#    define __NR_io_uring_setup 425
+#    define __NR_io_uring_enter 426
+#    define __NR_io_uring_register 427
+#    define __NR_open_tree 428
+#    define __NR_move_mount 429
+#    define __NR_fsopen 430
+#    define __NR_fsconfig 431
+#    define __NR_fsmount 432
+#    define __NR_fspick 433
+#    define __NR_pidfd_open 434
+#    define __NR_clone3 435
+#    define __NR_close_range 436
+#    define __NR_openat2 437
+#    define __NR_pidfd_getfd 438
+#    define __NR_faccessat2 439
+#    define __NR_process_madvise 440
```

x86-32:
```
+#    define __NR_semget 393
+#    define __NR_semctl 394
+#    define __NR_shmget 395
+#    define __NR_shmctl 396
+#    define __NR_shmat 397
+#    define __NR_shmdt 398
+#    define __NR_msgget 399
+#    define __NR_msgsnd 400
+#    define __NR_msgrcv 401
+#    define __NR_msgctl 402
+#    define __NR_clock_gettime64 403
+#    define __NR_clock_settime64 404
+#    define __NR_clock_adjtime64 405
+#    define __NR_clock_getres_time64 406
+#    define __NR_clock_nanosleep_time64 407
+#    define __NR_timer_gettime64 408
+#    define __NR_timer_settime64 409
+#    define __NR_timerfd_gettime64 410
+#    define __NR_timerfd_settime64 411
+#    define __NR_utimensat_time64 412
+#    define __NR_pselect6_time64 413
+#    define __NR_ppoll_time64 414
+#    define __NR_io_pgetevents_time64 416
+#    define __NR_recvmmsg_time64 417
+#    define __NR_mq_timedsend_time64 418
+#    define __NR_mq_timedreceive_time64 419
+#    define __NR_semtimedop_time64 420
+#    define __NR_rt_sigtimedwait_time64 421
+#    define __NR_futex_time64 422
+#    define __NR_sched_rr_get_interval_time64 423
+#    define __NR_pidfd_send_signal 424
+#    define __NR_io_uring_setup 425
+#    define __NR_io_uring_enter 426
+#    define __NR_io_uring_register 427
+#    define __NR_open_tree 428
+#    define __NR_move_mount 429
+#    define __NR_fsopen 430
+#    define __NR_fsconfig 431
+#    define __NR_fsmount 432
+#    define __NR_fspick 433
+#    define __NR_pidfd_open 434
+#    define __NR_clone3 435
+#    define __NR_close_range 436
+#    define __NR_openat2 437
+#    define __NR_pidfd_getfd 438
+#    define __NR_faccessat2 439
+#    define __NR_process_madvise 440
```

**Comment by abhinav92003** [comment]
Out of the new ones, the following have a similar syscall for which we have special handling today. @derekbruening I suppose it is high priority to add support for these?
```
SYS_openat2
SYS_close_range
SYS_clone3
SYS_pselect6_time64
SYS_rt_sigtimedwait_time64
SYS_ppoll_time64 => PR #5132 
```

**Comment by derekbruening** [comment]
clone3 seems the highest priority as it relates to losing control.

**Comment by AssadHashmi** [comment]
Looking in the `/usr/include/linux/sched.h` file on my Linux 5.4, Ubuntu 20.04.3 image, the size of `clone_args` is 64 bytes:
```
struct clone_args {
        __aligned_u64 flags;
        __aligned_u64 pidfd;
        __aligned_u64 child_tid;
        __aligned_u64 parent_tid;
        __aligned_u64 exit_signal;
        __aligned_u64 stack;
        __aligned_u64 stack_size;
        __aligned_u64 tls;
};
#endif

#define CLONE_ARGS_SIZE_VER0 64 /* sizeof first published struct */
```
But we have it as the latest version (88 bytes) in `core/unix/include/clone3.h`:
```
/* Derived from struct clone_args defined in /usr/include/linux/sched.h */
typedef struct {
    __aligned_u64 flags;
    __aligned_u64 pidfd;
    __aligned_u64 child_tid;
    __aligned_u64 parent_tid;
    __aligned_u64 exit_signal;
    __aligned_u64 stack;
    __aligned_u64 stack_size;
    __aligned_u64 tls;
    __aligned_u64 set_tid;
    __aligned_u64 set_tid_size;
    __aligned_u64 cgroup;
} clone3_syscall_args_t;
```
Matching https://github.com/torvalds/linux/blob/bfc484fe6abba4b89ec9330e0e68778e2a9856b2/include/uapi/linux/sched.h#L92

Is this intentionally larger for forward compatibility?

**Comment by abhinav92003** [comment]
> Is this intentionally larger for forward compatibility?

This `clone3_syscall_args_t` is derived from the `clone_args` on my machine, which has some additional fields over your machine's version it seems. `clone_args` is expected to grow; there's a size arg in the `clone3` syscall to support that. For DR's `clone3_syscall_args_t` though, I think it should be okay to trim it down till the last field which we need to be aware of (which is `stack_size` I think). Not worth the effort though I guess. 

In any case, I realised a possible forward compatibility issue in DR, which may cause issues if the app is using some future new `clone_args` field which is not present in `clone3_syscall_args_t`. The size of the DR's copy of the args object should be set based on the size of the user's `clone_args` (the third arg to the `clone3` syscall), not the size of the DR `clone3_syscall_args_t`. Or else those extra fields will not be included in the actual syscall to the kernel: https://github.com/DynamoRIO/dynamorio/blob/011757717810bff7fee64d466249727f74af2be9/core/unix/os.c#L6996

I'll send out a fix for this.

**Comment by abhinav92003** [comment]
I guess not setting the size correctly may cause backward-compatibility issues too (if some garbage value is set for the new fields by the memcpy). Is that what prompted your comment above?

**Comment by AssadHashmi** [comment]
> I guess not setting the size correctly may cause backward-compatibility issues too (if some garbage value is set for the new fields by the memcpy). Is that what prompted your comment above?

Yes partly. I was trying to understand how we keep kernel and DR structures in sync across different kernel versions, especially regarding the direction of compatibility, e.g. do we specify the oldest kernel version we can support? And what triggers adding support for newer versions?

**Comment by abhinav92003** [comment]
> I was trying to understand how we keep kernel and DR structures in sync across different kernel versions, especially regarding the direction of compatibility, 

We do try to keep things backward-compatible. E.g. some syscalls were removed in the latest Linux kernel (like umount, stime, alarm on ARM), but we retained their definitions in PR #5148.
https://github.com/DynamoRIO/dynamorio/blob/eb2a333f859d5a9b89bf6d9dbb77f9f4b372811d/core/unix/include/syscall_linux_uapi.h#L14

> e.g. do we specify the oldest kernel version we can support?

I don't think we specify the oldest kernel we support anywhere. @derekbruening might know better.

> And what triggers adding support for newer versions?

The last trigger for supporting newer versions was that Github Actions was deprecating support for Ubuntu 16, so we had to upgrade to Ubuntu 20 and support new syscalls that our tests we using, and a few others that seemed important (like `clone3`, `close_range`). Other than that I guess it can be triggered by some user reporting an issue, like #2759. We don't have a regular schedule afaik.

**Comment by derekbruening** [comment]
Right, the Platform Limitations docs
https://dynamorio.org/release_notes.html#sec_limit_platforms do not specifically name any Linux versions.  We try to run on old distros if it doesn't take much effort.  For libc versions, we do have a minimum (looks like 2.4 x86, 2.17 AArch64) and try to build the launchers (which use libc, unlike libdynamorio.so) without new symbols: xref #1504 and #5130 where we may bump the version there.

**Comment by AssadHashmi** [comment]
Is it worth implementing a tag in DR's syscall data structures which specifies the first kernel version it was introduced?

The reason for this is to catch incompatibilities in use-cases like the following: a Docker container running Ubuntu 20 on a host which is running a kernel <5.1 will crash when `clone3()` is called. Because we invoke this as a raw syscall, `-1` is returned and we can't check `errno` for `ENOSYS`.

A version tag checked at runtime can catch this?

**Comment by derekbruening** [comment]
First, we can check for ENOSYS: raw syscalls return -errno.  (See e.g.
https://github.com/DynamoRIO/dynamorio/blob/master/core/unix/rseq_linux.c#L295
)

Second: so the problem is that DR thinks SYS_clone3 will succeed but
actually it fails with ENOSYS?  In general DR tries to handle syscall
failures but it can be difficult to undo pre-syscall actions and it is
always better to accurately predict failure.  For SYS_clone3 in particular
are you seeing concrete problems?  Probably the easiest thing is to check
for ENOSYS ourselves.

**Comment by AssadHashmi** [comment]
> First, we can check for ENOSYS: raw syscalls return -errno. (See e.g. https://github.com/DynamoRIO/dynamorio/blob/master/core/unix/rseq_linux.c#L295 )

Ah ok, that's good enough, my bad assumption.

> For SYS_clone3 in particular are you seeing concrete problems?

I tested in a Docker container running Ubuntu 20 on a host kernel 4.15 and saw this type of failure in the clone tests:
```
17: Test command: /ubuntu2004/build/bin64/drrun "-s" "90" "-quiet" "-debug" "-killpg" "-stderr_mask" "0xC" "-dumpcore_mask" "0" "-code_api" "--" "/ubuntu2004/build/suite/tests/bin/linux.clone-pie"
17: Test timeout computed to be: 1500
17: Sideline thread started
17: i = 2500000
17: i = 5000000
17: i = 7500000
17: i = 10000000
17: i = 12500000
17: i = 15000000
17: i = 17500000
17: i = 20000000
17: i = 22500000
17: i = 25000000
17: Sideline thread finished
17: Waiting for child to exit
17: Child has exited
17: Error calling clone
17: : Success
17: linux.clone-pie: /ubuntu2004/dynamorio/suite/tests/linux/clone.c:119: test_thread: Assertion `child > -1' failed.
1/1 Test #17: code_api|linux.clone-pie .........***Failed  Required regular expression not found. Regex=[^Sideline thread started
```

The test worked as expected on a kernel version 5.4. Incidentally, the `clone3` man page states:
```
The clone3() system call first appeared in Linux 5.3.
```
bit the title of this issue implies it was around from 5.1.

> Probably the easiest thing is to check for ENOSYS 

Yes, that should be enough.

**Comment by abhinav92003** [comment]
> The test worked as expected on a kernel version 5.4.

clone3 was indeed introduced in 5.3: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=8f6ccf6159aed1f04c6d179f61f6fb2691261e84.

> but the title of this issue implies it was around from 5.1.

The title says 5.10 actually. 5.1 should really be 5.01, but unfortunately the version numbering is a little confusing that way :).

> I tested in a Docker container running Ubuntu 20 on a host kernel 4.15 and saw this type of failure in the clone tests:

So, did you confirm in your setup that the failure was indeed `ENOSYS` due to the test wrongly assuming that clone3 is available?

**Comment by derekbruening** [comment]
> So, did you confirm in your setup that the failure was indeed ENOSYS due to the test wrongly assuming that clone3 is available?

DR doesn't change the return value here so I would expect it to still return ENOSYS and the problem to be that DR expected success and did some work that might cause a resource leak or maybe worse behavior if DR didn't manage to undo it in post-syscall where it sees the failure.

**Comment by abhinav92003** [comment]
Yes, I added a TODO in my last PR for that. I'll fix that as part of this issue itself.
 https://github.com/DynamoRIO/dynamorio/blob/c8ef4f841c0a1be4bad7b52de08b185edf3674cc/core/unix/os.c#L8659

**Comment by AssadHashmi** [comment]
> So, did you confirm in your setup that the failure was indeed `ENOSYS` due to the test wrongly assuming that clone3 is available?

Yes

**Comment by abhinav92003** [comment]
We have handled all syscalls in https://github.com/DynamoRIO/dynamorio/issues/5131#issuecomment-930601571 that are known to have variants that already have special DR handling. Other new syscalls in the first comment can be handled when we find a use-case to do so.
