### ISSUE TITLE
Release DynamoRIO v9.0.0

### ISSUE THREAD

**Issue by abhinav92003** [DynamoRIO/dynamorio#5145]
From offline discussion with @derekbruening: we want to release a new version of DR soon. It has been a while since the last release, which was in April 2020. We have made several stability fixes since then, particularly some related to memory management options. As some users hit issues with OOM recently (see discussions on https://groups.google.com/g/dynamorio-users), possibly due to sub-optimal defaults, it'll be good to create a new release.

Task list for some more fixes to include in the release is as follows. We can add more to this list if needed.

- [X] #5144 (@AssadHashmi)
- [x] #5131 (@abhinav92003)
- [X] #4128 (@derekbruening)
- [X] #2414 (@derekbruening)
- [X] #5190 (@derekbruening)
- [X] samples.dox errors + missing samples (@derekbruening)
- [X] transparency library wording (@derekbruening)
- [X] broken pubs links (@derekbruening)
- [X] #5198 (@derekbruening)
- [X] #4958 (@derekbruening)
- [X] #2891
- [X] mark -attach as experimental in drrun output and deployment docs (done in PR #5227)
- [ ] #2626
- [ ] #4400
- [ ] #4532
- [x] #5233
- [x] DynamoRIO/drmemory#2440
- [x] #5054
- [x] Add AArch64 opcode enum reorderings to changelog
- [x] #2985

Nice to have:
- [ ] #38 for AArch64

**Comment by derekbruening** [comment]
I may try to implement a libunwind version of #2414 but would not be able to put SEH64 in there in time so it should not gate the release since it would not be an all-platform feature.

**Comment by derekbruening** [comment]
The other thing is that contributors added externally-triggered attach support (Window: #725 PR #5075; Linux: #38  PR #5019) which is a major feature that we could list for 9.0, but there is no test at all for Linux which makes it hard to claim it works.

@M3m3M4n if you could add an attach test we could then announce attach support for the 9.0 release.

@OrBenPorath if you get a chance to move the Windows attach test off the flaky list that would be great.

**Comment by derekbruening** [comment]
Xref #1995

Should fix #2891 docs minor issues

**Comment by M3m3M4n** [comment]
I'm quite tight on time until the end of the year. Will try to add the tests in my free time.
Also I think #5054 need to be fixed first, I haven't read too much into DR core aside from attaching part, so need more time to iron things out.

**Comment by derekbruening** [comment]
@M3m3M4n the attach feature is causing confusion with users who try to use it and complain that it's broken: https://groups.google.com/g/dynamorio-users/c/0n_cgKDPM_M/m/nRLdlKQQAwAJ?utm_medium=email&utm_source=footer   Would be great if you could help reply to questions like this, and help clearly mark it as experimental in the docs since it seems to not work everywhere

**Comment by ManojKumarChauhan** [comment]
Hi @M3m3M4n,  per my understanding there are 2 ways to use wrrap for any client application. 

Suppose I have a client C application testclient which contains some functions like malloc, function1, function2
To wrap malloc, I can either do it using attach option or by giving the app name.

1. Attach option
Run testclient from terminal one (pid-14948). From another terminal, use following command 
bin64/drrun -attach 14948 -c ./api/bin/libwrap.so

It does nothing and got stack while testclient is still running

2. Using app name
 bin64/drrun -client ./api/bin/libwrap.so 0 -- testclient
It starts to run testclient but I never get the access of testclient's functions (malloc, function1...)

As per https://dynamorio.org/page_deploy.html, following command is used to wrap malloc function
bin32/drrun -c ./api/bin/libwrap.so -- ls
But I never get the access of malloc function of ls. 
module_load_event is called only for libwrap.so and its dependencies and their malloc function. 
mod->names.module_name prints libwrap.so and its dependencies. It never find ls binary's module.

I compiled Dynamorio from source code using
git clone https://github.com/DynamoRIO/dynamorio
mkdir build_dr
cd build_dr/
cmake ../dynamorio/
make -j

**Comment by M3m3M4n** [comment]
Hi @ManojKumarChauhan, as stated in issue #5054. There is an unknown bug somewhere in the way DR load after injection. Could you build DR with -DDEBUG=ON and see if it works?

**Comment by M3m3M4n** [comment]
@derekbruening I'm not very familiar with google mail group. Can you tell them to try to build with DDEBUG option enabled as in #5054 for me? Thank you.

And I almost done with my company project. If the issue hasn't been fix by then I will see to it.

**Comment by ManojKumarChauhan** [comment]
Hi @M3m3M4n 
Sure, I will try with debug option and update you.

**Comment by ManojKumarChauhan** [comment]
Same issue while compiling Dynamorio in debug mode. When I close client application,  drrun gives following error
ERROR: unable to inject: exec of |(null)| failed
So attach to process functionality is not working.

For second case where we give the application name (bin64/drrun -client ./api/bin/libwrap.so 0 -- testclient),  it's working only when the function name is malloc because it finds that function from any of the dependent library of libwrap. But if I give any other function which is implemented in   testclient then it's unable to find that function because module_load_event doesn't find any module of testclient.

**Comment by derekbruening** [comment]
> 2. Using app name
>    bin64/drrun -client ./api/bin/libwrap.so 0 -- testclient
>    It starts to run testclient but I never get the access of testclient's functions (malloc, function1...)
> 
> As per https://dynamorio.org/page_deploy.html, following command is used to wrap malloc function bin32/drrun -c ./api/bin/libwrap.so -- ls But I never get the access of malloc function of ls. module_load_event is called only for libwrap.so and its dependencies and their malloc function. mod->names.module_name prints libwrap.so and its dependencies. It never find ls binary's module.

As the docs say, `module_name` is `NULL` for a non-.so: so you would expect it to be `NULL` for `ls`.  Again as the docs say, use `dr_module_preferred_name()`.

> I compiled Dynamorio from source code using git clone https://github.com/DynamoRIO/dynamorio mkdir build_dr cd build_dr/ cmake ../dynamorio/ make -j

Looks like this works fine, with `module_load_event` printing everything it sees:
```
$ cmake -GNinja ../src
$ ninja
$ bin64/drrun -client ./api/bin/libwrap.so 0 -- ls
Client wrap is running
module_load_event: libwrap.so
module_load_event: ls
module_load_event: ld-linux-x86-64.so.2
module_load_event: libdynamorio.so
module_load_event: linux-vdso.so.1
module_load_event: libc.so.6
<wrapped libc.so.6!malloc @0x00007f60721996c0
module_load_event: libpthread.so.0
module_load_event: libdl.so.2
module_load_event: libpcre2-8.so.0
module_load_event: libselinux.so.1
api	     cmake			 CMakeFiles	      configure_temp.h	       docs		   event_strings.h  libutil
bin64	     CMakeCache.txt		 cmake_install.cmake  core		       drcachesim.drrun64  ext		    logs
build.ninja  CMakeDoxyfile.in		 configure_defines.h  CPackConfig.cmake        drcov.drrun64	   include	    tools
clients      CMakeDoxygenDefaults.cmake  configure.h	      CPackSourceConfig.cmake  drcpusim.drrun64    lib64
<Largest malloc request: 32816>
<OOM simulations: 0>
```

But, please separate further questions you have about drwrap from this issue: please direct them to the users list https://groups.google.com/forum/#!forum/DynamoRIO-Users for help and discussion and if that discussion concludes there is an underlying bug it would be filed separately (and possibly linked here if it affects the release).

**Comment by derekbruening** [comment]
> @derekbruening I'm not very familiar with google mail group. Can you tell them to try to build with DDEBUG option enabled as in #5054 for me? Thank you.

I replied saying it's still experimental.  I tried debug build myself and it crashes there too on my machine.

> And I almost done with my company project. If the issue hasn't been fix by then I will see to it.

I put in PR #5227 which hides the feature on Linux since it is not ready yet.  As part of the fix for #5054 that hiding can be removed.

**Comment by derekbruening** [comment]
I went and figured out and fixed #5054 along with some other attach bugs and reversed the attach feature hiding.  However, there are missing generated code implementations for AArchXX, so this is an x86-only feature until someone implements those.

**Comment by derekbruening** [comment]
I think the only thing left is PR #5235 (unless someone wants to try to get AArch64 attach working)

**Comment by AssadHashmi** [comment]
> I think the only thing left is PR #5235 (unless someone wants to try to get AArch64 attach working)

Hoping to complete #5235 in the next day or so. AArch64 attach is work which we can't commit to at this time.
