### ISSUE TITLE
client convenience routines for eflags and register liveness

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#52]
_From [derek.br...@gmail.com](https://code.google.com/u/117968039472581148324/) on February 24, 2009 14:39:11_

this was PR 315333

We should expose our routines to identify which eflags (interp.c) or
registers (optimize.c) are live at a given point to clients as it makes it
easier to write efficient inlined code and save the client the trouble of
having to write their own versions.

We may want to provide an option for considering potentially-faulting
instructions as liveness barriers since that depends on the client's
fault translation and recovery approach.

_Original issue: http://code.google.com/p/dynamorio/issues/detail?id=52_

**Comment by johnfxgalea** [comment]
@derekbruening Isn't this issue somewhat resolved by drreg?

**Comment by derekbruening** [comment]
Agreed, let's close this out.
