### ISSUE TITLE
DRcov bb offsets not aligned

### ISSUE THREAD

**Issue by Semnodime** [DynamoRIO/dynamorio#5241]
**Describe the bug**
Some DRcov log file basic block offsets are slightly wrong (not aligned with any instructions).
Is this due to limitations in DRcov or unexpected behavior?

**To Reproduce**
1. `drrun_8.0.18956 -root /home/user/bin/dynamorio/8.0.18956 -t drcov -- ./foo_x86_64bit_elf`
2. Parse bb table for module id 0
3. Add base address to each bb start address
4. Search for bb starts that do align with the instructions in the binary

**Screenshot of disasm binary**
Note: DRcov includes a bb with address at 0x0065508f but there is none
addr: 0x00655087 size: 8
addr: 0x0065508b size: 22
addr: 0x0065508f size: 40
addr: 0x006550a1 size: 8
addr: 0x006550b7 size: 8
![image](https://user-images.githubusercontent.com/19511852/144767465-454e3632-007a-4769-bfcc-829c4fb4e970.png)

**Comment by derekbruening** [comment]
There are no known drcov issues with recording blocks.

Please run with logging and compare what was actually executed with what drcov recorded: see https://dynamorio.org/page_logging.html

**Comment by Semnodime** [comment]
Turned out, that the reported blocks were offset due to some parser bug in some external application.
