### ISSUE TITLE
Udefined symbol with `shm_open`

### ISSUE THREAD

**Issue by mchalupa** [DynamoRIO/dynamorio#5246]
If I try to create a shared memory object using `shm_open` on 64-bit Arch Linux (tried also on different 64-bit systems), I get `<ERROR: using undefined symbol!>`. It can be reproduced with the following simple client:

```C
DR_EXPORT void                                                                  
dr_client_main(client_id_t id, int argc, const char *argv[])                    
{                                                                               
     shm_open("/mykey", 0, 0); 
}
```

From the fact that the client is really trivial, I would guess that using shm is not supported, but I couldn't find any related documentation.

**Comment by derekbruening** [comment]
Did you look at what symbols are undefined in your library, as the error points at?  I suspect you failed to link with librt.so and that the undefined symbol error would be there with a regular load of your library: i.e., this is a build error in your library.  Try loading it in a regular app with dlopen RTLD_NOW and I bet it fails with dlerror  "undefined symbol: shm_open".

**Comment by mchalupa** [comment]
> Did you look at what symbols are undefined in your library, as the error points at? I suspect you failed to link with librt.so and that the undefined symbol error would be there with a regular load of your library: i.e., this is a build error in your library. Try loading it in a regular app with dlopen RTLD_NOW and I bet it fails with dlerror "undefined symbol: shm_open".

Then you'd lose the bet :) Everything is linked fine:

```C
#include <dlfcn.h>                                                              
#include <stdlib.h>                                                             
#include <stdio.h>                                                                                                                                                                             
                                                                                
int main(void) {                                                                
        void *handle = dlopen("./testlib.so", RTLD_NOW);                        
        if (!handle) {                                                          
                puts(dlerror());                                                
                abort();                                                        
        }                                                                       
}
```
```
$ gcc test.c -ldl && ./a.out && echo "OK"
OK
```

Are there any flags for DynamoRIO to tell me on what symbol it fails?
