### ISSUE TITLE
Support CFLAGS

### ISSUE THREAD

**Issue by dvyukov** [DynamoRIO/dynamorio#5266]
I am trying to figure out how to pass additional CFLAGS when building libraries.
The only option I found that works now is overriding CC to include a compiler with the flags:
```
(rm -rf dynamorio-test && mkdir -p dynamorio-test && cd dynamorio-test && \
CC="gcc -fsanitize=address" cmake -GNinja ../third_party/dynamorio && \
ninja libdrdecode.a && \
objdump -d lib64/libdrdecode.a | grep 0x7fff8000 | wc -l)
4141
```
But the following options don't work 
```
(rm -rf dynamorio-test && mkdir -p dynamorio-test && cd dynamorio-test && \
CFLAGS="-fsanitize=address" cmake -GNinja ../third_party/dynamorio && \
ninja libdrdecode.a && \
objdump -d lib64/libdrdecode.a | grep 0x7fff8000 | wc -l)
0
```
and:
```
(rm -rf dynamorio-test && mkdir -p dynamorio-test && cd dynamorio-test && \
cmake -GNinja -DCMAKE_C_FLAGS="-fsanitize=address" ../third_party/dynamorio && \
ninja libdrdecode.a && \
objdump -d lib64/libdrdecode.a | grep 0x7fff8000 | wc -l)
0
```

Overriding `CC` is quite inconvenient when combined with cross-compilation/toolchains.
I see docs mention setting `CFLAGS=-m32`. I am not sure if this broken, or wasn't supported, or I am holding it wrong...

**Comment by dvyukov** [comment]
I've mailed tentative #5267 to save a round-trip if that's indeed the solution.

**Comment by derekbruening** [comment]
The initial conversion to use CMake found it easiest to throw away all the compiler and linker flags due to problems with several problematic on-by-default Visual Studio flags and start from nothing.  That approach is still there in the code and is probably the source of the difficulties.

**Comment by dvyukov** [comment]
Yes, I see CMAKE_CXX_FLAGS is cleared here:
https://github.com/DynamoRIO/dynamorio/blob/master/CMakeLists.txt#L452
If not cleared, it would probably include env CFLAGS.

Does my approach in #5267 look good to you? It preserves not using cmake default flags.
