### ISSUE TITLE
Incorrect disassembly of AArch64 SHA instructions?

### ISSUE THREAD

**Issue by davidben** [DynamoRIO/dynamorio#5284]
Filing an issue for https://github.com/DynamoRIO/dynamorio/pull/4988/files#r785332308, in case a comment on an old PR gets lost. I think the AArch64 SHA instructions are mistranscribed. They use `d` registers for several parameters. Based on https://dynamorio.org/page_aarch64_port.html, it sounds `d` means the lower 64 bits, while `q` means the whole register. However, most of these parameters are the full width. Checking just the first few:

[SHA1C](https://developer.arm.com/documentation/ddi0602/2021-12/SIMD-FP-Instructions/SHA1C--SHA1-hash-update--choose--)
The PR decodes Rd as `q`, Rn as `s`, and Rm as `d`. However, Rm is described as `<Vm>.4S`, not `<Vm>.2S`, which totals 128-bit, not 64-bit.

[SHA1H](https://developer.arm.com/documentation/ddi0602/2021-12/SIMD-FP-Instructions/SHA1H--SHA1-fixed-rotate-)
This looks correct. The PR decodes Rd and Rn as `s`, which matches the documentation. Indeed, the pseudocode only reads 32 bits.

[SHA1M](https://developer.arm.com/documentation/ddi0602/2021-12/SIMD-FP-Instructions/SHA1M--SHA1-hash-update--majority--)
The PR decodes Rd as `q`, Rn as `s`, and Rm as `d`. However, Rm is described as `<Vm>.4S`, not `<Vm>.2S`, which totals 128-bit, not 64-bit.

[SHA1P](https://developer.arm.com/documentation/ddi0602/2021-12/SIMD-FP-Instructions/SHA1P--SHA1-hash-update--parity--)
The PR decodes Rd as `q`, Rn as `s`, and Rm as `d`. However, Rm is described as `<Vm>.4S`, not `<Vm>.2S`, which totals 128-bit, not 64-bit.

If this is right, the other instructions probably also need a re-check. Is it possible all the `V` registers were mistranscribed in this and other PRs?

Looking at dis-a64.txt, these tests seem to confirm this. Notice how the second column agrees that this is a `4s`, not `2s`, instruction. Meanwhile the test asserts a `%d2`.
```
5e020020 : sha1c q0, s1, v2.4s                      : sha1c  %s1 %d2 -> %q0
```

In contrast, the `add` decode uses `%d` for `2s` and `%q` for `4s`.
```
0ea28420 : add v0.2s, v1.2s, v2.2s                  : add    %d1 %d2 $0x02 -> %d0
[...]
4ea28420 : add v0.4s, v1.4s, v2.4s                  : add    %q1 %q2 $0x02 -> %q0
```

**Comment by AssadHashmi** [comment]
> Is it possible all the V registers were mistranscribed in this and other PRs?

In this case, the bug looks like it does not define the full vector and element size for the second source operand.
As you say, `v2.4s` should be represented by `%q2 $0x02` (128 bit vector split into 32 bits).

> If this is right, the other instructions probably also need a re-check.
