### ISSUE TITLE
Large performance regression on Windows due to indirect branch link breakage

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#5352]
Commit 638fb106d30d84887956853f8be1ce534cfa0f25 PR #4886 accidentally broke Windows indirect branch table updating.  This was discovered by a user: https://groups.google.com/d/msgid/dynamorio-users/CAO1ikSY7Uvgcw_b98H1ifkvFGhDUSYzZe9uatrYNPcETMYix-Q%40mail.gmail.com?utm_medium=email&utm_source=footer

This is pretty bad: this will cause massive slowdowns on some programs.  We need to put out an updated 9.1 release.

Performance regression tests are not always simple to set up.  Maybe we can more easily have a test that checks the exit stats.

**Comment by derekbruening** [comment]
```
% egrep 'Fcache exits, total|exits, total ind' ~/dr/releases/DynamoRIO-Windows-8.0.18740/logs/botan.exe.9016.00000000/botan.exe.0.13048.html | tail -2
                               Fcache exits, total :            302427
             Fcache exits, total indirect branches :            183528

% egrep 'Fcache exits, total|exits, total ind' ~/dr/releases/DynamoRIO-Windows-8.0.18747/logs/botan.exe.9108.00000000/b* | tail -2
                               Fcache exits, total :          37961007
             Fcache exits, total indirect branches :          37841753
```

**Comment by lieser** [comment]
Thanks a lot for the quick fix. Performance in version 9.0.1 seems to be now again around what it was with 8.0.18740 for our usage.
