### ISSUE TITLE
ERROR: unable to inject: exec of |(null)| failed at Windows 10

### ISSUE THREAD

**Issue by hdbreaker** [DynamoRIO/dynamorio#5384]
It seems like latest version of DinamoRIO do not work at Windows 10. The execution fail with ERROR: unable to inject: exec of |(null)|

**Comment by derekbruening** [comment]
There is not enough information here to take any action.  What application is this?  What version of Windows is this (no, "10" is not helpful: each sub-version is very different from each other)?  Things work fine on every version we have tested.

I don't know how you managed by bypass the template which Github is supposed to require.  Please fill it in: https://github.com/DynamoRIO/dynamorio/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by hdbreaker** [comment]
It happen with every program:

`C:\drio\bin32>drrun.exe -t drcov -- notepad
ERROR: unable to inject: exec of |(null)| failed`

<img width="379" alt="Screen Shot 2022-02-23 at 15 59 43" src="https://user-images.githubusercontent.com/5799585/155388777-cdc64f71-4402-448b-a242-9cef0e53b39d.png">

It is a Win 10 Home 21H2 Build: 19044.1526 Experience Pack 120.2212.4170.0 Running on VMWARE 12.2.1

**Comment by derekbruening** [comment]
Again, please supply all the information in the linked template which Github is supposed to require: version of DR, bitwidths, debug results, etc.

**Comment by derekbruening** [comment]
Closing due to lack of information.  #5512 might be the same thing but we'll never know w/o more info here.
