### ISSUE TITLE
movups is not mov

### ISSUE THREAD

**Issue by theMarina** [DynamoRIO/dynamorio#5391]
Hi,

I am trying to assert `DR_ASSERT(instr_is_mov(instr));`, but the assertion fails on the instruction `movups %xmm0 -> (%rdi)[16byte]`

**Comment by derekbruening** [comment]
As the docs say https://dynamorio.org/dr__ir__instr_8h.html#a38065c3db26272edab262a5222b99598
"Returns true iff instr is an IA-32/AMD64 "mov" instruction: either OP_mov_st, OP_mov_ld, OP_mov_imm, OP_mov_seg, or OP_mov_priv."  Clearly `movups` is not on that list: it only covers what would be `mov` in normal assembler mnemonics.

In the future, please use the users list https://groups.google.com/forum/#!forum/DynamoRIO-Users for questions like this where whether it is a bug is in question.
