### ISSUE TITLE
Build failure regression: 32-bit Linux with -DCMAKE_C_FLAGS=-m32 instead of CFLAGS=-m32 env var

### ISSUE THREAD

**Issue by SweetVishnya** [DynamoRIO/dynamorio#5395]
**Describe the bug**

Build failure of 32-bit DynamoRIO on Ubuntu 18.04 with gcc 7.5.0.

Is Werror now enabled by default? Is there a way to turn it off in build system?

```
/home/vishnya/fwork/sydr/dynamorio/core/drlibc/drlibc_unix.c:111:24: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
     ptr_int_t result = (ptr_int_t)retval;
                        ^
/home/vishnya/fwork/sydr/dynamorio/core/drlibc/drlibc_unix.c: In function ‘mmap_syscall’:
/home/vishnya/fwork/sydr/dynamorio/core/drlibc/drlibc_unix.c:135:12: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
     return (byte *)(ptr_int_t)dynamorio_syscall(
            ^
/home/vishnya/fwork/sydr/dynamorio/core/drlibc/drlibc_unix.c: In function ‘os_try_page_size’:
/home/vishnya/fwork/sydr/dynamorio/core/drlibc/drlibc_unix.c:522:9: error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
     if ((ptr_uint_t)addr >= (ptr_uint_t)-4096) /* mmap failed: should not happen */
         ^
In file included from /home/vishnya/fwork/sydr/dynamorio/core/drlibc/../globals.h:93:0,
                 from /home/vishnya/fwork/sydr/dynamorio/core/drlibc/drlibc_module_elf.c:37:
/home/vishnya/fwork/sydr/dynamorio/core/drlibc/drlibc_module_elf.c: In function ‘module_vaddr_from_prog_header’:
/home/vishnya/fwork/sydr/dynamorio/core/drlibc/drlibc_module_elf.c:196:32: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
                 MIN(min_vaddr, (app_pc)ALIGN_BACKWARD(prog_hdr->p_vaddr, PAGE_SIZE));
                                ^
/home/vishnya/fwork/sydr/dynamorio/core/lib/globals_shared.h:104:32: note: in definition of macro ‘MIN’
 #    define MIN(x, y) ((x) <= (y) ? (x) : (y))
                                ^
/home/vishnya/fwork/sydr/dynamorio/core/drlibc/drlibc_module_elf.c:196:32: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
                 MIN(min_vaddr, (app_pc)ALIGN_BACKWARD(prog_hdr->p_vaddr, PAGE_SIZE));
                                ^
/home/vishnya/fwork/sydr/dynamorio/core/lib/globals_shared.h:104:44: note: in definition of macro ‘MIN’
 #    define MIN(x, y) ((x) <= (y) ? (x) : (y))
                                            ^
/home/vishnya/fwork/sydr/dynamorio/core/drlibc/drlibc_module_elf.c:197:30: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
             if (min_vaddr == (app_pc)prog_hdr->p_vaddr)
                              ^
/home/vishnya/fwork/sydr/dynamorio/core/drlibc/drlibc_module_elf.c:198:29: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
                 first_end = (app_pc)prog_hdr->p_vaddr + prog_hdr->p_memsz;
                             ^
/home/vishnya/fwork/sydr/dynamorio/core/drlibc/drlibc_module_elf.c: In function ‘elf_loader_map_phdrs’:
/home/vishnya/fwork/sydr/dynamorio/core/drlibc/drlibc_module_elf.c:456:24: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
             seg_base = (app_pc)ALIGN_BACKWARD(prog_hdr->p_vaddr, PAGE_SIZE) + delta;
                        ^
/home/vishnya/fwork/sydr/dynamorio/core/drlibc/drlibc_module_elf.c:502:32: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
                     file_end = (app_pc)prog_hdr->p_vaddr + prog_hdr->p_filesz;
                                ^
/home/vishnya/fwork/sydr/dynamorio/core/drlibc/drlibc_module_elf.c: In function ‘elf_loader_find_pt_interp’:
/home/vishnya/fwork/sydr/dynamorio/core/drlibc/drlibc_module_elf.c:544:20: error: cast to pointer from integer of different size [-Werror=int-to-pointer-cast]
             return (const char *)(phdrs[i].p_vaddr + elf->load_delta);
```

**Comment by SweetVishnya** [comment]
I tried to use `-DDISABLE_WARNINGS=ON`. Now I'm getting:

```
/home/vishnya/fwork/sydr/dynamorio/core/ir/x86/decode_table.c:10580:87: note: in expansion of macro ‘tevexwb’
     {OP_CONTD, 0x663a2548, "vpternlogq cont'd", xx, xx, We, xx, xx, mrm|evex|reqp, x, tevexwb[188][3]},
                                                                                       ^~~~~~~
/home/vishnya/fwork/sydr/dynamorio/core/ir/x86/decode_table.c:2109:17: error: initializer element is not constant
 #define tevexwb (ptr_int_t)&evex_Wb_extensions
```

**Comment by SweetVishnya** [comment]
CMake args:

```
      CMAKE_ARGS -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
                 -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
                 -DCMAKE_C_FLAGS=-m32
                 -DCMAKE_CXX_FLAGS=-m32
                 -DCMAKE_INSTALL_PREFIX=${DYNAMORIO_DIR}
                 -DCMAKE_INSTALL_MESSAGE=LAZY
                 -DDISABLE_WARNINGS=ON
```

**Comment by SweetVishnya** [comment]
@dvyukov, this commit breaks the build.

https://github.com/DynamoRIO/dynamorio/commit/fecce1e115ecf7b0b1c54a543923257ec5920188

**Comment by SweetVishnya** [comment]
Made a PR

**Comment by dvyukov** [comment]
> CMake args:
> 
> ```
>       CMAKE_ARGS -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
>                  -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
>                  -DCMAKE_C_FLAGS=-m32
>                  -DCMAKE_CXX_FLAGS=-m32
>                  -DCMAKE_INSTALL_PREFIX=${DYNAMORIO_DIR}
>                  -DCMAKE_INSTALL_MESSAGE=LAZY
>                  -DDISABLE_WARNINGS=ON
> ```

Docs say one needs to use:
```
CXXFLAGS=-m32 CFLAGS=-m32 cmake ..
```
https://dynamorio.org/page_building.html
Does that work?

**Comment by SweetVishnya** [comment]
> > CMake args:
> > ```
> >       CMAKE_ARGS -DCMAKE_C_COMPILER=${CMAKE_C_COMPILER}
> >                  -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
> >                  -DCMAKE_C_FLAGS=-m32
> >                  -DCMAKE_CXX_FLAGS=-m32
> >                  -DCMAKE_INSTALL_PREFIX=${DYNAMORIO_DIR}
> >                  -DCMAKE_INSTALL_MESSAGE=LAZY
> >                  -DDISABLE_WARNINGS=ON
> > ```
> 
> Docs say one needs to use:
> 
> ```
> CXXFLAGS=-m32 CFLAGS=-m32 cmake ..
> ```
> 
> https://dynamorio.org/page_building.html Does that work?

Yeah, this works. However, setting flags via CMake flags is a more natural way.

**Comment by dvyukov** [comment]
Does `CMAKE_C_FLAGS` work at all?
I am not sure now, but looking at the commit:
https://github.com/DynamoRIO/dynamorio/commit/fecce1e115ecf7b0b1c54a543923257ec5920188#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aL783
`-m32` was added by the CMakefiles, so I wonder if `-DCMAKE_C_FLAGS=-m32` needed/worked?

**Comment by dvyukov** [comment]
If `CMAKE_C_FLAGS` work, why do we need to add it back to the cmake file?
https://github.com/DynamoRIO/dynamorio/pull/5396/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR793

**Comment by SweetVishnya** [comment]
We used CMake flags to build our tool for at least two years. So, it worked))) Maybe not intentional, but worked)

**Comment by SweetVishnya** [comment]
> If `CMAKE_C_FLAGS` work, why do we need to add it back to the cmake file? https://github.com/DynamoRIO/dynamorio/pull/5396/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR793

That's a real question. Maybe they are not added anywhere.

**Comment by SweetVishnya** [comment]
`-m32` may affect `CMAKE_C_SIZEOF_DATA_PTR` which affects `X86/X64` vars

**Comment by derekbruening** [comment]
Using the env vars `CFLAGS` and `CXXFLAGS` is how I was told by the CMake developers to configure the initial CMake try-compiles which determine things like `CMAKE_C_SIZEOF_DATA_PTR` back when DR was first ported to CMake.  I suspect that the versions of CMake back then did not support the initial config coming from `-DCMAKE_C_FLAGS`.  Plus, DR tends to throw away `CMAKE_C_FLAGS` for its own config, so setting that won't affect anything but the initial config, which might be misleading.  Using the env vars is how all our automated tests do it, which means that today any other method could break with nobody noticing.

**Comment by SweetVishnya** [comment]
I see it now. I'll try to properly support CMAKE_C_FLAGS in #5396 next week.
