### ISSUE TITLE
Add support for AVX512 VNNI instructions

### ISSUE THREAD

**Issue by prasun3** [DynamoRIO/dynamorio#5440]
**Add a pointer to any prior users list discussion.**
https://groups.google.com/g/dynamorio-users/c/_rgb7_8AIZw

**Is your feature request related to a problem? Please describe.**
Unable to run programs that use VNNI instructions.

**Describe the solution you'd like**
Enable programs that use VNNI instructions

Do you have any implementation in mind for this feature?
Add support in the decoder

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by prasun3** [comment]
```
 * When adding new instructions, be sure to update all of these places:
 *   1) decode_table op_instr array
 *   2) decode_table decoding table entries
 *   3) OP_ enum (here) via x86opnums.pl
 *   4) update OP_LAST at end of enum here
 *   5) decode_fast tables if necessary (they are conservative)
 *   6) instr_create macros
 *   7) suite/tests/api/ir* tests
```
I am trying to figure out what I need to do for steps 1 and 2.

Taking the example of `vpdpbusd`, the opcode is `{VEX 128/256,EVEX 128/256/512} 66.0F38.W0 50`

Should I add entries to `vex_W_extensions` and `evex_Wb_extensions`  with the `vex` entry pointing to the `evex` entry? And then should I refer to the `vex` entry in `op_instr`?

Looking at other entries, it looks like the opcode value should be `0x663850xx` rather than `0x663850` or `0x660f3850` -- is that right? What should that last byte be?

Pretty sure this is not correct (esp operands, flags etc), so would appreciate some help

```
diff --git a/core/ir/x86/decode_table.c b/core/ir/x86/decode_table.c
index a4477a4d..b8da3553 100644
--- a/core/ir/x86/decode_table.c
+++ b/core/ir/x86/decode_table.c
@@ -1575,6 +1575,8 @@ const instr_info_t * const op_instr[] =
     /* OP_vshufi32x4      */  &evex_Wb_extensions[143][0],
     /* OP_vshufi64x2      */  &evex_Wb_extensions[143][2],

+    /* OP_vpdpbusd        */  &vex_W_extensions[111][0],
+
     /* Intel SHA extensions */
     /* OP_sha1msg1        */  &third_byte_38[165],
     /* OP_sha1msg2        */  &e_vex_extensions[144][0],
@@ -7848,7 +7850,11 @@ const instr_info_t vex_W_extensions[][2] = {
   }, { /* vex_W_ext 109 */
     {OP_vmovd, 0x660f7e10, "vmovd", Ed, xx, Vd_dq, xx, xx, mrm|vex, x, tevexwb[136][0]},
     {OP_vmovq, 0x660f7e50, "vmovq", Ey, xx, Vq_dq, xx, xx, mrm|vex, x, tevexwb[136][2]},
+  }, { /* vex_W_ext 111 */
+    {OP_vpdpbusd, 0x663850, "vpdpbusd", Vdq, xx, Hdq, Wdq, xx, no, x, tevexwb[267][0]},
+    {INVALID,    0x663850,   "(bad)", xx,xx, xx,  xx,xx,     no,x,NA},
   },
+
 };

 /****************************************************************************
@@ -9242,6 +9248,11 @@ const instr_info_t evex_Wb_extensions[][4] = {
     {OP_vsqrtss, 0xf30f5110, "vsqrtss", Vdq, xx, KE1b, Hdq, Uss, mrm|evex|er|ttt1s, x, END_LIST},
     {OP_vsqrtsd, 0xf20f5140, "vsqrtsd", Vdq, xx, KE1b, Hdq, Wsd, mrm|evex|ttt1s, x, tevexwb[266][3]},
     {OP_vsqrtsd, 0xf20f5150, "vsqrtsd", Vdq, xx, KE1b, Hdq, Usd, mrm|evex|er|ttt1s, x, END_LIST},
+  },{ /* evex_W_ext 267 */
+    {OP_vpdpbusd, 0x660f38, "vpdpbusd", Vqq, xx, Hqq, Wqq, xx, no, x, END_LIST},
+    {INVALID, 0, "(bad)", xx, xx, xx, xx, xx, no, x, NA},
+    {INVALID, 0, "(bad)", xx, xx, xx, xx, xx, no, x, NA},
+    {INVALID, 0, "(bad)", xx, xx, xx, xx, xx, no, x, NA},
   },
 };

```

**Comment by derekbruening** [comment]
The opcode link is sufficient for the encoder, but for the decoder that vex_W_ext 111 needs to be hooked up to some existing table entry.

> Looking at other entries, it looks like the opcode value should be 0x663850xx rather than 0x663850 or 0x660f3850 -- is that right? What should that last byte be?

Yes.  The bottom byte is described at https://github.com/DynamoRIO/dynamorio/blob/master/core/ir/x86/decode_private.h#L145 and mostly involves whether the W and L bits have to be set.  The `0F38` IIRC would set `OPCODE_THREEBYTES` so the bottom nibble is probably 0x8.

**Comment by prasun3** [comment]
Please let me know how this looks.
