### ISSUE TITLE
CBW operand size is incorrect

### ISSUE THREAD

**Issue by dvyukov** [DynamoRIO/dynamorio#5448]
Currently decoding these bytes gives:
```
98	cwde		%ax -> %eax 
66 98	data16 cwde	%ax -> %ax 
48 98	cwde		%ax -> %rax 
```

The destination operand is always correct, but source operand size does not look correct. It should be half of destination. I think this would be correct decoding:
```
98	cwde		%ax -> %eax 
66 98	data16 cwde	%al -> %ax 
48 98	cwde		%eax -> %rax 
```

On commit 6e88738383e78c0be9c3dda373e43f311425b862.

**Comment by derekbruening** [comment]
Looks like this should be under #3009
