### ISSUE TITLE
USAGE ERROR when a directory named like an executable is present in the PATH variable [Minor bug]

### ISSUE THREAD

**Issue by derchr** [DynamoRIO/dynamorio#5455]
**Describe the bug**
When there is a directory named like an executable in one of the locations the PATH variable points to, normally it is ignored and a real executable is searched instead.
For example if there is a directory called `vim` in a user defined PATH directory (like `~/.bin`) it is ignored and the real vim application will be run.
DynamoRIO does not handle this case and will try to run the directory resulting in an error message like this:
`./drrun -- vim`
`<Application /home/derek/.bin/vim (543) DynamoRIO usage error : Failed to read app ELF headers.  Check path and architecture.>`

This can be confusing because just typing `vim` without `./drrun` does work in this case.

**To Reproduce**
1. Have a directory named like an executable in one of the PATH variables
2. Run `./drrun -- [name of the executable/directory]`

Please also answer these questions:
 - What happens when you run without any client?
 Same
 - What happens when you run with debug build ("-debug" flag to drrun/drconfig/drinject)?
 Same

**Expected behavior**
DynamoRIO should ignore directories and traverse through the other possible locations in the PATH variable.

**Versions**
 - What version of DynamoRIO are you using?
6e88738383e78c0be9c3dda373e43f311425b862
 - Does the latest build from https://github.com/DynamoRIO/dynamorio/releases solve the problem?
 No
- What operating system version are you running on? 
Manjaro Linux and Debian 11
- Is your application 32-bit or 64-bit?
64 bit

Additional context
This does also happen with non-executable files in `PATH`

**Comment by derekbruening** [comment]
Probably the fix would be in `drfront_searchenv` if you are motivated to fix this: https://github.com/DynamoRIO/dynamorio/blob/master/libutil/dr_frontend_unix.c#L125
