### ISSUE TITLE
BUILD ERROR due to change in linux/rseq.h on recent kernels

### ISSUE THREAD

**Issue by prasun3** [DynamoRIO/dynamorio#5469]
**Describe the bug**

On recent kernels build fails with the following error
```
dynamorio/core/unix/rseq_linux.c:221:64: error: request for member ‘ptr64’ in something not a structure or union
     if (is_dynamo_address((byte *)(ptr_uint_t)app_rseq->rseq_cs.ptr64))
                                                                ^
```

**To Reproduce**
Try building DR on a recent kernel which includes the change in https://github.com/torvalds/linux/commit/bfdf4e6208051ed7165b2e92035b4bf11f43eb63

**Expected behavior**
No build error

**Screenshots or Pasted Text**
See above

**Versions**
 - What version of DynamoRIO are you using?
Any recent version that includes `linux/rseq.h` will have this issue.

 - Does the latest build from https://github.com/DynamoRIO/dynamorio/releases solve the problem?
No

- What operating system version are you running on? ("Windows 10" is *not* sufficient: give the release number.)
Ubuntu

- Is your application 32-bit or 64-bit?
64-bit

**Additional context**

**Comment by derekbruening** [comment]
Another recent rseq issue is #5431 but I don't think they're related.

**Comment by derekbruening** [comment]
A recent upgrade on my laptop means my local build now hits this...
