### ISSUE TITLE
Add support for AVX512 BF16 instructions 

### ISSUE THREAD

**Issue by prasun3** [DynamoRIO/dynamorio#5483]
**Add a pointer to any prior users list discussion.**
NA

**Is your feature request related to a problem? Please describe.**
 Unable to run programs that use BF16 instructions.

**Describe the solution you'd like**
 Enable programs that use BF16 instructions

Do you have any implementation in mind for this feature?
Add encoder/decoder support and tests.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by khuey** [comment]
I think you want OPSZ_half_16_vex32_evex64?

**Comment by khuey** [comment]
It's in the set of weird extra OPSZ values at https://github.com/DynamoRIO/dynamorio/blob/17822fe61b305700d6b182eb9c7e06787e740387/core/ir/decode.h#L165

**Comment by prasun3** [comment]
Thanks for the info. I tried it but still seeing the same. I also tried `OPSZ_half_16_vex32` but did not see expected results.

I am also not sure how to encode broadcast or zeroctl so tests like the following are failing. Is there some API to set these attributes?

```
vcvtne2ps2bf16  (%r9){1to16}, %zmm29, %zmm30   #AVX512_BF16 BROADCAST_EN
vcvtne2ps2bf16  -8192(%rdx){1to16}, %zmm29, %zmm30{%k7}{z}   #AVX512_BF16 Disp8 BROADCAST_EN MASK_ENABLING ZEROCTL
```

**Comment by prasun3** [comment]
I was able to set those prefixes using `instr_set_prefix_flag`. The prefixes (`PREFIX_EVEX_b, PREFIX_EVEX_z`) are defined in `decode_private.h` so they are not available in `ir_x86.c`. Should we move these to a public header? I have defined them locally for now.

**Comment by derekbruening** [comment]
> I was able to set those prefixes using `instr_set_prefix_flag`. The prefixes (`PREFIX_EVEX_b, PREFIX_EVEX_z`) are defined in `decode_private.h` so they are not available in `ir_x86.c`. Should we move these to a public header? I have defined them locally for now.

Some prefix flags are only used during decoding and the information they convey is, after decoding, present in another aspect of the IR.  Such flags are not made public as they are private to the decoder.

**Comment by prasun3** [comment]
So I realized that with `OPSZ_half_16_vex32` it shows the right size if I use dr disas syntax even though the reg name doesn't match.
```
 62 f2 7e 0b 72 d3    vcvtneps2bf16 {%k3} %xmm3 -> %xmm2[8byte]
 62 d2 7e 2b 72 d3    vcvtneps2bf16 {%k3} %ymm11 -> %ymm2[16byte]
 62 92 7e 4b 72 d7    vcvtneps2bf16 {%k3} %zmm31 -> %zmm2[32byte]
```
The ideal output (from objdump) looks like this
```
 62 f2 7e 0b 72 d3       vcvtneps2bf16 xmm2{k3},xmm3
 62 d2 7e 2b 72 d3       vcvtneps2bf16 xmm2{k3},ymm11
 62 92 7e 4b 72 d7       vcvtneps2bf16 ymm2{k3},zmm31
```

With this change, the tests that do encode/decode followed by `inst_same` check fail if I use `YMM_x` as the dest reg (because the re-decoded reg is `ZMM_x`). They also fail if I use `ZMM_x` as the dest reg (because the re-decoded dst size is `OPSZ_32`).

I was able to get the test to pass if I use `ZMM_x` followed by [setting the dst size to `OPSZ_32`](https://github.com/DynamoRIO/dynamorio/commit/dfeced06c9373a235beff43f054eaeb5eee2fed6#diff-91728ce172020ae173685aebb16f957438ec420a04d04fb6d6d5d6fe327ed97dR1478) but then I had to disable the tests in [ir_x86_3args_avx512_evex_mask.h](https://github.com/DynamoRIO/dynamorio/commit/dfeced06c9373a235beff43f054eaeb5eee2fed6#diff-da8ab15579ce547d421cbb992aa27c089e3489e84716b35f0055790c7a636f5b) because I cannot set the size there.

**Comment by prasun3** [comment]
> > I was able to set those prefixes using `instr_set_prefix_flag`. The prefixes (`PREFIX_EVEX_b, PREFIX_EVEX_z`) are defined in `decode_private.h` so they are not available in `ir_x86.c`. Should we move these to a public header? I have defined them locally for now.
> 
> Some prefix flags are only used during decoding and the information they convey is, after decoding, present in another aspect of the IR. Such flags are not made public as they are private to the decoder.

So like I mentioned above I am trying to encode some binutils tests that have broadcast/zero prefixes. Is there a better way to set these prefixes?

```
vcvtne2ps2bf16  (%r9){1to16}, %zmm29, %zmm30   #AVX512_BF16 BROADCAST_EN
vcvtne2ps2bf16  -8192(%rdx){1to16}, %zmm29, %zmm30{%k7}{z}   #AVX512_BF16 Disp8 BROADCAST_EN MASK_ENABLING ZEROCTL
```

**Comment by khuey** [comment]
Look at e.g. the EVEX encoded vfmadd213ps around evex_W_ext 63. You'll need two separate lines in the table, one for the vector version and another for the broadcast version, and OPCODE_TWOBYTES is used to indicate the value of EVEX.b

**Comment by prasun3** [comment]
I did have those lines but I was trying to get the encode test going and I wasn't sure how to specify those flags while encoding.

I did realize that the operand size indicates whether it is broadcast or not, so the broadcast prefix need not be specified explicitly. I updated the code to change the operand size and not set the broadcast prefix. I am still now sure how to indicate `{z}`.

For example consider these instructions
```
   0:   62 62 15 40 a8 31       vfmadd213ps zmm30,zmm29,ZMMWORD PTR [rcx]
   6:   62 62 15 50 a8 31       vfmadd213ps zmm30,zmm29,DWORD PTR [rcx]{1to16}
   c:   62 62 15 51 a8 31       vfmadd213ps zmm30{k1},zmm29,DWORD PTR [rcx]{1to16}
  12:   62 62 15 d1 a8 31       vfmadd213ps zmm30{k1}{z},zmm29,DWORD PTR [rcx]{1to16}
```

I can specify the first thee with the `INSTR_CREATE_vfmadd213ps_mask` api alone. But to specify the fourth instruction I am calling `instr_set_prefix_flag(instr_z, PREFIX_EVEX_z);` and it seems to generate the right opcodes.

```
367:   0x00005645a7587220  62 62 15 40 a8 31    vfmadd213ps {%k0} %zmm29 (%rcx)[64byte] %zmm30 -> %zmm30
367:   0x00005645a7587220  62 62 15 50 a8 31    vfmadd213ps {%k0} %zmm29 (%rcx)[4byte] %zmm30 -> %zmm30
367:   0x00005645a7587220  62 62 15 51 a8 31    vfmadd213ps {%k1} %zmm29 (%rcx)[4byte] %zmm30 -> %zmm30
367:   0x00005645a7587220  62 62 15 d1 a8 31    vfmadd213ps {%k1} %zmm29 (%rcx)[4byte] %zmm30 -> %zmm30
```

This is my code and I am not sure how to specify `vfmadd213ps zmm30{k1}{z},zmm29,DWORD PTR [rcx]{1to16}` with the API alone without calling `instr_set_prefix_flag`
```
    memarg_disp = 0;
    instr_t *instr_x = INSTR_CREATE_vfmadd213ps_mask(dc, REGARG(ZMM30), REGARG(K0), REGARG(ZMM29), MEMARG(OPSZ_64));
    instr_t *instr_b = INSTR_CREATE_vfmadd213ps_mask(dc, REGARG(ZMM30), REGARG(K0), REGARG(ZMM29), MEMARG(OPSZ_4));
    instr_t *instr_k = INSTR_CREATE_vfmadd213ps_mask(dc, REGARG(ZMM30), REGARG(K1), REGARG(ZMM29), MEMARG(OPSZ_4));
    instr_t *instr_z = INSTR_CREATE_vfmadd213ps_mask(dc, REGARG(ZMM30), REGARG(K1), REGARG(ZMM29), MEMARG(OPSZ_4));
    uint PREFIX_EVEX_z = 0x000800000;
    instr_set_prefix_flag(instr_z, PREFIX_EVEX_z);

```

**Comment by khuey** [comment]
There is not currently any way to create a {z} instruction from scratch other than using instr_set_prefix_flag, afaik.

**Comment by khuey** [comment]
API design is a @derekbruening question, I just deal with the giant decode table :)

**Comment by derekbruening** [comment]
I filed #5488 on this.  It looks like something that was overlooked in the original AVX-512 work.

**Comment by prasun3** [comment]
I'll summarize the major issues I came across while working on this issue. This time I have added binutils tests that encode the assembly instructions using `instr_create_..` APIs and match against the opcode bytes rather than the opposite because we don't produce disassembly that can match exactly against binutils disassembly.

**zeroing support in encoder**
As mentioned above there is no straightforward way to encode zeroing instructions. As a workaround I have added the z flag to the tests until we have a solution for #5488 

**need to set opnd size to `OPSZ_half_16_vex32_evex64`**
Described here:  https://github.com/DynamoRIO/dynamorio/issues/5483#issuecomment-1119809599. Basically we don't have a good way to support instructions like `vcvtneps2bf16 ymm2{k3},zmm31` that write to "half" of the destination. I am using the flag `OPSZ_half_16_vex32_evex64` in the decode table. I have to set the destination to `ZMM2` and set destination size to `OPSZ_32` to get this to work.

Similarly I am setting dest to `YMMx` and set size to `OPSZ_16` for the following instructions
```
  vcvtneps2bf16 (%r9){1to8}, %xmm22  #AVX512{BF16,VL} BROADCAST_EN
  vcvtneps2bf16y  (%rcx){1to8}, %xmm2  #AVX512{BF16,VL} BROADCAST_EN
  vcvtneps2bf16y  4064(%rcx), %xmm23   #AVX512{BF16,VL} Disp8
  vcvtneps2bf16 -4096(%rdx){1to8}, %xmm27{%k7}{z}  #AVX512{BF16,VL} Disp8 BROADCAST_EN MASK_ENABLING ZEROCTL
```

**disassembler shows data16 prefix**

I had to move `vpdpwssd` from E_VEX_EXT to PREFIX_EXT since the opcode is shared with `vdpbf16ps` but then I started getting the test failure below. The `data16` prefix is shown in the disassembly if the entry is picked up from the `EVEX_Wb_EXT` table but not shown if it is picked up from the `PREFIX_EXT` table. This is because `read_prefix_ext` clears `di->data_prefix` if `0x66` is part of the opcode. I changed the entry in `PREFIX_EXT` from `0x66385218` to `0x385218` to get the test to pass but I think we should fix the test (and fix the `EVEX_Wb_EXT` handling).

```
383: Test timeout computed to be: 1500
383: -- diff: 102733,102736c102733,102736
383: <  c4 c2 59 52 d4       vpdpwssd %xmm4, %xmm12, %xmm2
383: <  c4 c2 59 52 d4       vpdpwssd %xmm4, %xmm12, %xmm2
383: <  c4 e2 59 52 11       vpdpwssd %xmm4, (%rcx), %xmm2
383: <  c4 e2 59 52 11       vpdpwssd %xmm4, (%rcx), %xmm2
383: ---
383: >  c4 c2 59 52 d4       data16 vpdpwssd %xmm4, %xmm12, %xmm2
383: >  c4 c2 59 52 d4       data16 vpdpwssd %xmm4, %xmm12, %xmm2
383: >  c4 e2 59 52 11       data16 vpdpwssd %xmm4, (%rcx), %xmm2
383: >  c4 e2 59 52 11       data16 vpdpwssd %xmm4, (%rcx), %xmm2
383:
383: CMake Error at /home/prasun/dynamorio/dynamorio/suite/tests/runcmp.cmake:86 (message):
383:   output in
383:   /home/prasun/dynamorio/build/suite/tests/drdecode_decenc_x86_64.expect-out
383:   failed to match expected output in
383:   /home/prasun/dynamorio/build/suite/tests/drdecode_decenc_x86_64.expect-expect
383:
383:
3/3 Test #383: code_api|decenc.drdecode_decenc_x86_64 ...***Failed    1.39 sec
```

**Comment by prasun3** [comment]
@derekbruening @khuey any comments on the three issues mentioned above?

**Comment by khuey** [comment]
> I'll summarize the major issues I came across while working on this issue. This time I have added binutils tests that encode the assembly instructions using `instr_create_..` APIs and match against the opcode bytes rather than the opposite because we don't produce disassembly that can match exactly against binutils disassembly.
> 
> **zeroing support in encoder** As mentioned above there is no straightforward way to encode zeroing instructions. As a workaround I have added the z flag to the tests until we have a solution for #5488

Right.

> **need to set opnd size to `OPSZ_half_16_vex32_evex64`** Described here: [#5483 (comment)](https://github.com/DynamoRIO/dynamorio/issues/5483#issuecomment-1119809599). Basically we don't have a good way to support instructions like `vcvtneps2bf16 ymm2{k3},zmm31` that write to "half" of the destination. I am using the flag `OPSZ_half_16_vex32_evex64` in the decode table. I have to set the destination to `ZMM2` and set destination size to `OPSZ_32` to get this to work.
> 
> Similarly I am setting dest to `YMMx` and set size to `OPSZ_16` for the following instructions
> 
> ```
>   vcvtneps2bf16 (%r9){1to8}, %xmm22  #AVX512{BF16,VL} BROADCAST_EN
>   vcvtneps2bf16y  (%rcx){1to8}, %xmm2  #AVX512{BF16,VL} BROADCAST_EN
>   vcvtneps2bf16y  4064(%rcx), %xmm23   #AVX512{BF16,VL} Disp8
>   vcvtneps2bf16 -4096(%rdx){1to8}, %xmm27{%k7}{z}  #AVX512{BF16,VL} Disp8 BROADCAST_EN MASK_ENABLING ZEROCTL
> ```

You should be able to do tests the same way that vcvtdq2pd_xlok0xlo and friends work (e.g. using REGARG_PARTIAL(XMM1, OPSZ_8), REGARG_PARTIAL(YMM1, OPSZ_16), REGARG_PARTIAL(ZMM1, OPSZ_32) for the half-width operands).  Grepping for vcvtdq2pd is instructive to see how we handle this elsewhere. For the binutils test we actually have the "wrong" disassembly checked in. For `c5 fe e6 e4` we have `vcvtdq2pd %ymm4, %ymm4` checked in even though binutils will decode this as `vcvtdq2pd %ymm4, %xmm4`

> **disassembler shows data16 prefix**
> 
> I had to move `vpdpwssd` from E_VEX_EXT to PREFIX_EXT since the opcode is shared with `vdpbf16ps` but then I started getting the test failure below. The `data16` prefix is shown in the disassembly if the entry is picked up from the `EVEX_Wb_EXT` table but not shown if it is picked up from the `PREFIX_EXT` table. This is because `read_prefix_ext` clears `di->data_prefix` if `0x66` is part of the opcode. I changed the entry in `PREFIX_EXT` from `0x66385218` to `0x385218` to get the test to pass but I think we should fix the test (and fix the `EVEX_Wb_EXT` handling).

I think this is what the REQUIRES_PREFIX/reqp flag is for. If you look at the code that handles it in `read_instruction` at the very end of that branch it erases whatever `prefix_var` was from further consideration. If you add reqp to vpdpwssd's decode table entries does it fix this?

> ```
> 383: Test timeout computed to be: 1500
> 383: -- diff: 102733,102736c102733,102736
> 383: <  c4 c2 59 52 d4       vpdpwssd %xmm4, %xmm12, %xmm2
> 383: <  c4 c2 59 52 d4       vpdpwssd %xmm4, %xmm12, %xmm2
> 383: <  c4 e2 59 52 11       vpdpwssd %xmm4, (%rcx), %xmm2
> 383: <  c4 e2 59 52 11       vpdpwssd %xmm4, (%rcx), %xmm2
> 383: ---
> 383: >  c4 c2 59 52 d4       data16 vpdpwssd %xmm4, %xmm12, %xmm2
> 383: >  c4 c2 59 52 d4       data16 vpdpwssd %xmm4, %xmm12, %xmm2
> 383: >  c4 e2 59 52 11       data16 vpdpwssd %xmm4, (%rcx), %xmm2
> 383: >  c4 e2 59 52 11       data16 vpdpwssd %xmm4, (%rcx), %xmm2

Is this stuff even right at all? C4 is a VEX prefix but doesn't vpdpwssd require EVEX?

**Comment by prasun3** [comment]
> Is this stuff even right at all? C4 is a VEX prefix but doesn't vpdpwssd require EVEX?

Both are supported. AVX-VNNI was introduced on Alder Lake.
