### ISSUE TITLE
CRASH Can't run drcachesim on Google's Workload Trace

### ISSUE THREAD

**Issue by Henrique-Potter** [DynamoRIO/dynamorio#5494]
**Describe the bug**
Can't use drcachesim on [Googles Trace Workload](https://console.cloud.google.com/storage/browser/external-traces?pli=1).

**To Reproduce**
1. Just run "bin64/drrun -t drcachesim -indir X"  On Google Cloud Trace. It can be any folder (charlie/merced/delta/whiskey)
2. It will output Failed to open "17571657100049929577.1012843.memtrace.gz"

The simulator works fine when I generate new offline traces. It just does not work for Google's traces
![image](https://user-images.githubusercontent.com/5942666/168399552-8defaa8b-e0f9-4415-8d3e-0dfc5c1826e6.png)

**Versions**
 - 9.0.19117
 - 64 bit ubuntu server

**Comment by Henrique-Potter** [comment]
Hi I just learned that there can be offline traces that cannot executed drcachesim do the lack of extra metadata. Google's workload trace is one of them. I will close this issue.

**Comment by derekbruening** [comment]
> Hi I just learned that there can be offline traces that cannot executed drcachesim due the lack of extra metadata.

Do you mean not having the binaries available?  That is only needed for trace analyzers that look at opcodes or instruction encodings, like the provided opcode_mix tool.  The cache simulator does not need that information and should work on these traces.

I can't reproduce this problem.
When I download the entire charlie/trace-1/ directory, it includes the branch files `*.csv.gz`: those cannot be processed by drcachesim.  When I move those somewhere else and the directory contains only `*.memtrace.gz`, it works:
```
$ bin64/drrun -t drcachesim -verbose 1 -indir ~/public_traces/charlie/trace-1/
...
Cache simulation results:
Core #0 (1211 thread(s))
  L1I stats:
    Hits:                    3,633,242,282
    Misses:                     38,772,926
    Compulsory misses:             260,559
    Invalidations:                       0
    Miss rate:                        1.06%
  L1D stats:
    Hits:                    1,324,984,721
    Misses:                     55,073,171
    Compulsory misses:          13,599,738
    Invalidations:                       0
    Prefetch hits:              14,764,130
    Prefetch misses:            50,462,422
    Miss rate:                        3.99%
Core #1 (1210 thread(s))
  L1I stats:
    Hits:                    2,805,407,642
```

It also works if I point only at the file in your output which has the error message:
```
$ bin64/drrun -t drcachesim -infile ~/public_traces/charlie/trace-1/17571657100049929577.935182.memtrace.gz 
Cache simulation results:
Core #0 (1 thread(s))
  L1I stats:
    Hits:                                0
    Misses:                              1
    Compulsory misses:                   1
    Invalidations:                       0
    Miss rate:                      100.00%
  L1D stats:
    Hits:                                0
    Misses:                              0
    Compulsory misses:                   0
    Invalidations:                       0
Core #1 (0 thread(s))
Core #2 (0 thread(s))
Core #3 (0 thread(s))
LL stats:
    Hits:                                0
    Misses:                              1
    Compulsory misses:                   1
    Invalidations:                       0
    Miss rate:                      100.00%
```

It makes me wonder if your file is corrupted?  That is my only theory.

Mine is:
```
$ zcat ~/public_traces/charlie/trace-1/17571657100049929577.935182.memtrace.gz | od -A x -t x2 -w12 | awk '{printf "%s | %s %s %s%s%s%s\n", $1, $2, $3, $7, $6, $5, $4}'
000000 | 0019 0000 0000000000000003
00000c | 001c 000c 0000000000000003
000018 | 001c 0009 0000000000000040
000024 | 0016 0004 00000000000e450e
000030 | 0018 0004 00000000000e20ee
00003c | 001c 000a 0000000000000040
000048 | 001c 0002 002f37d0c9c895e2
000054 | 001c 0003 0000000000000015
000060 | 000a 0002 000000001f0c7b3d
00006c | 001c 0002 002f37d0cd24ea23
000078 | 001c 0003 0000000000000012
000084 | 0017 0004 00000000000e450e
000090 | 001a 0000 0000000000000000
00009c |   
```

**Comment by Henrique-Potter** [comment]
I see.  I saw the discussion [here](https://groups.google.com/g/dynamorio-users/c/STk3wUCw0yk)  and assumed that not having the opcodes were the issue. 

Thank you very much!

**Comment by Henrique-Potter** [comment]
The 17571657100049929577.935182.memtrace.gz  matches with yours and drcachesim with single files work. But it does not work when I set for the whole directory with "-indir".

**Comment by derekbruening** [comment]
> The 17571657100049929577.935182.memtrace.gz matches with yours and drcachesim with single files work. But it does not work when I set for the whole directory with "-indir".

As you saw in my comment https://github.com/DynamoRIO/dynamorio/issues/5494#issuecomment-1128014214, it does work for us with -indir, so we cannot reproduce any problem.  Please debug in your setup: run with `-verbose 1` to see how many files it opened successfully; check file permissions; etc.

**Comment by Henrique-Potter** [comment]
I moved the dynamorio folder to /opt/ and was able to run drcachesim against a folder. Must have been a permission issue. I was running drrun from a mounted folder while Google's trace were in another mounted folder.

Thanks for the help!

**Comment by derekbruening** [comment]
Glad to hear it now works.
