### ISSUE TITLE
Add libipt as a submodule of dynamorio

### ISSUE THREAD

**Issue by dolanzhao** [DynamoRIO/dynamorio#5517]
Adding submodules in general brings up a bunch of auxiliary support we probably want.  I wonder if we should separate this out as its own PR.  I assume we want the submodule to be initialized all the time?  If so, things we would want:

+ We have to tell GA CI to init submodules: `submodules: true` arg to checkout step
+ Add submodule update to `make/git/devsetup.sh`
+ Add submodule update to `make/git/git_pullall.sh`
+ Potentially add to how-to-build docs if not completely automated
+ Potentially add a pre-commit hook to prevent the common mistake of accidentally rolling back a recent submodule update when switching branches

_Originally posted by @derekbruening in https://github.com/DynamoRIO/dynamorio/pull/5515#discussion_r889369065_

**Comment by derekbruening** [comment]
Not sure this needed to be its own issue?  The reason libipt is desired is for dr$sim kernel traces #5505.
