### ISSUE TITLE
Android build failing due to NDK setup problems

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#5527]
This started happening yesterday and has caused every Android build to fail, including the weekly package:

https://github.com/DynamoRIO/dynamorio/actions/runs/2478571712

https://github.com/DynamoRIO/dynamorio/runs/6840580519?check_suite_focus=true

```
...
2022-06-11 03:14:38 (67.2 MB/s) - ‘android-ndk-r10e-linux-x86_64.zip’ saved [1110915721/1110915721]
ERROR: Your ANDROID_NDK_ROOT variable does not point to a valid directory.
Error: Process completed with exit code 1.
```

**Comment by abhinav92003** [comment]
@dolanzhao also hit this on #5515.

**Comment by derekbruening** [comment]
Android support is not in great shape in general: there are private loader problems on Android 9 #3543 and Android 10 #3683.  (#5437's loader refactoring proposal may help there.)

There is DR-on-Android interest out there and there have been some PR's trying to improve things: maybe we should ask the community to help maintain by getting Android regression tests working.  The current tiny set of regular maintainers just do not have the bandwidth to maintain Android and it would simplify things to drop Android support, unless more maintainers step up.

**Comment by derekbruening** [comment]
I was going to mark the Android build as not required for PR merging -- but it's just part of the arm cross-compile job.  Maybe we should split it out.
