### ISSUE TITLE
CRASH: DR ELF code does not check for NULL soname

### ISSUE THREAD

**Issue by jweezy24** [DynamoRIO/dynamorio#5554]
**The Bug**
While writing some example code to be executed in a docker image, I ran into a strange bug. While initializing drrun, the tool would crash. While using GDB, I saw that the problem was a segfault pictured below:
![GDB_Bug](https://user-images.githubusercontent.com/30905615/177217744-e0e3a92f-959c-4a1c-84f3-a239a2ed0037.png)

The significance of `libpthread` is negligible as the problem lies within `pd->soname`. 

**To Reproduce**
1. Download my lab's [code](https://github.com/wi-pi/VCAMuteButton_PoPETS) for our paper. 
2. Clone the [dynamorio repository](https://github.com/DynamoRIO/dynamorio) to the root directory. 
3. Build the docker image, `docker build -t vca .`
4. Once the image has completed, enter the container. I have instructions on how to do that in the README in the root directory of the repository.
5. `cd /home/scripts/data_collection/Linux/DyanamoRIO_Example_Files/simple_c_example`
6. `make`
7. `cd ..; make`
8. `make docker`
10. If done correctly, the output should be:

![Exact_Text_for_Bug](https://user-images.githubusercontent.com/30905615/177218235-7b9c8978-db2b-42e8-8f56-a1eaa00c0db1.png)

Please also answer these questions:
 - What happens when you run without any client?
        - If run without client, the code runs fine. There were no build errors or any errors when running "drrun echo "hello world"`. Also, when executing in a normal desktop environment this bug does not occur. In other words, my desktop is able to run the code without any bug.
 - What happens when you run with debug build ("-debug" flag to drrun/drconfig/drinject)?
          -  I build with debug flags and disabled optimization and the bug still occurs. The gdb output is pictured above.

**Expected behavior**
This is the expected behavior:

![Expected_output](https://user-images.githubusercontent.com/30905615/177219142-baf0536f-a1ac-4b41-a227-ce70fda046cd.png)

**Versions**
 - What version of DynamoRIO are you using?

   I am using the most current release of Dynamorio (9.0.19174). 
 
- Does the latest build from https://github.com/DynamoRIO/dynamorio/releases solve the problem?
 
  No. 
 
- What operating system version are you running on? ("Windows 10" is *not* sufficient: give the release number.)

I am running all code in docker. The docker image and container live on base Arch Linux rolling.  

- Is your application 32-bit or 64-bit?

The application is 64 bit.

**Additional context**

I was able to solve the problem when I added these lines below in the core/string.c file:
![Fix_to_bug](https://user-images.githubusercontent.com/30905615/177218915-17bd86ed-6c56-46a5-887b-da45e28511e1.png)

The expected behavior occurs after I implemented the lines of code into the string.c file.

**Comment by derekbruening** [comment]
Thank you for the detailed report.  

I would vote for solving this by adding checks for soname being NULL in the ELF handling code though, rather than inside strstr, as A) there are other uses of soname in DR code that need to handle NULL and B) strstr normally would not have a check for NULL in libc or other standard implementations.

@jweezy24 are you interested in implementing a fix of handling soname being NULL in the DR ELF code?

**Comment by jweezy24** [comment]
@derekbruening I would love to attempt to implement the fix. Thank you!
