### ISSUE TITLE
Add support for pointer-authenticated indirect branches in ARMv8.3

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#5623]
PR #5497 adds AArch64 IR support for BLRAAZ, BRAA, RETAA (and some other non-branches) because apparently they are in use on Mac on M1.  This issue covers adding the rest of that set of ISA enhancements, separated from the other general AArch64 filed issues because it may be implemented separately to support M1.

**Comment by jackgallagher-arm** [comment]
@derekbruening I have implemented all of the v8.3 pointer authentication instructions and addressed all of the i#5623 TODOs in the code base. Can we close this issue now, or is there anything else to do?

**Comment by derekbruening** [comment]
There is a significant unresolved issue:

Currently DR turns an authenticated indirect branch into an un-authenticated branch by running XPACI to clear the top bits (necessary for a canonical address for lookup in DR's hashtables) and then doing a regular un-authenticated indirect branch in the IBL (indirect branch lookup routine).  It should be possible for DR to preserve the top pointer bits in some way (maybe it does the authentication in the fragment before the XPACI) and use an AUTI* instruction to validate: right?  DR would need to ensure an authentication failure turned into the same type of fault as would happen without DR.
