### ISSUE TITLE
Incorrect decoding of PSHUFLW/PSHUFHW

### ISSUE THREAD

**Issue by dvyukov** [DynamoRIO/dynamorio#5645]
**Describe the bug**

Decoding `4d 49 41 f3 f3 f2 4b 0f 70 76 00 ff` with drdecode gives:
```
pshufhw 0x00(%r14)[16byte] $0xff -> %xmm6
```
executing this instruction with %r14 pointing to memory region with 0x00, 0x01, 0x02, ... bytes should result in:
`XMM6=0x0f0e0f0e0f0e0f0e706050403020100`
But executing it on a CPU gives:
`XMM6=0x0f0e0d0c0b0a09080706070607060706`

Decoding the instruction with other decoders suggests it's a different instruction:
```
echo -en " 0x4d 0x49 0x41 0xf3 0xf3 0xf2 0x4b 0x0f 0x70 0x76 0x00 0xff" | llvm-mc --disassemble -
	rep
	pshuflw	$255, (%r14), %xmm6             # xmm6 = mem[3,3,3,3,4,5,6,7]
```

```
echo -en "\x4d\x49\x41\xf3\xf3\xf2\x4b\x0f\x70\x76\x00\xff" > /tmp/bin | objdump -mi386 -Mx86-64 -b binary -D /tmp/bin
00000000 <.data>:
   0:	4d                   	rex.WRB
   1:	49                   	rex.WB
   2:	41                   	rex.B
   3:	f3 f3 f2 4b 0f 70 76 	repz repz rex.WXB pshuflw $0xff,0x0(%r14),%xmm6
   a:	00 ff 
```

PSHUFLW would indeed produce the result that agrees with actual CPU execution. 

**Expected behavior**

Decode the instruction as PSHUFLW.

**Versions**
 - What version of DynamoRIO are you using?
6e69f2a90b55870e849718223815c2d23fba0871

 - Does the latest build from https://github.com/DynamoRIO/dynamorio/releases solve the problem?
Did not try, but there are only 3 commits that don't look relevant.

**Comment by derekbruening** [comment]
```
$ disasm 4d 49 41 f3 f3 f2 4b 0f 70 76 00 ff 
Disassembling 0x4d 0x49 0x41 0xf3 0xf3 0xf2 0x4b 0x0f 0x70 0x76 0x00 0xff
<stdin>:1:1: warning: invalid instruction encoding
0x4d 0x49 0x41 0xf3 0xf3 0xf2 0x4b 0x0f 0x70 0x76 0x00 0xff
^
llvm-mc:   0x4d 0x49 0x41 0xf3 0xf3 0xf2 0x4b 0x0f 0x70 0x76 0x00 0xff  rep pshuflw $255, (%r14), %xmm6 # xmm6 = mem[3,3,3,3,4,5,6,7]
capstone:  494d f341 pshuflw xmm6, xmmword ptr [r14], 0xff
bfd:       4d rex.WRB
xed:       0x4d 0x49 0x41 0xf3 0xf3 0xf2 0x4b 0x0f 0x70 0x76 0x00 0xff pshuflw xmm6, xmmword ptr [r14], 0xff
DynamoRIO: 4d 49 41 f3 f3 f2 4b pshufhw xmm6, oword ptr [r14+0x00], 0xff 0f 70 76 00 ff
```

**Comment by derekbruening** [comment]
There are a bunch of pshuflw test cases in third_party/binutils/test_decenc/drdecode_decenc_x86.expect but none of them must happen to hit this case.

**Comment by khuey** [comment]
The issue here is that both rep_prefix and repne_prefix end up set during decode. Then when we decode rep (f3) takes precendce over repne (f2) which causes this to be decoded incorrectly. It seems like maybe the last one should win here ...

**Comment by dvyukov** [comment]
It looks like the root cause of #5447 as well.

**Comment by khuey** [comment]
Yes I think that's right.
