### ISSUE TITLE
something about detach.c

### ISSUE THREAD

**Issue by nxnonxno** [DynamoRIO/dynamorio#5701]
detach.c seems to be implemented only in win32, so if I want to implement it in unix, what should I focus on?

**Comment by derekbruening** [comment]
Thank you for your interest, but please use the users list https://groups.google.com/forum/#!forum/DynamoRIO-Users for questions, as it will reach a wider audience of people who might have an answer, and it will reach other users who may find the information beneficial. The issue tracker is for specific detailed bugs or fully-formed feature requests, both of which should generally start out with a users list discussion.
