### ISSUE TITLE
<CRASH> Just crash

### ISSUE THREAD

**Issue by trcrsired** [DynamoRIO/dynamorio#5703]
**Describe the bug**
Crash down with a simple C++ tool modified from instrcalls.c

**To Reproduce**
1. Pointer to a minimized application (ideally the source code for it and instructions on which toolchain it was built with).
2. Precise command line for running the application.
3. Exact output or incorrect behavior.

Please also answer these questions:
 - What happens when you run without any client?
 - What happens when you run with debug build ("-debug" flag to drrun/drconfig/drinject)?

**Expected behavior**
Shouldn't crash

**Screenshots or Pasted Text**
![image](https://user-images.githubusercontent.com/100043421/197884148-00e3e227-a942-4a89-861c-cdfe8293bf6b.png)

```
paste output here
```
</pre>

**Versions**
 - What version of DynamoRIO are you using? DynamoRIO-Windows-9.0.19265
 - Does the latest build from https://github.com/DynamoRIO/dynamorio/releases solve the problem? No
- What operating system version are you running on? ("Windows 10" is *not* sufficient: give the release number.) Microsoft Windows [Version 10.0.19044.2130]
- Is your application 32-bit or 64-bit? 64-bit

**Additional context**

**Comment by derekbruening** [comment]
This bug report says it modified the provided client, but doesn't say how. It doesn't say whether the *unmodified* client works.  It doesn't answer the provided questions about whether plain DR works with no client, nor what happens in debug build.  For all we know these not-shown modifications added the crash.

**Comment by trcrsired** [comment]
[instrcalls2.cc.txt](https://github.com/DynamoRIO/dynamorio/files/9864229/instrcalls2.cc.txt)

**Comment by derekbruening** [comment]
The requested base information was not provided; closing as invalid.
