### ISSUE TITLE
attach_test and attach_blocking timing out on Jenkins

### ISSUE THREAD

**Issue by abhinav92003** [DynamoRIO/dynamorio#5740]
Happened multiple times on retrying: http://139.178.82.61:8080/job/DynamoRIO-AArch64-Precommit/2360/console.

Seems to have started after the recent AArch64 hardware move: https://groups.google.com/g/dynamorio-devs/c/lSaVAoryR1E/m/xTylpzXvDAAJ?utm_medium=email&utm_source=footer.

**Comment by derekbruening** [comment]
Xref attach and detach test failures but with different symptoms on x86-64: #6452, #6536.

**Comment by derekbruening** [comment]
Is this #6558?

**Comment by derekbruening** [comment]
Confirmed: this is #6558.  It works if I enable ptrace_scope.  And that explains why the failures started on a new machine.
