### ISSUE TITLE
Only the shared library part is traced by cbrtrace

### ISSUE THREAD

**Issue by mmxsrup** [DynamoRIO/dynamorio#5762]
**Describe the bug**
I am testing to get a trace using cbrtrace in `api/sample`, but I can probably only see the shared library part in the output results. I get results like the following file, but all addresses start with `0x7f`, which I believe is a trace of the shared library part. I would like to trace the actual main function part, etc. How can I do this?

```txt
...
0x00007ffff7847c5a [0x00007ffff7847c68, 0x00007ffff7847c6e, 0x00007ffff7847d52] => 0x00007ffff7847c6e
0x00007ffff7847d89 [0x00007ffff7847d96, 0x00007ffff7847d9c, 0x00007ffff7847fd8] => 0x00007ffff7847d9c
0x00007ffff7c8dcb0 [0x00007ffff7c8dce6, 0x00007ffff7c8dce8, 0x00007ffff7c8dd08] => 0x00007ffff7c8dce8
0x00007ffff7847dc0 [0x00007ffff7847dd0, 0x00007ffff7847dd2, 0x00007ffff7847df5] => 0x00007ffff7847dd2
0x00007ffff7847dd2 [0x00007ffff7847ddc, 0x00007ffff7847de2, 0x00007ffff7848088] => 0x00007ffff7847de2
0x00007ffff7847de2 [0x00007ffff7847e0e, 0x00007ffff7847e14, 0x00007ffff7847f51] => 0x00007ffff7847e14
0x00007ffff7847e50 [0x00007ffff7847e56, 0x00007ffff7847e58, 0x00007ffff7847e38] => 0x00007ffff7847e58
0x00007ffff7847e58 [0x00007ffff7847e61, 0x00007ffff7847e63, 0x00007ffff7847e38] => 0x00007ffff7847e38
0x00007ffff7847e38 [0x00007ffff7847e4a, 0x00007ffff7847e50, 0x00007ffff7847f48] => 0x00007ffff7847f48
0x00007ffff7847f48 [0x00007ffff7847f59, 0x00007ffff7847f5b, 0x00007ffff7847f7d] => 0x00007ffff7847f5b
0x00007ffff7847f5b [0x00007ffff7847f70, 0x00007ffff7847f76, 0x00007ffff7848020] => 0x00007ffff7847f76
0x00007ffff7847f76 [0x00007ffff7847f80, 0x00007ffff7847f82, 0x00007ffff7847f9f] => 0x00007ffff7847f82
0x00007ffff7c8dd20 [0x00007ffff7c8dd3f, 0x00007ffff7c8dd41, 0x00007ffff7c8dd60] => 0x00007ffff7c8dd41
0x00007ffff7c8dd41 [0x00007ffff7c8dd43, 0x00007ffff7c8dd45, 0x00007ffff7c8dd58] => 0x00007ffff7c8dd58
0x00007ffff7847f9f [0x00007ffff7847fad, 0x00007ffff7847fb3, 0x00007ffff7848104] => 0x00007ffff7847fb3
0x00007ffff77fb9b2 [0x00007ffff77fb9b9, 0x00007ffff77fb9bb, 0x00007ffff77fb9b0] => 0x00007ffff77fb9bb
```

**To Reproduce**
1. Create an image using the following Dockerfile: `docker build -t dynamorio-test`.
2. Run the image: `docker run --rm -it dynamorio-test`.
3. Obtain a trace of ls command on the docker container: `$DYNAMORIO_HOME/build/bin64/drrun -c $DYNAMORIO_HOME/build/api/bin/libcbrtrace.so -- /bin/ls /`
4.  Check the output log file.

```Dockerfile
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV GIT_SSL_NO_VERIFY 1

RUN apt-get update && apt-get install -y cmake g++-multilib git

# Build dynamorio
RUN git clone https://github.com/DynamoRIO/dynamorio.git -b cronbuild-9.0.19088 && \
	cd /dynamorio && \
	mkdir ./build && \
	cd ./build && \
	cmake ../ && \
	make -j$(nproc)
ENV DYNAMORIO_HOME /dynamorio
```

**Expected behavior**
I would expect the non-shared library to be traced as well. But, however, only addresses starting with `0x7f` are traced.

**Comment by mmxsrup** [comment]
I was mistaken; it appears that the non-shared library parts are also mapped to addresses beginning with `0x7f`. This looks different from a normal memory map. Is it possible to get a memory map and trace the non-shared library?

**Comment by derekbruening** [comment]
> Is it possible to get a memory map and trace the only non-shared library?

See dr_get_main_module to find the exe: https://dynamorio.org/dr__modules_8h.html#a7c8ab7e9af187cfd427206033ccadf49

Please ask further general questions on the users list https://groups.google.com/forum/#!forum/DynamoRIO-Users
