### ISSUE TITLE
genhtml fails with coverage report

### ISSUE THREAD

**Issue by Desperado17** [DynamoRIO/dynamorio#5824]
Greetings,

I try to convert a coverage report I recorded with latest aarch64 cronbuild drrun and converted with drcov2lcov to a html representation using genhtml. But it fails:

perl DynamoRIO-Linux-9.0.19368/tools/bin64/genhtml ./[coverage.info](http://coverage.info/)                                                                                          

Reading data file ./[coverage.info](http://coverage.info/)
Found 32342 entries.
Found common filename prefix "/home/jenkins-slave/workspace"
Writing .css and .png files.
Generating output.
Processing file ./md-unwind-support.h
genhtml: ERROR: cannot read ./md-unwind-support.h

ls -la
-rw-rw-r--   1 user user        141 Jan 16 17:11 amber.png
-rw-rw----   1 user user   24620194 Jan 16 17:01 [coverage.info](http://coverage.info/)
-rw-rw-r--   1 user user        141 Jan 16 17:11 emerald.png
-rw-rw-r--   1 user user      13605 Jan 16 17:11 gcov.css
-rw-rw-r--   1 user user        167 Jan 16 17:11 glass.png
-rw-rw-r--   1 user user       2232 Jan 16 17:11 gthr-default.h.gcov.html
-rw-rw-r--   1 user user       2246 Jan 16 17:07 md-unwind-support.h.gcov.html
-rw-rw-r--   1 user user        141 Jan 16 17:11 ruby.png
-rw-rw-r--   1 user user        141 Jan 16 17:11 snow.png
-rw-rw-r--   1 user user        117 Jan 16 17:11 updown.png

Any ideas?

Regards

**Comment by derekbruening** [comment]
Please see the documentation: https://dynamorio.org/page_drcov.html#sec_drcov2lcov => `–ignore-errors=source`

In the future, please use the users list https://groups.google.com/forum/#!forum/DynamoRIO-Users for questions, as it will reach a wider audience of people who might have an answer, and it will reach other users who may find the information beneficial. The issue tracker is for specific detailed bugs. If you are not sure it's a bug, please start by asking on the users list.
