### ISSUE TITLE
Latest Aarch64 cronbuild doesn't produce log anymore

### ISSUE THREAD

**Issue by Desperado17** [DynamoRIO/dynamorio#5869]
The latest cronbuild doesn't produce a drcov* output anymore. For comparison:

[xxx:/var]# /var/DynamoRIO-AArch64-Linux-9.0.19368/bin64/drrun -root /var/DynamoRIO-AArch64-Linux-9.0.19368 -t drcov  -dump_text  --  /usr/bin/myapp --no-systemd --ro-path=/etc/nav

produces an output

[xxx:/var]# /var/DynamoRIO-AArch64-Linux-9.0.19397/bin64/drrun -root /var/DynamoRIO-AArch64-Linux-9.0.19397 -t drcov  -dump_text  --  /usr/bin/myapp --no-systemd --ro-path=/etc/nav

does not. The cronbuild also shows this message at the beginning:

<Application /usr/bin/myapp (4022). Client library targets an incompatible API version and should be re-compiled.>

**Comment by derekbruening** [comment]
Looks similar to what was on the user list last week: https://groups.google.com/d/msgid/dynamorio-users/d763d2705252660d6512a2929fcc4b4d%40gmx.de?utm_medium=email&utm_source=footer

**Comment by derekbruening** [comment]
As noted on the user list, the regression tests all pass, so this is limited to the cronbuild.  Related to the version bump to 9.90 probably -- and the cronbuild package command still being passed 9.0?

**Comment by derekbruening** [comment]
https://github.com/DynamoRIO/dynamorio/releases/tag/cronbuild-9.90.19402
