### ISSUE TITLE
Unable to post to users list

### ISSUE THREAD

**Issue by prasun3** [DynamoRIO/dynamorio#5897]
**Describe the bug**
Not quite a bug but I ran into a problem today.

I tried posting to the users list https://groups.google.com/forum/#!forum/DynamoRIO-Users but got the error below.

```
Message rejected by Google Groups. Please visit http://mail.google.com/support/answer/188131?hl=en to review our Bulk Email Senders Guidelines.
```

**Comment by derekbruening** [comment]
More than one of us have hit this in the last week and filed issues with Groups.  Could you click the "Send feedback to Google" under the gear icon at the top to add another bug report?

**Comment by prasun3** [comment]
> More than one of us have hit this in the last week and filed issues with Groups. Could you click the "Send feedback to Google" under the gear icon at the top to add another bug report?

Done.

**Comment by derekbruening** [comment]
This turned out to be a global issue and it should now be resolved.  Unfortunately any blocked posts are gone and will have to be re-posted.
