### ISSUE TITLE
tool.drcov.fib failing in local runs due to lack of DWARF5 support in libelftc used by drsyms

### ISSUE THREAD

**Issue by abhinav92003** [DynamoRIO/dynamorio#5926]
Xref the user report on dynamorio-users: https://groups.google.com/g/dynamorio-users/c/mDwTAPFek40, where following https://dynamorio.org/page_drcov.html for a simple app generates an empty file.

I was able to reproduce the user-reported issue on my workstation. @derekbruening found that `tool.drcov.fib` is also failing. It's passing in our CI so maybe this is the result of some recent lib update.

**Comment by abhinav92003** [comment]
I tried updating the version in `rebuild_elftc.sh` to the latest but some changes in https://sourceforge.net/p/elftoolchain/code/3898 are breaking the build. Also, r3897 doesn't fix the test failure.

**Comment by abhinav92003** [comment]
I was able to get around it by ignoring warnings (at least for now to test if the latest libelftc version fixes it), but I'm hitting other issues with building libelftc.

```
In file included from elf.c:31:
_libelf.h:36:10: fatal error: _elftc.h: No such file or directory
   36 | #include "_elftc.h"
      |          ^~~~~~~~~~
compilation terminated.
*** Error code 1

```

**Comment by abhinav92003** [comment]
I tried to run rebuild_elftc.sh on a Ubuntu 20.04 VM (since that is what the build instructions at https://sourceforge.net/p/elftoolchain/code/HEAD/tree/trunk/INSTALL use), but the script still fails with the same issue. Next I thought maybe rebuild_elftc.sh itself needs to be updated, and tried building libelftc myself. I could do successfully that on the Ubuntu 20.04 VM (but not on my own workstation), and replaced the generated .a and header files and re-ran the test, but it still failed.

**Comment by abhinav92003** [comment]
I was able to use rebuild_elftc.sh to get new 64-bit libraries and headers from the latest libelftc (32-bit still not building successfully). It needed some extra steps: either installing libelftc or at least copying the elfdefinitions.h header file to /use/include/sys. But I'm still getting the same error in the tool.drcov.fib test: `drsym_lookup_address` returning `DRSYM_ERROR_LINE_NOT_AVAILABLE`. Maybe the issue is in drsym; looking.

**Comment by abhinav92003** [comment]
The dwarf call at https://github.com/DynamoRIO/dynamorio/blob/dcbaca81b9816a40fddc2b0211475a7c5a9220a3/ext/drsyms/drsyms_dwarf.c#L153 is failing with

```
drsyms: Dwarf error: Unsupported version [_dwarf_info_load(229)]
```

**Comment by abhinav92003** [comment]
Looks like the test binary CU version is higher than what is supported by even the latest version of libelftc (https://sourceforge.net/p/elftoolchain/code/HEAD/tree/trunk/libdwarf/libdwarf_info.c#l228)
```
$ readelf --debug-dump=info suite/tests/bin/client.drsyms-test | grep -A 2 'Compilation Unit @' 
  Compilation Unit @ offset 0:
   Length:        0x10a0 (32-bit)
   Version:       5
--
  Compilation Unit @ offset 0x10a4:
   Length:        0x15c4 (32-bit)
   Version:       5
--
  Compilation Unit @ offset 0x266c:
   Length:        0x2a (32-bit)
   Version:       2
--
  Compilation Unit @ offset 0x269a:
   Length:        0x2a (32-bit)
   Version:       2

```

**Comment by abhinav92003** [comment]
There's already a ticket on supporting DWARFv5: https://sourceforge.net/p/elftoolchain/tickets/611/; we're blocked on that.

**Comment by abhinav92003** [comment]
A possible workaround to get coverage using drcov is to use g++/gcc older than v11, or specify "-gdwarf-4" to g++/gcc when compiling the target executable.

**Comment by derekbruening** [comment]
This is an issue for Dr. Memory (DynamoRIO/drmemory#2485) and since gcc 11+ has DWARF5 on by default the priority seems a little higher...

**Comment by derekbruening** [comment]
The proposal is to switch to using libdw from elfutils.
