### ISSUE TITLE
DynamoRIO crash on dr_get_proc_address() / dr_get_proc_address_ex()

### ISSUE THREAD

**Issue by apach301** [DynamoRIO/dynamorio#5946]
System: ubuntu 20.04
DynamoRIO version: 9.91.19442, but it is reproduced on the latest master.

DynamoRIO crashes on dr_get_proc_address() call during module load event handling of shared library loading.
Crash occurs during initializing dynamic section in os_module_data_t structure. The library itself have this segments:
![image](https://user-images.githubusercontent.com/13482580/229368553-ae7356d0-9929-4f76-ade2-ba63ebd5f5b6.png)

When I made target program to use standard system library (at /usr/lib/x86_64-linux-gnu/) it DynamoRIO works correctly, this library segments are:
![image](https://user-images.githubusercontent.com/13482580/229368754-6951cd45-3a98-4233-bdd5-cdfa6afed4eb.png)

Debug build of DynamoRIO shows that crash is caused by null bitmask:  
![image](https://user-images.githubusercontent.com/13482580/229369004-690efaf4-39d6-48cd-885f-5481e7975fc9.png)

Also there are some `<CURIOSITY : (0) && "crashed while walking dynamic header" in file /home/kutz/workspace/sydr/dynamorio/core/unix/module_elf.c line 323` on loading such shared libraries.

This bug is similar to the #3385 and #3525.

**Comment by derekbruening** [comment]
Could you include a callstack of the crash?  Who is calling dr_get_proc_address(): is that DR itself?

**Comment by derekbruening** [comment]
> Crash occurs during initializing dynamic section in os_module_data_t structure. 

This is where I'm confused: if it's a client calling dr_get_proc_address() (I don't think DR itself calls it (the internal version) so I assume it's a client) how is it during DR's initialization of module data?  A callstack and maybe a timeline of what happened when would help.

**Comment by apach301** [comment]
Debug-build get SIGBUS on loading module with this stacktrace:
![image](https://user-images.githubusercontent.com/13482580/229573560-1d0f30e6-b7b6-4bcb-8d7e-071db241f47e.png)

While the stacktrace of dr_get_proc_address usage looks like this (no failure in this example):
![image](https://user-images.githubusercontent.com/13482580/229574200-24347433-252a-4b31-97ae-f9f0ab1db8c0.png)

**Comment by derekbruening** [comment]
Please elaborate on how PR #5947 solves the problem: it is calling an initialization routine; when is that normally called and why was it not called in time in this situation?

**Comment by apach301** [comment]
Initialization routine normally happens during module_hashtab_init() execution, that called in the end of module_fill_os_data(), but it the latter one is crashes on `test string readability`. I don't understand why its happening - because of .dynstr isn't mapped at that moment? When module_load_event callback is executed (after some time) and I manually call module_fill_os_data() it works out successfully. (module_fill_os_data can be called manually either via the module_read_os_data - as in PR #5947, either via the os_module_update_dynamic_info).

**Comment by apach301** [comment]
Considering the comments all around that code, I guess similar problem occurs on Android. For the Android this problem was salved by manually calling os_module_update_dynamic_info from the next mmap handlers - in mmap_check_for_module_overlap function: https://github.com/DynamoRIO/dynamorio/blob/ec5199091de2dd53791f0b11d34992376c82c3f1/core/unix/os.c#L8414

I remove `#ifdef ANDROID` and this also fixed the problem.

**Comment by apach301** [comment]
Inserted a lot of  debug-printfs to check how its  working now:
![image](https://user-images.githubusercontent.com/13482580/229780547-b93a1106-bf1e-430f-beb2-76d8c135b208.png)

**Comment by apach301** [comment]
So this basically the same issue as #3385: .dynstr is located in last +rw segment of library, hence we can't correctly initialize os_module_data_t during the first mmap of the whole file.

My fix in PR #5946 calls re-initialization of module data from dr_get_proc_address (which is called from client) - so this won't fix another possible crashes. I think that fix with re-initialization of dynamic info is workable solution but it should be applied in some other place (after first mmap-event and before actual os_module_data_t usage):
- I tried to call os_module_update_dynamic_info() from subsequent mmap-events (just as for Android): it seems working
- Maybe performing dynamic info initialization from module load event is more neat way to fix bug?

**Comment by derekbruening** [comment]
Thank you, this makes it more clear why the later init call works in your PR.  Looking at #3385: looks like a complete fix is not simple as you seem to be hitting as well.  Should we merge this issue into #3385 and continue discussion there, including @AssadHashmi who was working on #3385 before?

**Comment by apach301** [comment]
Yeah, I think we could close this issue and continue in #3385.
I wanted to try @AssadHashmi's solution first ([i3385-elf-dynstr-fix](https://github.com/DynamoRIO/dynamorio/tree/i3385-elf-dynstr-fix)) but wasn't able to rebase correctly on master.
