### ISSUE TITLE
Drcov - Two BB Tables in file without thread local cache option

### ISSUE THREAD

**Issue by Desperado17** [DynamoRIO/dynamorio#5981]
Greetings,

I managed to cross compile dynamorio for Aarch64. Now, I try to use drcov2lcov to generate coverage info but it only seems to process a part of the lines from the log file. Opening the log file, the first BB Table entry only has 256053 lines when it should be in the late hundred thousands.

Now it seems to me that the generated file has _two_ BB Table entries although I do not use thread-individual caching:

DRCOV VERSION: 3
DRCOV FLAVOR: drcov-64
Module Table: version 5, count 211
Columns: id, containing_id, start, end, entry, offset, preferred_base, path
<...>
drcov.myapp.14722.0000.proc.log:216:BB Table: 256053 bbs
<...>
VERSION: 3
DRCOV FLAVOR: drcov-64
Module Table: version 5, count 221
Columns: id, containing_id, start, end, entry, offset, preferred_base, path
<...>
drcov.myapp.14722.0000.proc.log:5860:BB Table: 602217 bbs
<...>

I assume that the second table is not processed by drcov2lcov for some reason.

Is this normal? Should there be two BB Tables in the log file without thread specific caches?

Regards

github Master from February 15th 2023.

Edit: It seems that suddenly a second table is created after 256053 entries. I have no idea why.

**Comment by Desperado17** [comment]
Now it becomes weird: I added some logging to bbtable_print:

`static void
bb_table_print(void *drcontext, per_thread_t *data)
{
    ASSERT(data != NULL, "data must not be NULL");
    if (data->log == INVALID_FILE) {
        ASSERT(false, "invalid log file");
        return;
    }
    /* We do not support >32U-bit-max (~4 billion) blocks.
     * drcov2lcov would need a number of changes to support this.
     * We have a debug-build check here.
     */
    ASSERT(drtable_num_entries(data->bb_table) <= UINT_MAX,
           "block count exceeds 32-bit max");

    dr_fprintf(STDERR, "bb_table_print ptr: %#x\n", data->bb_table);
    dr_fprintf(STDERR, "\n");`

The message is only printed once, but there are definitely two BB Table: entries in the resulting drcov file!

**Comment by derekbruening** [comment]
From https://groups.google.com/g/dynamorio-users/c/eX3HoZshZcg it seems the culprit is a hardcoded value for SYS_execve which is wrong for AArch64:

 https://github.com/DynamoRIO/dynamorio/blob/master/ext/drcovlib/drcovlib.c#L83
