### ISSUE TITLE
Incorrect decoding of FS prefix

### ISSUE THREAD

**Issue by dvyukov** [DynamoRIO/dynamorio#6003]
Drdecode decodes `26 26 26 26 26 26 26 64 26 26 26 26 13 04 0a` as `adc %es:(%rdx,%rcx)[4byte] %eax -> %eax`.

However, gdb thinks it's `fs` instead of `es`:
```
Thread 1 "fuzzer" received signal SIGSEGV, Segmentation fault.
(gdb) p /x $rip
$1 = 0x40000002
(gdb) x/i 0x40000002
=> 0x40000002:	es es es es es es es fs es es es adc %fs:(%rdx,%rcx,1),%eax
```

This is indirectly confirmed by the fact that `%es:(%rdx,%rcx)` address is valid and should not cause SIGSEGV, while fs is not valid and CPU generates an exception.

Also:
```
echo -en "\x26\x26\x26\x26\x26\x26\x26\x64\x26\x26\x26\x26\x13\x04\x0a" > /tmp/bin | objdump -mi386 -Mx86-64 -b binary -D /tmp/bin
es es es es es es es fs es es es adc %fs:(%rdx,%rcx,1),%eax
```
while llvm-mc agrees with drdecode:
```
echo -en "0x26 0x26 0x26 0x26 0x26 0x26 0x26 0x64 0x26 0x26 0x26 0x26 0x13 0x04 0x0a" | llvm-mc --disassemble -
	adcl	%es:(%rdx,%rcx), %eax
```

On commit e879d71f0be203a2297dc9578f4fd8e3a65cc36e.

**Comment by abhinav92003** [comment]
Thanks for the bug report.

Curious whether this issue was encountered while running an actual application under DynamoRIO? Or, from the thread name "fuzzer", is the app trying to find decoder issues?

To help make this actionable: do we know what is the correct decoding for that sequence of bytes? Looks like the processor you're running on expects it to be `fs`.

**Comment by khuey** [comment]
Can you check all of these tools (and the CPU) in both 32 and 64 bit mode? "Last prefix wins" is the general rule but the non FS/GS segment prefixes are ignored in 64 bit mode, so I expect this to be an ES relative instruction in 32 bit and an FS relative instruction in 64 bit.

**Comment by dvyukov** [comment]
> Curious whether this issue was encountered while running an actual application under DynamoRIO? Or, from the thread name "fuzzer", is the app trying to find decoder issues?

It's found by a fuzzer.

> To help make this actionable: do we know what is the correct decoding for that sequence of bytes? Looks like the processor you're running on expects it to be fs.

I think it's fs, or it wouldn't SIGSEGV.

**Comment by dvyukov** [comment]
Do we need something similar to #5648 ("fs prefix always wins")?

**Comment by dvyukov** [comment]
Kyle, thanks for the fix!
This unblocked our fuzzing.

**Comment by khuey** [comment]
Great! Feel free to ping me on x86 decoder issues in the future, I do a lot of the maintenance there.

**Comment by dvyukov** [comment]
Will keep in mind, thanks. But now I can run the fuzzer for hours and nothing falls out!

The only open issue I have is #5979, it does not block fuzzing, but prevents other test I am trying to do: decode all instructions in a large real binary and ensure we can decode all of them.
