### ISSUE TITLE
Windows 11 and Windows 10 22H2 crash due to wrong handling of ThreadLocalStoragePointer

### ISSUE THREAD

**Issue by cr4zyserb** [DynamoRIO/dynamorio#6024]
Issue is in **core/win32/loader.c**:

```
/* Isolate TEB->ThreadLocalStoragePointer. */
static void *pre_static_tls;
```

Then we follow to the first reference here in function **os_loader_init_prologue**

```
        if (should_swap_teb_static_tls()) {
            pre_static_tls = d_r_get_tls(STATIC_TLS_TIB_OFFSET);
            d_r_set_tls(STATIC_TLS_TIB_OFFSET, NULL);
            LOG(GLOBAL, LOG_LOADER, 2,
                "initial thread TEB->ThreadLocalStoragePointer=" PFX "\n",
                pre_static_tls);
        }
```

So far so good, **should_swap_teb_static_tls()** returns **false**, as **tls_next_idx == 0**. Then we load our client, and it will load **kernelbase.dll** which has TLS (Win11/Win10 22H2) in it which will cause **tls_next_idx** to be incremented in **privload_os_finalize**. Next check for  **should_swap_teb_static_tls** will return **true** and in **os_loader_thread_init_prologue** will lead to this code:

```
            if (should_swap_teb_static_tls()) {
                dcontext->app_static_tls = pre_static_tls;
                d_r_set_tls(STATIC_TLS_TIB_OFFSET, dcontext->app_static_tls);
            }
```

Which in the end will set **ThreadLocalStoragePointer** to **NULL** and will cause application crash.

Proposed solution is to always initialize **pre_static_tls** in **os_loader_init_prologue** and replace code with:

```
//        if (should_swap_teb_static_tls()) {
            //always save ThreadLocalStoragePointer
            pre_static_tls = d_r_get_tls(STATIC_TLS_TIB_OFFSET);
            d_r_set_tls(STATIC_TLS_TIB_OFFSET, NULL);
            LOG(GLOBAL, LOG_LOADER, 2,
                "initial thread TEB->ThreadLocalStoragePointer=" PFX "\n",
                pre_static_tls);
//        }
```

**Comment by bete0** [comment]
Hi, can you  send a PR with your proposed solution and we can review it? 

Thank you for the contribution.

**Comment by cr4zyserb** [comment]
Hi, will do so. After a bit more of checking I think that proper solution would be actually this:

```
//        if (should_swap_teb_static_tls()) {
            //always save ThreadLocalStoragePointer
            pre_static_tls = d_r_get_tls(STATIC_TLS_TIB_OFFSET);
//            d_r_set_tls(STATIC_TLS_TIB_OFFSET, NULL);
            LOG(GLOBAL, LOG_LOADER, 2,
                "initial thread TEB->ThreadLocalStoragePointer=" PFX "\n",
                pre_static_tls);
//        }
```
And the reason is that in this case that we would set *ThreadLocalStoragePointer* to NULL when **tls_next_idx** is **false**. On systems which don't have this **kernelbase.dll* we will set **ThreadLocalStoragePointer** to **NULL** and will never recover it, thus leading to main exe crashing when it accesses **ThreadLocalStoragePointer**.
