### ISSUE TITLE
PMOVSX/ZX family instructions have unnecessarily wide source operands

### ISSUE THREAD

**Issue by dvyukov** [DynamoRIO/dynamorio#6046]
Drdecode decodes `66 0f 38 31 47 40` as `pmovzxbd 0x40(%rdi)[16byte] -> %xmm0`.
pmovzxbd reads 4 bytes at source, not 16.
On commit 4330a720d345a4374c3fbdc50abb1b7fb97bfd92.

**Comment by khuey** [comment]
All of the non-AVX pmovzx family instructions have this sort of issue.
