### ISSUE TITLE
Enable more compiler warnings in CI workflows

### ISSUE THREAD

**Issue by abhinav92003** [DynamoRIO/dynamorio#6060]
Xref #6058 where we fixed an obvious bug where a variable was being moved to itself: `x = std::move(x)`. Our CI failed to catch this, but @ksco reported that the LicheePi4A (RISC-V SBC) compiler complained about it. We should enable this check in our workflows too.

**Comment by ksco** [comment]
Also #6059, this one exists for a long time.

**Comment by derekbruening** [comment]
The issue is that the `-Wall -Werror` we use for core DR compilation gets lost in the drcachesim CMake code.  @lihasgupta is looking into addressing this for #6040, PR #6041 -- maybe one or the other should be closed as a duplicate.
