### ISSUE TITLE
Speed up test suite to <20 minutes from >30 minutes

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#6127]
Xref some discussion at https://github.com/DynamoRIO/dynamorio/pull/6096#issuecomment-1569110298 and https://github.com/DynamoRIO/dynamorio/pull/6096#issuecomment-1578824111 at adding parallelism to the ci-aarch64-native runner to avoid a backlog from simultaneous PR's waiting on each other.

The latency of the ci-aarch64-native job is also something to look at: when it was Jenkins it was pretty fast, under 10 minutes IIRC.  Now you can see it is consistently over 33 minutes and is by far the slowest of our jobs:

https://github.com/DynamoRIO/dynamorio/actions/workflows/ci-aarch64-native.yml

The general goal is to be under 20 minutes.  The Windows and Linux x86 jobs have gotten slower over time and are both over 20 minutes now.  This issue covers trying to speed all of these up.  The ci-aarch64-native seems the highest priority at the longest and because it used to be faster making it seems like there may be some low-hanging fruit there for improvements.

**Comment by joshua-warburton** [comment]
I've recently looked into it an the length of the aarch64 tests is almost completely due to the client attach/detach tests all timing out after 10 minutes.

We should be able to reduce this by either completely disabling the de/attach tests, fixing them to actually work, or reducing the timeouts.

**Comment by derekbruening** [comment]
Looks like that is #5740 which says it happened after a Jenkins hardware change.  

The client.detach test did not exist until 2 days ago in PR #6513.  It has been flaky on x86-64 since being added which I filed as #6536; the failures look like the client.attach_test failures which had happened a few times on the Linux x86-64 suite: #6452.  But, those x86-64 failures are not timeouts, so it is not clear any of that is related to #5740.

**Comment by derekbruening** [comment]
You can see the drop from 33 mins down to 8 mins at the point I enabled ptrace: https://github.com/DynamoRIO/dynamorio/actions/workflows/ci-aarch64-native.yml

Maybe the only final action item would be to reduce the timeouts: but we already did that, with the default at 90s.  So I'm confused as to why the attach/detach tests would take 10 mins to time out: I don't see timeout overrides for those.  Hmm actually it seems to only explicitly set a CTest timeout property for runcmp -- I will fix that, as part of this and #6558.

**Comment by joshua-warburton** [comment]
Glad to see it. I'm making sure this is set properly on the new AWS runners too.
