### ISSUE TITLE
OpenMPI crashes under drrun due to invalid opcode

### ISSUE THREAD

**Issue by prasun3** [DynamoRIO/dynamorio#6136]
**Describe the bug**
OpenMPI crashes under drrun because DR disassembler does not understand VPOPCNTQ.

**To Reproduce**
Just running mpirun under drrun results in a crash due to invalid opcode.
```
$ mpirun --version
mpirun (Open MPI) 4.1.4

$ drrun -- mpirun
...
<Invalid opcode encountered>
...
Illegal instruction (core dumped)
```

Running with logs enabled shows this as the bad instruction.
```
SYSLOG_WARNING: Invalid opcode encountered
Error decoding 0x00007ffdf7495150 == 0x62 0xf2 0xfd 0x28 0x55 0xc 0xfa
```
objdump shows that this is vpopcntq which requires AVX512_VPOPCNTDQ which was introduced in Ice Lake

```
62 f2 fd 28 55 0c fa    vpopcntq (%rdx,%rdi,8),%ymm1
```

**Expected behavior**
No crash

**Screenshots or Pasted Text**

**Versions**
drrun version 9.93.19518 -- build 0 (latest version available)

**Additional context**

**Comment by bete0** [comment]
@prasun3 Would you like to take on this issue and add decoder support for this instr?

**Comment by khuey** [comment]
If he does not want to I can.

**Comment by prasun3** [comment]
> If he does not want to I can.

@khuey That would be awesome!

**Comment by bete0** [comment]
Thanks @khuey!

**Comment by khuey** [comment]
You should retry this workload now in case there are other unhandled opcodes.

**Comment by prasun3** [comment]
Thanks @khuey for the quick fix! I did some basic testing and things look good. I'll report if there are any other unhandled opcodes.
