### ISSUE TITLE
Add invariant check that timestamps always increase monotonically

### ISSUE THREAD

**Issue by ivankyluk** [DynamoRIO/dynamorio#6187]
**Add a pointer to any prior users list discussion.**

https://github.com/DynamoRIO/dynamorio/issues/2039#issuecomment-1294014977 and https://github.com/DynamoRIO/dynamorio/pull/5704#discussion_r1007187555

**Is your feature request related to a problem? Please describe.**

This is a feature request, and not related to any problems.

**Describe the solution you'd like**

Add a invariant check to verify timestamps always increase monotonically.

Do you have any implementation in mind for this feature?

The implementation is similar to https://github.com/DynamoRIO/dynamorio/pull/6037, with additional check for 
32 bit systems given that the timestamp is truncated (i#5634)

**Comment by derekbruening** [comment]
This was fixed by [76b5455](https://github.com/DynamoRIO/dynamorio/commit/76b545554ce3c7e350487ea009cab9fa19596872) but the commit description failed to list it so we have no auto-link or auto-close.
