### ISSUE TITLE
reg_get_size return wrong size for GS segment register in x64

### ISSUE THREAD

**Issue by yangyixiaof** [DynamoRIO/dynamorio#6240]
**Describe the bug**
reg_get_size(DR_SEG_GS)  returns OPSZ_2 in x64 Windows, however, it is actually OPSZ_8. 
I print the value of GS through following code in  a clean call inserted in any position:
```
opnd_t created_opd = opnd_create_far_abs_addr(DR_SEG_GS, 0, OPSZ_2);
auto created_gs_addr = opnd_compute_address(created_opd, mc);
printf("%p\n", created_gs_addr);
```  
The printed address is actually 0x0000007701254000, obiviously, it is more than 2 bytes.

**Comment by ivankyluk** [comment]
The segment register GS is a 16 bit register.

Please see: 

Intel® 64 and IA-32 Architectures Software Developer’s Manual, Volume 3A: System Programming Guide, Part 1
Figure 8-2

https://www.intel.com/content/www/us/en/content-details/782154/intel-64-and-ia-32-architectures-software-developer-s-manual-volume-3a-system-programming-guide-part-1.html?wapkw=Intel%C2%AE%2064%20and%20IA-32%20Architectures%20Software%20Developer%E2%80%99s%20Manual

Is there a doc that indicates it's actually OPSZ_8?

**Comment by derekbruening** [comment]
Agreed, segment selector registers are 16 bits.  A linear address is constructed using the selector, but the size of the address is completely different from the size of the selector register.  In the future, I would recommend first asking a question on the users list https://groups.google.com/forum/#!forum/DynamoRIO-Users to confirm it's a real bug.  The users list discussion will also benefit other users.

**Comment by yangyixiaof** [comment]
> Agreed, segment selector registers are 16 bits. A linear address is constructed using the selector, but the size of the address is completely different from the size of the selector register. In the future, I would recommend first asking a question on the users list https://groups.google.com/forum/#!forum/DynamoRIO-Users to confirm it's a real bug. The users list discussion will also benefit other users.

May I ask how to get the value of GS segment register? I cannot imagine how 0x0000007701254000 is computed from a 16 bit register.

**Comment by yangyixiaof** [comment]
> > Agreed, segment selector registers are 16 bits. A linear address is constructed using the selector, but the size of the address is completely different from the size of the selector register. In the future, I would recommend first asking a question on the users list https://groups.google.com/forum/#!forum/DynamoRIO-Users to confirm it's a real bug. The users list discussion will also benefit other users.
> 
> May I ask how to get the value of GS segment register? I cannot imagine how 0x0000007701254000 is computed from a 16 bit register.

OK, I figure out that GS cannot be directly fetched, and only the base address computed by GS can be got from asm code:
```
asm volatile("mov %%gs:%1, %0" : "=r"(sel) : "m"(*(void **)0));
``` 
Thanks, I have no problem now.
