### ISSUE TITLE
where can I find zero-masking in AVX-512 instruction?

### ISSUE THREAD

**Issue by yangyixiaof** [DynamoRIO/dynamorio#6249]
For instructions with zero-masking as follows:
```
vsubps ymm0 {k4}{z}, ymm1, ymm2
```
I cannot find  {z} in any opnd. That instruction is described in [MASM page](https://learn.microsoft.com/en-us/cpp/assembler/masm/instruction-format?view=msvc-170#AVX-512%20Options). 
If instruction has {z}, the 'should not sub float part' controled by {k4} should be set to zero, otherwise, remain unchanged. 
I think this {z} is important when handling instructions, especially for taint analysis, so does {z} is not supported by current DynamoRIO?

**Comment by ivankyluk** [comment]
Please use the users list https://groups.google.com/forum/#!forum/DynamoRIO-Users for general questions, as it will reach a wider audience of people who might have an answer, and it will reach other users who may find the information beneficial. The issue tracker is for specific detailed bugs.

**Comment by derekbruening** [comment]
Looks like a dup of #5488
