### ISSUE TITLE
drwrap_replace() is not overloading properly.

### ISSUE THREAD

**Issue by chaitanyaupp18** [DynamoRIO/dynamorio#6259]
**Describe the bug**

While using the drwrap_replace() function, even on passing `true` to overload, overloading is not happening. Instead, it is still going through the same call stack it would have taken otherwise.

**To Reproduce**
1. The source code is in this drive link: https://drive.google.com/drive/folders/1sYGWCRJjhI4n8UJoV1C3Dv-pZS61qhmc?usp=sharing
2. The command for running is: $make
3. <Application /home/cmama002/to_dynamorio_issues/build/example (1756568).  Internal Error: DynamoRIO debug check failure: /home/runner/work/dynamorio/dynamorio/core/heap.c:1966 IF_WINDOWS(doing_detach ||) vmh->num_free_blocks == vmh->num_blocks - unfreed_blocks || ((ever_beyond_vmm IF_WINDOWS(|| get_os_version() >= WINDOWS_VERSION_8_1)) && vmh->num_free_blocks >= vmh->num_blocks - unfreed_blocks)
(Error occurred @2586 frags in tid 1756568)
version 9.93.19566, custom build
-no_dynamic_options -loglevel 1 -client_lib '/home/cmama002/to_dynamorio_issues/build/profiler/libprofiler.so;0;' -client_lib64 '/home/cmama002/to_dynamorio_issues/build/profiler/libprofiler.so;0;' -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ig
0x00007fb54bd29870 0x00007fb78fd4a6be
0x00007fb54bd29ac0 0x00007fb78fde034d
0x00007fb54bd29b00 0x00007fb78fde03dc
0x00007fb54bd29b10 0x00007fb78fcc13be
0x00007fb54bd29b50 0x00007fb78fcc1701
0x00007fb54bd29b70 0x00007fb78fcc188f
0x00007fb54bd29b90 0x00007fb78ff18ad3
0x00007fb54bd29ba8 0x00007fb54bce2880
/home/cmama002/to_dynamorio_issues/install/DynamoRIO/lib64/debug/libdynamorio.so=0x00007fb78fc63000>
make: *** [Makefile:11: run] Error 255

Please also answer these questions:
 - What happens when you run without any client?
 Client is required for my problem.
 - What happens when you run with debug build ("-debug" flag to drrun/drconfig/drinject)?
 Same behavior is generated.

**Expected behavior**

I am trying overload realloc() with my_realloc() in DynamoRIO by wrapping. Somehow, it is not properly overloading!

**Screenshots or Pasted Text**
If applicable, add screenshots to help explain your problem.  For text, please cut and paste the text here, delimited by lines consisting of three backtics to render it verbatim, like this:
<pre>

</pre>

**Versions**
 - What version of DynamoRIO are you using?
 9.93.19566
 - Does the latest build from https://github.com/DynamoRIO/dynamorio/releases solve the problem?
 No
- What operating system version are you running on? ("Windows 10" is *not* sufficient: give the release number.)
Ubuntu 22.10
- Is your application 32-bit or 64-bit?
64 bit

**Additional context**

**Comment by derekbruening** [comment]
The heap.c assert is a memory leak: most likely something in your client and not related to this issue.

> overloading is not happening. Instead, it is still going through the same call stack it would have taken otherwise.

Please paste in the evidence that convinced you of this.

At what point in time was the drwrap_replace() call issued?  Was there already code in the cache for the target PC?

Is the target PC not the start of a block?  Was it inlined into a superblock trace maybe?  Does `-disable_traces` make a difference?

Generally what you want to do is run `-loglevel 3` (see https://dynamorio.org/page_logging.html) which prints out every app instruction and find your target PC.  This helps confirm you have the right PC.  Is it the start of a block?  Does it appear before your client asked to replace it, and it wasn't flushed by drwrap's lazy flush attempt?

**Comment by chaitanyaupp18** [comment]
I am new to DynamoRIO. Please correct me if I am wrong. 

I think some realloc() is called before the actual drwrap_replace()'s app_pc for realloc. I am attaching few screenshots from the log file, I obtained after running -loglevel 3
 
Will you please check and let me know how to proceed further?

![Screenshot 2023-08-11 at 11 39 40 AM](https://github.com/DynamoRIO/dynamorio/assets/43720440/d7fc938f-7b69-45c3-a496-d15da2847e86)

![Screenshot 2023-08-11 at 11 39 50 AM](https://github.com/DynamoRIO/dynamorio/assets/43720440/148bdba7-7bd5-42f9-bb25-bb10085d8982)

![Screenshot 2023-08-11 at 11 40 23 AM](https://github.com/DynamoRIO/dynamorio/assets/43720440/f61e4aab-3eee-4635-922e-2334def4123c)

**Comment by derekbruening** [comment]
> I think some realloc() is called before the actual drwrap_replace()'s app_pc for realloc. 

You mean you see ... was going to paste the realloc address but you've used screenshots which can't have their text selected: better to just paste the text instead of a screenshot for log file contents.  From just these snippets, I would guess your code is based on the wrap.c sample and it looks for realloc in every module and finds none in most (the 0 ones) and then finds one and successfully replaces it and crashes probably soon after the replacement routine -- probably from a bug in the replacement routine itself?  As with any crash, you'd want a symbolized callstack, and look in the log for precisely where it happens.  Maybe there is a bug in your replacement routine code.

**Comment by chaitanyaupp18** [comment]
In my replacement routine, just to check I am just allocating memory for a pointer and returning the pointer's address. If I comment that line, replacement routine works fine!

The below is what I find in the log file when the error occurs:

SYSLOG_ERROR: Application /home/cmama002/to_dynamorio_issues/build/example (1860545).  Internal Error: DynamoRIO debug check failure: /home/runner/work/dynamorio/dynamorio/core/heap.c:1966 IF_WINDOWS(doing_detach ||) vmh->num_free_blocks == vmh->num_blocks - unfreed_blocks || ((ever_beyond_vmm IF_WINDOWS(|| get_os_version() >= WINDOWS_VERSION_8_1)) && vmh->num_free_blocks >= vmh->num_blocks - unfreed_blocks)
(Error occurred @2587 frags in tid 1860545)
version 9.93.19566, custom build
-no_dynamic_options -loglevel 3 -client_lib '/home/cmama002/to_dynamorio_issues/build/profiler/libprofiler.so;0;' -client_lib64 '/home/cmama002/to_dynamorio_issues/build/profiler/libprofiler.so;0;' -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ig
0x00007f43c2e65870 0x00007f4606e866be
0x00007f43c2e65ac0 0x00007f4606f1c34d
0x00007f43c2e65b00 0x00007f4606f1c3dc
0x00007f43c2e65b10 0x00007f4606dfd3be
0x00007f43c2e65b50 0x00007f4606dfd701
0x00007f43c2e65b70 0x00007f4606dfd88f
0x00007f43c2e65b90 0x00007f4607054ad3
0x00007f43c2e65ba8 0x00007f43c2e1e880
/home/cmama002/to_dynamorio_issues/install/DynamoRIO/lib64/debug/libdynamorio.so=0x00007f4606d9f000
SYSLOG_ERROR: Application /home/cmama002/to_dynamorio_issues/build/example (1860545).  Internal Error: DynamoRIO debug check failure: /home/runner/work/dynamorio/dynamorio/core/heap.c:1966 IF_WINDOWS(doing_detach ||) vmh->num_free_blocks == vmh->num_blocks - unfreed_blocks || ((ever_beyond_vmm IF_WINDOWS(|| get_os_version() >= WINDOWS_VERSION_8_1)) && vmh->num_free_blocks >= vmh->num_blocks - unfreed_blocks)
(Error occurred @2587 frags in tid 1860545)
version 9.93.19566, custom build
-no_dynamic_options -loglevel 3 -client_lib '/home/cmama002/to_dynamorio_issues/build/profiler/libprofiler.so;0;' -client_lib64 '/home/cmama002/to_dynamorio_issues/build/profiler/libprofiler.so;0;' -code_api -stack_size 56K -signal_stack_size 32K -max_elide_jmp 0 -max_elide_call 0 -early_inject -emulate_brk -no_inline_ig
0x00007f43c2e65870 0x00007f4606e866be
0x00007f43c2e65ac0 0x00007f4606f1c34d
0x00007f43c2e65b00 0x00007f4606f1c3dc
0x00007f43c2e65b10 0x00007f4606dfd3be
0x00007f43c2e65b50 0x00007f4606dfd701
0x00007f43c2e65b70 0x00007f4606dfd88f
0x00007f43c2e65b90 0x00007f4607054ad3
0x00007f43c2e65ba8 0x00007f43c2e1e880
/home/cmama002/to_dynamorio_issues/install/DynamoRIO/lib64/debug/libdynamorio.so=0x00007f4606d9f000
DynamoRIO call stack:
Thread 1860545 call stack:
	frame ptr 0x00007f43c2e65700 => parent 0x00007f43c2e65870, 0x00007f4606e8c4f9  
	frame ptr 0x00007f43c2e65870 => parent 0x00007f43c2e65ac0, 0x00007f4606e866be  
	frame ptr 0x00007f43c2e65ac0 => parent 0x00007f43c2e65b00, 0x00007f4606f1c34d  
	frame ptr 0x00007f43c2e65b00 => parent 0x00007f43c2e65b10, 0x00007f4606f1c3dc  
	frame ptr 0x00007f43c2e65b10 => parent 0x00007f43c2e65b50, 0x00007f4606dfd3be  
	frame ptr 0x00007f43c2e65b50 => parent 0x00007f43c2e65b70, 0x00007f4606dfd701  
	frame ptr 0x00007f43c2e65b70 => parent 0x00007f43c2e65b90, 0x00007f4606dfd88f  
	frame ptr 0x00007f43c2e65b90 => parent 0x00007f43c2e65ba8, 0x00007f4607054ad3  
	frame ptr 0x00007f43c2e65ba8 => parent 0x0000000000000000, 0x00007f43c2e1e880

**Comment by derekbruening** [comment]
Like I already said up above https://github.com/DynamoRIO/dynamorio/issues/6259#issuecomment-1673967226 the heap.c assert indicates a memory leak in your client.

In the future, please use the users list https://groups.google.com/forum/#!forum/DynamoRIO-Users for something like this or other questions, as it will reach a wider audience of people who might have an answer, and it will reach other users who may find the information beneficial.  It is best to confirm through questions on the users list first whether something is a bug in DynamoRIO itself before filing an issue about it.
