### ISSUE TITLE
Update raw2trace.cpp to Import syscall_linux_xxx header file based on the target architecture.

### ISSUE THREAD

**Issue by ivankyluk** [DynamoRIO/dynamorio#6406]
raw2trace_t::is_maybe_blocking_syscall() depends on the definitions of SYS_xxx to determine if the syscall may be blocking or not. 

core/unix/include/syscall.h imports syscall_linux_xxx header file based on the host architecture. For cross platform support, the syscall_linux_xxx header file should be imported based on the target architecture.

**Comment by derekbruening** [comment]
This has to be carefully considered as there may well be syscalls executed in host!=target modes which of course have to match the host.
