### ISSUE TITLE
api.dis and decenc.drdecode_decenc_x86_64 failures in output matching

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#6411]
This seems to have started recently (though xref #5725):

x64 Linux:
https://github.com/DynamoRIO/dynamorio/actions/runs/6752187857/job/18358030169
```
420/473 Test #422: code_api|api.dis .................................................***Failed    0.10 sec
CMake Error at /home/runner/work/dynamorio/dynamorio/suite/tests/runcmp.cmake:114 (message):
  failed to match expected output
```

Same failure on win64:
https://github.com/DynamoRIO/dynamorio/actions/runs/6775123864/job/18413681364?pr=6410

Similarly obscure failure in the same win64 run:
```
297/303 Test #290: code_api|decenc.drdecode_decenc_x86_64 ...........................***Failed    2.10 sec
CMake Error at D:/a/dynamorio/dynamorio/suite/tests/runcmp.cmake:114 (message):
  failed to match expected output
```

Did we change runcmp.cmake to not print out the diff?
I think PR #6254 is the culprit: that is why we now just have this opaque
message without details.  So these may be the same as #5725.

**Comment by derekbruening** [comment]
From https://github.com/DynamoRIO/dynamorio/pull/6428#issuecomment-1803128207 adding the diff: this does look like #5725 so let's collapse into that one.

**Comment by leewvic** [comment]
Attaching a diff output for the decoder problem.  Current theory:  there are some difference how AMD vs. Intel machines interpret the opcodes.
[6_Run Suite.txt](https://github.com/DynamoRIO/dynamorio/files/13311768/6_Run.Suite.txt)
