### ISSUE TITLE
api.ir test fails on AArch64 hardware trying to encode LDAPR

### ISSUE THREAD

**Issue by egrimley-arm** [DynamoRIO/dynamorio#6420]
When I do `make test` with `DEBUG=ON` (fe8eec30c07fa4b1b70a7ab1f3c08190cb4b2c5b) on a system with Cortex-A72 CPUs running Ubuntu 22.04 one of the 18 failures I see is `code_api|api.ir`, which fails because it tries to encode an LDAPR instruction which the encoder refuses to encode because the host does not have the LRCPC feature.

To me it seems like an unpleasant surprise for the user that the behaviour of the encoder depends on detected features of the hardware. It also does not seem particularly useful: if you were going to do something different depending on the host hardware then presumably you would prefer to know that an instruction is not available well before the point at which the encoder is invoked. For example, if I remember correctly how `instrlist_preinsert` is typically used, having the encoder unexpectedly return `NULL` is probably going to lead to a SIGSEGV in `libdynamo.so` and thus be rather less helpful than getting a SIGILL from the mangled code. So would it be better for the encoder to just encode (like how the decoder just decodes, as I understand it) and for there to be a separate function for querying whether an instruction will execute or give SIGILL on the current hardware?

**Comment by egrimley-arm** [comment]
Probably the test in question should be moved from `ir_aarch64.c` to `ir_aarch64_something.c` or a call to `enable_all_test_cpu_features()` should be added to `ir_aarch64.c`. But I'm still interested in the general question of whether the encoder should be sensitive to host features.

**Comment by derekbruening** [comment]
I would agree that the encoder should at least have a mode (and probably the default mode) where it doesn't care about CPU feature support, especially a standalone encoder which doesn't know the use case of the user which could easily be cross-generating or testing.  Neither the x86 nor aarch32 encoders in DR today have any check on which ISA versions/features are/should be enabled (except of course what major ISA mode is enabled: arm vs thumb or 32-bit vs 64-bit), though they don't store such info in their tables currently either and just have a couple of separate opcode lists for some major feature sets (used by drcpusim): xref #431.

**Comment by egrimley-arm** [comment]
The LDAPR thing in the title was fixed by #6433 so I've created #6450 for the more general issue of the encoder being sensitive to details of the host hardware and I'm closing this.
