### ISSUE TITLE
instrace_simple's operand

### ISSUE THREAD

**Issue by 2020270127** [DynamoRIO/dynamorio#6723]
A clear and concise description of what the problem is.  E.g., "I'm always frustrated when [...]"
with api/sample, instrace.simple.c, we can get target process's opcodes. 
however, we can't get operand with this code. Is it possible to get opcode's src, dst with struct "ins_ref_t"?

**Comment by 2020270127** [comment]
i found dynamo's api "disassemble()" :)

**Comment by derekbruening** [comment]
Please use the users list https://groups.google.com/forum/#!forum/DynamoRIO-Users for questions, as it will reach a wider audience of people who might have an answer, and it will reach other users who may find the information beneficial. The issue tracker is for specific detailed bugs. If you are not sure it's a bug, please start by asking on the users list.
