### ISSUE TITLE
ubuntu22 GA workflows failing apt-get update

### ISSUE THREAD

**Issue by abhinav92003** [DynamoRIO/dynamorio#6790]
Our x86-64-ubuntu22 and x86-32-ubuntu22 Github Action workflows are failing in the "Create Build Environment" stage at `sudo apt-get update` with the following error:

```
Hit:21 https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu jammy InRelease
Reading package lists...
E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease' is no longer signed.
```

E.g., https://github.com/DynamoRIO/dynamorio/actions/runs/8814125003/job/24199585784?pr=6783

This seems related to https://github.com/orgs/community/discussions/120966

As of now, this is blocking all merges.

**Comment by edeiana** [comment]
Seems to be resolved.
Re-running the workflow yesterday (multiple times) didn't work.
Re-running it today did.

**Comment by abhinav92003** [comment]
This was resolved without any action from our side: https://github.com/orgs/community/discussions/120966#discussioncomment-9213550.
