### ISSUE TITLE
Failed to build a DynamoRIO client: linker error with elftc library

### ISSUE THREAD

**Issue by apach301** [DynamoRIO/dynamorio#6909]
Hi!

I was trying to test the last version of DynamoRIO and found out that my client is failed to build with link error:
```
/usr/bin/ld: cannot find -lelftc
```
The problem occured with 0a6c0579d8ecb72430121bff72c0348d56397efb.
DynamoRIO itself is successfully builds, the problem with linking a custom client library. File `link.txt` in generated CMakeFiles for client contains:
```
<...> /path/libdynamorio.so /path/libdw_pic.a -lpthread /path/libdwelf_pic.a path/libelf_pic.a /path/libebl_pic.a /path/libz.so -lelftc 
```

When client builds with DynamoRIO on previous commit, its `link.txt` contains:
```
<...> /path/libdynamorio.so /path/libdwarf.a /path/libelftc.a /path/libelf.a
```

So the problem is that `-lelftc` is somehow passed to linker instead of path to static library? The `libelftc.a` is exist in DynamoRIO sources, and `elftc_libpath` in Cmake is pointing to it (dynamorio/ext/drsyms/libelftc/lib64/libelftc.a). Maybe there are some additional settings needed to pass for client's Cmake rules?

The Cmake for client is looking like this:
```
configure_DynamoRIO_client(name)
use_DynamoRIO_extension([drmgr_static|drutil_static|drwrap_static|drsyms_static])
```

Building with ubuntu20.04/clang-14.

Thanks!

**Comment by derekbruening** [comment]
You did not say what cmake generator you used: please provide full details on how it was configured and built.  Please check whether it only happens with a particular generator.  Are you sure you tried from a completely clean build.  The Github Actions tests use Ubuntu20 (https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2004-Readme.md) and have no trouble for `clients/drcov/CMakeLists.txt:use_DynamoRIO_extension(drcov2lcov drsyms_static)`. If you use the same cmake version as the G.A. does it work?  Does your drcov2lcov build?  What if you use the prebuilt weekly cronbuild?

**Comment by apach301** [comment]
> You did not say what cmake generator you used: please provide full details on how it was configured and built. Please check whether it only happens with a particular generator. Are you sure you tried from a completely clean build. The Github Actions tests use Ubuntu20 (https://github.com/actions/runner-images/blob/main/images/ubuntu/Ubuntu2004-Readme.md) and have no trouble for `clients/drcov/CMakeLists.txt:use_DynamoRIO_extension(drcov2lcov drsyms_static)`. If you use the same cmake version as the G.A. does it work? Does your drcov2lcov build? What if you use the prebuilt weekly cronbuild?

CMake-3.30.2 (also tested CMake-3.25). I tried from a completely new build of my whole project, also tried to use prebuilt cronbuild version to compile my client - the problem is still here.

DynamoRIO is built succesfully: libdrcov.so, drcov2lcov etc. are built and linked with libelftc.a (as specified in dynamorio-build/src/DynamoRIO-build/clients/drcov/CMakeFiles/drcov2lcov.dir/link.txt).

Tried to build with Ninja, result same:
![image](https://github.com/user-attachments/assets/b9cfbdb1-e87c-430f-a100-8fae6a06fc28)
 
For some reason, it's adding `-lelftc` to build rules instead of `dynamorio/ext/drsyms/libelftc/lib64/libelftc.a`.

**Comment by apach301** [comment]
I found a first commit that failing my build (https://github.com/DynamoRIO/dynamorio/commit/0a6c0579d8ecb72430121bff72c0348d56397efb), and it seems like ext/drsyms/CMakeLists.txt is the only file that could affect this, but I can't figure out how exactly.

**Comment by derekbruening** [comment]
Is it https://github.com/DynamoRIO/dynamorio/blob/master/make/DynamoRIOConfig.cmake.in#L434?  If you add a separate conditional for the elftc does that solve it?  If so, since you have a test in front you, could you send a PR?  Ideally some test using the import would be added: `samples_proj` builds all the samples; none must use drsyms as a static lib.

**Comment by apach301** [comment]
> Is it https://github.com/DynamoRIO/dynamorio/blob/master/make/DynamoRIOConfig.cmake.in#L434? If you add a separate conditional for the elftc does that solve it? If so, since you have a test in front you, could you send a PR? Ideally some test using the import would be added: `samples_proj` builds all the samples; none must use drsyms as a static lib.

Yes, that fixed a problem, thanks a lot! In my case the `libelftc.a` is the only library out of these three (libdwarf, libelf) that is placed in dynamorio/ext/lib64/release directory.

**Comment by apach301** [comment]
> none must use drsyms as a static lib.

Made a PR, but didn't add any test for it. I tried it only on my tool (not a test), and as I understand the bug is triggered by linking client with `drsyms_static`, which can't be checked by building samples in tests.

**Comment by derekbruening** [comment]
> > none must use drsyms as a static lib.
> 
> Made a PR, but didn't add any test for it. I tried it only on my tool (not a test), and as I understand the bug is triggered by linking client with `drsyms_static`, which can't be checked by building samples in tests.

I believe the `samples_proj` test builds the samples as external clients using the DynamoRIOConfig.cmake so I think a sample that linked with `drsyms_static` would hit the bug.  But we can live without.
