### ISSUE TITLE
APP CRASH: XMM not properly restored by thread_set_self_mcontext

### ISSUE THREAD

**Issue by ndrewh** [DynamoRIO/dynamorio#6919]
`thread_set_self_mcontext` should fill in `fpstate` from`mcontext` on x86.

 Currently, `fpstate` set to NULL in `thread_set_self_mcontext`:
https://github.com/DynamoRIO/dynamorio/blob/30c3a9befd88596a17df1509f9c85c3d5cd39bf6/core/unix/signal.c#L3343-L3345

and then unsuccessfully initialized in `thread_set_self_context` here (line 3246 overwrites changes made by 3244):
https://github.com/DynamoRIO/dynamorio/blob/30c3a9befd88596a17df1509f9c85c3d5cd39bf6/core/unix/signal.c#L3241-L3251

The subsequent call to `save_fpstate` is a nop when fpstate is NULL, but even if fpstate were initializated -- it looks like it would just overwrite the saved fpstate with the current (likely clobbered) fp regs from xsave.

As a result, the following path does not appear to properly restore fp (xmm) regs:

dispatch_enter_fcache => check_wait_at_safe_spot => thread_set_self_mcontext => thread_set_self_context

test forthcoming in PR

**Comment by derekbruening** [comment]
I believe this path `dispatch_enter_fcache => check_wait_at_safe_spot => thread_set_self_mcontext` happens with: synchall flush or reset; dr_app_stop.  So it won't happen if reset is disabled and a detach with dr_app_stop_and_cleanup is done which is our typical use case which is perhaps why we have never hit it.

**Comment by ndrewh** [comment]
I was hitting it in synchall flush. You have to get a bit unlucky to hit it naturally -- I've only been able to trigger this when you have multiple threads and one of them is spamming dr_flush_region (That's what my test PR does). There are some common libc funcs (e.g. `_int_free`) that rely on xmm preservation across bbs.

Without the fix, the test I wrote will also randomly crash in libc functions if you replace `write` with `printf` for example. (That's why the test uses `write` -- because I didn't want to hit the bug before we even make it to the asserts)
