### ISSUE TITLE
dynamorio client do not work  why?

### ISSUE THREAD

**Issue by Wang-H-Y** [DynamoRIO/dynamorio#6957]
I created a `build` folder under the `sample` directory of the release version. After compiling, I used
 `./drrun -c ~/Desktop/code/DynamoRIO-Linux-10.93.19959/samples/build/bin/libbbcount.so`,
 but it couldn't perform the calculation function. 
However, using the **pre-compiled** `bin64/libbbcount.so` in the release version **works fine**. 
Why is this happening? Where could the problem be? I would really appreciate it if someone could help resolve this. 
Thank you very much.

**Comment by AssadHashmi** [comment]
In future, please use the users list https://groups.google.com/forum/#!forum/DynamoRIO-Users for questions like this, as it will reach a wider audience of people who might have an answer, and it will reach other users who may find the information useful. This issue tracker is for specific detailed bugs. If you are not sure it's a bug, please start by asking on the users list.

> but it couldn't perform the calculation function.

Do you mean it fails to run or the output counts are not what you expect?
Can you paste the commands you used to build and run the client  and the output which includes the actual error message(s), or the erroneous counts.

Have you followed the instructions at https://dynamorio.org/page_build_client.html ?

**Comment by ivankyluk** [comment]
For questions and discussion, please join the DynamoRIO Users group http://groups.google.com/group/dynamorio-users, and post your question there.
