### ISSUE TITLE
nondeterminism in the DynamoRIO Memtrace Reuse Time metric between two runs of the same executable

### ISSUE THREAD

**Issue by joalen** [DynamoRIO/dynamorio#6958]
Hi Dynamorio maintainers and team!

I encountered nondeterministic behavior in the reuse_time logs from DynamoRIO's memtrace tool, where I had a sample of 42 projects to test against it and resulted in 23 of these projects getting affected across seven architecture types (aarch64, armv7, mips, mips64, riscv64, x64, and x86) ran under GitHub Actions. Moreover, I noted the following observations in general when running these projects: 
- `x64` architecture: 23 repositories out of 42 reported inconsistencies -- average of 7/10 runs per executable tested
- `aarch64`, `mips`, `mips64`, `riscv64`, `x86` architecture: 23 repositories out of 42 reported inconsistencies -- average of 6/10 runs per executable tested
- `armv7` architecture: 23 repositories out of 42 reported inconsistencies -- average of 5/10 runs per executable tested

Would the maintainers and team do the needful to remedy this or provide explanations for my observations? Thank you so much!!

**To Reproduce**
1. Run on GitHub Actions utilizing an Ubuntu 22.04 runner and use Dynamorio's cron build version 10.91.19860 and define necessary architecture types as separate jobs (the aforementioned). *Note: Make sure you disable ASLR and memory swapping within the GitHub runners.*
2. Initialize 10 runs of this GitHub Action of Dr. Memory and use this command line: `drrun -t drmemtrace -tool reuse_time -- <app>` and make sure to redirect the output into a log for easier comparison
3. Obtain those logs for the 10 runs to analyze

**Observed results** 
I saw some differences in the total access, total instructions, mean reuse time, and the histogram (which the histogram is a "hit-or-miss" in getting accurate readings I suppose). However, when I ran one binary for ten consecutive runs, I noticed the following across these architecture types: 
- In `aarch64`,  10/10 runs showed inconsistencies across the reports compared sequentially 
- In `armv7`,  6/10 runs showed inconsistencies across the reports compared sequentially
- In `mips`, `riscv64`, and `x64`,  7/10 runs showed inconsistencies across the reports compared sequentially. 
- In `mips64`,  8/10 runs showed inconsistencies across the reports compared sequentially. 
- In `x86`,  3/10 runs showed inconsistencies across the reports compared sequentially. 

From that, I notice that the total access, total instructions values, and the mean reuse time change (with total instructions being somewhat more significant in change compared to the access or mean reuse time fields). The attached screenshot shows two runs of the jq project (in GitHub) as a binary tested against dynamorio's memtrace product with the reuse_time option.

**Screenshots or Pasted Text**
I have a PDF attached that shows these changes. Run 1 represents the left column while Run 2 represents the right column.  
[dynamorio_reusetime_comparison.pdf](https://github.com/user-attachments/files/16813323/dynamorio_reusetime_comparison.pdf)

**Versions**
 - DynamoRIO cron build 10.91.19860
 - Ubuntu 22.04
 - jq should be a 64-bit ELF binary

**Comment by derekbruening** [comment]
There is non-determinism in the system loader ld.so code and sometimes in other startup code that can cause even hello,world to have varying instruction counts on the *same machine*, let alone across machines.  Even if these Github Actions virtual machines are supposed to be identical they can have slight variations.  One extra environment variable somewhere can result in extra startup code run.  Seeing slight variations in the code run by a set of random applications run across different virtual machines is not at all surprising.  Your pdf has a 0.01% variation in instruction count which is in line with these observations: so I assume all of these "inconsistencies" are similarly small variations.  Only if you have a statically linked application with absolutely no inherent variation can you expect to never have a slight difference across runs.  

Did you try things like `perf -e instructions:u` on this same set of applications across these machines?  I'm sure you'll see variations there too.  There is inherent variation in the libraries if not in the applications themselves.  Additionally, are you sure these 42 different projects don't have further sources of non-determinism of their own?  How would you know?

I don't think there's anything surprising here or anything urgent to investigate.  If you are really curious to dive deeper I would suggest gathering two traces using the `-offline` parameter to drmemtrace and then diff-ing the traces to zero in on the non-determinism.
