### ISSUE TITLE
drmemory Win10/i686 CRASH

### ISSUE THREAD

**Issue by sebifeld** [DynamoRIO/dynamorio#7075]
**Describe the bug**
drmemory on Win10/i686 crashes in dynamorio code

**To Reproduce**
1. Download Drmemory, either 2.6 or latest build:
https://github.com/DynamoRIO/drmemory/releases/tag/cronbuild-2.6.20005
2. Install drmemory
3. Precise command line for running the application.
Any drmemory call will crash it

**Comment by derekbruening** [comment]
There's nothing actionable here: "Win10" is not really any more specific than "Windows" as there are many many versions quite different from each other.  There's no application listed.  The template https://github.com/DynamoRIO/drmemory/issues/new?assignees=&labels=&template=bug_report.md&title= was not filled out.  Closing as not usable.
