### ISSUE TITLE
Change raw2trace::handle_rseq_abort_marker parameter name to rseq_aborted.

### ISSUE THREAD

**Issue by ivankyluk** [DynamoRIO/dynamorio#7084]
**Describe the bug**
raw2trace_t::handle_rseq_abort_marker() uses different names of the last parameter. It's interrupted in raw2trace.h
but it is rseq_aborted in raw2trace.cpp.

**Expected behavior**
The parameter names should be consistent.

**Versions**
 - What version of DynamoRIO are you using? The latest.
 - Does the latest build from https://github.com/DynamoRIO/dynamorio/releases solve the problem? Yes.
- What operating system version are you running on? ("Windows 10" is *not* sufficient: give the release number.) N/A
- Is your application 32-bit or 64-bit? N/A

**Comment by derekbruening** [comment]
The inconsistent names were introduced in PR #7058.
