### ISSUE TITLE
attach feature on Windows

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#725]
_From [bruen...@google.com](https://code.google.com/u/109494838902877177630/) on April 09, 2012 14:58:26_

xref issue #38 : attach injection on Linux
xref issue #722 : internally-triggered attach

the problem with attach on windows of course is the inability to
maintain control across a callback return when the callback
occurred prior to attaching.

idea: have thin_client presence up front that hooks all alertable
syscalls.  risk: there are many alertable syscalls and maybe we
don't really know all of them.  probably best to hook all the
file i/o calls even though their alertability depends on their
args.

in absence of control up front, we could go ahead and try on windows and lose control briefly, counting on native_exec_syscalls like we do when we lose control on AppInit (though here there are multiple threads), and
just document the limitations to any users

_Original issue: http://code.google.com/p/dynamorio/issues/detail?id=725_

**Comment by derekbruening** [comment]
9c95ba5aadd1dcc42b1e43161ad0193ca561a071 added enumeration and takeover of unknown threads, invoked by default on regular startup

**Comment by OrBenPorath** [comment]
Added in #5075.
Test still requires works, and to be removed from the flaky list.



Test occasionally failing in one of two ways:
1. [Nothing happens until the test times out](https://github.com/DynamoRIO/dynamorio/runs/3685679149?check_suite_focus=true).
Unclear how that could happen, as one of the first things the target does is print something.
Maybe it doesn't even start?

2. [Test output missing 'MessageBox closed' before 'done'](https://github.com/DynamoRIO/dynamorio/pull/5075/checks?check_run_id=3684533264):
Unclear how the target terminates, as there is no FATAL_ERROR reported, and all normal termination paths have another print before "done".

**Comment by derekbruening** [comment]
I thought the Windows detach via nudge was exposed today but it's not:

The existing Windows detach nudge feature is internal to DR and does not go
through a client.  It looks like it is not exposed in drconfig and the old
tests for it are not all enabled; the old way to trigger it is in the
no-longer-supported "drcontrol" front-end, but it's just a different nudge
type so it should be feasible to tweak drconfig to enable it to try it out.
You can see the code paths in libutil/detach.c triggering the nudge to be
sent and handling it in core/nudge.c "TEST(NUDGE_GENERIC(detach),
nudge_action_mask)" calling detach_helper() which calls the
shared-with-all-detach-types detach_on_permanent_stack().

So that is a remaining action item as well.  Xref adding a nudge detach
for Linux #95 where we have to create a new stack.

**Comment by derekbruening** [comment]
Still remaining:
+ We want to get an automated test in place
+ We should update the documentation to include how to detach

Once we have those 2 things we should be able to close this issue (with any future problems being opened as new bugs).

**Comment by onroadmuwl** [comment]
The automated [test of detach](https://github.com/DynamoRIO/dynamorio/pull/6221) and [detach documentation](https://github.com/DynamoRIO/dynamorio/pull/6222) have been fixed, although the detach test for vs2019-32 may complain timeout like the attach test.

**Comment by derekbruening** [comment]
Looks like the attach_test is still listed on the ignore-failures list.  That should be fixed before this issue is closed.
Looks like it might be easy: it just has the wrong order of two lines:
```
126/257 Test #125: code_api|client.attach_test ..................................***Failed  Required regular expression not found. Regex=[^starting attachee
thank you for testing attach
thread init
event_post_attach
MessageBox closed
done$] 61.93 sec
```
Vs the actual output
```
starting attachee
thank you for testing attach
event_post_attach
thread init
MessageBox closed
done
```

**Comment by onroadmuwl** [comment]
Even if I swap the order of the two lines, there are still some tests that don't pass. 
https://github.com/DynamoRIO/dynamorio/pull/6227

**Comment by derekbruening** [comment]
Looks like there is non-determinism as this win32 run has "thread_init" before "event_post_attach": https://github.com/DynamoRIO/dynamorio/actions/runs/5764745468/job/15629345646?pr=6241
