### ISSUE TITLE
ASSERT (api.startstop) dispatch.c:681 dcontext-last_exit == get_starting_linkstub()

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#813]
_From [bruen...@google.com](https://code.google.com/u/109494838902877177630/) on June 19, 2012 22:41:21_

happened in one suite run.  can't repro though:

debug-internal-32: 106 tests passed, ***\* 2 tests failed: ****
        code_api|client.timer 
        code_api|api.startstop =>  Application api.startstop (1942).  Internal Error Internal DynamoRIO Error: /work/dr/build_suite/src/core/dispatch.c:681 dcontext-last_exit == get_starting_linkstub() || IF_APP_EXPORTS(dcontext-last_exit == get_native_exec_linkstub() ||) IF_WINDOWS_ELSE_0(dcontext-last_exit == get_asynch_linkstub())

_Original issue: http://code.google.com/p/dynamorio/issues/detail?id=813_

**Comment by hgreving2304** [comment]
xref #2694
