### ISSUE TITLE
build: use "astyle" to check coding style

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#83]
_From [derek.br...@gmail.com](https://code.google.com/u/117968039472581148324/) on March 08, 2009 17:30:08_

xref issue #78 and the "make ugly" style checks

we could have codereview.cmake use astyle ( http://astyle.sourceforge.net/ )
for more complete checks

_Original issue: http://code.google.com/p/dynamorio/issues/detail?id=83_

**Comment by fhahn** [comment]
We now use vera++ for better style checks (#2369), closing this issue
