### ISSUE TITLE
events.h build race still in there on windows

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#859]
_From [bruen...@google.com](https://code.google.com/u/109494838902877177630/) on August 02, 2012 14:46:54_

*\* TODO events.h build race still in there, but can't repro w/ /diag

```
   "D:\derek\dr\git\build_x86_dbg_tests\ALL_BUILD.vcxproj" (default target) (1) ->
   "D:\derek\dr\git\build_x86_dbg_tests\api\samples\bbcount.vcxproj" (default target) (2) ->
   "D:\derek\dr\git\build_x86_dbg_tests\core\dynamorio.vcxproj" (default target) (20) ->
   (ClCompile target) -> 
     d:\derek\dr\git\src\core\utils.h(1725): fatal error C1083: Cannot open include file: 'events.h': No such file or directory [D:\derek\dr\git\build_x86_dbg_tests\core\dynamorio.vcxproj]
     d:\derek\dr\git\src\core\utils.h(1725): fatal error C1083: Cannot open include file: 'events.h': No such file or directory [D:\derek\dr\git\build_x86_dbg_tests\core\dynamorio.vcxproj]
```

I don't get it

--------------------------------------------------
another one, this time w/ generate_syslog:

debug-internal-64: ***\* 2 build errors ****
        13&gt:d:\derek\dr\git\src\core\utils.h(1729): fatal error C1083: Cannot open include file: 'event_strings.h': No such file or directory [D:\derek\dr\build_suite\build_debug-internal-64\core\drdecode.vcxproj]
        d:\derek\dr\git\src\core\utils.h(1729): fatal error C1083: Cannot open include file: 'event_strings.h': No such file or directory [D:\derek\dr\build_suite\build_debug-internal-64\core\drdecode.vcxproj]

looks like it's created 3 times:
&#37; grep -E 'generate_syslog|event_strings' build_debug-internal-64/Testing/Temporary/LastBuild_20120802-1815.log 
    10>Project "D:\derek\dr\build_suite\build_debug-internal-64\libutil\policy_static.vcxproj" (10) is building "D:\derek\dr\build_suite\build_debug-internal-64\core\generate_syslog.vcxproj" (25) on node 2 (default targets).
         Creating directory "x64\Debug\generate_syslog\".
         Creating "x64\Debug\generate_syslog\generate_syslog.unsuccessfulbuild" because "AlwaysCreate" was specified.
         Generating ../event_strings.h
         Deleting file "x64\Debug\generate_syslog\generate_syslog.unsuccessfulbuild".
         Touching "x64\Debug\generate_syslog\generate_syslog.lastbuildstate".
    25>Done Building Project "D:\derek\dr\build_suite\build_debug-internal-64\core\generate_syslog.vcxproj" (default targets).
         Generating ../event_strings.h
    13>d:\derek\dr\git\src\core\utils.h(1729): fatal error C1083: Cannot open include file: 'event_strings.h': No such file or directory [D:\derek\dr\build_suite\build_debug-internal-64\core\drdecode.vcxproj]
         Generating ../event_strings.h
         d:\derek\dr\git\src\core\utils.h(1729): fatal error C1083: Cannot open include file: 'event_strings.h': No such file or directory [D:\derek\dr\build_suite\build_debug-internal-64\core\drdecode.vcxproj]

dynamorio, preinject, drdecodelib, drinjectlib, unit_tests, policy_static,
drconfiglib, dumpevts, and mfapi targets all depend on it

but only one "is building" is listed.
more context around the generating:
    10>CustomBuild:^M
         Generating ../events.h^M
         MC: Compiling D:/derek/dr/git/src/core/win32/events.mc^M
         Generating ../event_strings.h^M

MC is for events, not event_strings

looks like events.h is also generated 3x:
&#37; grep 'Generating.*event' build_debug-internal-64/Testing/Temporary/LastBuild_20120802-1815.log 
         Generating ../events.h
         Generating ../event_strings.h
         Generating ../events.h
         Generating ../event_strings.h
         Generating ../events.h
         Generating ../event_strings.h

ditto in successful build:
&#37; grep 'Generating._event' build_debug-internal-32/Testing/Temporary/LastBuild__
         Generating ../event_strings.h
         Generating ../events.h
         Generating ../events.h
         Generating ../event_strings.h
         Generating ../events.h
         Generating ../event_strings.h

sequential build for easier to read logs:
Project "D:\derek\dr\git\build_x64_dbg_tests\libutil\policy_static.vcxproj" (4) is building "D:\derek\dr\g
it\build_x64_dbg_tests\core\generate_syslog.vcxproj" (6) on node 1 (default targets).^M
InitializeBuildStatus:^M
  Creating "x64\Debug\generate_syslog\generate_syslog.unsuccessfulbuild" because "AlwaysCreate" was specif
ied.^M
CustomBuild:^M
  Building Custom Rule D:/derek/dr/git/src/core/CMakeLists.txt^M
  CMake does not need to re-run because D:\derek\dr\git\build_x64_dbg_tests\core\CMakeFiles\generate.stamp
 is up-to-date.^M
  Generating ../event_strings.h^M
FinalizeBuildStatus:^M
  Deleting file "x64\Debug\generate_syslog\generate_syslog.unsuccessfulbuild".^M
  Touching "x64\Debug\generate_syslog\generate_syslog.lastbuildstate".^M
Done Building Project "D:\derek\dr\git\build_x64_dbg_tests\core\generate_syslog.vcxproj" (default targets).^M
InitializeBuildStatus:^M
  Creating "policy_static.dir\Debug\policy_static.unsuccessfulbuild" because "AlwaysCreate" was specified.^M
CustomBuild:^M
  Building Custom Rule D:/derek/dr/git/src/libutil/CMakeLists.txt^M
  CMake does not need to re-run because D:\derek\dr\git\build_x64_dbg_tests\libutil\CMakeFiles\generate.stamp is up-to-date.^M
  Generating ../events.h^M
  MC: Compiling D:/derek/dr/git/src/core/win32/events.mc^M
  Generating ../event_strings.h^M
ClCompile:^M

looks like the source file issue ( issue #801 ).  in fact libutil still has these guys
listed as sources:
  ${EVENTS_SRCS}
  ${SYSLOG_SRCS}
so that must be it

_Original issue: http://code.google.com/p/dynamorio/issues/detail?id=859_

**Comment by illera88** [comment]
What is it `events.h`? I see is a generated file but I can't find where it gets generated.

I'm getting a bunch of errors when building:
```
33>c:\users\default.desktop-h4fc4gg\documents\code\forks\dynamorio\core\utils.h(1946): fatal error C1083: Cannot open include file: 'events.h': No such file or directory (compiling source file C:\Users\default.DESKTOP-H4FC4GG\Documents\code\forks\dynamorio\core\win32\injector.c)
33>c:\users\default.desktop-h4fc4gg\documents\code\forks\dynamorio\core\utils.h(1946): fatal error C1083: Cannot open include file: 'events.h': No such file or directory (compiling source file C:\Users\default.DESKTOP-H4FC4GG\Documents\code\forks\dynamorio\core\win32\inject.c)
33>c:\users\default.desktop-h4fc4gg\documents\code\forks\dynamorio\core\utils.h(1946): fatal error C1083: Cannot open include file: 'events.h': No such file or directory (compiling source file C:\Users\default.DESKTOP-H4FC4GG\Documents\code\forks\dynamorio\core\win32\module_shared.c)
33>c:\users\default.desktop-h4fc4gg\documents\code\forks\dynamorio\core\utils.h(1946): fatal error C1083: Cannot open include file: 'events.h': No such file or directory (compiling source file C:\Users\default.DESKTOP-H4FC4GG\Documents\code\forks\dynamorio\core\win32\ntdll.c)
33>c:\users\default.desktop-h4fc4gg\documents\code\forks\dynamorio\core\utils.h(1946): fatal error C1083: Cannot open include file: 'events.h': No such file or directory (compiling source file C:\Users\default.DESKTOP-H4FC4GG\Documents\code\forks\dynamorio\core\win32\os.c)
33>c:\users\default.desktop-h4fc4gg\documents\code\forks\dynamorio\core\utils.h(1946): fatal error C1083: Cannot open include file: 'events.h': No such file or directory (compiling source file C:\Users\default.DESKTOP-H4FC4GG\Documents\code\forks\dynamorio\core\config.c)
```

**Comment by derekbruening** [comment]
CMake_events.cmake creates it, included in core/CMakeLists.txt.
