### ISSUE TITLE
detach on linux

### ISSUE THREAD

**Issue by derekbruening** [DynamoRIO/dynamorio#95]
_From [derek.br...@gmail.com](https://code.google.com/u/117968039472581148324/) on March 24, 2009 00:47:16_

this was PR 212088

we support detach on Windows but not on Linux

we don't support detach with clients: that was PR 199120 (not filed here yet)

xref attach: issue #38 for detach we'll need a scheme to free the sigstack for suspended threads,
as on linux suspended threads sit on their sigstack

_Original issue: http://code.google.com/p/dynamorio/issues/detail?id=95_

**Comment by derekbruening** [comment]
Re: the ongoing and back-and-forth argument over having dr_app_stop do full
cleanup or just send all threads native:

It seems like we can design start/stop and attach/detach to permanently
split up the features so that we can implement them all and pick which
combination best suits each use case:

1) Send all threads native: dr_app_stop() will trigger this.
   This leaves signal handlers and hooks in place, but they handle
   (generally via pass-through) native threads.

2) Have dr_app_start() re-takeover known threads, and re-examine app state
   that might have changed (unless we get enough syscall hooks to not need
   this: #721).  We support making optional assumptions depending on the
   app for improved perf: that no libs were loaded, no code was modified,
   etc.

3) Add "thread going native" and "thread re-takeover" client events, as
   these are distinct from thread_exit and thread_init in the presence of
   re-takeover.  Maybe call them "thread_detach" and "thread_attach"?
   Should we invoke them in normal operation as well?  I.e., whenever we
   call a thread_init event, we subsequently call the thread_attach event?

   Is this adding too much complexity?  Should we step back and say we
   don't want to support re-takeover and that dr_app_stop() should do a
   full cleanup (though we've gone down that road before and rejected
   it...)

3) Clean up and unload DR lib (if it's not static): dr_app_cleanup() will
   trigger this.  This requires all threads to already be native.

4) Re-start: for non-static DR, this would be an attach via injecting the
   DR lib.  For static this gets trickier as it hits all the global
   variable issues discussed earlier.

**Comment by derekbruening** [comment]
However, it is much easier to remove hooks while all threads are suspended.
Should we have a dr_app_stop_and_cleanup()?

For going native, b/c each thread has to restore its own segment, it's not
currently possible to bound the time for the whole process to go native due
to threads waiting at syscalls.  We'll have to put in place a way for those
threads to restore their segments lazily while we clean up the rest of DR:
we'll have to leave tombstones that aren't cleaned up.

**Comment by derekbruening** [comment]
For taking over known-but-native threads we actually need a synchall-style loop

**Comment by derekbruening** [comment]
*** TODO translate threads at syscalls: assume app will re-try interrupted syscall?

Doesn't seem good enough.  Xref #1145 and adjust_syscall_for_restart().

            /* FIXME i#95: this will xl8 to a post-syscall point for a thread at
             * a syscall, and we rely on the app itself to retry a syscall interrupted
             * by our suspend signal.  This is not good enough, as this is an
             * artifical signal that the app has not planned for with SA_RESTART or
             * a loop.  We want something like adjust_syscall_for_restart().
             * Xref #1145.
             */

**Comment by derekbruening** [comment]
This is a big feature with a lot of pieces and corner cases.

Recent CL's have the basics working for an app-triggered detach:

a84214e i#95 Linux detach: post-sysenter is a safe spot
a6a062d i#95 Linux detach: change dr_app_stop to send all threads native
ba6e2e6 i#95 Linux detach, i#1512 startstop flaky: rewrite api.startstop test
c7524ac i#95 Linux detach: generalize call_switch_stack
410aa08 i#95 Linux detach: translate do_syscall when method is sysenter
9592116 i#95 Linux detach: detaching via dr_app_stop_and_cleanup()
5214e9b i#95 Linux detach: merge with Windows detach

**Comment by derekbruening** [comment]
dr_app_stop_and_cleanup() does a full detach today.

A separated dr_app_stop() and later dr_app_cleanup() are different: today a separate cleanup kind of assumes it's terminating the app.  I have a forthcoming CL to at least remove the thread termination in the final synch.  But it seems better to look like dr_app_stop_and_cleanup() and do a full detach: worst-case we can insert a dr_app_start() first?!?  Or we could just drop support for dr_app_cleanup().

**Comment by derekbruening** [comment]
Nudge-based detach is only supported on Windows due to the assumption of a separate thread stack.  If we implement a scheme to create a temporary separate stack for a client-triggered detach #2644 we could use the same mechanism for a nudge-based detach on UNIX which I believe is the only reason this issue is still open?

**Comment by derekbruening** [comment]
Pasting notes from re-examining the Windows detach status today:

The existing Windows detach nudge feature is internal to DR and does not go through a client.  It looks like it is not exposed in drconfig and the old tests for it are not all enabled; the old way to trigger it is in the no-longer-supported "drcontrol" front-end, but it's just a different nudge type so it should be feasible to tweak drconfig to enable it to try it out.  You can see the code paths in libutil/detach.c triggering the nudge to be sent and handling it in core/nudge.c "TEST(NUDGE_GENERIC(detach), nudge_action_mask)" calling detach_helper() which calls the shared-with-all-detach-types detach_on_permanent_stack().

**Comment by derekbruening** [comment]
We'd want to merge nudgeunix into drdeploy.c so we can invoke nudges in general and detach nudges from the dronconfig front-end: that's part of #840.

**Comment by derekbruening** [comment]
Re-exposing the Windows detach from drconfig is part of #725

**Comment by onroadmuwl** [comment]
The relevant code is submitted in [#6513](https://github.com/DynamoRIO/dynamorio/pull/6513)

**Comment by derekbruening** [comment]
I think we can close this now.  Any problems or enhancements can be filed as separate issues.
